<link href="<?php echo $this->basePath('public');?>/css/oldAdmin.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_style.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_v5.3.2_min.js"></script>


<div class="row"> 
	<div class="col-md-12">
		<div class="portlet no_mb">
	        <div class="portlet-title">
	            <div class="actions btn-set">
					<a href="<?php echo $this->url('capitaledit') ?>" class="btn default yellow-stripe tjfjz"><i class="fa fa-plus"></i><span class="hidden-480">新增会员账户</span></a>
				</div>
	        </div>
	    </div>
	</div>
	<div class="col-md-12">
	<?php echo $this->datagrid(array(
		'id'=>'table-list',
		'dataProvider'=>$pager,
		'columns'=>array(
			array(
				'header' => '账户名称',
				'name' => 'name',
				'filter'=>'t.name',
			),
			array(
				'header' => '账户类型',
				'name' => 'type',
				'value'=>'{\CompanyCapital::getType($data["type"])}',
				'filter'=>array('t.type',\CompanyCapital::getType()),
			),
			array(
				'header' => '状态',
				'name' => 'status',
				'filter'=>array('t.status',\CompanyCapital::getStatus()),
				'value'=>'{\CompanyCapital::getStatus($data["status"])}',
			),
			array(
				'header' => '购买项目',
				'name' => 'is_project',
				'value'=>'{\CompanyCapital::getYN($data["is_project"])}',
				'filter'=>array('t.is_project',\CompanyCapital::getYN()),
			),
			array(
				'header' => '购买产品',
				'name' => 'is_product',
				'value'=>'{\CompanyCapital::getYN($data["is_product"])}',
				'filter'=>array('t.is_product',\CompanyCapital::getYN()),
			),
			array(
				'header' => '购买卡劵',
				'name' => 'is_voucher',
				'value'=>'{\CompanyCapital::getYN($data["is_voucher"])}',
				'filter'=>array('t.is_product',\CompanyCapital::getYN()),
			),
			array(
				'header' => '账户说明',
				'name' => 'note',
			),
			array(
				'header' => '操作',
				'rel'=>'id',
				'value'=> '<a href="'.$this->url("capitaledit").'&id={$data["id"]}" class="edit">编辑</a>',
			)
		),
	));?>

	<?php if(!empty($_GET['yd'])):?>
		<div class="zhezhao">
			<div class="zhezhao_center">
				<span>第五步</span>
				<a class="zhezhao_center_back" href="<?php echo $this->url('/admin/membership/index',array('yd'=>1));?>">返回上一步</a>
				<a class="zhezhao_center_next" href="<?php echo $this->url('/admin/product/index',array('yd'=>1));?>">进入下一步</a>
			</div>
		</div>
	<?php endif;?>

	</div>
</div>




<!--tjfj-->
<div class="tjfj add_card none" style="display: none;">
	<div class="tjfj_two">
		<form method="post">

		</form>
	</div>
</div>

<script type="text/javascript">

	<?php if(!empty($_GET['yd'])):?>
		$("body").css("padding-bottom","100px");
		$(".content_left").hide();
		$(".content_right_son").css('margin-left','20px');
	<?php endif;?>

$('select[name="is_member"] option:first').remove()
function validate(classname){
	var nf = classname.Validform({
		tiptype:3,
	});

	nf.addRule([
	{
		ele:".new_inputxt:eq(0)",
		datatype:"*",
		nullmsg:"请输入账户名称！"
	}
	]);
}

	/**
	 * 修改会员账户
	 */
	$(document).on('click','.tjfjz,.edit',function(){
		var obj = $(this).parent().parent();
		var is_new=$(this).hasClass('tjfjz');
		var _url=$(this).attr('href'),yd='<?php echo $_GET['yd'];?>';
		$.get(_url, { ajax: 1 },function(html){
			var d = Idialog({
				top:120,
				width:480,
				title:is_new?'新增会员账户':'编辑会员账户',
				content:html,
				ok:function(obj){
					obj._self.find('form').submit();
					return false;
				},
				init:function(self){
					self.find("form").attr("class","newform");

					self.find(".inputxt").attr("class","new_inputxt");

					validate($('.newform'));
				},
			});
			$("input[name=yd]").val(yd);
		});
		return false;
	});
	
	/**
	 * 修改会员账户状态
	 */
	$(document).on('click','.change',function(){
		var obj = $(this).parent().parent();
		var id = obj.attr('rel');
		var thisobj = $(this);
		$.get("<?php echo $this->url('change') ?>", { id: id },function(html){
			var jobj = $.parseJSON(html);
			var dataobj = jobj['data'];
			var status = dataobj['status'];
			thisobj.html(status==1?"启用":"停用");
		});
	});
	
	/**
	 * 删除会员账户
	 */
	$(document).on('click','.delete',function(){
		var obj = $(this).parent().parent();
		var _url=$(this).attr('href');
		var d = Idialog({
			top:120,
			width:500,
			title:'通知',
			content:'您确认删除吗？',
			ok:function(html){
				$.get(_url, { ajax: 1 },function(html){
					var jobj = $.parseJSON(html);
					if(jobj['code']=='200'){
						var d = Idialog({
							top:120,
							width:500,
							title:'通知',
							content:'删除成功',
							ok:function(html){
								obj.remove();
								return true;
							},
							cancel:false,
						});
					}else{
						var d = Idialog({
							top:120,
							width:500,
							title:'通知',
							content:'删除失败',
							ok:function(obj){
								return true;
							},
							cancel:false,
						});
					}
				});
				return true;
			},
			cancel:true,
		});
		return false;
	});

</script>
