<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
	<div class="print_show col-md-12">
		<div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/卡券兑换-查看
                </div>
                <div class="tools">
	                	<button onclick="history.go(-1)" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>返回</button>
                </div>
            </div>
        </div>
		<?php $sum_lc = array_sum(array_column($model->pros, 'use_num')) ?>
        <div class="row">
			<div class="col-md-6 col-sm-12">
	            <div class="portlet solid green-haze">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>订单概况
	                    </div>
	                    <div class="actions">
		                    <button class="btn red">疗次合计<?php echo $sum_lc ?></button>
	                    </div>
	                </div>
	                <div class="portlet-body">
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">实操单号：</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->sn ?>
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">耗卡时间</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->pay_time?date('Y-m-d H:i:s',$model->o_s->pay_time):'未耗卡';?>
	                        </div>
	                    </div>

	                    <div class="row static-info">
	                        <div class="col-xs-5 name">订单状态：</div>
	                        <div class="col-xs-7 value text-right">
		                        <?php if (!$model): ?>
	                        	<span class="label label-info label-sm">草稿</span>
								<?php else: ?>
	                        	<span class="label label-warning label-sm"><?php echo \OrderVoucher::getStatus($model->o_s->status);?></span>
								<?php endif ?>
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">本次实操项目：</div>
	                        <div class="col-xs-7 value text-right">
	                        	<font class="xj_xm"><?php echo count($model->pros) ?></font> 个
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">本次实操疗次：</div>
	                        <div class="col-xs-7 value text-right">
                                <font class="xj_lc"><?php echo $sum_lc ?></font> 次
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <div class="col-md-6 col-sm-12">
	            <div class="portlet solid red-intense">
	                <div class="portlet-body" style="padding-top: 10px;">
	                    <?php echo $cu_info ?>
	                </div>
	            </div>
	        </div>


        </div>

        <div class="row"> 
	        <div class="col-md-12">
		        <div class="portlet box blue-steel">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>本次兑换卡券
	                    </div>
	                </div>
	                <div class="portlet-body">
	                	<div class="table-responsive"> 
							<table class="table table-bordered table-hover " >
								<thead>
									<tr>
										<th>时效</th>
										<th>卡券名称</th>
										<th>卡券数量</th>
										<th>可用现金金额（元）</th>
										<th>可用赠送金额（元）</th>
										<th>可用项目</th>
										<th>可用产品</th>
										<th>备注</th>
									</tr>
								</thead>
								<tbody>
									<?php
									 	if ($CustomerVoucher): 
										$pro=\CustomerVoucher::getLastProNames($CustomerVoucher->id);
									?>
									<tr class="table_list">
											<td><?php echo date('Y/m/d',$CustomerVoucher->stime),'-',date('Y/m/d',$CustomerVoucher->etime) ?></td>
											<td><?php echo $CustomerVoucher->name ?></td>
											<td>1</td>
											<td><?php echo \CustomerVoucher::getLastMoney($CustomerVoucher->id) ?></td>
											<td><?php echo \CustomerVoucher::getLastMoneyZS($CustomerVoucher->id) ?></td>
											<td><?php echo $pro['project'] ?></td>
											<td><?php echo $pro['product'] ?></td>
											<td><?php echo $CustomerVoucher->note ?></td>
									</tr>
									<?php endif ?>
								</tbody>
							</table>
						</div>
	                </div>
	            </div>
	        </div>
        </div>

        <!--兑换卡券-->
		<div class="pos_cz_tow voucher_html">
			<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span><?php echo $CustomerVoucher->name ?> 兑换成</div>
			<div class="pos_cz_tow_two">
				<div class="pos_kj_top_top">
					<ul>
						<li>兑换现金金额：<?php
						$capital=\CompanyCapital::model()
						->field(array("t.name","cc.id",))
						->join('customer_capital cc on t.id=cc.capital_id')
						->findByPk($model->o_s->capital_id);
							echo $model->o_s->capital_id?$capital->name.':'.$model->o_s->money:'无';
						?>
						</li>
						<li>兑换赠送金额：<?php
						$gift_capital=\CompanyCapital::model()
						->field(array("t.name","cc.id",))
						->join('customer_capital cc on t.id=cc.capital_id')
						->findByPk($model->o_s->gift_capital_id);
						 echo $model->o_s->gift_capital_id?$gift_capital->name.':'.$model->o_s->gift_money:'无';
						  ?>
						</li>
					</ul>
				</div>

				<div class="pos_kj_top_two">
					<div class="portlet portlet-table ">
			            <div class="portlet-body">
				            <table class="table table-bordered table-hover">
								<thead>
									<tr>
											<th>项目名称</th>
											<th>兑换次数</th>
									</tr>
								</thead>
								<tbody>
									<?php 
										if($model)
											foreach ($model->pros as $key => $value):
												if ($value['pro_type']!=1)continue;
											$pro_num=$value['num'];
											$pro=\pos\SaleModel::model()->getProInfo($value['pro_id'],$value['pro_type']);
									 ?>
									<tr class="table_list">
											<td><?php echo $pro->name; ?></td>
											<td><?php echo $pro_num ?></td>
									</tr>
									<?php endforeach; ?>
								</tbody>
							</table>
			            </div>
			        </div>
				</div>
				<div class="pos_kj_top_two">
					<div class="portlet portlet-table ">
			            <div class="portlet-body">
				            <table class="table table-bordered table-hover" >
								<thead>
									<tr>
										<th>产品名称</th>
										<th>兑换次数</th>
									</tr>
								</thead>
								<tbody>
									<?php 
										if($model)
											foreach ($model->pros as $key => $value):
												if ($value['pro_type']!=2)continue;
											$pro_num=$value['num'];
											$pro=\pos\SaleModel::model()->getProInfo($value['pro_id'],$value['pro_type']);
									 ?>
									<tr class="table_list">
											<td><?php echo $pro->name; ?></td>
											<td><?php echo $pro_num ?></td>
									</tr>
									<?php endforeach; ?>
								</tbody>
							</table>
			            </div>
			        </div>
				</div>

			</div>
		</div>
		<!--兑换卡券!end--> 




		<!--备注-->
		<div class="pos_cz_tow pos_cz_for_bz">
			<div class="pos_cz_for_bz01">备注</div>
			<div class="pos_cz_for_bz02">
				<div class="pos_cz_for_bz02_son">
				<?php echo $model?$model->o_s->note:"" ?>
				</div>
			</div>
		</div>
		<!--备注!end-->
    </div>
</div>






<script type="text/javascript">
$(function(){
	//收起效果
	$(".pos_cz_tow_top_r").click(function(){
		var self=$(this);
		self.parent().next().slideToggle("fast",function(){
			if(self.hasClass("pos_cz_tow_top_rcl")){
				self.removeClass("pos_cz_tow_top_rcl");
			}else{
				self.addClass("pos_cz_tow_top_rcl");
			}
		});
	});
})
</script>