<?php 
$top_cate=\ProCate::getProductTopCate();
$prod_type=\ProCate::getProductType();
$child_cate=array();
if(isset($_GET['t_search']['c_t.id']))
	$tmp_cate=\ProCate::model()->findAll('fid='.(int)$_GET['t_search']['c_t.id'].' and comp_id='.\Ivy::app()->user->comp_id);
	$child_cate = $this->optArr($tmp_cate,'id','name');
?>
<link href="<?php echo $this->basePath('public');?>/css/oldAdmin.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_style.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_v5.3.2_min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/html5uploader/jquery.html5uploader.js"></script>

<div class="row">
	<div class="col-md-12">
		<div class="portlet">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-users"></i>商品管理
				</div>
				<div class="actions btn-set">
					<a href="javascript:" class="btn default yellow-stripe c_update"><i class="fa fa-upload"></i>批量上传</a>
					<a href="javascript:" class="btn default yellow-stripe c_add"><i class="fa fa-plus"></i><span class="hidden-480">新增商品</span></a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
	<!--  模版引擎扩展 -->
	<?php echo $this->datagrid(array(
		'id'=>'product-list',
		'dataProvider'=>$pager,
		'check'=>'id',
		'search'=>true,
		'columns'=>array(
			array(
				'header' => '商品分类',
				'name'  => 'fname',
				'filter'=>array("c_t.id",$top_cate,""),
			),
			array(
				'header' => '商品系列',
				'name'  => 'cname',
				'filter'=>array("t.cate",$child_cate,""),
			),
			array(
				'header' => '商品属性',
				'name'  => 'type',
				'value'=>'{\ProCate::getProductType($data["type"])}',
			),
			array(
				'header' => '商品名称',
				'name'  => 'name',
				'filter'=>"t.name",
			),
			array(
				'header' => '商品编码',
				'name' => 'code',
			),
			array(
				'header' => '单价',
				'name' => 'price',
			),
			array(
				'header' => '规格',
				'name' => 'specs',
			),
			array(
				'header' => '单位',
				'name' => 'unit',
			),
			array(
				'header' => '实操用量',
				'name' => 'num',
			),
			array(
				'header' => '状态',
				'name' => 'status',
				'value'=>'{$data["status"]==1?"启用":"<fone style=\"color:red\">停用</font>"}'
			),
			array(
				'header' => '操作',
				'name' => 'status',
				'rel'=>'id',
				'template'=>'<a href="javascript:" class="btn default btn-xs blue-hoki-stripe change">{$data["status"]==0?"启用":"停用"}</a>
					,edit,delete'
			)
		),
	));?>

	</div>
</div>
	<?php if(!empty($_GET['yd'])):?>
		<div class="zhezhao">
			<div class="zhezhao_center">
				<span>第六步</span>
				<a class="zhezhao_center_back" href="<?php echo $this->url('/admin/config/capital',array('yd'=>1));?>">返回上一步</a>
				<a class="zhezhao_center_next" href="<?php echo $this->url('/admin/project/index',array('yd'=>1));?>">进入下一步</a>
			</div>
		</div>
	<?php endif;?>
<!--content_right_con!end-->


<!--tjfj-->
<div class="add_prod display-none" title="新增商品">
	<div class="tjfj_two" action="#">
	<form method="post" action="<?php echo $this->url('add') ?>">
		<div class="list">
	        <label>商品分类：</label>
			<div style="margin-left: 100px;">
			<select class="top_cate">
				<option value="">--请选择--</option>
			<?php foreach ($top_cate as $key => $value): ?>
				<option value="<?php echo $key ?>"><?php echo $value ?></option>
			<?php endforeach ?>
			</select>（必填）</div>
        </div>
		<div class="list"><label>商品系列：</label><div style="margin-left: 100px;"><select name="cate"></select>（必填）</div></div>
		<div class="list"><label>商品属性：</label><div style="margin-left: 100px;"><select name="type">
		<option value="0">--无--</option>
		<?php foreach ($prod_type as $key => $value): ?>
			<option value="<?php echo $key ?>"><?php echo $value ?></option>
		<?php endforeach ?>
		</select></div></div>

        <div class="list"><label>供应商：</label>
			<div class="list_right">
				<select name="supp_id">
					<option value="0">--无--</option>
					<?php foreach (\SupplierInfo::getList() as $key => $value): ?>
					<option value="<?php echo $key ?>"><?php echo $value ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</div>

		<div class="list"><label>商品名称：</label><div style="margin-left: 100px;"><input type="text" name="name" class="inputxt"/>（必填）</div></div>
		<div class="list"><label>商品编码：</label><div style="margin-left: 100px;"><input type="text" name="code" /></div></div>

		<div class="list"><label>实操用量：<div class="help" explain="此处填入一个最小库存单位的商品能够做多少次实操,如一瓶院装的保湿舒敏精油开瓶后可供60次实操项目的调配使用,则该商品的用量为60次. （家装产品不填）"></div></label><div style="margin-left: 100px;"><input type="text" placeholder="" name="num" class="inputxt"/>（必填）</div></div>
		<div class="list"><label>单价：<div class="help" explain="此处请填入商品的售价"></div></label><div style="margin-left: 100px;"><input type="text" placeholder="" name="price" class="inputxt"/>（必填）</div></div>
		<div class="list"><label>规格：<div class="help" explain="按照什么单位录的, 就填什么规格如, 单位是”瓶”,那么液体的规格为XXXml/瓶单位是”盒”,那么小支装产品的规格为XXX支/盒单位是”套盒”,那么规格是XXX组/套盒"></div></label><div style="margin-left: 100px;"><input type="text" placeholder="" name="specs" /></div></div>
		<div class="list"><label>单位：<div class="help" explain="如果没有在下拉框中找到对应的商品单位,请到“商品单位管理”模块选择  “商品单位新建”"></div></label><div style="margin-left: 100px;"><input type="text" placeholder="" name="unit"   class="inputxt"/>（必填）</div></div>


	</form>
	</div>
</div>



<!--tjfj03-->
<div class="update display-none" title="批量上传">
	<div class="tjfj_two">
		<p>请严格按照我们提供的项目格式编辑并上传。<a href="<?php echo SITE_URL . '/upload/product_template.xls' ?>" target="_new">下载商品信息模板</a></p>
		<p style=" text-align:center;"><img src="<?php echo $this->basePath('public') ?>/images/pl_02.png" /></p>
		<p style=" text-align:center;"><div id="upload"></div></p>
		<p style=" text-align:center; color:#999;">(上传文档必须小于2MB,格式*.xls)</p>
	</div> 
</div>


<script type="text/javascript">
	<?php if(!empty($_GET['yd'])):?>
		$("body").css("padding-bottom","100px");
		$(".content_left").hide();
		$(".content_right_son").css('margin-left','20px');
		$(".filter_search").parent().hide();
		$(".c_add").parent().hide();
	<?php endif;?>

function validate(classname){
	var nf = classname.Validform({
		tiptype:3,
	});

	nf.addRule([
	{
		ele:"select:eq(0)",
		datatype:"*",
		nullmsg:"请输入商品分类！"
	},
	{
		ele:"select:eq(1)",
		datatype:"*",
		nullmsg:"请选择商品系列！"
	},
	{
		ele:"select:eq(2)",
		datatype:"*",
		nullmsg:"请选择商品属性！"
	},
	{
		ele:".new_inputxt:eq(0)",
		datatype:"*",
		nullmsg:"请填写商品名称！"
	},
	{
		ele:".new_inputxt:eq(1)",
		datatype:"*",
		nullmsg:"请填写实操用量！"
	},
	{
		ele:".new_inputxt:eq(2)",
		datatype:"*",
		nullmsg:"请填写单价！"
	},
	{
		ele:".new_inputxt:eq(3)",
		datatype:"*",
		nullmsg:"请填写单位！"
	}
	]);
}


$(function(){
	// 添加商品
	$('.c_add').click(function(){
		var d = Idialog({
			top:120,
			width:500,
			title:'新增商品',
			content:$('.add_prod'),
			ok:function(obj){
				obj._self.find('form').submit();
				return false;
			},
			cancel:true,
			init:function(self){
				self.find("form").attr("class","newform");
				self.find(".inputxt").attr("class","new_inputxt");
				$('.help').help();

				validate($('.newform'));
			}
		});
	});

	// 编辑商品
	$('.edit').click(function(){
		var id=$(this).parent().attr('rel');
		$.get("<?php echo $this->url('edit') ?>", { id: id },function(html){
			var d = Idialog({
				top:120,
				width:500,
				title:'编辑商品',
				content:html,
				ok:function(obj){
					obj._self.find('form').submit();
					return false;
				},
				cancel:true,
				init:function(self){
					self.find("form").attr("class","newform");
					self.find(".inputxt").attr("class","new_inputxt");
					$('.help').help();

					validate($('.newform'));
				}
			});
		});
	});

	// 修改商品状态
	$('.change').click(function(){
		var id=$(this).parent().attr('rel');
		var obj = $(this);
		$.get("<?php echo $this->url('change') ?>", { id: id },function(html){
			var jobj = $.parseJSON(html);
			var dataobj = jobj['data'];
			var status = dataobj['status'];
			//obj.html(status==1?"启用":"<fone style='color:red'>停用</font>");
			obj.html(status==0?"启用":"停用");
			obj.attr('style',status==0?'':'background-color: #ddd;color: #666;');
			obj.parent().prev().attr('title',status==1?"启用":"停用").html(status==1?"启用":'<fone style="color:red">停用</fone>');
		});
	});

	//批量上传 
	$('.c_update').click(function(){
		<?php if($pager['pagener']['recordsTotal']): ?>
			Idialog({
					top:150,
					width:500,
					title:'数据警告',
					content:'确定将追加数据！',
					ok:function(obj){
						upload()
					}
			})
		<?php else: ?>
		upload();
		<?php endif; ?>
	});
	function upload(){
		var d = Idialog({
			top:150,
			width:500,
			title:'批量上传',
			content:$('.update'),
			init:function(obj){
				obj.find('#upload').html5uploader({
					auto:true,
					multi:false,
					removeTimeout:2000,
					buttonText:'<img src="<?php echo $this->basePath("public") ?>/images/pl_03.png" />',
					url:'<?php echo $this->url("upload") ?>',
					itemTemplate:'',
					fileTypeExts:'application/vnd.ms-excel',
					onUploadStart:function(){
						//alert('开始上传');
						var _html = "<div id='loading' style='position:fixed;left:0;width:100%;height:100%;top:0;background:rgb(0, 0, 0);opacity:0.5;filter:alpha(opacity=50);z-index: 1000;'><div style='position:absolute;cursor1:wait;left:50%;top:50%;width:auto;height:16px;padding:13px 22px 28px 30px;background: url(<?php echo $this->basePath('public');?>/images/loading.gif) no-repeat scroll 5px 10px;text-indent: -99999px;color:#000;'>正在加载，请等待...</div></div>";
    					$('body').append(_html);
						},
					onInit:function(){
						//alert('初始化');
						},
					onUploadError:function (file,data) {
						console.log(file);
						console.log(data);
					},
					onUploadComplete:function(){
						// alert('上传完成');
						},
					onUploadSuccess:function(file,json){
						//console.log(file);
						json = eval('('+json+')');
						$('#loading,.idialog').remove();
						if(json.code==200){
							Idialog({
								top:150,
								width:500,
								title:'提示',
								content:json.msg+'一共'+json.data.total+'条,成功导入:'+json.data.success+'条!',
								init:function(obj){
									obj.find('.idialog').css('z-index','1001');
								},
								ok:function(obj){
									location.reload();
								},
								cancel:false
							})
							
						}

					}
				});
				obj.find('.uploadfile').css('width','164px');

			},
			ok:function(obj){
				//console.log(obj);
				
				return false;
			},
			cancel:true
		});
	}

	//分类下拉级联
	$('body').on('change','.top_cate',function(){
		var self=$(this);
		var fid=self.val();
		var opt='';
		$.getJSON("<?php echo $this->url('childCate') ?>",{fid:fid}, function(json){
			if(json.code==200){
				$.each(json.data, function(i, v){
					opt+='<option value="'+v.id+'">'+v.name+'</option>';
				});
			}
			self.parent().parent().next().find('select').empty().append(opt);
		});
	});

	$(document).on('click','.delete',function(){
		var obj = $(this).parent().parent();
		var id = $(this).parent().attr('rel');

		var d = Idialog({
			top:120,
			width:500,
			title:'通知',
			content:'您确认删除吗？',
			ok:function(html){
				$.get("<?php echo $this->url('delete') ?>", { id: id },function(html){
					var jobj = $.parseJSON(html);
					if(jobj['code']=='200'){
						var d = Idialog({
							top:120,
							width:500,
							title:'通知',
							content:'删除成功',
							ok:function(html){
								obj.remove();
								return true;
							},
							cancel:false,
						});
					}else{
						var d = Idialog({
							top:120,
							width:500,
							title:'通知',
							content:'删除失败',
							ok:function(obj){
								return true;
							},
							cancel:false,
						});
					}
				});
				return true;
			},
			cancel:true,
		});
	});
});
</script>