<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">续费升级</div>
	<div class="xufei_page">
		<?php if ($model->has_invo=='N'): ?>
			<div class="xufei_page_list">您当前使用的是美慧智能云平台标准版 <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=279414999&amp;menu=yes" target="_blank">联系客服升级</a></div>
		<?php endif ?>
		<div class="xufei_page_list">服务费将于 <?php echo date("Y-m-d H:i",$model->server_time) ?> 到期<a href="http://wpa.qq.com/msgrd?v=3&amp;uin=279414999&amp;menu=yes" target="_blank">联系客服续费</a><em style="margin-left:20px; display:inline-block; font-style:normal;">客服电话：027-87050505</em></div>

		<?php if ($model->has_invo=='N'): ?>
		<div class="xufei_page_text">
		  <div class="xufei_page_text_tit">
		    <p style="color:#f00;">现在升级全功能版即可达成对成本的控制, 对顾客的O2O服务, 还能实现老板的移动办公，.更加全面地满足连锁标准化管控需要！</p>
		    <p>&nbsp;</p>
	      </div>
		  <div class="xufei_page_text_page">
		    <p>在标准化账务管控的同时, 将&rdquo;钱账&ldquo;和&rdquo;物账&ldquo; 一体化做管理，如: 当顾客购买家居产品时, 门店开出的销售订单直接关联了库存的出库单,出账后默认&rdquo;待出库&ldquo;; 门店可以根据需要选择本次出库或以后出库, 一但&rdquo;以后出库&ldquo;, 系统智能地将产品划出商品数量, 划入寄存数量,寄存列表可以随时筛查。让你的&ldquo;钱、账、物&ldquo;穿成一条线, 里里外外只查一本账, 所有进出都能明明白白。 </p>
		    <h3 style="line-height:40px;color:#07f;padding-top:10px;">美业专属进销存</h3>
		    <p style=" display:block; padding:0px;">&nbsp;</p>
		    <table width="800" border="0" cellspacing="1" cellpadding="0" style="background-color:#ccc;">
		      <tr>
		        <td width="20%" rowspan="13" align="center" valign="middle" bgcolor="#fff"><strong>美业专属经销存</strong></td>
		        <td width="40%" align="center" valign="middle" bgcolor="#fff"><strong>供应商管理</strong></td>
		        <td width="40%" align="center" valign="middle" bgcolor="#fff">&nbsp;</td>
	          </tr>
		      <tr>
		        <td rowspan="2" align="center" valign="middle" bgcolor="#fff"><strong>采购管理</strong></td>
		        <td align="center" valign="middle" bgcolor="#fff">采购与入库</td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#fff">退货与出库</td>
	          </tr>
		      <tr>
		        <td rowspan="2" align="center" valign="middle" bgcolor="#fff"><strong>库存管理</strong></td>
		        <td align="center" valign="middle" bgcolor="#fff">盘库/盘库流水表</td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#fff">报损报溢/损益流水表</td>
	          </tr>
		      <tr>
		        <td rowspan="4" align="center" valign="middle" bgcolor="#fff"><strong>调拨管理</strong></td>
		        <td align="center" valign="middle" bgcolor="#fff">报货</td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#fff">调拨出库</td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#fff">调拨入库</td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#fff">货品往来流水</td>
	          </tr>
		      <tr>
		        <td rowspan="4" align="center" valign="middle" bgcolor="#ffffdd"><strong>美业钱账务一体化</strong></td>
		        <td align="center" valign="middle" bgcolor="#ffffdd">实操调配领用记录</td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#ffffdd"><p>顾客家具产品购买智能生成寄存表单</p></td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#ffffdd">寄存商品与库存商品分开记账</td>
	          </tr>
		      <tr>
		        <td align="center" valign="middle" bgcolor="#ffffdd"> 顾客领用寄存后自动扣减寄存数目</td>
	          </tr>
	        </table>
		    </p>
		    <h3 style="line-height:40px; color:#07f; padding-top:10px;">配有微信服务平台----目前市面上唯一一款能够与公司内部管理系统一体化的微信服务平台</h3>
		    <p>通过微信查看自己账户信息, 护理记录, 诊断记录…<br />
		      通过微信预约到店护理, 预约记录可自动同步到门店前台的meihui系统上, <br />
		      通过微信确认实耗耗卡, 实操后通过微信接受服务满意度调查, 老板可在meihui系统上直接看到顾客对护理服务的满意度和评价, 客观真实<br />
	        </p>
		    <p style=" display:block; padding:0px;">&nbsp;</p>
		    <table width="800" cellpadding="0" cellspacing="1" style="background-color:#ccc;">
		      <tr>
		        <td height="0" colspan="4" bgcolor="#fff"><p style="display:block; text-align:center; font-weight:bold; color:#222; font-size:18px;">meihui 美业O2O微信服务平台</p></td>
	          </tr>
		      <tr>
		        <td width="20%" height="0" bgcolor="#eee"><strong>模块</strong></td>
		        <td width="20%" height="0" bgcolor="#eee"><strong>功能类目</strong></td>
		        <td width="30%" height="0" bgcolor="#eee"><strong>功能</strong></td>
		        <td width="30%" height="0" bgcolor="#eee"><strong>实现明细</strong></td>
	          </tr>
		      <tr>
		        <td width="0" rowspan="7" bgcolor="#fff"><strong>客户服务<br />
		          </strong></td>
		        <td width="642" height="0" rowspan="2" bgcolor="#fff">个人信息在线查询</td>
		        <td width="0" height="0" bgcolor="#fff">动态账户信息查看</td>
		        <td width="0" height="0" rowspan="2" bgcolor="#fff">与门店meihui管理系统互通<br />
		          实时跟踪个人账户动态</td>
	          </tr>
		      <tr>
		        <td width="0" height="0" bgcolor="#fff">动态护理记录查看</td>
	          </tr>
		      <tr>
		        <td width="642" height="0" bgcolor="#fff">在线预约到店护理</td>
		        <td width="0" height="0" bgcolor="#fff">微信预约与确认</td>
		        <td width="0" height="0" bgcolor="#fff">与门店meihui管理系统互通<br />
		          预约信息实时同步到门店电子预约本</td>
	          </tr>
		      <tr>
		        <td width="642" height="0" bgcolor="#fff">在线确认耗卡</td>
		        <td width="0" height="0" bgcolor="#fff">微信耗卡与确认</td>
		        <td width="0" height="0" bgcolor="#fff">与门店meihui管理系统互通<br />
		          耗卡时做客户微信身份认证</td>
	          </tr>
		      <tr>
		        <td width="642" height="0" bgcolor="#fff">在线满意度调查</td>
		        <td width="0" height="0" bgcolor="#fff">离店后微信满意度调查</td>
		        <td width="0" height="0" bgcolor="#fff">顾客确认耗卡后30分钟收到满意度调查<br />
		          离店填写确保客观真实</td>
	          </tr>
		      <tr>
		        <td width="642" height="0" rowspan="2" bgcolor="#fff">在线导航</td>
		        <td width="0" height="0" bgcolor="#fff">查询&quot;离我最近的门店&quot;</td>
		        <td width="0" height="0" rowspan="2" bgcolor="#fff">微信查询地址推荐门店及导航</td>
	          </tr>
		      <tr>
		        <td width="0" height="0" bgcolor="#fff">选择门店进行导航</td>
	          </tr>
	        </table>
		    </p>
		    <h3 style="line-height:40px; color:#07f; padding-top:10px;">配有BOSS版本App----无论在哪里出差, 老板都能在第一时间对公司业务远程监督</h3>
		    <h3><a class="red" href="http://www.etwasd.com/function.html" target="_blank">点击查看更多功能&gt;&gt;</a></h3>
	      </div>
	  </div>
		<?php endif ?>
		
	</div>
</div>
<!--content_right_con!end-->