

<?php foreach($list as $item):?>
    <tr class="table_list" data-id="<?php echo $item['id']?>" data-pid="<?php echo $item['product_id']?>">
        <td><?php echo $item['fname']?></td>
        <td><?php echo $item['cname']?></td>
        <td><?php echo $item['name']?></td>
        <td><?php echo $item['code']?></td>
        <td><?php echo $item['num']?></td>
        <td><?php echo $item['storage_num']?></td>
        <td><?php echo $item['extra_num']?></td>
        <td><input type="text" name="num" class="pos_cz_tow_two05" /></td>
        <td class="extra_num" ><input type="text" name="extra_num" class="pos_cz_tow_two05" /></td>
    </tr>
<?php endforeach;?>


