<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jquery.PrintArea.js"></script>
<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>

<?php $hd_list = \SaleNoticeInfo::model()->getListOpt();?>
<!--content_right_con-->
<div class="row">
	<div class="print_show col-md-12">
		<div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-eye-slash"></i>订单查看
                </div>
                <div class="tools">
                	<button class="btn btn-sm yellow table-group-action-submit to_print"><i class="fa fa-check"></i>打印订单</button>
                </div>
            </div>
        </div>

		<div class="row">
			<div class="col-md-6 col-sm-12">
	            <div class="portlet solid green-haze">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>订单概况
	                    </div>
	                    <div class="actions"><button class="btn red">交易成功</button> </div>
	                </div>
	                <div class="portlet-body">
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">订单号：</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->sn ?>
	                        </div>
	                    </div>

	                    <div class="scroller" style="height:140px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">
	                    	<?php if($model->o_s->pay_status==1): ?>

		                    	<?php foreach ($model->getXJList() as $key => $value): ?>
		                    		<?php if($value>0): ?>
		                    		<div class="row static-info">
				                        <div class="col-xs-5 name"><?php echo $key ?>卡扣：</div>
				                        <div class="col-xs-7 value text-right">
				                        	<?php echo $value ?> 元
				                        </div>
				                    </div>
				                	<?php endif; ?>
								<?php endforeach ?>

								<div class="row static-info">
			                        <div class="col-xs-5 name">欠款：</div>
			                        <div class="col-xs-7 value text-right red">
			                        	<font color="red"><?php echo $model->o_s->current_arrears ?></font>  元
			                        </div>
			                    </div>
			                    <div class="row static-info">
			                        <div class="col-xs-5 name">实收现金：</div>
			                        <div class="col-xs-7 value text-right">
			                        	<font color="yellow"><?php echo $model->o_s->cash+$model->o_s->cash_pos+$model->o_s->cash_tra+$model->o_s->cash_other ?></font> 元
			                        	
			                        </div>
			                    </div>
			                    <?php if($model->o_s->cash>0): ?>
			                    <div class="row static-info">
			                        <div class="col-xs-5 name">现金支付：</div>
			                        <div class="col-xs-7 value text-right">
			                        	<?php echo $model->o_s->cash ?> 元
			                        </div>
			                    </div>
				                <?php endif; ?>
			                    <?php if($model->o_s->cash_pos>0): ?>
			                    <div class="row static-info">
			                        <div class="col-xs-5 name">POS刷卡：</div>
			                        <div class="col-xs-7 value text-right">
			                        	<?php echo $model->o_s->cash_pos ?> 元
			                        </div>
			                    </div>
				                <?php endif; ?>
			                    <?php if($model->o_s->cash_tra>0): ?>
			                    <div class="row static-info">
			                        <div class="col-xs-5 name">银行转账：</div>
			                        <div class="col-xs-7 value text-right">
			                        	<?php echo $model->o_s->cash_tra ?> 元
			                        </div>
			                    </div>
				                <?php endif; ?>
			                    <?php if($model->o_s->cash_other>0): ?>
			                    <div class="row static-info">
			                        <div class="col-xs-5 name">其他方式支付：</div>
			                        <div class="col-xs-7 value text-right"><?php echo $model->o_s->cash_other ?> 元</div>
			                    </div>
				                <?php endif; ?>
		                	<?php endif; ?>

		                    <div class="row static-info">
		                        <div class="col-xs-5 name">总价(原价)：</div>
		                        <div class="col-xs-7 value text-right">
		                             <font class="order_old_money">0</font> 元
		                        </div>
		                    </div>

		                    <div class="row static-info">
		                        <div class="col-xs-5 name">抵扣总价：</div>
		                        <div class="col-xs-7 value text-right">
		                             <font class="order_dk_money">0</font> 元
		                        </div>
		                    </div>
		                    <div class="row static-info">
		                        <div class="col-xs-5 name">折扣率：</div>
		                        <div class="col-xs-7 value text-right">
		                             <font class="order_rate">100</font> %
		                        </div>
		                    </div>

		                    <div class="row static-info">
		                        <div class="col-xs-5 name">应付总金额：</div>
		                        <div class="col-xs-7 value text-right">
		                             <font class="order_money">100</font> 元
		                        </div>
		                    </div>

		                    <div class="row static-info">
		                        <div class="col-xs-5 name">已优惠：</div>
		                        <div class="col-xs-7 value text-right">
		                             - <font class="order_yh_money">0</font> 元
		                        </div>
		                    </div>


		                    <div class="row static-info">
		                        <div class="col-xs-5 name">订单状态：</div>
		                        <div class="col-xs-7 value text-right">
		                        	<span class="label label-warning label-sm"><?php echo \OrderSale::getPayStatus($model->o_s->pay_status);?></span>
		                        	<?php if($model->o_s->rh_id):?>
		                    		<span class="label label-success label-sm">新客入会</span>
		                			<?php endif;?>
		                        </div>
		                    </div>
		                    <div class="row static-info">
		                        <div class="col-xs-5 name">购买商品：</div>
		                        <div class="col-xs-7 value text-right">
		                        	<font class="order_pro_num">0</font> 件
		                        </div>
		                    </div>

		                	</div>

						
	                </div>
	            </div>
	        </div>

	        <div class="col-md-6 col-sm-12">
	            <div class="portlet solid red-intense">
	                <div class="portlet-body" style="padding-top: 10px;">
	                    <?php echo $cu_info ?>
	                </div>
	            </div>
	        </div>
        </div>



		<!--销售人员及业绩比例-->
		<?php echo $effect ?>
		<!--销售人员及业绩比例!end-->

		<!--购买项目-->
		<div class="pos_cz_tow box_xm">
			<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>购买项目</div>
			<div class="pos_cz_tow_two">
				<!--table_container-->
				<div class="table_container">
				<!--table_con-->
				<div class="table_con" >
					<!--table_con_son-->
					<div class="table_con_son table-responsive">
						<table class="table table-bordered table-hover pos_table">
							<thead>
								<tr>
									<th style="min-width:150px;">项目</th>
									<th>疗次</th>
									<th>原价</th>
									<th>面折率</th>
									<th>赠送账户抵扣</th>
									<th>现金账户抵扣</th>
									<th>欠款</th>
									<th>应付金额</th>
									<th>活动</th>
								</tr>
							</thead>
							<tbody>

								<?php if ($model): ?>
									<?php $project_arrears=0; foreach ($model->pros as $pro): ?>
										<?php if($pro['pro_type']!=1) continue; ?>
										<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

										<tr data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" class="table_list">
												<td class="li001"><?php echo $info->name ?>(<?php echo $info->num*$info->price ?>元/<?php echo $info->num ?>疗次)</td>
												<td class="li002"><?php echo $pro['num'] ?></td>
												<td class="li003"><?php echo $pro['price'] ?></td>
												<td class="li004"><?php echo $pro['rebate'] ?>%</td>
												<td class="li005 zszh"><?php  echo $pro['card_gift']; ?></td>
												<td class="li009 xjzh"><?php  echo $pro['card_cash']; ?></td>
												<td class="li009"><?php $project_arrears+=$pro['arrears']; echo $pro['arrears'] ?></td>
												<td class="li006"><?php echo $pro['pay_price']; ?></td>
												<td class="li007"><?php echo $hd_list[$pro['promotion_id']] ?></td>
										</tr>
									<?php endforeach ?>
								<?php endif ?>
									
							</tbody>
						</table>


						
					</div><!--table_con_son!end-->
				</div><!--table_con!end-->
				</div>
				<!--table_containter!end-->
				<div class="pos_cz_tow_two_two pos_gm_02_border_top">
					<span class="pos_cz_tow_two04 ">应付金额：<em class="all_xm_money">0</em>&nbsp;元</span>
					<span class="pos_gm_01">购买项目<span class="pos_gm_03 all_xm_num">0</span>个</span>
					<span class="pos_gm_01">总价小计(原价)：<span class="pos_gm_04">￥<font class="all_xm_money_old">0</font></span></span>
					<span class="pos_gm_01">抵扣小计：<span class="pos_gm_04">-￥<font class="all_xm_money_dk">0</font></span></span>
					<span class="pos_gm_01">面折率：<span class="pos_gm_04"><font class="all_xm_money_zk">0</font>%</span></span>
					<span class="pos_gm_01">项目欠款：<span class="pos_gm_04">￥<font><?php echo $project_arrears;?></font></span></span>
				</div>
			</div>
		</div><!--购买项目!end-->


		<!--购买产品-->
		<div class="pos_cz_tow box_cp">
			<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>购买产品</div>
			<div class="pos_cz_tow_two">
				<!--table_container-->  
				<div class="table_container" >
				<!--table_con-->
				<div class="table_con" >
					<!--table_con_son-->
					<div class="table_con_son table-responsive">

						<table class="table table-bordered table-hover pos_table">
							<thead>
								<tr>
									<th style="min-width:100px;">产品</th>
									<th>数量</th>
									<th>原价</th>
									<th>面折率</th>
									<th>赠送账户抵扣</th>
									<th>现金账户抵扣</th>
									<th>欠款</th>
									<th>应付金额</th>
									<th>活动</th>
								</tr>
							</thead>
							<tbody>

								<?php if ($model): ?>
									<?php $product_arrears=0; foreach ($model->pros as $pro): ?>
									<?php if($pro['pro_type']!=2) continue; ?>
									<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

									<tr data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" class="table_list">
										<td class="li001"><?php echo $info->name ?></td>
										<td class="li002"><?php echo $pro['num'] ?>(<?php echo $info->unit ?>)</td>
										<td class="li003"><?php echo $pro['price'] ?></td>
										<td class="li004"><?php echo $pro['rebate'] ?>%</td>
										<td class="li005 zszh"><?php  echo $pro['card_gift']; ?></td>
										<td class="li009 xjzh"><?php  echo $pro['card_cash']; ?></td>
										<td class="li009"><?php $product_arrears+=$pro['arrears']; echo $pro['arrears'] ?></td>
										<td class="li006"><?php echo $pro['pay_price']; ?></td>
										<td class="li007"><?php echo $hd_list[$pro['promotion_id']] ?></td>
									</tr>
									<?php endforeach ?>
								<?php endif ?>
									
							</tbody>
						</table>

						
					</div><!--table_con_son!end-->
				</div><!--table_con!end-->
				</div>
				<!--table_containter!end-->
				<div class="pos_cz_tow_two_two pos_gm_02_border_top">
					<span class="pos_cz_tow_two04">应付金额：<em class="all_cp_money">0</em>&nbsp;元</span>
					<span class="pos_gm_01">购买产品<span class="pos_gm_03 all_cp_num">0</span>个</span>
					<span class="pos_gm_01">总价小计(原价)：<span class="pos_gm_04">￥<font class="all_cp_money_old">0</font></span></span>
					<span class="pos_gm_01">抵扣小计：<span class="pos_gm_04">-￥<font class="all_cp_money_dk">0</font></span></span>
					<span class="pos_gm_01">面折率：<span class="pos_gm_04"><font class="all_cp_money_zk">0</font>%</span></span>
					<span class="pos_gm_01">产品欠款：<span class="pos_gm_04">￥<font><?php echo $product_arrears;?></font></span></span>
				</div>
			</div>
		</div><!--购买产品!end-->


		<!--购买卡券-->
		<div class="pos_cz_tow box_kq">
			<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>购买卡券</div>
			<div class="pos_cz_tow_two">
				<!--table_container-->  
				<div class="table_container">
				<!--table_con-->
				<div class="table_con">
					<!--table_con_son-->
					<div class="table_con_son table-responsive">

						<table class="table table-bordered table-hover pos_table">
							<thead>
								<tr>
									<th style="min-width:100px;">卡券</th>
									<th>数量</th>
									<th>原价</th>
									<th>面折率</th>
									<th>赠送账户抵扣</th>
									<th>现金账户抵扣</th>
									<th>欠款</th>
									<th>应付金额</th>
									<th>活动</th>
								</tr>
							</thead>
							<tbody>

								<?php if ($model): ?>
									<?php $voucher_arrears=0; foreach ($model->pros as $pro): ?>
									<?php if($pro['pro_type']!=3) continue; ?>
									<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

									<tr data-sold="<?php echo $info->sold_num ?>" data-num="<?php echo $info->num ?>" data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>"  data-zs="<?php echo $pro['money_str'] ?>" class="table_list">
											<td class="li001"><?php echo $info->name ?></td>
											<td class="li002"><?php echo $pro['num'] ?></td>
											<td class="li003"><?php echo $pro['price'] ?></td>
											<td class="li004"><?php echo $pro['rebate'] ?>%</td>
											<td class="li005 zszh"><?php  echo $pro['card_gift']; ?></td>
											<td class="li009 xjzh"><?php  echo $pro['card_cash']; ?></td>
											<td class="li009"><?php $voucher_arrears+=$pro['arrears']; echo $pro['arrears'] ?></td>
											<td class="li006"><?php echo $pro['pay_price'] ?></td>
											<td class="li007"><?php echo $hd_list[$pro['promotion_id']] ?></td>
									</tr>
									<?php endforeach ?>
								<?php endif ?>
									
							</tbody>
						</table>

						
					</div><!--table_con_son!end-->
				</div><!--table_con!end-->
				</div>
				<!--table_containter!end-->
				<div class="pos_cz_tow_two_two pos_gm_02_border_top">
					<span class="pos_cz_tow_two04">应付金额：<em class="all_kq_money">0</em>&nbsp;元</span>
					<span class="pos_gm_01">购买卡券<span class="pos_gm_03 all_kq_num">0</span>个</span>
					<span class="pos_gm_01">总价小计(原价)：<span class="pos_gm_04">￥<font class="all_kq_money_old">0</font></span></span>
					<span class="pos_gm_01">抵扣小计：<span class="pos_gm_04">-￥<font class="all_kq_money_dk">0</font></span></span>
					<span class="pos_gm_01">面折率：<span class="pos_gm_04"><font class="all_kq_money_zk">0</font>%</span></span>
					<span class="pos_gm_01">卡券欠款：<span class="pos_gm_04">￥<font><?php echo $voucher_arrears;?></font></span></span>
				</div>
			</div>
		</div><!--购买卡券!end-->


		<!--赠送-->
		<?php echo $gift ?>
		<!--赠送!end-->



		<!--备注-->
		<div class="pos_cz_tow pos_cz_for_bz">
			<div class="pos_cz_for_bz01">备注</div>
			<div class="pos_cz_for_bz02">
				<div class="pos_cz_for_bz02_son"><?php echo $model?$model->o_s->note:"" ?></div>
			</div>
		</div><!--备注!end-->

		<!---->
		

	</div>
</div>
<!--content_right_con!end-->



<!-- 选择账户分配弹出 -->
<div style="display:none">
	<div class="zszhdk">
		<div class="pos_gm_th_01">购买《肽美白》1疗次，原价：1000 元</div>
		<!--table_container-->  
		<div class="table_container">
			<!--table_con-->
			<div class="table_con pos_cz_qr_top_04">

				<!--table_con_son-->
				<div class="table_con_son" >
					<table class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>账户类型</th>
								<th>余额(元)</th>
								<th>抵扣金额(元)</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div><!--table_con_son!end-->

			</div><!--table_con!end-->
		</div>
		<!--table_containter!end-->
	</div>
</div>
<!-- 选择账户分配弹出 end-->

{__TOKEN__}



<script type="text/javascript">

$(function(){
	change_total();
	
	//默认空值收起
	$(".pos_cz_tow_top_r").each(function(i){
		var self=$(this);
		var num = self.parent().next().find('.pos_gm_03').html();
		if(num=='0'){
			self.html('展开').addClass("pos_cz_tow_top_rcl");//收起
			self.parent().next().hide();
		}
	});

	//收起效果
	$(".pos_cz_tow_top_r").click(function(){
		var self=$(this);
		self.parent().next().slideToggle("fast",function(){
			//alert("Animation Done.");
			if(self.hasClass("pos_cz_tow_top_rcl")){
				self.html('收起').removeClass("pos_cz_tow_top_rcl");
			}else{
				self.html('展开').addClass("pos_cz_tow_top_rcl");
			}
		});
		
	});

	


	//项目 赠送账户抵扣分配
	$('.box_xm,.box_cp,.box_kq').on('click','.zszh',function(){
		var table_list = $(this).closest('.table_list');
		var capital_money=table_list.attr("data-zs");
		var d = Idialog({
			top:150,
			width:500,
			title:'赠送账户抵扣',
			content:$('.zszhdk'),
			cancel:false,
			init:function(content){
				var titlestr="购买《"+table_list.find('.li001').html()+"》"+table_list.find('.li002').html()+"次，原价："+table_list.find('.li003').html()+" 元"
				content.find('.pos_gm_th_01').html(titlestr);

				$.each( capital_zs, function(i, capital){
					var money = str_money(capital_money,capital.id);
					var s_list ='<tr class="table_list">';
						s_list+='<td class="li001">'+capital.name+'</td>';
						s_list+='<td class="li002">'+capital.balance+'</td>';
						s_list+='<td class="li003">'+money+'</td>';
						s_list+='</tr>';
						content.find('tbody').append(s_list);
				});
			},
		});
	});

	//项目 现金账户抵扣分配
	$('.box_xm,.box_cp,.box_kq').on('click','.xjzh',function(){
		var table_list = $(this).closest('.table_list');
		var capital_money=table_list.attr("data-zs");
		var d = Idialog({
			top:150,
			width:500,
			title:'现金账户抵扣',
			content:$('.zszhdk'),
			cancel:false,
			init:function(content){
				var titlestr="购买《"+table_list.find('.li001').html()+"》"+table_list.find('.li002').html()+"次，原价："+table_list.find('.li003').html()+" 元"
				content.find('.pos_gm_th_01').html(titlestr);

				$.each( capital_xj, function(i, capital){
					var money = str_money(capital_money,capital.id);
					var s_list ='<tr class="table_list">';
						s_list+='<td class="li001">'+capital.name+'</td>';
						s_list+='<td class="li002">'+capital.balance+'</td>';
						s_list+='<td class="li003">'+money+'</td>';
						s_list+='</tr>';
						content.find('tbody').append(s_list);
				});
			},
		});
	});



	//获取具体账户金额
	function str_money(money_str,capital_id){
		var res = 0;
		if(money_str){
			var arr=money_str.split(",");
			$.each( arr, function(i, n){
				var c_m=this.split("|");
				if(c_m[0]==capital_id) res = c_m[1];
			});
		}
		return res;
	}

	//同步修改 box小计
	function change_total(){
		//同步修改 box小计
		$.each( ['xm','cp','kq'], function(i, boxname){
			$('.all_'+boxname+'_num').html($('.box_'+boxname+' .table_list').length);
			$('.all_'+boxname+'_money_old').html(eval($('.box_'+boxname+' .li003').map(function(){
				return $(this).html();
			}).get().join('+')));
			$('.all_'+boxname+'_money_dk').html(eval($('.box_'+boxname+' .li005').map(function(){
				var zs_all=$.isNumeric($(this).html())?$(this).html():0;//赠送抵扣额
				return zs_all;
			}).get().join('+')));
			$('.all_'+boxname+'_money').html(eval($('.box_'+boxname+' .li006').map(function(){
				return $(this).html();
			}).get().join('+')));
			var all_zk=(parseInt($('.all_'+boxname+'_money').html())+parseInt($('.all_'+boxname+'_money_dk').html()))/$('.all_'+boxname+'_money_old').html()*100;
			if($('.all_'+boxname+'_money_old').html()==0) all_zk=0; //除数为0
			$('.all_'+boxname+'_money_zk').html( all_zk.toFixed(2) );
		});

		change_all();
	}
	//项目产品卡券价格联动 end
	
	//同步整单数据
	function change_all(){
		var money=0;//应付总金额
		money+=parseInt($('.all_xm_money').html());
		money+=parseInt($('.all_cp_money').html());
		money+=parseInt($('.all_kq_money').html());

		var dk_money=0;//总抵扣金额
		dk_money+=parseInt($('.all_xm_money_dk').html());
		dk_money+=parseInt($('.all_cp_money_dk').html());
		dk_money+=parseInt($('.all_kq_money_dk').html());

		var old_money=0;//总原价
		old_money+=parseInt($('.all_xm_money_old').html());
		old_money+=parseInt($('.all_cp_money_old').html());
		old_money+=parseInt($('.all_kq_money_old').html());

		var num=0;//总商品数量
		num+=parseInt($('.all_xm_num').html());
		num+=parseInt($('.all_cp_num').html());
		num+=parseInt($('.all_kq_num').html());

		$('.order_old_money').html(old_money);
		$('.order_money').html(money);
		$('.order_dk_money').html(dk_money);
		$('.order_pro_num').html(num);
		$('.order_yh_money').html(old_money-money);
		if(old_money==0) return;
		$('.order_rate').html((money/old_money*100).toFixed(2));


	}


	$(".to_print").click(function(){
		$(".print_show").printArea();
	});


});
</script>