<div class="wrapper wrapper-content">
	<!-- 月数据 -->
    <div class="row">
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-success pull-right">月</span>
                    <h5>销售业绩</h5>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins"><?php echo $target['xj_m'] ?></h1>
                    <div class="stat-percent font-bold text-danger">目标：<?php echo $target['sale_target'] ?> <i class="fa fa-bolt"></i>
                    </div>
                    <small>总业绩</small>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-success pull-right">月</span>
                    <h5>实操业绩</h5>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins"><?php echo $target['sc_m'] ?></h1>
                    <div class="stat-percent font-bold text-danger">目标：<?php echo $target['prac_target'] ?> <i class="fa fa-bolt"></i>
                    </div>
                    <small>实操金额</small>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-success pull-right">月</span>
                    <h5>客流量</h5>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins"><?php echo $target['kk_m'] ?></h1>
                    <div class="stat-percent font-bold text-warning">成交人头：<?php echo $target['cj_m'] ?> <i class="fa fa-bolt"></i>
                    </div>
                    <small>月客流</small>
                </div>
            </div>
        </div>
    </div>
    <!-- 日数据 -->
    <div class="row">
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-info pull-right">今日</span>
                    <h5>销售业绩</h5>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins"><?php echo $target['xj_d'] ?></h1>
                    <div class="stat-percent font-bold text-info">完成率：<?php echo round($target['xj_m']/$target['sale_target'],2)*100 ?>% <i class="fa fa-level-up"></i>
                    </div>
                    <small>现金业绩</small>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-info pull-right">今日</span>
                    <h5>实操业绩</h5>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins"><?php echo $target['sc_d'] ?></h1>
                    <div class="stat-percent font-bold text-navy">完成率：<?php echo round($target['sc_m']/$target['prac_target'],2)*100 ?>% <i class="fa fa-level-up"></i>
                    </div>
                    <small>实操金额</small>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <span class="label label-info pull-right">今日</span>
                    <h5>客流量</h5>
                </div>
                <div class="ibox-content">
                    <h1 class="no-margins"><?php echo $target['kk_d'] ?></h1>
                    <div class="stat-percent font-bold text-navy">成交人头：<?php echo $target['cj_d'] ?> <i class="fa fa-level-up"></i>
                    </div>
                    <small>客流</small>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                	<a href="javascript:" >
                    <span class="label label-danger pull-right chart_b" data="container">业绩</span>
                    <span class="label label-warning pull-right chart_b" data="container1">客流</span>
                    </a>
                    <h5>本月数据曲线图</h5>
                </div>
                <div class="ibox-content">
                    
					<div id="container" style="height: 300px;"></div>
			        <div id="container1" style="height: 300px;"></div>
					
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <span class="label label-warning pull-right"><?php echo $out["A"]+$out["B"]+$out["C"]+$out["D"]+$out["E"] ?></span>
                    <h5>30天内将流失客户数</h5>
                </div>
                <div class="ibox-content">
	                <div class="row">
	                	<div class="col-lg-4">
	                        <div class="widget style1 red-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=A">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">A类客户：<?php echo $out["A"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                    <div class="col-lg-4">
	                        <div class="widget style1 yellow-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=B">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">B类客户：<?php echo $out["B"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                    <div class="col-lg-4">
	                        <div class="widget style1 blue-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=C">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">C类客户：<?php echo $out["C"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                </div>
	                <div class="row">
	                	<div class="col-lg-4">
	                        <div class="widget style1 navy-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=D">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">D类客户：<?php echo $out["D"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                    <div class="col-lg-4">
	                        <div class="widget style1 gray-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=E">
		                            <div class="row vertical-align">
		                                <div class="col-xs-3">
		                                    <i class="fa fa-user fa-3x"></i>
		                                </div>
		                                <div class="col-xs-9 text-right">
		                                    <h2 class="font-bold">E类客户：<?php echo $out["E"] ?></h2>
		                                </div>
		                            </div>
	                            </a>
	                        </div>
	                    </div>
	                </div>
					
                </div>
            </div>
        </div>
    </div>

</div>


<script src="<?php echo $this->basePath('public');?>/js/Highcharts/highcharts.js"></script>
<!-- <script src="<?php echo $this->basePath('public');?>/js/Highcharts/modules/exporting.js"></script> -->
<script src="<?php echo $this->basePath('public');?>/js/Highcharts/modules/draggable-legend.js"></script>

<!--content_right_con!end-->
<script type="text/javascript">
$(function () {
	$('#container').highcharts({
		title: {
			text: '',
			x: -20 //center
		},
		colors: ['#91e8e1','#f15c80','#e4d354', '#8085e9','#7cb5ec',   '#90ed7d', '#434348',  '#8085e8', '#8d4653', '#f7a35c'],
		subtitle: {
			text: '',
			x: -20
		},
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: { // don't display the dummy year
				day: '%e日'   
			}
		},
		exporting: {
			enabled: false
		},
		yAxis: {
			title: {
				text: ''
			},
			plotLines: [{
				value: 0,
				width: 1,
				color: '#808080'
			}]
		},
		tooltip: {
			enabled: true,
			crosshairs: true,
			formatter: function() {
				return Highcharts.dateFormat('%e', this.x)+'日<br><b>'+ this.series.name +'</b>: '+ this.y +'元';
			}
		},
		legend: {
			layout: 'vertical',
			backgroundColor: 'white',
			align: 'right',
			verticalAlign: 'top',
			y: 20,
			x: -20,
			borderWidth: 1,
			borderRadius: 0,
			title: {
				text: ':: 拖动'
			},
			floating: true,
			draggable: true,
			zIndex: 20
		},
		series: [{
			name: '现金业绩',
			data: [
			<?php 
			$str=array();
			foreach($data['sale_list'] as $index=>$v){
				$str[] = "[Date.UTC(".date('Y').",".(date('n')-1).",$index),$v]";//UTC 时间月份减1 0~11
			}
			echo implode(",",$str);
			?>]
		}, {
			name: '现金实耗',
			data: [
			<?php 
			$str=array();
			foreach($data['prac_list'] as $index=>$v){
				$str[] = "[Date.UTC(".date('Y').",".(date('n')-1).",$index),$v]";
			}
			echo implode(",",$str);
			?>]
		}]
	});
	
	$('#container1').highcharts({
		title: {
			text: '',
			x: -20 //center
		},
		subtitle: {
			text: '',
			x: -20
		},
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: { // don't display the dummy year
				day: '%e日'   
			}
		},
		exporting: {
			enabled: false
		},
		yAxis: {
			title: {
				text: ''
			},
			plotLines: [{
				value: 0,
				width: 1,
				color: '#808080'
			}]
		},
		tooltip: {
			enabled: true,
			crosshairs: true,
			formatter: function() {
				return Highcharts.dateFormat('%e', this.x)+'日<br><b>'+ this.series.name +'</b>: '+ this.y +'人';
			}
		},
		legend: {
			layout: 'vertical',
			backgroundColor: 'white',
			align: 'right',
			verticalAlign: 'top',
			y: 20,
			x: -20,
			borderWidth: 1,
			borderRadius: 0,
			title: {
				text: ':: 拖动'
			},
			floating: true,
			draggable: true,
			zIndex: 20
		},
		series: [{
			name: '到店客流',
			data: [
			<?php 
			$str=array();
			foreach($data['kk_list'] as $index=>$v){
				$str[] = "[Date.UTC(".date('Y').",".(date('n')-1).",$index),$v]";
			}
			echo implode(",",$str);
			?>]
		}]
	});
	$("#container1").hide(); 
	
	
   
	$(".chart_b").click(function(){
		var forid=$(this).attr('data');
		$("#container").hide();
		$("#container1").hide();
		$("#"+forid).show();
	});
	
});

</script>