<style type="text/css">
    .dashboard-stat .details .number{padding-top: 10px;}
</style>
<!-- BEGIN DASHBOARD STATS -->
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat blue-madison">
            <div class="visual">
                <i class="fa fa-comments"></i>
            </div>
            <div class="details">
                <div class="number">
                     <?php echo $target['xj_m'] ?>
                </div>
                <div class="desc">
                     月销售业绩
                </div>
                <div class="desc">目标：<?php echo $target['sale_target'] ?></div>
            </div>
            <a class="more" href="#">
            View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat green-haze">
            <div class="visual">
                <i class="fa fa-shopping-cart"></i>
            </div>
            <div class="details">
                <div class="number">
                     <?php echo $target['sc_m'] ?>
                </div>
                <div class="desc">
                     月实操业绩
                </div>
                <div class="desc">目标：<?php echo $target['prac_target'] ?></div>
            </div>
            <a class="more" href="#">
            View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat purple-plum">
            <div class="visual">
                <i class="fa fa-globe"></i>
            </div>
            <div class="details">
                <div class="number">
                     <?php echo $target['kk_m'] ?>
                </div>
                <div class="desc">
                     月客流
                </div>
                <div class="desc">成交人头：<?php echo $target['cj_m'] ?></div>
            </div>
            <a class="more" href="#">
            View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat red-intense">
            <div class="visual">
                <i class="fa fa-bar-chart-o"></i>
            </div>
            <div class="details">
                <div class="number">
                     <?php echo $target['xj_d'] ?>
                </div>
                <div class="desc">
                     日销售业绩
                </div>
                <div class="desc">完成率：<?php echo round($target['xj_m']/$target['sale_target'],2)*100 ?>%</div>

            </div>
            <a class="more" href="#">
            View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat green-haze">
            <div class="visual">
                <i class="fa fa-shopping-cart"></i>
            </div>
            <div class="details">
                <div class="number">
                     <?php echo $target['sc_d'] ?>
                </div>
                <div class="desc">
                     日实操业绩
                </div>
                <div class="desc">完成率：<?php echo round($target['sc_m']/$target['prac_target'],2)*100 ?>%</div>
            </div>
            <a class="more" href="#">
            View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="dashboard-stat purple-plum">
            <div class="visual">
                <i class="fa fa-globe"></i>
            </div>
            <div class="details">
                <div class="number">
                     <?php echo $target['kk_d'] ?>
                </div>
                <div class="desc">
                     日客流
                </div>
                <div class="desc">成交人头：<?php echo $target['cj_d'] ?></div>
            </div>
            <a class="more" href="#">
            View more <i class="m-icon-swapright m-icon-white"></i>
            </a>
        </div>
    </div>
</div>
<!-- END DASHBOARD STATS -->
<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="portlet solid bordered grey-cararra">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-bar-chart-o"></i>本月数据曲线图
                </div>
                <div class="actions">
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn grey-steel btn-sm active chart_b" data="container">
                        <input type="radio" name="options" class="toggle" >业绩</label>
                        <label class="btn grey-steel btn-sm chart_b" data="container1">
                        <input type="radio" name="options" class="toggle" >客流</label>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div id="container" class="chart"></div>
                <div id="container1" class="chart"></div>
            </div>
        </div>
    </div>
</div>




<div class="wrapper wrapper-content">
	


    


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <div class="ibox-title">
                    <span class="label label-warning pull-right"><?php echo $out["A"]+$out["B"]+$out["C"]+$out["D"]+$out["E"] ?></span>
                    <h5>30天内将流失客户数</h5>
                </div>
                <div class="ibox-content">
	                <div class="row">
	                	<div class="col-lg-4">
	                        <div class="widget style1 red-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=A">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">A类客户：<?php echo $out["A"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                    <div class="col-lg-4">
	                        <div class="widget style1 yellow-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=B">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">B类客户：<?php echo $out["B"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                    <div class="col-lg-4">
	                        <div class="widget style1 blue-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=C">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">C类客户：<?php echo $out["C"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                </div>
	                <div class="row">
	                	<div class="col-lg-4">
	                        <div class="widget style1 navy-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=D">
	                            <div class="row vertical-align">
	                                <div class="col-xs-3">
	                                    <i class="fa fa-user fa-3x"></i>
	                                </div>
	                                <div class="col-xs-9 text-right">
	                                    <h2 class="font-bold">D类客户：<?php echo $out["D"] ?></h2>
	                                </div>
	                            </div>
	                            </a>
	                        </div>
	                    </div>
	                    <div class="col-lg-4">
	                        <div class="widget style1 lazur-bg">
	                        	<a style="color:#fff" href="<?php echo $this->url("customer/index/outlist") ?>&cu_type=E">
		                            <div class="row vertical-align">
		                                <div class="col-xs-3">
		                                    <i class="fa fa-user fa-3x"></i>
		                                </div>
		                                <div class="col-xs-9 text-right">
		                                    <h2 class="font-bold">E类客户：<?php echo $out["E"] ?></h2>
		                                </div>
		                            </div>
	                            </a>
	                        </div>
	                    </div>
	                </div>
					
                </div>
            </div>
        </div>
    </div>

</div>


<script src="<?php echo $this->basePath('public');?>/js/Highcharts/highcharts.js"></script>
<!-- <script src="<?php echo $this->basePath('public');?>/js/Highcharts/modules/exporting.js"></script> -->
<script src="<?php echo $this->basePath('public');?>/js/Highcharts/modules/draggable-legend.js"></script>

<!--content_right_con!end-->
<script type="text/javascript">
$(function () {
	$('#container').highcharts({
		title: {
			text: '',
			x: -20 //center
		},
		colors: ['#91e8e1','#f15c80','#e4d354', '#8085e9','#7cb5ec',   '#90ed7d', '#434348',  '#8085e8', '#8d4653', '#f7a35c'],
		subtitle: {
			text: '',
			x: -20
		},
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: { // don't display the dummy year
				day: '%e日'   
			}
		},
		exporting: {
			enabled: false
		},
		yAxis: {
			title: {
				text: ''
			},
			plotLines: [{
				value: 0,
				width: 1,
				color: '#808080'
			}]
		},
		tooltip: {
			enabled: true,
			crosshairs: true,
			formatter: function() {
				return Highcharts.dateFormat('%e', this.x)+'日<br><b>'+ this.series.name +'</b>: '+ this.y +'元';
			}
		},
		legend: {
			layout: 'vertical',
			backgroundColor: 'white',
			align: 'right',
			verticalAlign: 'top',
			y: 20,
			x: -20,
			borderWidth: 1,
			borderRadius: 0,
			title: {
				text: ':: 拖动'
			},
			floating: true,
			draggable: true,
			zIndex: 20
		},
		series: [{
			name: '现金业绩',
			data: [
			<?php 
			$str=array();
			foreach($data['sale_list'] as $index=>$v){
				$str[] = "[Date.UTC(".date('Y').",".(date('n')-1).",$index),$v]";//UTC 时间月份减1 0~11
			}
			echo implode(",",$str);
			?>]
		}, {
			name: '现金实耗',
			data: [
			<?php 
			$str=array();
			foreach($data['prac_list'] as $index=>$v){
				$str[] = "[Date.UTC(".date('Y').",".(date('n')-1).",$index),$v]";
			}
			echo implode(",",$str);
			?>]
		}]
	});
	
	$('#container1').highcharts({
		title: {
			text: '',
			x: -20 //center
		},
		subtitle: {
			text: '',
			x: -20
		},
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: { // don't display the dummy year
				day: '%e日'   
			}
		},
		exporting: {
			enabled: false
		},
		yAxis: {
			title: {
				text: ''
			},
			plotLines: [{
				value: 0,
				width: 1,
				color: '#808080'
			}]
		},
		tooltip: {
			enabled: true,
			crosshairs: true,
			formatter: function() {
				return Highcharts.dateFormat('%e', this.x)+'日<br><b>'+ this.series.name +'</b>: '+ this.y +'人';
			}
		},
		legend: {
			layout: 'vertical',
			backgroundColor: 'white',
			align: 'right',
			verticalAlign: 'top',
			y: 20,
			x: -20,
			borderWidth: 1,
			borderRadius: 0,
			title: {
				text: ':: 拖动'
			},
			floating: true,
			draggable: true,
			zIndex: 20
		},
		series: [{
			name: '到店客流',
			data: [
			<?php 
			$str=array();
			foreach($data['kk_list'] as $index=>$v){
				$str[] = "[Date.UTC(".date('Y').",".(date('n')-1).",$index),$v]";
			}
			echo implode(",",$str);
			?>]
		}]
	});
	$("#container1").hide(); 
	
	
   
	$(".chart_b").click(function(){
		var forid=$(this).attr('data');
		$("#container").hide();
		$("#container1").hide();
		$("#"+forid).show();
	});
	
});

</script>