<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>meihui</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link rel="stylesheet" href="<?php echo $this->basePath('public/h5/assets');?>/css/amazeui.min.css"/>
    <link rel="stylesheet" href="<?php echo $this->basePath('public/h5/assets');?>/css/app.css"/>

    <link rel="stylesheet" href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>" >
    <script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>"></script>

</head>
<body class="login-page">
<div class="am-text-center">
    <img class="logo" src="<?php echo $this->basePath('public/h5/assets');?>/i/logo.png">
</div>
<section>
    <form id="login-form" method="post" class="am-form">
        <fieldset>
            <div class="am-form-group am-form-icon">
                <i class="am-icon-user"></i>
                <input class="am-form-field no-border" type="text" name="user_name" placeholder="请输入您的账户">
            </div>
            <hr>
            <div class="am-form-group am-form-icon">
                <i class="am-icon-lock"></i>
                <input class="am-form-field no-border" type="password" name="password" placeholder="请输入您的密码">
            </div>
            <hr>
            <div class="am-form-group am-form-icon captcha">
                <i class="am-icon-shield"></i>
                <input class="am-form-field no-border" type="text" name="verifyCode" placeholder="请输入验证码">
                <img id="verify" onclick="changeVerify()" src="<?php echo $this->url('verify'); ?>" width="150" height="45">
            </div>
        </fieldset>
        <div class="am-padding-sm">
            <input type="submit" value="登 录" class="am-btn am-btn-primary am-btn-block am-padding-sm">
        </div>
    </form>
</section>
<footer class="am-text-center copyright fixed-bottom">
    <div>美慧商业软件</div>
    <div>meihui Business Technology Copyright</div>
</footer>
</body>
</html>

<script type="text/javascript">
//提交前验证
$('form').Validform({
    tiptype:3,
    ignoreHidden:true,
    beforeSubmit:function() {
        var next = false;
        var ajax_url = "<?php echo $this->url('validate'); ?>";
        var data = $('form').serialize();
        $.ajax({
            url : ajax_url,
            data : data,
            type : 'POST',
            async : false,
            dataType : 'json',
            complete : function() {
            },
            success : function(json) {
                if(json.code == '200') {
                    next = true;
                }else{
                    alert(json.msg);
                }
            }
        });
        return next;
    }
});
function changeVerify() {
    var timestamp=new Date().getTime();
    var url = "<?php echo $this->url('verify'); ?>";
    url += '&timestamp=' + timestamp;
    $("#verify").attr('src', url);
}
</script>
