<script src="<?php echo $this->basePath('public') ?>/laydate/laydate.js" type="text/javascript"></script>

<div class="add_store" title="新增活动">
  <div class="tjfj_two">
    <form method="post" action="<?php echo $this->url('add') ?>" class="form">
      <div class="list"><label>活动名称：</label><div style="margin-left: 100px;"><input type="text" class="gysgl_07 inputxt" name="title" value="<?php echo $model->title; ?>"/></div></div>
      <div class="list"><label>开始时间：</label><div style="margin-left: 100px;"><input type="text" class="gysgl_07 laydate-icon" name="start_time" value="<?php echo date("Y-m-d H:i:s",$model->start_time); ?>"  onclick="laydate(laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss',event: 'focus'}))" style=" width:150px;"/></div></div>
      <div class="list"><label>结束时间：</label><div style="margin-left: 100px;"><input type="text" class="gysgl_07 laydate-icon" name="end_time" value="<?php echo date("Y-m-d H:i:s",$model->end_time); ?>"  onclick="laydate(laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss',event: 'focus'}))" style=" width:150px;"/></div></div>
      <div class="list"><label>活动方案：</label><div style="margin-left: 100px;">

      <textarea rows="3"  style="width: auto;" name="note"><?php echo $model->note; ?></textarea>
      </div></div>
    	<input name="id" type="hidden" value="<?php echo $model->id ?>" />
    </form>
  </div>
</div>