<link href="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_style.css" rel="stylesheet">
<link href="<?php echo $this->basePath('public');?>/css/oldAdmin.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_v5.3.2_min.js"></script>
<script src="<?php echo $this->basePath('public') ?>/laydate/laydate.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/PCASClass.js"></script>

<div class="row">
	<div class="col-md-12">
		<div class="portlet no_mb">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-users"></i>活动管理
				</div>
				<div class="actions btn-set">
					<a href="<?php echo $this->url('edit') ?>" class="btn default yellow-stripe tjfjz"><i class="fa fa-plus"></i>新增活动</a>
				</div>
			</div>
		</div>

<?php echo $this->datagrid(array(
	'id'=>'list',
	'dataProvider'=>$pager,
	'search'=>false,
	'columns'=>array(
		array(
			'header' => '活动名称',
			'name'  => 'title',
		),
		array(
			'header' => '活动时间',
			'name'  => 'time',
			'value'=>'{date("Y-m-d H:i",$data["start_time"])."至".date("Y-m-d H:i",$data["end_time"])}'
		),
		array(
			'header' => '活动方案',
			'name'  => 'note',
		),
		array(
			'header' => '状态',
			'name' => 'status',
			'value'=>'{\SaleNoticeInfo::getStatus($data["id"])}'
		),
		array(
			'header' => '操作',
			'rel'=>'id',
			'template'=>'<a rel="{$data[id]}" href="javascript:" class="btn default btn-xs red-stripe change">{$data["status"]==0?"启用":"停用"}</a>
				<a href="javascript:" class="btn default btn-xs blue-stripe edit">修改</a>'
		)
	),
));?>
	</div>
</div>




<!--tjfj-->

<div class="add_store none" title="新增门店">
  <div class="tjfj_two">
    <form method="post" action="<?php echo $this->url('add') ?>" class="form">
      <div class="list"><label>活动名称：</label><div style="margin-left: 100px;"><input type="text"  class="gysgl_07 inputxt" name="title"/></div></div>
      <div class="list"><label>开始时间：</label><div style="margin-left: 100px;"><input type="text" class="gysgl_07 laydate-icon" name="start_time" onclick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss',event: 'focus'})" style=" width:150px;"/></div></div>
      <div class="list"><label>结束时间：</label><div style="margin-left: 100px;"><input type="text"  class="gysgl_07 laydate-icon" name="end_time" onclick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss',event: 'focus'})" style=" width:150px;"/></div></div>
      <div class="list"><label>活动方案：</label><div style="margin-left: 100px;">
      
      <textarea rows="3" style="width: auto;" name="note"></textarea>
      </div>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">

function validate(classname){
	var nf = classname.Validform({
		tiptype:3,
	});

	nf.addRule([
	{
		ele:".new_inputxt:eq(0)",
		datatype:"*",
		nullmsg:"请输入活动名称！"
	}
	]);
}


	//添加活动
	$(document).on('click','.tjfjz',function(){
		var d = Idialog({
			top:120,
			width:500,
			title:'新增活动',
			content:$('.add_store'),
			ok:function(obj){
				obj._self.find('form').submit();
				return false;
			},
			init:function(self){
				self.find("form").attr("class","newform");
				self.find(".inputxt").attr("class","new_inputxt");

				validate($('.newform'));
			}
		});
	});
	
	$(document).on('click','.delete',function(){
		var obj = $(this).parent().parent();
		var id = $(this).parent().attr('rel');

		var d = Idialog({
			top:120,
			width:500,
			title:'通知',
			content:'您确认删除吗？',
			ok:function(html){
				$.get("<?php echo $this->url('delete') ?>", { id: id },function(html){
					var jobj = $.parseJSON(html);
					if(jobj['code']=='200'){
						var d = Idialog({
							top:120,
							width:500,
							title:'通知',
							content:'删除成功',
							ok:function(html){
								obj.remove();
								return true;
							},
							cancel:false,
						});
					}else{
						var d = Idialog({
							top:120,
							width:500,
							title:'通知',
							content:'删除失败',
							ok:function(obj){
								return true;
							},
							cancel:false,
						});
					}
				});
				return true;
			},
			cancel:true,
		});
	});
	
	$(document).on('click','.change',function(){
		var obj = $(this).parent().parent();
		var id = $(this).parent().attr('rel');
		var thisobj = $(this);
		$.get("<?php echo $this->url('change') ?>", { id: id },function(html){
			var jobj = $.parseJSON(html);
			var dataobj = jobj['data'];
			var status = dataobj['status'];
			//thisobj.html(status==1?"启用":"<fone style='color:red'>停用</font>");
			thisobj.html(status==0?"启用":"停用");
			thisobj.attr('style',status==0?'':'background-color: #ddd;color: #666;');
			thisobj.parent().prev().attr('title',status==1?"启用":"停用").html(status==1?"启用":'<fone style="color:red">停用</fone>');
		});
	});
	
	$(document).on('click','.edit',function(){
		var obj = $(this).parent().parent();
		var id = $(this).parent().attr('rel');
		var thisobj = $(this);
		$.get("<?php echo $this->url('edit') ?>", { id: id },function(html){
			var d = Idialog({
				top:120,
				width:500,
				title:'编辑活动',
				content:html,
				ok:function(obj){
					obj._self.find('form').submit();
					return false;
				},
				init:function(self){
					self.find("form").attr("class","newform");
					self.find(".inputxt").attr("class","new_inputxt");

					validate($('.newform'));
				},
			});
		});
	});
</script>