<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>系统错误</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="" name="description"/>
<meta content="" name="author"/>
<link href="<?php echo $this->basePath('public/M'); ?>/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath('public/M'); ?>/admin/pages/css/error.css" rel="stylesheet" type="text/css"/>
<link rel="shortcut icon" href="favicon.ico"/>
</head>
<body class="page-404-3">
<div class="page-inner">
	<img src="<?php echo $this->basePath('public/M'); ?>/admin/pages/media/pages/earth.jpg" class="img-responsive" alt="">
</div>
<div class="container error-404">
	<h1><?php echo $code; ?></h1>
	<h2>Sorry...闹情绪啦！</h2>
	<p>
		<?php echo $msg; ?>
	</p>
	<p>
		<a href="<?php echo $this->url('/'); ?>">返回首页</a>
	</p>
</div>
</body>
</html>