<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js" charset="utf-8"></script>
<?php 
	$md_list=\EmployDept::getList(true);
    if ($this->controller->is_store)
        $_GET['dept_id']=\Ivy::app()->user->dept_id;
?>
<div class="row">
    <div class="col-md-12 ">
        <div class="note note-info">
            <div class="top_com">
                <span class="spanl">门店范围：</span>
                <div class="choose_md">
                <?php if(!$this->controller->is_store):?>
                <a href="javascript:" rel="0"><span >全连锁</span></a>
                <?php endif;?>
                <?php foreach ($md_list as $key => $value): ?>
                <a href="javascript:" rel="<?php echo $key ?>"><span><?php echo $value ?></span></a>
                <?php endforeach ?>
                </div>
            </div>
            
            <div class="top_com stime">
                <span class="spanl">日期：</span>
                <span  id="choose_time">
                    <select id="year">
                        <?php $_year = date('Y');?>
                        <?php for($i=0;$i<=4;$i++):?>
                            <option <?php echo $year==$_year-$i?'selected="selected"':''?> value="<?php echo $_year-$i;?>"><?php echo $_year-$i;?>年</option>
                        <?php endfor;?>
                    </select>
                    <select id="month">
                        <?php for($i=1;$i<=12;$i++):?>
                            <option <?php echo $month==$i?'selected="selected"':''?> value="<?php echo $i;?>"><?php echo $i<10?'0'.$i:$i;?>月</option>
                        <?php endfor;?>
                    </select>
                </span>
            </div>

            <a href="javascript:" class="btn btn-sm btn-success changa01">搜索</a>
            <a href="javascript:;" download="美容师服务分析表.xls" class="btn btn-sm purple-plum to_excel">导出</a>
        </div>
    </div>

    <div class="col-md-12" id="order-list">
        <table class="table table-bordered table-striped table-hover table-bb">
            <thead>
                <tr>
                    <th>日期</th>
                    <th>服务人次</th>
                    <th>人均服务人次</th>
                    <?php foreach($mrs_list as $mrs):?>
                    <th><?php echo $mrs?></th>
                    <?php endforeach;?>
                </tr>
            </thead>
            <tbody>
            <?php if ($data): ?>
            <?php $ddkl = 0; $pjkl = 0; $mrskl = array();?>
            <?php foreach ($data as $_data): ?>
                <tr>
                    <td><?php echo $_data['DATE'];?></td>
                    <td><?php echo $_data['DDKL'];?></td>
                    <td><?php echo $_data['PJKL'];?></td>
                    <?php foreach($mrs_list as $key=>$mrs):?>
                    <td><?php echo $_data['MRS'][$key];?></td>
                    <?php $mrskl[$key] += $_data['MRS'][$key];?>
                    <?php endforeach;?>

                    <?php
                    $ddkl += $_data['DDKL'];
                    $pjkl += $_data['PJKL'];
                    ?>
                </tr> 
            <?php endforeach ?>
                <tr class="table_weight">
                    <td>合计</td>
                    <td><?php echo $ddkl;?></td>
                    <td><?php echo $pjkl;?></td>
                    <?php foreach($mrs_list as $key=>$mrs):?>
                        <td><?php echo $mrskl[$key];?></td>
                    <?php endforeach;?>
                </tr> 
            <?php endif ?>
            </tbody>
        </table>
    </div>

</div>




<script type="text/javascript">
$(function(){
    //门店范围选择
    $(".choose_md a").click(function(){
        $(".choose_md span").removeClass("span_01");
        $(this).find("span").addClass("span_01");
    });


//填充默认门店
<?php if (isset($_GET['dept_id'])): ?>
    <?php foreach (explode(',', $_GET['dept_id']) as $v): ?>
        $(".choose_md").find("a[rel='<?php echo $v ?>']").trigger("click");
    <?php endforeach ?>
<?php endif ?>

    function getMd(){
        if($(".choose_md a[rel='0']").find("span").hasClass("span_01"))
            return "0";
        var l = $(".choose_md a").map(function(){
            if($(this).find("span").hasClass("span_01"))
                return $(this).attr("rel");
        }).get().join(",");
        return l;
    }


    $(".changa01").click(function(){
        var dept_id=getMd();
        if(dept_id==''){
            Idialog.tips('门店未选择！',2);
            return;
        }
        var year = $("#year").val();
        var month = $("#month").val();
        var url="<?php echo $this->url('FWFX')?>";
        window.location.href = url+'&dept_id='+dept_id+'&year='+year+'&month='+month;
    });

    
    $(".to_excel").click(function(event){
        var t = Itable2excel({
            worksheet:'数据分析',
            table: $('#order-list table')
        });
        var data64 = t.uri();
        if(data64==false)
            return false;
        event.currentTarget.href = data64;
    });
});
</script>