<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js" charset="utf-8"></script>
<?php 
	$md_list=\EmployDept::getList(true);
    if ($this->controller->is_store)
        $_GET['dept_id']=\Ivy::app()->user->dept_id;
?>
<!--content_right_con-->
<div class="content_right_con">
    <div class="content_right_con_top">
        <div class="fjgl_top_r">
            <span><a href="#" download="美容师服务分析表.xls"class="to_excel fjgl_top_r_05">导出</a></span>
        </div>
        <div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>数据报表><span>美容师服务分析表</span>
    </div>

    <!--sjbb_ddkl_one-->
    <div class="sjbb_ddkl_one">
        <ul>
            <li>
                <div class="sjbb_ddkl_one_l">门店范围：</div>
                <div class="sjbb_ddkl_one_r">
                    <div class="sjbb_ddkl_one_r_son">
                        <?php foreach ($md_list as $key => $value): ?>
                            <a href="javascript:" rel="<?php echo $key ?>" class="changa02 <?php echo $_GET['dept_id']==$key?'changa01':''?>"><?php echo $value ?></a>
                        <?php endforeach ?>
                    </div>
                    <input id="dept_id" value="<?php echo $_GET['dept_id']?>" type="hidden">
                </div>
            </li>
            <li>
                <div class="sjbb_ddkl_one_l">日期：</div>
                <div class="sjbb_ddkl_one_r">
                    <div class="sjbb_ddkl_one_r_son">
                        <select id="year" class="sjbb_ddkl_one_r_son_01">
                            <?php $_year = date('Y');?>
                            <?php for($i=0;$i<=4;$i++):?>
                                <option <?php echo $year==$_year-$i?'selected="selected"':''?> value="<?php echo $_year-$i;?>"><?php echo $_year-$i;?>年</option>
                            <?php endfor;?>
                        </select>
                        <select id="month" class="sjbb_ddkl_one_r_son_01">
                            <?php for($i=1;$i<=12;$i++):?>
                                <option <?php echo $month==$i?'selected="selected"':''?> value="<?php echo $i;?>"><?php echo $i<10?'0'.$i:$i;?>月</option>
                            <?php endfor;?>
                        </select>
                    </div>
                </div>
            </li>

            <li class="lastli">
                <div class="sjbb_ddkl_one_l">
                </div>
                <div class="sjbb_ddkl_one_r">
                    <div class="sjbb_ddkl_one_r_son">
                        <a href="javascript:" class="changa01" id="search">搜索</a>
                    </div>
                </div>
            </li>
        </ul>
    </div> <!--sjbb_index_onesjbb_ddkl_oneend-->

    <!--table_container-->
    <div id="order-list" class="table_table table_center">
        <div class="table_hiddle">
        <table width="100%" cellspacing="0" cellpadding="0" border="0" last-float="false">
            <thead>
                <tr class="table_title">
                    <th>日期</th>
                    <th>服务人次</th>
                    <th>人均服务人次</th>
                    <?php foreach($mrs_list as $mrs):?>
                    <th><?php echo $mrs?></th>
                    <?php endforeach;?>
                </tr>
            </thead>
            <tbody>
            <?php if ($data): ?>
            <?php $ddkl = 0; $pjkl = 0; $mrskl = array();?>
            <?php foreach ($data as $_data): ?>
                <tr class="table_list clear">
                    <td><?php echo $_data['DATE'];?></td>
                    <td><?php echo $_data['DDKL'];?></td>
                    <td><?php echo $_data['PJKL'];?></td>
                    <?php foreach($mrs_list as $key=>$mrs):?>
                    <td><?php echo $_data['MRS'][$key];?></td>
                    <?php $mrskl[$key] += $_data['MRS'][$key];?>
                    <?php endforeach;?>

                    <?php
                    $ddkl += $_data['DDKL'];
                    $pjkl += $_data['PJKL'];
                    ?>
                </tr> 
            <?php endforeach ?>
                <tr class="table_list table_weight clear">
                    <td>合计</td>
                    <td><?php echo $ddkl;?></td>
                    <td><?php echo $pjkl;?></td>
                    <?php foreach($mrs_list as $key=>$mrs):?>
                        <td><?php echo $mrskl[$key];?></td>
                    <?php endforeach;?>

                </tr> 
            <?php endif ?>
            </tbody>
        </table>
        </div><!--table_hiddle!end-->
    </div>
    <!--table_container-->






</div>
<!--content_right_con!end-->


<script type="text/javascript">
$(function(){
	//门店范围选择
	$(".changa02").click(function(){
		var rel = $(this).attr("rel");
        $(this).siblings().removeClass('changa01');
        if($(this).hasClass('changa01')){
            $(this).removeClass('changa01');
            $("#dept_id").val('');
        }else{
            $(this).addClass('changa01');
            $("#dept_id").val(rel);
        }
	});

    $("#search").click(function(){
        var dept_id = $("#dept_id").val();
        if(dept_id==''){
            alert('请选择门店！');
            return false;
        }
        var year = $("#year").val();
        var month = $("#month").val();
        var url="<?php echo $this->url('FWFX')?>";
        window.location.href = url+'&dept_id='+dept_id+'&year='+year+'&month='+month;
    });

    
    $(".to_excel").click(function(event){
        var t = Itable2excel({
            worksheet:'数据分析',
            table: $('#order-list table')
        });
        var data64 = t.uri();
        if(data64==false)
            return false;
        event.currentTarget.href = data64;
    });
});
</script>