<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itime.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js"></script>
<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="fjgl_top_r"><span><a href="#" download="负债分析表.xls"class="to_excel fjgl_top_r_05">导出</a></span></div>
		数据报表><span>负债分析表</span>
	</div>

	<!--sjbb_ddkl_one-->
    <div class="sjbb_ddkl_one">
        <ul>
			<li>
				<div class="sjbb_ddkl_one_l">日期：</div>
				<div class="sjbb_ddkl_one_r">
					<div class="sjbb_ddkl_one_r_son" id="choose_time">
					</div>
				</div>
			</li>
            <li class="lastli">
                <div class="sjbb_ddkl_one_l">
                </div>
                <div class="sjbb_ddkl_one_r">
                    <div class="sjbb_ddkl_one_r_son">
                        <a href="javascript:" class="changa01" id="search">搜索</a>
                    </div>
                </div>
            </li>
        </ul>
    </div> <!--sjbb_index_onesjbb_ddkl_oneend-->

	<!--table_table-->	
	<div id='order-list' class='table_table table_center'>
		<div class='table_hiddle'>
		<table width='100%' cellspacing='0' cellpadding='0' border='0' last-float='false'>
			<thead>
				<tr class='table_title'>
					<th >门店</th>
					<th >上月现金账户余额</th>
					<th >本月现金账户卡扣</th>
					<th >本月现金账户余额</th>
					<th >上月赠送账户余额</th>
					<th >本月赠送账户卡扣</th>
					<th >本月赠送账户余额</th>
					<th >上月疗程账户余额</th>
					<th >本月疗程账户消耗</th>
					<th >本月疗程账户余额</th>
				</tr>
			</thead>
			<tbody>

			<?php foreach ($list as $k => $row): ?>
				<tr class='table_list'>
					<td ><?php echo $row['dept_name'] ?></td>
					<td ><?php echo $list_pre[$k]['xjye']?:"/" ?></td>
					<td ><?php echo $list_kk[$k]['xjkk']?:"/" ?></td>
					<td ><?php echo $row['xjye']?:"/" ?></td>
					<td ><?php echo $list_pre[$k]['zsye']?:"/" ?></td>
					<td ><?php echo $list_kk[$k]['zskk']?:"/" ?></td>
					<td ><?php echo $row['zsye']?:"/" ?></td>
					<td ><?php echo $list_pre[$k]['lcye']?:"/" ?></td>
					<td ><?php echo $list_kk[$k]['lcxh']?:"/" ?></td>
					<td ><?php echo $row['lcye']?:"/" ?></td>
				</tr>
			<?php endforeach ?>
			<?php if (!$list&&!$list_pre): ?>
				<tr class='table_list'>
					<td colspan=12 >暂无数据</td>
				</tr>
			<?php endif ?>

			</tbody>
		</table>
		</div><!--table_hiddle!end-->
	</div><!--table_table!end-->


	
</div>
<!--content_right_con!end-->

<script type="text/javascript">
$(function(){
	var t = Itime({
		content:$('#choose_time'),
		endoff:true,
		<?php if (isset($_GET['month'])): ?>
		begin:'<?php echo $_GET["month"] ?>', //填充默认时间
		<?php endif ?>
		//end:'201507', //默认当前时间
		type:'m',  	  // 日 模式
	})._self.find('a,br').remove(); 

    $("#search").click(function(){
        var times=$(".itime").find(".b_y").val()+''+$(".itime").find(".b_m").val();
        var url="<?php echo $this->url('FZFX')?>";
        window.location.href = url+'&month='+times;
    });

	$(".to_excel").click(function(event){
		var t = Itable2excel({
			worksheet:'数据分析',
			table: $('#order-list table')
		});
		var data64 = t.uri();
		if(data64==false)
			return false;
		event.currentTarget.href = data64;
	});
});
</script>