<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		数据报表
	</div>
	<div class="shuju_list">
		<div class="shuju_list_left"><span><img src="<?php echo $this->basePath("public") ?>/images/shuju_ico1.png" width="25" height="25" /></span>业绩报表</div>
		<div class="shuju_list_right">
			<a class="hot_a" href="<?php echo $this->url('MDYJ') ?>">门店业绩报表</a>
			<a href="<?php echo $this->url('PLYJ') ?>">品类业绩报表</a>
			<a href="<?php echo $this->url('PXYJBB') ?>">品项业绩报表</a>
			<a class="hot_a" href="<?php echo $this->url('RYYJ') ?>">人员业绩报表</a>
		</div>
		<div class="clear"></div>
	</div>
	<div class="shuju_list">
		<div class="shuju_list_left"><span><img src="<?php echo $this->basePath("public") ?>/images/shuju_ico2.png" width="25" height="25" /></span>客流报表</div>
		<div class="shuju_list_right">
			<a class="hot_a" href="<?php echo $this->url('DDKL') ?>">到店客流报表</a>
			<a href="<?php echo $this->url('FWFX') ?>">美容师服务表</a>
			<a href="<?php echo $this->url('YKLFX') ?>">月客流分析表</a>
			<a href="<?php echo $this->url('XKFX') ?>">新客分析表</a>
		</div>
		<div class="clear"></div>
	</div>
	<div class="shuju_list">
		<div class="shuju_list_left"><span><img src="<?php echo $this->basePath("public") ?>/images/shuju_ico3.png" width="25" height="25" /></span>经营报表</div>
		<div class="shuju_list_right">
			<a class="hot_a" href="<?php echo $this->url('JYBB') ?>">经营报告</a>
			<a href="<?php echo $this->url('XJLS') ?>">现金流水表</a>
			<a href="<?php echo $this->url('FZFX') ?>">负债分析表</a>
			<a href="<?php echo $this->url('TKFX') ?>">退款分析表</a>
			<a href="<?php echo $this->url('KHGMFX') ?>">客户购买分析表</a>
			<a href="<?php echo $this->url('KHNXFFX') ?>">客户年消费分析表</a>
			<a href="<?php echo $this->url('KHSHFX') ?>">客户实耗分析表</a>
			<a href="<?php echo $this->url('XMFGFX') ?>">项目覆盖分析表</a>
		</div>
		<div class="clear"></div>
	</div>
</div>
<!--content_right_con!end-->
