<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itime.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js"></script>
<?php 
	$md_list=\EmployDept::getList(true);
?>
<div class="row">
    <div class="col-md-12 ">
        <div class="note note-info">
            <div class="top_com">
                <span class="spanl">门店范围：</span>
                <div class="choose_md">
                <?php if(!$this->controller->is_store):?>
                <a href="javascript:" rel="0"><span >全连锁</span></a>
                <?php endif;?>
                <?php foreach ($md_list as $key => $value): ?>
                <a href="javascript:" rel="<?php echo $key ?>"><span><?php echo $value ?></span></a>
                <?php endforeach ?>
                </div>
            </div>
            
            <div class="top_com stime">
                <span class="spanl">日期：</span>
                <span  id="choose_time">
                </span>
            </div>

            <a href="javascript:" class="btn btn-sm btn-success changa01">搜索</a>
            <a href="javascript:;" download="经营报表.xls" class="btn btn-sm purple-plum to_excel">导出</a>
        </div>

    <!--  模版引擎扩展 -->
	<?php echo $this->datagrid(array(
		'id'=>'order-list',
		'dataProvider'=>array('list'=>$model),
	    'search'=>false,
		'columns'=>array(
			array(
				'header' => '门店',
				'name'   => 'dept_name',
			),
			array(
				'header' => '现金收入 <a href="javascript:;" class="action_xjsr">查看</a>',
				'name'   => 'XJSR',
			),
			array(
				'header' => '现金卡扣 <a href="javascript:;" class="action_xjhk">查看</a>',
				'name'   => 'XJKK',
			),
			array(
				'header' => '现金实耗业绩 <a href="javascript:;" class="action_shyj">查看</a>',
				'name'   => 'XJSHYJ',
			),
			array(
				'header' => '到店客流 <a href="javascript:;" class="action_kl">查看</a>',
				'name'   => 'DDKL',
			),
			array(
				'header' => '成交人头 <a href="javascript:;" class="action_kl">查看</a>',
				'name'   => 'CJRT',
			),
			
		),
	));?>

    </div>
</div>    


<script type="text/javascript">
$('.action_xjsr').click(function(event) {
	var _url=window.location.href;
	_url= _url.replace("JYBB","JYBB_XJSR");
	$.get(_url, function(html) {
		var d = Idialog({
				top:120,
				width:800,
				title:'现金收入',
				content:html,
				ok:true,
				cancel:false
			});
		
	});
});
$('.action_xjhk').click(function(event) {
	var _url=window.location.href;
	_url= _url.replace("JYBB","JYBB_KKYJ");
	$.post(_url,{},function(html) {
		var d = Idialog({
			top:75,
			width:800,
			title:'卡扣业绩',
			content:html,
			ok:true,
			cancel:false
		});
		
	});
});
$('.action_shyj').click(function(event) {
	var _url=window.location.href;
	_url= _url.replace("JYBB","JYBB_SHYJ");  
	$.get(_url, function(html) {
		var d = Idialog({
				top:120,
				width:800,
				title:'实耗业绩',
				content:html,
				ok:true,
				cancel:false
			});
		
	});
});
$('.action_kl').click(function(event) {
	var _url=window.location.href;
	_url= _url.replace("JYBB","JYBB_KL");  
	$.get(_url, function(html) {
		var d = Idialog({
				top:120,
				width:800,
				title:'客流总汇',
				content:html,
				ok:true,
				cancel:false
			});
		
	});
});
$(function(){
	var t = Itime({
		content:$('#choose_time'),
		endoff:true,
		<?php if (isset($_GET['times'])): ?>
		begin:'<?php echo str_replace('-','',$_GET["times"])?>', //填充默认时间
		<?php endif ?>
		//end:'201507', //默认当前时间
		type:'<?php echo $_GET["type"]?$_GET["type"]:"d"; ?>',  	  // 日 模式
	}); 

	//门店范围选择
	$(".choose_md a").click(function(){
		var rel=$(this).attr("rel");
		if($(this).find("span").hasClass("span_01")){
			$(this).find("span").removeClass("span_01");
			if(rel=="0")
				$(".choose_md span").removeClass("span_01");
		}else{
			$(this).find("span").addClass("span_01");
			if(rel=="0")
				$(".choose_md span").addClass("span_01");
		}
	});



<?php if ($this->controller->is_store): ?>
		$(".choose_md").find("a").trigger("click");
		<?php if (!isset($_GET['md_ids'])):?>
		$(function(){
		$(".changa01").trigger("click");
		})
		<?php endif; ?>
<?php else: ?>
//填充默认门店
<?php if (isset($_GET['md_ids'])): ?>
	<?php foreach (explode(',', $_GET['md_ids']) as $v): ?>
		$(".choose_md").find("a[rel='<?php echo $v ?>']").trigger("click");
	<?php endforeach ?>
<?php endif ?>
<?php endif ?>

	//搜索提交
	$(".changa01").click(function(){
		var md_ids=getMd();
		if(md_ids==''){
			Idialog.tips('门店未选择！',2);
			return;
		}
		var type=$('.itime').find('.changa').attr('rel');
		if (type=='y') {
			var times=$(".itime").find(".b_y").val();
		}else if (type=='m') {
			var times=$(".itime").find(".b_y").val()+'-'+$(".itime").find(".b_m").val();
		}else{
			var times=$(".itime").find(".b_y").val()+'-'+$(".itime").find(".b_m").val()+'-'+$(".itime").find(".b_d").val();
		}
		to_url('<?php echo $this->url("JYBB") ?>&md_ids='+md_ids+'&times='+times+'&type='+type);

	});

	function getMd(){
		if($(".choose_md a[rel='0']").find("span").hasClass("span_01"))
			return "0";
		var l = $(".choose_md a").map(function(){
			if($(this).find("span").hasClass("span_01"))
				return $(this).attr("rel");
		}).get().join(",");
		return l;
	}

	$(".to_excel").click(function(event){
		var t = Itable2excel({
			worksheet:'数据分析',
			table: $('#order-list table')
		});
		var data64 = t.uri();
		if(data64==false)
			return false;
		event.currentTarget.href = data64;
	});

});
</script>