

<!--table_container-->
<div class="table_container">
	<!--table_con-->
	<div class="table_con table-responsive">
		<!--table_con_son-->

		<div class="pos_cz_tow_top pos_cz_qr_02" style="color: #07aaff;">现金账户卡扣</div>
		<table class="table_con_son table table-bordered table-hover">
			<tr>
				
					<td>业务明细</td>
					<?php foreach ($md_info as $dept_name):?>
						<td><?php echo $dept_name;?></td>
					<?php endforeach;?>
				
			</tr>
			<tr>
				
					<td class="li001">购买项目/疗程</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo $data[$dept_id]['gm_xm'];?></td>
						<?php $gm_total[$dept_id] += $data[$dept_id]['gm_xm'];?>
					<?php endforeach;?>
				
			</tr>
			<tr>
				
					<td class="li001">购买产品</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo $data[$dept_id]['gm_cp'];?></td>
						<?php $gm_total[$dept_id] += $data[$dept_id]['gm_cp'];?>
					<?php endforeach;?>
				
			</tr>
			<tr>
				
					<td class="li001">购买卡券</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo $data[$dept_id]['gm_kq'];?></td>
						<?php $gm_total[$dept_id] += $data[$dept_id]['gm_kq'];?>
					<?php endforeach;?>
				
			</tr>
			<tr>
				
					<td class="li001">现金还款</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo $data[$dept_id]['gm_hk'];?></td>
						<?php $gm_total[$dept_id] += $data[$dept_id]['gm_hk'];?>
					<?php endforeach;?>
				
			</tr>
			<tr>
				
					<td class="li001">合计</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo sprintf('%.2f',$gm_total[$dept_id]);?></td>
					<?php endforeach;?>
				
			</tr>
		</table><!--table_con_son!end-->
	</div>
	<!--table_con!end-->
</div>
<!--table_containter!end-->
<!--table_container-->
<div class="table_container">
	<!--table_con-->
	<div class="table_con table-responsive">
		<!--table_con_son-->
		<div class="pos_cz_tow_top pos_cz_qr_02" style="color: #07aaff;">赠送账户卡扣</div>
		<table class="table_con_son table table-bordered table-hover">
			<tr>
				
					<td>业务明细</td>
					<?php foreach ($md_info as $dept_name):?>
						<td><?php echo $dept_name;?></td>
					<?php endforeach;?>
				
			</div>
			<tr>
				
					<td class="li001">购买项目/疗程</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo $data[$dept_id]['zs_xm'];?></td>
						<?php $zs_total[$dept_id] += $data[$dept_id]['zs_xm'];?>
					<?php endforeach;?>
				
			</div>
			<tr>
				
					<td class="li001">购买产品</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo $data[$dept_id]['zs_cp'];?></td>
						<?php $zs_total[$dept_id] += $data[$dept_id]['zs_cp'];?>
					<?php endforeach;?>
				
			</div>
			<tr>
				
					<td class="li001">购买卡券</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo $data[$dept_id]['zs_kq'];?></td>
						<?php $zs_total[$dept_id] += $data[$dept_id]['zs_kq'];?>
					<?php endforeach;?>
				
			</tr>
			<tr>
				
					<td class="li001">合计</td>
					<?php foreach ($md_info as $dept_id=>$dept_name):?>
						<td class="li002"><?php echo sprintf('%.2f',$zs_total[$dept_id]);?></td>
					<?php endforeach;?>
				
			</tr>
		</table><!--table_con_son!end-->
	</div>
	<!--table_con!end-->
</div>
<!--table_containter!end-->