<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itime.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js"></script>
<?php 
	$md_list=\EmployDept::getList(true);
	$prod_cate=\ProCate::getProductTopCate();
	$proj_cate=\ProCate::getProjectTopCate();
?>

<div class="row">
	<div class="col-md-12 ">
		<div class="note note-info">
			<div class="top_com">
				<span class="spanl">门店范围：</span>
				<div class="choose_md">
				<?php if(!$this->controller->is_store):?>
				<a href="javascript:" rel="0"><span >全连锁</span></a>
				<?php endif;?>
				<?php foreach ($md_list as $key => $value): ?>
				<a href="javascript:" rel="<?php echo $key ?>"><span><?php echo $value ?></span></a>
				<?php endforeach ?>
				</div>
			</div>
			<div class="top_com">
				<span class="spanl">项目范围：</span>
				<div class="choose_xm">
					<?php foreach ($proj_cate as $key => $value): ?>
					<a href="javascript:" rel="<?php echo $key ?>"><span><?php echo $value ?></span></a>
					<?php endforeach ?>
				</div>
			</div>
			<div class="top_com">
				<span class="spanl">产品范围：</span>
				<div class="choose_cp">
					<?php foreach ($prod_cate as $key => $value): ?>
					<a href="javascript:" rel="<?php echo $key ?>"><span><?php echo $value ?></span></a>
					<?php endforeach ?>
				</div>
			</div>
			<div class="top_com stime">
				<span class="spanl">日期：</span>
				<span  id="choose_time"></span>
			</div>

			<a href="javascript:" class="btn btn-sm btn-success changa01">搜索</a>
			<a href="javascript:;" download="品类业绩报表.xls" class="btn btn-sm purple-plum to_excel">导出</a>
		</div>
	</div>

	<div class="col-md-12" id="order-list">
		<table class="table table-bordered table-striped table-hover table-bb">
			<thead>
				<tr class="up_title">
					<th rowspan="2">品类</th>
					<th colspan="3">购买</th>
					<th colspan="3">实操</th>
				</tr>
				<tr>
					<th>现金收入</th>
					<th>现金账户卡扣</th>
					<th>赠送账户卡扣</th>
					<th>购买消耗</th>
					<th>赠送消耗</th>
					<th>卡券消耗</th>
				</tr>
			</thead>
			<tbody>
			<?php if ($list): ?>
			<?php foreach ($list as $v): ?>
				<tr >
					<td><?php echo $v['name'] ?></td>
					<td><?php echo $v['cash'] ?></td>	<?php $a_cash+=$v['cash']; ?>
					<td><?php echo $v['card'] ?></td>	<?php $a_card+=$v['card']; ?>
					<td><?php echo $v['gift'] ?></td>	<?php $a_gift+=$v['gift']; ?>
					<td><?php $p1 = \Utils::searchArr('buy_type',1, $v['practice'],"money");echo $p1; ?></td><?php $a_p1+=$p1; ?>
					<td><?php $p2 = \Utils::searchArr('buy_type',2, $v['practice'],"money");echo $p2; ?></td><?php $a_p2+=$p2; ?>
					<td><?php $p3 = \Utils::searchArr('buy_type',3, $v['practice'],"money");echo $p3; ?></td><?php $a_p3+=$p3; ?>
				</tr> 
				<?php endforeach ?>
				<tr class="table_weight clear">
					<td>合计</td>
					<td><?php echo $a_cash ?></td>
					<td><?php echo $a_card ?></td>
					<td><?php echo $a_gift ?></td>
					<td><?php echo $a_p1 ?></td>
					<td><?php echo $a_p2 ?></td>
					<td><?php echo $a_p3 ?></td>
				</tr> 
			<?php endif ?>
			</tbody>
		</table>
	</div>

</div>



<script type="text/javascript">

$(function(){

	var t = Itime({
		content:$('#choose_time'),
		<?php if (isset($_GET['begin'])): ?>
		begin:'<?php echo $_GET["begin"]?>', //填充默认时间
		<?php endif ?>
		<?php if (isset($_GET['end'])): ?>
		end:'<?php echo $_GET["end"]?>', //填充默认时间
		<?php endif ?>
		//type:'d',  	  // 日 模式
	})._self.find("a,br").remove();

	//门店、范围选择
	$(".choose_md a,.choose_xm a,.choose_cp a").click(function(){
		var rel=$(this).attr("rel");
		if($(this).find("span").hasClass("span_01")){
			$(this).find("span").removeClass("span_01");
			if(rel=="0")
				$(".choose_md span").removeClass("span_01");
		}else{
			$(this).find("span").addClass("span_01");
			if(rel=="0")
				$(".choose_md span").addClass("span_01");
		}
	});

	
	<?php if ($this->controller->is_store): ?>
		$(".choose_md").find("a").trigger("click");
	<?php else: ?>
	//填充默认门店
	<?php if (isset($_GET['md_id'])): ?>
	<?php foreach (explode(',', $_GET['md_id']) as $v): ?>
		$(".choose_md").find("a[rel='<?php echo $v ?>']").trigger("click");
	<?php endforeach ?>
	<?php endif ?>
	<?php endif ?>
	//填充默认项目
	<?php if (isset($_GET['xm'])): ?>
	<?php foreach (explode(',', $_GET['xm']) as $v): ?>
		$(".choose_xm").find("a[rel='<?php echo $v ?>']").trigger("click");
	<?php endforeach ?>
	<?php endif ?>
	//填充默认产品
	<?php if (isset($_GET['cp'])): ?>
	<?php foreach (explode(',', $_GET['cp']) as $v): ?>
		$(".choose_cp").find("a[rel='<?php echo $v ?>']").trigger("click");
	<?php endforeach ?>
	<?php endif ?>

	function getMd(){
		if($(".choose_md a[rel='0']").find("span").hasClass("span_01"))
			return "0";
		var l = $(".choose_md a").map(function(){
			if($(this).find("span").hasClass("span_01"))
				return $(this).attr("rel");
		}).get().join(",");
		return l;
	}
	function getXm(){
		var l = $(".choose_xm a").map(function(){
			if($(this).find("span").hasClass("span_01"))
				return $(this).attr("rel");
		}).get().join(",");
		return l;
	}
	function getCp(){
		var l = $(".choose_cp a").map(function(){
			if($(this).find("span").hasClass("span_01"))
				return $(this).attr("rel");
		}).get().join(",");
		return l;
	}

	//搜索提交
	$(".changa01").click(function(){
		var md_id=getMd();
		if(md_id==''){
			Idialog.tips('门店未选择！',2);
			return;
		}
		var xm=getXm();
		var cp=getCp();
		if(xm==''&&cp==''){
			Idialog.tips('项目、产品未选择！',2);
			return;
		}

		var begin=$(".itime").find(".b_y").val()+""+$(".itime").find(".b_m").val()+""+$(".itime").find(".b_d").val();
		var end  =$(".itime").find(".e_y").val()+""+$(".itime").find(".e_m").val()+""+$(".itime").find(".e_d").val();
		to_url('<?php echo $this->url("PLYJ") ?>&md_id='+md_id+'&begin='+begin+'&end='+end+'&xm='+xm+'&cp='+cp);
	});


	$(".to_excel").click(function(event){
		var t = Itable2excel({
			worksheet:'数据分析',
			table: $('#order-list table')
		});
		var data64 = t.uri();
		if(data64==false){
			return false;
		}
		event.currentTarget.href = data64;
	});

});
</script>