<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itime.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js"></script>
<?php 
	$md_list=\EmployDept::getList(true);
	if($_GET['user_ids']){
		$user_list = \EmployUser::model()->field("id,netname")->findAll("id IN (".$_GET['user_ids'].")");
	}
?>
<div class="row">
	<div class="col-md-12 ">
		<div class="note note-info">
			<div class="top_com">
				<span class="spanl">门店范围：</span>
				<div class="choose_md">
				<?php if(!$this->controller->is_store):?>
				<a href="javascript:" rel="0"><span >全连锁</span></a>
				<?php endif;?>
				<?php foreach ($md_list as $key => $value): ?>
				<a href="javascript:" rel="<?php echo $key ?>"><span><?php echo $value ?></span></a>
				<?php endforeach ?>
				</div>
			</div>
			<div class="top_com">
				<span class="spanl">人员选择：</span>
				<div class="user_list">
					<button type="button" class="btn yellow btn-xs c_add">请选择</button>
					<?php foreach ($user_list as $v):?>
					<a href="javascript:" data-id="<?php echo $v['id'] ?>"><span class="span_01 spandefa"><?php echo $v['netname'] ?></span></a>
					<?php endforeach;?>
				</div>
			</div>
			
			<div class="top_com stime">
				<span class="spanl">日期：</span>
				<span  id="choose_time"></span>
			</div>

			<a href="javascript:" class="btn btn-sm btn-success changa01">搜索</a>
			<a href="javascript:;" download="人员业绩报表.xls" class="btn btn-sm purple-plum to_excel">导出</a>
		</div>
	</div>

	<div class="col-md-12" id="order-list">
		<table class="table table-bordered table-striped table-hover table-bb">
			<thead>
				<tr>
					<th>门店</th>
					<th>员工</th>
					<th>现金实收</th>
					<th>现金卡扣</th>
					<th>实操消耗</th>
					<th>标准实耗金额</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
			<?php if ($list): ?>
			<?php foreach ($list as $row): ?>
				<tr>
					<td><?php echo $row['dept_name'] ?></td>
					<td><?php echo $row['netname'] ?></td>
					<td><?php echo $row['xj'] ?></td><?php $_xj+=$row['xj'] ?>
					<td><?php echo $row['xjkk'] ?></td><?php $_xjkk+=$row['xjkk'] ?>
					<td><?php echo $row['scxh'] ?></td><?php $_scxh+=$row['scxh'] ?>
					<td><?php echo $row['bzxh'] ?></td><?php $_bzxh+=$row['bzxh'] ?>
					<td><a rel="<?php echo $row['uid'] ?>" href="javascript:" class="khgl_03 detail">查看</a></td>
				</tr> 
				<?php endforeach ?>
				<tr class="table_weight">
					<td>合计</td>
					<td></td>
					<td><?php echo $_xj ?></td>
					<td><?php echo $_xjkk ?></td>
					<td><?php echo $_scxh ?></td>
					<td><?php echo $_bzxh ?></td>
					<td></td>

				</tr> 
			<?php endif ?>
			</tbody>
		</table>
	</div>

</div>





<div class="none" id="widget_cu"> 
	<div class="widget_content">
	    <!--widget_select-->
	    <div class="widget_select widget_select_mb bottom_dashed">
	        <div class="widget_select_l">人员名称：</div>
	        <div class="widget_select_r">
	            <ul class="add_pro">
	            <li class="" rel="7" data-name="肽精神" data-num="10" data-price="1000.00"><span></span>肽精神</li>
	            <li class="" rel="8" data-name="肽水润" data-num="5" data-price="1000.00"><span></span>肽水润</li>
	            <li class="widget_select_on" rel="9" data-name="太太测试" data-num="10" data-price="1000.00"><span></span>太太测试</li>
	            </ul>
	        </div>
	    </div>

	    <div class="widget_select widget_select_result">
	        <div class="widget_select_l">已选择项：<br><a class="widget_select_clean" href="javascript:;">清空已选</a></div>
	        <div class="widget_select_r">
	            <ul class="result_pro">
	            </ul>
	        </div>
	    </div>
	</div>
</div>


<script type="text/javascript">
$(function(){
	
	//删除
	$("body").on('click', '.spandefa', function(event) {
		$(this).parent().remove();
	});

	$(".c_add").click(function(){
		var self=$(this).closest('.user_list');//box对象
		var md_id=getMd();
		if(md_id==''){
			Idialog.tips('门店未选择！',2);
			return;
		}
		$.getJSON("<?php echo $this->url('getMdUser') ?>", { md_id: md_id }, function(json){
			if(json.code==200){
				$(".add_pro").empty();
				$.each( json.data, function(i, n){
					$(".add_pro").append('<li rel="'+n.id+'" data-name="'+n.netname+'" ><span></span>'+n.netname+'</li>')
					
				});

				var d = Idialog({
					top:150,
					width:800,
					title:'选择人员',
					content:$('#widget_cu'),
					cancel:false,
					ok:function(obj){
						var _self=obj._self;
						var has_list = self.find('a');//已经存在的列
						var pro_k=has_list.length;//当前序号
						var result_list=_self.find('.result_pro li');
						$.each( result_list, function(i, pro){
							pro=$(pro);
							var p_name=pro.attr('data-name');
							var p_id=pro.attr('rel');
							//如果存在 则略过
							if(has_list.filter("[data-id='"+p_id+"']").length>0) return ;
							var str  ='<a href="javascript:;" data-id="'+p_id+'"><span class="span_01 spandefa">'+p_name+'</span></a>';
							self.append(str);
							pro_k++;
						});
					}
				});
			}
		});

	});


	
	//将项目添加到result
	$('body').off('click','.add_pro li');
	$('body').on('click','.add_pro li',function(){
		var self=$(this);
		if(self.hasClass('widget_select_on'))
			return;
		var content = $(this).closest('.widget_content');
		self.addClass('widget_select_on');
		content.find('.result_pro').append(self.clone().removeClass('widget_select_on'));
	});

	//将项目从result 删除
	$('body').off('click','.result_pro li');
	$('body').on('click','.result_pro li',function(){
		var self=$(this);
		var content = $(this).closest('.widget_content');
		content.find(".add_pro li[rel='"+self.attr('rel')+"']").removeClass('widget_select_on');
		self.remove();
	});

	//清空result
	$('body').off('click','.widget_select_clean li');
	$('body').on('click','.widget_select_clean',function(){
		var self=$(this);
		var content = $(this).closest('.widget_content');
		content.find(".add_pro li").removeClass('widget_select_on');
		content.find('.result_pro').empty();
	});


	
	var t = Itime({
		content:$('#choose_time'),
		<?php if (isset($_GET['begin'])): ?>
		begin:'<?php echo $_GET["begin"]?>', //填充默认时间
		<?php endif ?>
		<?php if (isset($_GET['end'])): ?>
		end:'<?php echo $_GET["end"]?>', //填充默认时间
		<?php endif ?>
		//type:'d',  	  // 日 模式
	})._self.find("a,br").remove();

	//门店范围选择
	$(".choose_md a").click(function(){
		var rel=$(this).attr("rel");
		if($(this).find("span").hasClass("span_01")){
			$(this).find("span").removeClass("span_01");
			if(rel=="0")
				$(".choose_md span").removeClass("span_01");
		}else{
			$(this).find("span").addClass("span_01");
			if(rel=="0")
				$(".choose_md span").addClass("span_01");
		}
	});


<?php if ($this->controller->is_store): ?>
		$(".choose_md").find("a").trigger("click");
<?php else: ?>
	//填充默认门店
	<?php if (isset($_GET['md_id'])): ?>
		<?php foreach (explode(',', $_GET['md_id']) as $v): ?>
			$(".choose_md").find("a[rel='<?php echo $v ?>']").find("span").addClass('span_01');// trigger("click");
		<?php endforeach ?>
	<?php endif ?>
<?php endif ?>

	function getMd(){
		if($(".choose_md a[rel='0']").find("span").hasClass("span_01"))
			return "0";
		var l = $(".choose_md a").map(function(){
			if($(this).find("span").hasClass("span_01"))
				return $(this).attr("rel");
		}).get().join(",");
		return l;
	}
	function getUser () {
		var list='';
		list=$('.user_list').find('a').map(function(index, elem) {
			return $(this).attr('data-id');
		}).get().join(',');
		return list;
	}


	//搜索提交
	$(".changa01").click(function(){
		var md_ids=getMd();
		if(md_ids==''){
			Idialog.tips('门店未选择！',2);
			return;
		}
		var user_ids=getUser();
		if(user_ids==''){
			Idialog.tips('人员未选择！',2);
			return;
		}
		var begin=$(".itime").find(".b_y").val()+""+$(".itime").find(".b_m").val()+""+$(".itime").find(".b_d").val();
		var end  =$(".itime").find(".e_y").val()+""+$(".itime").find(".e_m").val()+""+$(".itime").find(".e_d").val();
		to_url('<?php echo $this->url("RYYJ") ?>&md_id='+md_ids+'&begin='+begin+'&end='+end+'&user_ids='+user_ids);

	});

	//详细查看
	$(".detail").click(function(){
		var user_id=$(this).attr("rel");
		var url = changeURL("","r","report/index/RYYJ_X");
		to_url(url+'&user_id='+user_id);
	});


	$(".to_excel").click(function(event){
		var t = Itable2excel({
			worksheet:'数据分析',
			table: $('#order-list table')
		});
		var data64 = t.uri();
		if(data64==false){
			return false;
		}
		event.currentTarget.href = data64;
	});

});

</script>