<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js" charset="utf-8"></script>
<?php 
	$md_list=\EmployDept::getList(true);
    if ($this->controller->is_store)
        $dept_ids=\Ivy::app()->user->dept_id;
?>
<!--content_right_con-->
<div class="content_right_con">
    <div class="content_right_con_top">
        <div class="fjgl_top_r">
            <span><a href="#" download="新客分析表.xls"class="to_excel fjgl_top_r_05">导出</a></span>
        </div>
        <div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>数据报表><span>新客分析表</span>
    </div>

    <!--sjbb_ddkl_one-->
    <div class="sjbb_ddkl_one">
        <ul>
            <li>
                <div class="sjbb_ddkl_one_l">门店范围：</div>
                <div class="sjbb_ddkl_one_r">
                    <div class="sjbb_ddkl_one_r_son choose_md">
                        <?php if(!$this->controller->is_store):?>
                        <a href="javascript:" rel="0"><span <?php echo in_array('0',explode(',',$dept_ids))?'class="span_01"':''?>></span>全连锁</a>
                        <?php endif;?>
                        <?php foreach ($md_list as $key => $value): ?>
                            <a href="javascript:" rel="<?php echo $key ?>"><span <?php echo in_array($key,explode(',',$dept_ids))?'class="span_01"':''?>></span><?php echo $value ?></a>
                        <?php endforeach ?>
                    </div>
                </div>
            </li>

            <li>
                <div class="sjbb_ddkl_one_l">日期：</div>
                <div class="sjbb_ddkl_one_r">
                    <div class="sjbb_ddkl_one_r_son">
                        <select id="year" class="sjbb_ddkl_one_r_son_01">
                            <?php $_year = date('Y');?>
                            <?php for($i=0;$i<=4;$i++):?>
                                <option <?php echo $year==$_year-$i?'selected="selected"':''?> value="<?php echo $_year-$i;?>"><?php echo $_year-$i;?>年</option>
                            <?php endfor;?>
                        </select>
                        <select id="month" class="sjbb_ddkl_one_r_son_01">
                            <?php for($i=1;$i<=12;$i++):?>
                                <option <?php echo $month==$i?'selected="selected"':''?> value="<?php echo $i;?>"><?php echo $i<10?'0'.$i:$i;?>月</option>
                            <?php endfor;?>
                        </select>
                    </div>
                </div>
            </li>
            <li class="lastli">
                <div class="sjbb_ddkl_one_l">
                </div>
                <div class="sjbb_ddkl_one_r">
                    <div class="sjbb_ddkl_one_r_son">
                        <a href="javascript:" class="changa01" id="search">搜索</a>
                    </div>
                </div>
            </li>
        </ul>
    </div> <!--sjbb_index_onesjbb_ddkl_oneend-->



    <!--table_container-->
    <div id="order-list" class="table_table table_center">
        <div class="table_hiddle">
        <table width="100%" cellspacing="0" cellpadding="0" border="0" last-float="false">
            <thead>
                <tr class="table_title">
                    <th>门店</th>
                    <th>新客人头</th>
                    <th>新客实收现金</th>
                    <th>总成交量</th>
                    <th>总实收现金</th>
                    <th>新客成交人数占比</th>
                    <th>新客成交金额占比</th>
                    <th>查看档案</th>
                </tr>
            </thead>
            <tbody>
            <?php if ($data): ?>
            <?php $xk_rs=0;$xk_scxj=0;$z_cjcs=0;$z_cjje=0;?>
            <?php foreach($data as $_data):?>
                <tr class="table_list clear">
                    <td><a href="<?php echo $this->url('XKFX_X',array('dept_id'=>$_data['dept_id'],'year'=>$_GET['year'],'month'=>$_GET['month']))?>" class="alinks"><?php echo $_data['dept_name'];?></a></td>
                    <td><?php echo $_data['xk_rs'];?></td>
                    <td><?php echo $_data['xk_scxj'];?></td>
                    <td><?php echo $_data['z_cjcs'];?></td>
                    <td><?php echo $_data['z_cjje'];?></td>
                    <td><?php echo empty($_data['z_cjcs'])?0:sprintf('%.2f',$_data['xk_rs']/$_data['z_cjcs']);?></td>
                    <td><?php echo empty($_data['z_cjje'])?0:sprintf('%.2f',$_data['xk_scxj']/$_data['z_cjje']);?></td>
                    <td>
                        <?php if($_data['xk_rs']!=0):?>
                            <a href="<?php echo $this->url('XKFX_X',array('dept_id'=>$_data['dept_id'],'year'=>$_GET['year'],'month'=>$_GET['month']))?>" class="alinks">查看</a>
                        <?php endif;?>
                    </td>
                
                </tr>
                <?php
                    $xk_rs += $_data['xk_rs'];
                    $xk_scxj += $_data['xk_scxj'];
                    $z_cjcs += $_data['z_cjcs'];
                    $z_cjje += $_data['z_cjje'];
                ?>
            <?php endforeach;?>
                <tr class="table_list table_weight clear">
                    <td>本月合计</td>
                    <td><?php echo $xk_rs;?></td>
                    <td><?php echo $xk_scxj==0?0:sprintf('%.2f',$xk_scxj);?></td>
                    <td><?php echo $z_cjcs;?></td>
                    <td><?php echo $z_cjje==0?0:sprintf('%.2f',$z_cjje);?></td>
                    <td><?php echo empty($z_cjcs)?0:sprintf('%.2f',$xk_rs/$z_cjcs);?></td>
                    <td><?php echo empty($z_cjje)?0:sprintf('%.2f',$xk_scxj/$z_cjje);?></td>
                    <td></td>
                </tr> 
            <?php endif ?>
            </tbody>
        </table>
        </div><!--table_hiddle!end-->
    </div>
    <!--table_container-->



</div>
<!--content_right_con!end-->

<script type="text/javascript">
$(function(){
    //门店范围选择
    $(".choose_md a").click(function(){
        var rel=$(this).attr("rel");
        if($(this).find("span").hasClass("span_01")){
            $(this).find("span").removeClass("span_01");
            if(rel=="0")
                $(".choose_md span").removeClass("span_01");
        }else{
            $(this).find("span").addClass("span_01");
            if(rel=="0")
                $(".choose_md span").addClass("span_01");
        }
    });

    $("#search").click(function(){
        var dept_ids = new Array;
        $(".choose_md a span").each(function(){
            if($(this).hasClass('span_01')){
                dept_ids.push($(this).parent().attr("rel"));
            }
        });
        if(dept_ids.join(',').length<=0){
            alert('请选择门店！');
            return false;
        }
        var year = $("#year").val();
        var month = $("#month").val();
        var url="<?php echo $this->url('XKFX')?>";
        window.location.href = url+'&dept_ids='+dept_ids+'&year='+year+'&month='+month;
    });

    
    $(".to_excel").click(function(event){
        var t = Itable2excel({
            worksheet:'数据分析',
            table: $('#order-list table')
        });
        var data64 = t.uri();
        if(data64==false)
            return false;
        event.currentTarget.href = data64;
    });
});
</script>