<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jsapi.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/corechart.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jquery.gvChart-1.0.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js"></script>
<?php 
	$md_list=\EmployDept::getList(true);
?>
<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="fjgl_top_r"><span><a href="#" download="项目覆盖分析报表.xls"class="to_excel fjgl_top_r_05">导出</a></span></div>
		<div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>
		数据报表><span>项目覆盖分析报表</span> </div>
	
	<!--sjbb_ddkl_one-->
	<div class="sjbb_ddkl_one">
		<ul>
			<li>
				<div class="sjbb_ddkl_one_l">门店范围：</div>
				<div class="sjbb_ddkl_one_r">
					<div class="sjbb_ddkl_one_r_son choose_md"> 
						<?php if(!$this->controller->is_store):?>
						<a href="javascript:" rel="0"><span ></span>全连锁</a>
						<?php endif;?>
						<?php foreach ($md_list as $key => $value): ?>
						<a href="javascript:" rel="<?php echo $key ?>"><span></span><?php echo $value ?></a>
						<?php endforeach ?>
					</div>
				</div>
			</li>
			
			<li>
				<div class="sjbb_ddkl_one_l">项目范围： </div>
				<div class="sjbb_ddkl_one_r">
					<div class="sjbb_ddkl_one_r_son">
						<div class="sjbb_khgm_top sjbb_khgm_top_pad box_xm">
							<div class="sjbb_khgm_top_01 c_add">请选择</div>
							<ul>
								<li style="padding: 0;"><!-- 占位用的 --></li>
								<?php 
									if($xm_list)
										foreach ($xm_list as $key => $value):
								?>
								<li class="fzxzxm_two_com_09" data-id="<?php echo $key ?>"><span class="spandefa"></span><?php echo $value;?></li>
								<?php endforeach;?>
							</ul>
						</div>
					</div>
				</div>
			</li>
			<li class="lastli">
				<div class="sjbb_ddkl_one_l"> </div>
				<div class="sjbb_ddkl_one_r">
					<div class="sjbb_ddkl_one_r_son"> <a href="javascript:" class="changa01">搜索</a> </div>
				</div>
			</li>
		</ul>
	</div>
	<!--切换-->
	<div class="khgl_da_top khgl_zhdt_01" style=" margin-top:20px;">
			<ul>
	    	<li><a href="javascript:"  class="khgl_da_03">列表视图</a></li>
	        <li><a href="javascript:">图形视图</a></li>
	    </ul>

	</div>
    <!-- -->
    <!--列表视图-->
	<div class="sjbb_xmfgfx_none" style="display:block;">
	<!--  模版引擎扩展 -->
	<?php echo $this->datagrid(array(
		'id'=>'order-list',
		'dataProvider'=>array('list'=>$model),
	    'search'=>false,
	    'lastFloat'=>false,
		'columns'=>array(
			array(
				'header' => '品类',
				'name'   => 'PL',
			),
			array(
				'header' => '品牌系列',
				'name'   => 'SX',
			),
			array(
				'header' => '品项',
				'name'   => 'PX',
			),
			array(
				'header' => '有效客户数',
				'name'   => 'YXKHS',
			),
			array(
				'header' => '有效覆盖人数',
				'name'   => 'YXFGRS',
			),
			array(
				'header' => '有效覆盖率',
				'name'   => 'YXFGL',
			),
			
		),
	));?>
	</div>
	<!--图形视图-->
	<div class="sjbb_xmfgfx_con sjbb_xmfgfx_none">
		<?php if($model)
				foreach ($model as $key => $value):
		?>
		<div class="sjbb_xmfgfx_con_l">
	       <table  class="chart">
	            <caption>"<?php echo $value['PX']?>"有效覆盖率</caption>
	            <thead>
	                <tr>
	                    <th></th>
	                    <th>有效覆盖人数</th>
	                    <th>未覆盖客户数</th>
	                </tr>
	            </thead>
	            <tbody>
	                <tr>
	                    <th><?php echo $value['YXKHS'];?></th>
	                    <td><?php echo $value['YXFGRS'];?></td>
	                    <td><?php echo $value['YXKHS']-$value['YXFGRS'];?></td>
	                </tr>
	            </tbody>
	        </table>  
	   </div>
	<?php endforeach;?>
	   
	</div>
    <!--图形视图!end-->
</div>
<!--content_right_con!end-->
<div class="none" id="widget_project"> <?php echo \Ivy::app()->widget('common/selectProject',array('param'=>"rich",'show_del'=>1)); ?> </div>
<script type="text/javascript">

$(function(){
	gvChartInit();
	$('.chart').each(function(index, el) {
		$(this).gvChart({
			chartType: 'PieChart',
			gvSettings: {
				vAxis: {title: 'No of players'},
				hAxis: {title: 'Month'},
				width: 600,
				height: 350
			}
		});
	});

	
	//切换标签
	$(".khgl_da_top ul li").click(function(){
	   var _index =  $(this).index();
	   //alert(_index);
	   $(".khgl_da_top ul li").find("a").removeClass("khgl_da_03");
	   $(this).find("a").addClass("khgl_da_03");
	   $(".sjbb_xmfgfx_none").hide();
	   $(".sjbb_xmfgfx_none").eq(_index).show();
   });
	//鼠标移上效果
	$("body").on('mouseover', '.fzxzxm_two_com_09', function(event) {
		$(this).addClass('fzxzxm_two_com_010').find('.spandefa').addClass('spandclck');
	});
	$("body").on('mouseout', '.fzxzxm_two_com_09', function(event) {
		$(this).removeClass('fzxzxm_two_com_010').find('.spandefa').removeClass('spandclck');
	});
	//删除
	$("body").on('click', '.spandefa', function(event) {
		$(this).parent().remove();
	});
	//项目的添加
	$('.box_xm').on('click','.c_add',function(){
		var self=$(this).closest('.box_xm');//box对象
		var d = Idialog({
			top:150,
			width:800,
			title:'添加项目',
			content:$('#widget_project'),
			cancel:false,
			ok:function(obj){
				var _self=obj._self;
				var has_list = self.find('.fzxzxm_two_com_09');//已经存在的列
				var pro_k=has_list.length;//当前序号
				var result_list=_self.find('.result_pro li');
				$.each( result_list, function(i, pro){
					pro=$(pro);
					var p_name=pro.attr('data-name');
					var p_id=pro.attr('rel');
					//如果存在 则略过
					if(has_list.filter("[data-id='"+p_id+"']").length>0) return ;
					var str  ='<li class="fzxzxm_two_com_09" data-id="'+p_id+'"><span class="spandefa"></span>'+p_name+'</li>';
					self.find('ul').append(str);
					pro_k++;
				});
			}
		});
	});
	//门店范围选择
	$(".choose_md a").click(function(){
		var rel=$(this).attr("rel");
		if($(this).find("span").hasClass("span_01")){
			$(this).find("span").removeClass("span_01");
			if(rel=="0")
				$(".choose_md span").removeClass("span_01");
		}else{
			$(this).find("span").addClass("span_01");
			if(rel=="0")
				$(".choose_md span").addClass("span_01");
		}
	});



<?php if ($this->controller->is_store): ?>
		$(".choose_md").find("a").trigger("click");
<?php else: ?>
//填充默认门店
<?php if (isset($_GET['md_ids'])): ?>
	<?php foreach (explode(',', $_GET['md_ids']) as $v): ?>
		$(".choose_md").find("a[rel='<?php echo $v ?>']").trigger("click");
	<?php endforeach ?>
<?php endif ?>
<?php endif ?>

	//搜索提交
	$(".changa01").click(function(){
		var md_ids=getMd();
		if(md_ids==''){
			Idialog.tips('门店未选择！',2);
			return;
		}
		var xm=getXMORCP('xm');
		if(xm== ''){
			Idialog.tips('项目未选择！',2);
			return;
		}

		to_url('<?php echo $this->url("XMFGFX") ?>&md_ids='+md_ids+'&xm='+xm);

	});
	function getXMORCP (o) {
		var list='';
		list=$('.box_'+o).find('.fzxzxm_two_com_09').map(function(index, elem) {
			return $(this).attr('data-id');
		}).get().join(',');
		return list;
	}
	function getMd(){
		if($(".choose_md a[rel='0']").find("span").hasClass("span_01"))
			return "0";
		var l = $(".choose_md a").map(function(){
			if($(this).find("span").hasClass("span_01"))
				return $(this).attr("rel");
		}).get().join(",");
		return l;
	}

	$(".to_excel").click(function(event){
		var t = Itable2excel({
			worksheet:'数据分析',
			table: $('#order-list table')
		});
		var data64 = t.uri();
		if(data64==false)
			return false;
		event.currentTarget.href = data64;
	});


});
</script> 
