<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itime.js"></script>
<?php 
	$md_list=\EmployDept::getList(true);
?>
<?php 
$top_cate=\ProCate::getProductTopCate();
$child_cate=array();
if(isset($_GET['t_search']['tpc.id']))
    $tmp_cate=\ProCate::model()->findAll('fid='.(int)$_GET['t_search']['tpc.id']);
    $child_cate = $this->optArr($tmp_cate,'id','name');
?>
<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="fjgl_top_r"><span><a class="fjgl_top_r_05" href="javascript:">导出</a></span></div>
		仓库管理><span>库存报告</span>
	</div>

	<!--sjbb_ddkl_one-->
	<div class="sjbb_ddkl_one">
		<ul>
    <li>
      <div class="sjbb_ddkl_one_l">日期：</div>
      <div class="sjbb_ddkl_one_r">
        <div class="sjbb_ddkl_one_r_son" id="choose_time">
        </div>
      </div>
    </li>
		<li>
			<div class="sjbb_ddkl_one_l">部门：</div>
			<div class="sjbb_ddkl_one_r">
				<div class="sjbb_ddkl_one_r_son choose_md">
					<?php foreach ($md_list as $key => $value): ?>
					<a href="javascript:" rel="<?php echo $key ?>" class="sjbb_ddklchanga"><?php echo $value ?></a>
					<?php endforeach ?>
				</div>
			</div>
		</li>
		<li class="lastli">
				<div class="sjbb_ddkl_one_l">
				</div>
				<div class="sjbb_ddkl_one_r">
					<div class="sjbb_ddkl_one_r_son">
						<a href="javascript:" class="changa01">搜索</a>
					</div>
				</div>
		</li>
		</ul>
	</div> <!--sjbb_index_onesjbb_ddkl_oneend-->
<!--  模版引擎扩展 -->
    <?php echo $this->datagrid(array(
        'id'=>'list',
        'dataProvider'=>$pager,
        'search'=>true,
        'columns'=>array(
            array(
                'header' => '商品分类',
                'name'  => 'tcname',
                'filter'=>array("tpc.id",$top_cate,""),
            ),
            array(
                'header' => '商品系列',
                'name'  => 'cname',
                'filter'=>array("pc.id",$child_cate,""),
            ),
            array(
                'header' => '商品名称',
                'name'  => 'name',
                'filter'=>'pro.name',
            ),
            array(
                'header' => '商品编码',
                'name' => 'code',
                'filter'=>'pro.code',
            ),
            array(
                'header' => '规格',
                'name' => 'specs',
            ),
            array(
                'header' => '单位',
                'name' => 'unit',
            ),
            array(
                'header' => '期初结存',
                'name' => 's_num',
            ),
            array(
                'header' => '本期入库',
                'name' => 'in_num',
            ),
            array(
                'header' => '本期出库',
                'name' => 'out_num',
            ),
            array(
                'header' => '本期损益',
                'name' => 'loss_num',
            ),
            array(
                'header' => '本期结存',
                'name' => 'e_num',
            ),
            array(
                'header' => '操作',
                'rel' => 'in_id',
                'value'=> '<a href="'.$this->url("view").'&pid={$data["pid"]}&md_id={$_GET["md_id"]}&begin={$_GET["begin"]}&end={$_GET["end"]}" class="view khca">查看</a>',
            ),
           
        ),
    ));?>

	
</div>
<!--content_right_con!end-->



<script type="text/javascript">

$(function(){
	var t = Itime({
		content:$('#choose_time'),
		<?php if (isset($_GET['begin'])): ?>
		begin:'<?php echo $_GET["begin"]?>', //填充默认时间
		<?php endif ?>
		<?php if (isset($_GET['end'])): ?>
		end:'<?php echo $_GET["end"]?>', //填充默认时间
		<?php endif ?>
		//type:'d',  	  // 日 模式
	})._self.find("a,br").remove();

	//门店、范围选择
	$(".choose_md a").click(function(){
		var rel=$(this).attr("rel");
		$(this).siblings('.sjbb_ddklchanga').removeClass('sjbb_ddklchanga');
    $(this).addClass('sjbb_ddklchanga');
	});
  //搜索提交
  $(".changa01").click(function(){
    var md_id=getMd();
    if(md_id==''){
      Idialog.tips('门店未选择！',2);
      return;
    }
    

    var begin=$(".itime").find(".b_y").val()+""+$(".itime").find(".b_m").val()+""+$(".itime").find(".b_d").val();
    var end  =$(".itime").find(".e_y").val()+""+$(".itime").find(".e_m").val()+""+$(".itime").find(".e_d").val();
    to_url('<?php echo $this->url("index") ?>&md_id='+md_id+'&begin='+begin+'&end='+end);
  });

<?php if ($this->controller->is_store): ?>
    $(".choose_md").find("a").trigger("click");
    <?php if (!isset($_GET['md_id'])): ?>
    $(".changa01").trigger('click');
    <?php endif ?>
<?php else: ?>
  //填充默认门店
  <?php if (isset($_GET['md_id'])): ?>
  <?php foreach (explode(',', $_GET['md_id']) as $v): ?>
    $(".choose_md").find("a[rel='<?php echo $v ?>']").trigger("click");
  <?php endforeach ?>
  <?php endif ?>
<?php endif ?>
	function getMd(){
		if($(".choose_md a[rel='0']").hasClass("sjbb_ddklchanga"))
			return "0";
		var l = $(".choose_md a").map(function(){
			if($(this).hasClass("sjbb_ddklchanga"))
				return $(this).attr("rel");
		}).get().join(",");
		return l;
	}



});
</script>