<?php 
$sex_list=\CustomerInfo::getSex();
$member_list=\ConfigMembership::getList();
?>
<link href="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_style.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_v5.3.2_min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/html5uploader/jquery.html5uploader.js"></script>
<div class="row">
	<div class="col-md-12">
		<div class="portlet no_mb">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-users"></i>待建期初客户
				</div>
				<div class="actions btn-set">
					<a href="javascript:" class="btn default red-stripe">待建期初客户</a>
					<a href="<?php echo $this->url('bill') ?>" class="btn default gray-stripe">待开账客户列表</a>

				</div>
			</div>
		</div>


<?php echo $this->datagrid(array(
	'id'=>'table-list',
	'dataProvider'=>$pager,
	'search'=>true,
	'check'=>'id',
	'columns'=>array(
		array(
			'header' => '会员卡号',
			'name' => 'cardid',
			'filter'=>'t.cardid',
		),
		array(
			'header' => '姓名',
			'name' => 'name',
			'filter'=>'t.name',
			'value' => '<span class="khgl_xmpic"><img src="'.$this->basePath('public').'/images/kh_06.png" height="24" width="24" /></span><span class="khgl_03">{$data["name"]}</span>',
		),
		array(
			'header' => '性别',
			'name' => 'sex',
			'filter'=>array('t.sex',$sex_list),
		),
		array(
			'header' => '客户等级',
			'name' => 'lname',
			'filter'=>array('l.id',$member_list),
		),
		array(
			'header' => '客户类型',
			'name' => 'cu_type',
			'filter'=>array('t.cu_type',\CustomerInfo::getCuType()),
		),
		array(
			'header' => '客户状态',
			'value' => '{\CustomerInfo::getStatus($data["status"])}',
			'filter'=>array('t.status',\CustomerInfo::getStatus()),
		),
		array(
			'header' => '私人顾问',
			'name' => 'cnetname',
			'filter'=>array('t.counselor_id',\EmployUser::getList()),
		),

		array(
			'header' => '私人美疗师',
			'name' => 'onetname',
			'filter'=>array('t.operator_id',\EmployUser::getList(' AND position_id=7')),
		),
		array(
			'header' => '档案归属部门',
			'name' => 'dept_name',
			'filter'=>array('t.store_id',\EmployDept::getList()),
		),
		array(
			'header' => '状态',
			'value' => '未建期初',
		),
		array(
			'header' => '操作',
			'rel'=>'id',
			'value'=> '<a href="'.$this->url('pos/init/add').'&id={$data["id"]}" class="khca">建立期初</a>',
		)
	),
));?>
	



	</div>
</div>


