<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
	<div class="print_show col-md-12">
		<div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/实操单
                </div>
                <div class="tools">
                	<?php if (!$model): ?>
		                <button class="btn btn-sm green table-group-action-submit c_submit"><i class="fa fa-check"></i>提交订单</button>
					<?php else: ?>
	                	<button class="btn btn-sm green table-group-action-submit c_submit"><i class="fa fa-check"></i>更新订单</button>
	                	<button onclick="to_url('<?php echo $this->url("pay",array('id'=>$model->o_s->id)) ?>')" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>确认实操</button>
					<?php endif ?>
                </div>
            </div>
        </div>

        <div class="row">
			<div class="col-md-6 col-sm-12">
	            <div class="portlet solid green-haze">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>订单概况
	                    </div>
	                    <div class="actions">
		                    <?php if (!$model): ?>
		                    <button class="btn red">订单新建</button>
							<?php else: ?>
		                    <button class="btn red">订单编辑</button>
							<?php endif ?>
	                    </div>
	                </div>
	                <div class="portlet-body">
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">实操单号：</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->sn ?>
	                        </div>
	                    </div>


	                    <div class="row static-info">
	                        <div class="col-xs-5 name">订单状态：</div>
	                        <div class="col-xs-7 value text-right">
		                        <?php if (!$model): ?>
	                        	<span class="label label-info label-sm">草稿</span>
								<?php else: ?>
	                        	<span class="label label-warning label-sm"><?php echo \PracticeOrder::getStatus($model->o_s->status);?></span>
								<?php endif ?>
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">本次实操项目：</div>
	                        <div class="col-xs-7 value text-right">
	                        	<font class="xj_xm"><?php echo count($model->pros) ?></font> 个
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">本次实操疗次：</div>
	                        <div class="col-xs-7 value text-right">
                                <font class="xj_lc"><?php echo array_sum(array_column($model->pros, 'use_num')) ?></font> 次
	                        </div>
	                    </div>


						
	                </div>
	            </div>
	        </div>

	        <div class="col-md-6 col-sm-12">
	            <div class="portlet solid red-intense">
	                <div class="portlet-body" style="padding-top: 10px;">
	                    <?php echo $cu_info ?>
	                </div>
	            </div>
	        </div>


        </div>

        <div class="row"> 
        <div class="col-md-12">
	        <div class="portlet box blue-steel">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i>剩余项目疗次
                    </div>
                </div>
                <div class="portlet-body">
                	<div class="table-responsive"> 
						<table class="table table-bordered table-hover " >
							<thead>
								<tr>
									<th style="width: 50px;">选择</th>
									<th>购买时间</th>
									<th>账户剩余项目</th>
									<th>项目来源</th>
									<th>购买次数</th>
									<th>可实操疗次</th>
									<th>实操次数(疗次)</th>
									<th>实操美容师</th>
									<th>实操配方</th>
								</tr>
							</thead>
							<tbody>
								<?php if($CustomerReProject): ?>
								<?php 
									$sum_xm=$sum_lc=0;
									foreach ($CustomerReProject as $key => $value): 
										$checked='';
										$formula_str='选择配方';
										$operators_str='选择美容师';
										$operators=$formula_id=$use_nums='';
										$max_num=$value['re_num'];
										$OrderSaleDetail=\OrderSaleDetail::model()->findByPk($value['detail_id']);
										if($OrderSaleDetail->buy_type==1  && $OrderSaleDetail->num && $OrderSaleDetail->pay_price>0){
											$price=$OrderSaleDetail->num?$OrderSaleDetail->pay_price/$OrderSaleDetail->num:0;
											$max_num=$price?intval($OrderSaleDetail->var_price/$price):0;
										}
										if ($model) {
											foreach ((array)$model->pros as $pro) {
												if($pro['detail_id']==$value['detail_id'])
												{
													$checked='checked="checked"';
													$use_nums=$pro['use_num'];
													$sum_xm++;
													$sum_lc+=$use_nums;
													$formula_id=$pro['formula_id'];
													$operators=$pro['operators'];
													$formula_str=\ProjectFormula::getName($formula_id);
													$operators_str=\EmployUser::getUserNames($operators);
													break;
												}
											}
										}
								?>
										<tr role="row">
											<td>
												<input class="detail_ids checkboxes" type="checkbox" value="<?php echo $value['detail_id'] ?>"  <?php echo $checked; ?>/>
											</td>
											<td><?php echo date('Y-m-d',strtotime($value['create_time'])) ?></td>
											<td><?php echo $value['name']; ?></td>
											<td><?php echo \OrderSaleDetail::getBuyType($value['buy_type']); ?></td>
											<td><?php echo $value['num'] ?></td>
											<td><?php echo $max_num;?></td>
											<td>
												<input type="text" value="<?php echo $use_nums ?>" class="pos_cz_tow_two05 use_nums" data-max="<?php echo $max_num ?>" />
											</td>
											<td >
												<input name="operators" class="operators" type="hidden" value="<?php echo $operators?>" />
												<span class="btn btn-info btn-xs action_mrs"><?php echo $operators_str ?></span>
											</td>
											<td>
												<input name="formula_ids" class="formula_ids" type="hidden" value="<?php echo $formula_id?>" />
												<span class="btn btn-info btn-xs action_pf"><?php echo $formula_str ?></span>
											</td>
										</tr>
								<?php endforeach; ?>
								<?php endif; ?>
							</tbody>
						</table>
					</div>
                </div>
            </div>
        </div>
        </div>


		<!--备注-->
		<div class="pos_cz_tow pos_cz_for_bz">
			<div class="pos_cz_for_bz01">备注</div>
			<div class="pos_cz_for_bz02">
				<div class="pos_cz_for_bz02_son">
					<textarea class="order_note" rows="4"><?php echo $model?$model->o_s->note:"" ?></textarea>
				</div>
			</div>
		</div>
		<!--备注!end-->



    </div>
</div>

{__TOKEN__} 
<script type="text/javascript">

$(function(){

	//收起效果
	$(".pos_cz_tow_top_r").click(function(){
		var self=$(this);
		self.parent().next().slideToggle("fast",function(){
			//alert("Animation Done.");
			if(self.hasClass("pos_cz_tow_top_rcl")){
				self.removeClass("pos_cz_tow_top_rcl");
			}else{
				self.addClass("pos_cz_tow_top_rcl");
			}
		});
	});
	//添加疗次
	$('.use_nums').keyup(function(event) {
		if ($(this).val()=='') {
			$(this).parents('tr').find('.detail_ids').prop('checked',true);
		}else{
			$(this).parents('tr').find('.detail_ids').removeAttr('checked');
		}
		$(this).parents('tr').find('.detail_ids').trigger('click');
	});
	//选中项目
	$('.detail_ids').click(function(event) {
		var xj_xm=xj_lc=0;
		if ($(this).parents('tr').find('.use_nums').val()=='')
			$(this).parents('tr').find('.use_nums').val(1);
		$('.detail_ids').each(function(index, el) {
			if ($(this).is(':checked')) {
				xj_xm++;
				xj_lc+=parseInt($(this).parents('tr').find('.use_nums').val());
			};
		});
		$('.xj_xm').html(xj_xm);
		$('.xj_lc').html(xj_lc);
	});
	//数据提交
	$(".c_submit").click(function(){
		var post_data=submit_data();
		if(post_data==false){
			return false;
		}
		$('.c_submit').addClass("disabled");

	<?php if ($model): ?>
		var url="<?php echo $this->url('editSave',array('id'=>$model->o_s->id)) ?>";			
	<?php else: ?>
		var url="<?php echo $this->url('addSave') ?>";	
	<?php endif ?>
		$.post(url, post_data,function(data){
			Idialog.tips(data.msg,2);
			if(data.code==200){
				//转到付款界面
				setTimeout(function(){to_url('<?php echo $this->url("pay");?>&id='+data.data)},3000);
			}
			$('.c_submit').removeClass("disabled");
		}, "json");
	});

	function to_url(url){
		window.location.href=url;
	}
	//选择配方
	$('.action_pf').click(function(event) {
		var self=$(this)
		var pro_id=self.parents('tr').find('.detail_ids').val();
		var formula_ids=self.siblings('.formula_ids').val();
		$.get('<?php echo $this->url("getpf") ?>&pro_id='+pro_id+'&formula_ids='+formula_ids, function(data) {
				var d = Idialog({
				top:150,
				width:474,
				title:'选择配方',
				content:data,
				//cancel:false,
				ok:function(obj){
					var _ids=_names='';
					obj._self.find('.formula_xz:radio:checked').each(function(index, el) {
						_ids+=$(this).val()+',';
						_names+=$(this).attr('data-name')+','
					});
					if(_ids)
						_ids=_ids.substring(0,_ids.length-1);
					if(_names)
						_names=_names.substring(0,_names.length-1);
					self.siblings('.formula_ids').val(_ids);
					self.html(_names);
				}
			});
		});
	});
	//选择美疗师
	$('.action_mrs').click(function(event) {
		var self=$(this);
		var operators=self.siblings('.operators').val();
		$.get('<?php echo $this->url("getmls") ?>&operators='+operators, function(data) {
				var d = Idialog({
				top:150,
				width:474,
				title:'选择美疗师',
				content:data,
				//cancel:false,
				ok:function(obj){
					var _ids=_names='';
					obj._self.find('.mls_xz:checkbox:checked').each(function(index, el) {
						_ids+=$(this).val()+',';
						_names+=$(this).attr('data-name')+','
					});
					if(_ids)
						_ids=_ids.substring(0,_ids.length-1);
					if(_names)
						_names=_names.substring(0,_names.length-1);
					self.siblings('.operators').val(_ids);
					self.html(_names);
				}
			});
		});
	});

	//提交保存数据构造
	function submit_data(){
		var data={};
		data.__hash__ = $("input[name='__hash__']").val();//表单令牌
		if (parseInt($('.xj_lc').html())==0) {
			Idialog.tips('请选择实操项目',2);
			return false;
		};

		var _is=false;
		//实操项目
		data.pro=[];
		$('.detail_ids:checkbox:checked').each(function(index, el) {
			use_nums_obj=$(this).parents('tr').find('.use_nums');
			if (parseInt(use_nums_obj.val())>parseInt(use_nums_obj.attr('data-max'))) {
				Idialog.tips('实操疗次不能超出可实操疗次!',2);
				_is=true;
				return false;
			};
			operators_obj=$(this).parents('tr').find('.operators')
			if (operators_obj.val()=='') {
				Idialog.tips('没有选择本次实操美容师!',2);
				_is=true;
				return false;
			};
			if(parseInt(use_nums_obj.val())>0)
				data.pro.push({
						"detail_id":$(this).val(),
						"use_nums":use_nums_obj.val(),
						"formula_id":$(this).parents('tr').find('.formula_ids').val(),
						"operators":$(this).parents('tr').find('.operators').val()
					})
		});
		if (_is) {return false;};

		data.order_id="<?php echo $model?$model->o_s->id:0; ?>";
		data.sn="<?php echo $model?$model->o_s->sn:''; ?>";
		data.cu_id="<?php echo $model?$model->o_s->cu_id:$id; ?>"

		data.note=$('.order_note').val();
		//console.log(data)
		//return false; 发生验证错误 返回false
		return data;
	}


});
</script>