<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/Itable2excel.js" charset="utf-8"></script>
<?php 
	$md_list=\EmployDept::getList(true);
	$md_id=isset($_GET['md_id'])?$_GET['md_id']:"0";
?>
<!--content_right_con-->
<div class="content_right_con">
	
	<div class="jyjl_top note note-info">
        <div class="top_com">
            <span class="spanl">交易类别：</span>
            <a href="<?php echo $this->url("pos/sale/index") ?>">购买记录</a>
            <a href="<?php echo $this->url("pos/recharge/index") ?>">充值记录</a>
            <a href="<?php echo $this->url("pos/repay/index") ?>">还款记录</a>
            <a href="javascript:" class="aaddys">实操记录</a>
            <a href="<?php echo $this->url("pos/voucher/index") ?>">兑换记录</a>
            <a href="<?php echo $this->url("pos/refund/index") ?>">退款记录</a>
            <a href="<?php echo $this->url("pos/sale/index") ?>">寄存领取记录</a>
            <a href="<?php echo $this->url("pos/init/index") ?>">期初订单</a>
        </div>
		<div class="top_com stime">
			<span class="spanl">日期：</span>
			<a rel="1"  href="javascript:" <?php if ($timeType==1): ?>class="aaddys"<?php endif ?>>最近一天</a>
			<a rel="2"  href="javascript:" <?php if ($timeType==2): ?>class="aaddys"<?php endif ?>>最近一周</a>
			<a rel="3"  href="javascript:" <?php if ($timeType==3): ?>class="aaddys"<?php endif ?>>最近30天</a>
			<a rel="4"  href="javascript:" <?php if ($timeType==4): ?>class="aaddys"<?php endif ?>>全部</a>
        </div>
		
		<?php if(!$this->controller->is_store):?>
		<div class="top_com md_type">
			<span class="spanl">门店：</span>
			<a rel="0"  href="javascript:" <?php if ($md_id==0): ?>class="aaddys"<?php endif ?>>全连锁</a>
			<?php foreach ($md_list as $key => $value): ?>
				<a rel="<?php echo $key ?>"  href="javascript:" <?php if ($md_id==$key): ?>class="aaddys"<?php endif ?> ><?php echo $value ?></a>
			<?php endforeach ?>
		</div>
		<?php endif;?>
    </div>
	
<!--  模版引擎扩展 -->
<?php echo $this->datagrid(array(
	'id'=>'order-list',
	'dataProvider'=>$pager,
    'search'=>true,
	'columns'=>array(
		array(
			'header' => '订单号',
			'name' => 'sn',
            'filter'=>'sn'
		),
		array(
			'header' => '订单建立日期',
			'name' => 'last_time',
		),
		array(
			'header' => '客户',
			'name' => 'cu_name',
			'value' => '<span class="khgl_xmpic"><img src="'.$this->basePath('public').'/images/kh_06.png" height="24" width="24" /></span><span class="khgl_03">{$data["cu_name"]}</span>',
            'filter'=>'cu_name'
        ),
		array(
			'header' => '实操项目',
			'name' => 'project_name',
            'filter'=>'project_name'
		),
		array(
			'header' => '疗程总次数',
			'name' => 'num',
		),
		array(
			'header' => '实操前剩余',
			'name' => 'before_num',
		),
		array(
			'header' => '本次实操次数',
			'name' => 'use_num',
		),
		array(
			'header' => '实操后剩余',
			'name' => 'after_num',
			'value' => '{$data["status"]<0?"N/A":$data["after_num"]}',
		),
		array(
			'header' => '美容师',
			'name' => 'operators',
            'value' => '{\PracticeOrder::getOperators($data["operators"],true)}',
		),
		array(
			'header' => '实操状态',
			'name' => 'status',
			'value' => '{\PracticeOrder::getStatus($data["status"],true)}',
		),
		array(
			'header' => '操作人',
			'name' => 'made_name',
		),
		array(
			'header' => '操作',
			'rel'=>'id',
			'template'=> '<a href="javascript:;" data-status="{$data["status"]}" class="btn default btn-xs green-stripe view">查看</a>',
		)
	),
));?>


</div>
<!--content_right_con!end-->
<script type="text/javascript">
$(function(){
	$(".stime a").click(function(){
		var stime = $(this).attr("rel");
		var url = changeURL("","stime",stime);
		var md_id = $('.md_type .aaddys').attr('rel');
		if(md_id!=undefined) 
			url = changeURL(url,"md_id",md_id);
		to_url(url);
	});

	$(".md_type a").click(function(){
		var md_id = $(this).attr("rel");
		var url = changeURL("","md_id",md_id);
		to_url(url);
	});

	
	$(".to_excel").click(function(event){
		var t = Itable2excel({
			worksheet:'数据分析',
			table: $('#order-list table')
		});
		var data64 = t.uri();
		if(data64==false)
			return false;
		event.currentTarget.href = data64;
	});

	$(".view").click(function(event){
		var status = $(this).attr("data-status");
		var id = $(this).parent().attr("rel");
		if(status==0){
			var url = "<?php echo $this->url('pay') ?>";
		}else{
			var url = "<?php echo $this->url('view') ?>";
		}
		url = changeURL(url,"id",id);
		to_url(url);

	});

});
</script>