<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/实操单-确认
                </div>
                <div class="tools">
                    <?php if($model->o_s->status==0): ?>
                        <button class="btn btn-sm blue table-group-action-submit action_hk"><i class="fa fa-check"></i>确认卡扣</button>
                        <button id="cancelOrder" class="btn btn-sm red table-group-action-submit"><i class="fa fa-eraser"></i>废弃订单</button>
                        <button onclick="to_url('<?php echo $this->url('edit',array('id'=>$model->o_s->id)) ?>')" class="btn btn-sm green table-group-action-submit"><i class="fa fa-mail-forward "></i>修改订单</button>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>订单概况
                        </div>
                        <div class="actions">
                            <button class="btn red"><?php echo \PracticeOrder::getStatus($model->o_s->status);?></button>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">实操单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn ?>
                            </div>
                        </div>


                        <div class="row static-info">
                            <div class="col-xs-5 name">耗卡时间：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->o_s->pay_time?date('Y-m-d H:i:s',$model->o_s->pay_time):'未耗卡';?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">本次实操项目：</div>
                            <div class="col-xs-7 value text-right">
                                <font class="xj_xm"><?php echo count($model->pros) ?></font> 个
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">本次实操疗次：</div>
                            <div class="col-xs-7 value text-right">
                                <font class="xj_lc"><?php echo array_sum(array_column($model->pros, 'use_num')) ?></font> 次
                            </div>
                        </div>


                        
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="row"> 
        <div class="col-md-12">
            <div class="portlet box blue-steel">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i>本次实操项目疗次
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-responsive"> 
                        <table class="table table-bordered table-hover " >
                            <thead>
                                <tr>
                                    <th>项目</th>
                                    <th>项目来源</th>
                                    <th>购买次数</th>
                                    <th>剩余次数</th>
                                    <th>成交价格（元）</th>
                                    <th>疗次单价（元）</th>
                                    <th>上次实操该项目日期(疗次)</th>
                                    <th>本次实操次数（疗次）</th>
                                    <th>本次实操配方</th>
                                    <th>本次实操美容师</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                    $sum_xm=$sum_lc=0;
                                    if($model->pros)
                                    foreach ($model->pros as $key => $value): 
                                        $ProjectInfo=\ProjectInfo::model()->findByPk($value['project_id']);
                                        $OrderSaleDetail=\OrderSaleDetail::model()->findByPk($value['detail_id']);
                                        $CustomerReProject=\CustomerReProject::model()->find("detail_id={$value['detail_id']}");
                                        $ProjectFormula=\ProjectFormula::model()->findByPk($value['formula_id']);
                                        $sum_xm++;
                                        $sum_lc+=$value['use_num'];
                                ?>
                                    <tr class="table_list">
                                        <td ><?php echo $ProjectInfo->name ?></td>
                                        <td ><?php echo \OrderSaleDetail::getBuyType($OrderSaleDetail->buy_type); ?></td>
                                        <td ><?php echo $OrderSaleDetail->num; ?></td>
                                        <td ><?php echo $CustomerReProject->re_num; ?></td>
                                        <td ><?php echo sprintf('%.2f',$OrderSaleDetail->pay_price); ?></td>
                                        <td ><?php echo sprintf('%.2f',$OrderSaleDetail->num?$OrderSaleDetail->pay_price/$OrderSaleDetail->num:0); ?></td>
                                        <td ><?php echo \PracticeOrderDetail::getLastTime($value["detail_id"]) ?></td>
                                        <td ><?php echo $value['use_num'] ?></td>
                                        <td ><?php echo $ProjectFormula->formula_name; ?></td>
                                        <td ><?php echo \EmployUser::getUserNames($value['operators']); ?></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        </div>


        <!--备注-->
        <div class="pos_cz_tow pos_cz_for_bz">
            <div class="pos_cz_for_bz01">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son">
                    <?php echo $model?$model->o_s->note:"" ?>
                </div>
            </div>
        </div>
        <!--备注!end-->



    </div>
</div>



{__TOKEN__}
<script type="text/javascript">


	$("#cancelOrder").click(function(){
        if(confirm("您确定要废弃此订单吗？")){
            var data={};
            data.__hash__ = $("input[name='__hash__']").val();//表单令牌
            $.post("<?php echo $this->url('cancel',array('id'=>$model->o_s->id)) ?>",data,function(data){
                Idialog.tips(data.msg,2);
                if(data.code==200){
                    setTimeout(function(){to_url('<?php echo $this->url("view",array('id'=>$model->o_s->id));?>')},2000);
                }
            }, "json");
        }
    });

    //确认卡扣
    $(".action_hk").click(function(){
        if(confirm("确认卡扣?")){
            var data={};
            data.__hash__ = $("input[name='__hash__']").val();//表单令牌
            $.post("<?php echo $this->url('paySave',array('id'=>$model->o_s->id)) ?>",data,function(data){
                Idialog.tips(data.msg,2);
                if(data.code==200){
                	if(data.data===true){
                		$.post("<?php echo $this->url('wxSendWj',array('id'=>$model->o_s->id)) ?>", '', function(data) {
                			/*optional stuff to do after success */
                		});
                    	setTimeout(function(){to_url('<?php echo $this->url("view",array('id'=>$model->o_s->id));?>')},2000);
                	}else{
                		var html=' 耗卡成功。警告：您当前所扣实操项目的设置中，存在问题：<br>1. 项目的配方配置不完善，<br>2. 配方中的商品不存在。以上问题将会导致库存管理的准确性失去控制。<br>建议您尽快联系管理员，为所有项目建立配方，前台人员也需要为本店建立好期初库存。'+data.data;
                		var d = Idialog({
								top:120,
								width:600,
								title:'警告',
								content:html,
								ok:function(obj){
									$.post("<?php echo $this->url('wxSendWj',array('id'=>$model->o_s->id)) ?>", '', function(data) {
			                			/*optional stuff to do after success */
			                		});
									to_url('<?php echo $this->url("view",array('id'=>$model->o_s->id));?>');
								},
								cancel:false,
								init:function(self){
									self.parents('.idialog_body').find(".idialog_ok").html('我知道了');
									self.parents('.idialog_body').siblings('.idialog_title').find('span').remove();
								},
							});
                	}
                }
            }, "json");
        }
    });
</script>