<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
	<div class="print_show col-md-12">
		<div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/实操单-查看
                </div>
                <div class="tools">
	                	<button onclick="history.go(-1)" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>返回</button>
                </div>
            </div>
        </div>
		<?php $sum_lc = array_sum(array_column($model->pros, 'use_num')) ?>
        <div class="row">
			<div class="col-md-6 col-sm-12">
	            <div class="portlet solid green-haze">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>订单概况
	                    </div>
	                    <div class="actions">
		                    <button class="btn red">疗次合计<?php echo $sum_lc ?></button>
	                    </div>
	                </div>
	                <div class="portlet-body">
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">实操单号：</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->sn ?>
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">耗卡时间</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->pay_time?date('Y-m-d H:i:s',$model->o_s->pay_time):'未耗卡';?>
	                        </div>
	                    </div>

	                    <div class="row static-info">
	                        <div class="col-xs-5 name">订单状态：</div>
	                        <div class="col-xs-7 value text-right">
		                        <?php if (!$model): ?>
	                        	<span class="label label-info label-sm">草稿</span>
								<?php else: ?>
	                        	<span class="label label-warning label-sm"><?php echo \PracticeOrder::getStatus($model->o_s->status);?></span>
								<?php endif ?>
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">本次实操项目：</div>
	                        <div class="col-xs-7 value text-right">
	                        	<font class="xj_xm"><?php echo count($model->pros) ?></font> 个
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">本次实操疗次：</div>
	                        <div class="col-xs-7 value text-right">
                                <font class="xj_lc"><?php echo $sum_lc ?></font> 次
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>

	        <div class="col-md-6 col-sm-12">
	            <div class="portlet solid red-intense">
	                <div class="portlet-body" style="padding-top: 10px;">
	                    <?php echo $cu_info ?>
	                </div>
	            </div>
	        </div>


        </div>

        <div class="row"> 
        <div class="col-md-12">
	        <div class="portlet box blue-steel">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i>本次实操项目疗次
                    </div>
                </div>
                <div class="portlet-body">
                	<div class="table-responsive"> 
						<table class="table table-bordered table-hover " >
							<thead>
								<tr>
									<th>项目</th>
									<th>项目来源</th>
									<th>购买次数</th>
									<th>剩余次数</th>
									<th>成交价格（元）</th>
									<th>疗次单价（元）</th>
									<th>上次实操该项目日期</th>
									<th>本次实操次数（疗次）</th>
									<th>本次实操配方</th>
									<th>本次实操美容师</th>
								</tr>
							</thead>
							<tbody>
								<?php 
									$sum_xm=$sum_lc=0;
									if($model->pros)
									foreach ($model->pros as $key => $value): 
										$ProjectInfo=\ProjectInfo::model()->findByPk($value['project_id']);
										$OrderSaleDetail=\OrderSaleDetail::model()->findByPk($value['detail_id']);
										$CustomerReProject=\CustomerReProject::model()->find("detail_id={$value['detail_id']}");
										$ProjectFormula=\ProjectFormula::model()->findByPk($value['formula_id']);
										$sum_xm++;
										$sum_lc+=$value['use_num'];
								?>
									<tr class="table_list">
											<td class="li001"><?php echo $ProjectInfo->name ?></td>
											<td class="li002"><?php echo \OrderSaleDetail::getBuyType($OrderSaleDetail->buy_type); ?></td>
											<td class="li003"><?php echo $OrderSaleDetail->num; ?></td>
											<td class="li004"><?php echo $CustomerReProject->re_num; ?></td>
											<td class="li005"><?php echo sprintf('%.2f',$OrderSaleDetail->pay_price); ?></td>
											<td class="li006"><?php echo sprintf('%.2f',$OrderSaleDetail->num?$OrderSaleDetail->pay_price/$OrderSaleDetail->num:0); ?></td>
											<td class="li007"><?php echo \PracticeOrderDetail::getLastTime($value["detail_id"]) ?></td>
											<td class="li008"><?php echo $value['use_num'] ?></td>
											<td class="li009"><?php echo $ProjectFormula->formula_name; ?></td>
											<td class="li010"><?php echo \EmployUser::getUserNames($value['operators']); ?></td>
									</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					</div>
                </div>
            </div>
        </div>
        </div>



		<?php if($list):?>
		<div class="row"> 
        <div class="col-md-12">
	        <div class="portlet box blue-steel">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-wechat "></i>客户满意度反馈
                    </div>
                </div>
                <div class="portlet-body">
                	<div class="table-responsive"> 
						<table class="table table-bordered table-hover " >
							<thead>
								<tr>
									<?php foreach($list as $v):?>
									<th><?php echo $v['title'];?></th>
									<?php endforeach;?>
									<th>备注</th>
								</tr>
							</thead>
							<tbody>
								<?php 
									$sum_xm=$sum_lc=0;
									if($model->pros)
									foreach ($model->pros as $key => $value): 
										$ProjectInfo=\ProjectInfo::model()->findByPk($value['project_id']);
										$OrderSaleDetail=\OrderSaleDetail::model()->findByPk($value['detail_id']);
										$CustomerReProject=\CustomerReProject::model()->find("detail_id={$value['detail_id']}");
										$ProjectFormula=\ProjectFormula::model()->findByPk($value['formula_id']);
										$sum_xm++;
										$sum_lc+=$value['use_num'];
								?>
									<tr class="table_list">
									<?php foreach($list as $v):?>
									<td><?php echo $v['score'];?></td>
									<?php endforeach;?>
									<td><?php echo $list[0]['note']?$list[0]['note']:'无';?></td>
									</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					</div>
                </div>
            </div>
        </div>
        </div>
		<?php endif;?>


		<!--备注-->
		<div class="pos_cz_tow pos_cz_for_bz">
			<div class="pos_cz_for_bz01">备注</div>
			<div class="pos_cz_for_bz02">
				<div class="pos_cz_for_bz02_son">
				<?php echo $model?$model->o_s->note:"" ?>
				</div>
			</div>
		</div>
		<!--备注!end-->
    </div>
</div>
