<?php
$themePath = $this->basePath('public');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>美业连锁管控平台-忘记密码</title>
<link href="<?php echo $this->basePath('public'); ?>/css/login.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->basePath('public/js/jquery.js'); ?>"></script>
<script src="<?php echo $this->basePath('public'); ?>/js/Idialog.js" type="text/javascript"></script>
<link href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>"></script>
<!--
<script id="adLayer" type="text/javascript" src="<?php echo $this->basePath('public/js/King_Chance_Layer.js');?>" data="<?php echo $themePath;?>"></script>
-->
<style type="text/css">
	.idialog_tips {
		background-color: #fff;
		border: 1px solid #00dddd;
		left: 50%;
		overflow: hidden;
		padding: 20px;
		position: fixed;
		top: 200px;
		z-index: 999;
	}
	#loading {
		position:fixed;
		left:0;
		width:100%;
		height:100%;
		top:0;
		background:rgb(0, 0, 0);
		opacity:0.5;
		filter:alpha(opacity=50);
	}
	#loading div{
		position:absolute;  cursor1:wait;left:50%;top:50%;width:auto;height:16px;padding:13px 22px 28px 30px;background: url(<?php echo $this->basePath('public');?>/images/loading.gif) no-repeat scroll 5px 10px;text-indent: -99999px;color:#000;
	}
</style>
</head>
<body>
	<div class="top">
		<div class="top_center">
			<span
				id="go_back_home" style="float: right; background-color: #fff; border: solid 1px #ddd; display: inline-block; line-height: 25px; height: 25px; padding-left: 15px; padding-right: 15px; color: #666; font-size: 12px; margin-top: 25px; cursor: pointer;">返回首页</span>
			<div class="logo">
				<img src="<?php echo $themePath; ?>/images/meihui_logo.png" width="170" height="42" />
			</div>
			<span class="logo_span">忘记密码</span>
		</div>
	</div>
	<div class="forget_page">
	  	<div class="forget_page_tit forget_buzhou_1">
	    	<ul>
	        	<li class="forget_li">1、确认账号</li>
	            <li class="forget_visit">2、安全验证</li>
				<li class="forget_visit">3、重置密码</li>
	        </ul>
	    </div>
		<div class="main">
			<form action="" method="post">
		    	<div class="forget_pp">
			    	<div class="plat_list">
			            <div class="plat_list_left">手机号</div>
						<div class="plat_list_right">
						    <input name="phone" datatype="m"  type="text" class="input_1 red_border" placeholder="请输入您的账号（手机号）" />
						    <p class="red_text"></p>
						</div>
						<div class="clear"></div>
					</div>
				    <div class="plat_list">
				        <div class="plat_list_left">验证码</div>
				        <div class="plat_list_right">
				            <input id="verifyCode" datatype="n4-4" errormsg="请输入4位验证码" name="verifyCode"  type="text" class="input_2" value="" placeholder="请输入4位验证码"/>
				            <span class="login_img" style="margin-left:12px;"><img src="<?php echo $this->url('verify'); ?>" width="105" height="40" /></span>
				            <span style="float:left; font-size:14px; line-height:40px;"><a href="javascript:changeVerify();" class="blue">换一张</a></span>
				        	<p class="red_text"></p>
				        </div>
				        <div class="clear"></div>
				                    
				    </div>
				          <div class="start_goto"><a id="form_submit" href="javascript:;" class="xiayibu_a">下一步</a></div>
				</div>
			</form>
	    </div>
	</div>
	
	<div class="footer">
		<div class="footer_center">© Copyright 2011-2016 武汉美慧商业技术有限公司
			鄂ICP备14003221号</div>
	</div>



<script type="text/javascript">
//new PCAS("pca_province,--省--","pca_city,--市--");
$('#go_back_home').click(function() {
	var url = 'http://www.etwasd.com';
	window.location.href = url;
});
$('#form_submit').click(function() {
	$('form').submit();
});


//提交前验证
$('form').Validform({
	tiptype:3,
	ignoreHidden:true,
	ajaxPost:true,
	beforeSubmit:function() {
		var next = false;
		var ajax_url = "<?php echo $this->url('checkdecode'); ?>";
		var data = $('form').serialize();
		var _html = "<div id='loading'><div>正在加载，请等待...</div></div>";
	    $('body').append(_html);
		$.ajax({
			url : ajax_url,
			data : data,
			type : 'post',
			async : false,
			dataType : 'json',
			complete : function() {
				$('#loading').remove();
			},
			success : function(json) {
				if(json.code == '200') {
					next = true;
				}else{
					Idialog.tips(json.msg,3);
					changeVerify();
				}
			},
			error : function(XMLHttpRequest, textStatus, errorThrown) {
				alert('连接失败！');
			}
		});

		return next;
	},
	callback:function(json){
		var next = false;
		$('#Validform_msg').remove();
		if (json.status) {
			alert('连接失败！');
		};
		if(json.code == '200') {
			next = true;
			window.location.href=json.msg;
		}else{
			Idialog.tips(json.msg,3);
			changeVerify();
		}
		return next;
	}
});

function changeVerify() {
	var timestamp=new Date().getTime();
	var url = "<?php echo $this->url('verify'); ?>";
	url += '&timestamp=' + timestamp;
	$('.login_img').children('img').attr('src', url);
	$('#verifyCode').val('')
}
</script>
</body>
</html>
