<?php
$themePath = $this->basePath('public');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>美业连锁管控平台-忘记密码</title>
<link href="<?php echo $this->basePath('public'); ?>/css/login.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->basePath('public/js/jquery.js'); ?>"></script>
<script src="<?php echo $this->basePath('public'); ?>/js/Idialog.js" type="text/javascript"></script>
<link href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>"></script>
<!--
<script id="adLayer" type="text/javascript" src="<?php echo $this->basePath('public/js/King_Chance_Layer.js');?>" data="<?php echo $themePath;?>"></script>
-->
<style type="text/css">
	.idialog_tips {
		background-color: #fff;
		border: 1px solid #00dddd;
		left: 50%;
		overflow: hidden;
		padding: 20px;
		position: fixed;
		top: 200px;
		z-index: 999;
	}
	#loading {
		position:fixed;
		left:0;
		width:100%;
		height:100%;
		top:0;
		background:rgb(0, 0, 0);
		opacity:0.5;
		filter:alpha(opacity=50);
	}
	#loading div{
		position:absolute;  cursor1:wait;left:50%;top:50%;width:auto;height:16px;padding:13px 22px 28px 30px;background: url(<?php echo $this->basePath('public');?>/images/loading.gif) no-repeat scroll 5px 10px;text-indent: -99999px;color:#000;
	}
</style>
</head>
<body>
	<div class="top">
		<div class="top_center">
			<span
				id="go_back_home" style="float: right; background-color: #fff; border: solid 1px #ddd; display: inline-block; line-height: 25px; height: 25px; padding-left: 15px; padding-right: 15px; color: #666; font-size: 12px; margin-top: 25px; cursor: pointer;">返回首页</span>
			<div class="logo">
				<img src="<?php echo $themePath; ?>/images/howa_logo.png" width="170" height="42" />
			</div>
			<span class="logo_span">忘记密码</span>
		</div>
	</div>
	<div class="forget_page">
	  <div class="forget_page_tit forget_buzhou_2">
	    	<ul>
	        	<li class="forget_visit">1、确认账号</li>
	            <li class="forget_li">2、安全验证</li>
				<li class="forget_visit">3、重置密码</li>
	        </ul>
	    </div>
	    <form action="" method="post">
		<div class="main">
	    	<div class="forget_pp">
	    	  <div class="forget_two_text">您的账号为：<?php echo substr_replace($model->user_name,'*****',3,5);?></div>
	          <div class="plat_list">
	            <div class="plat_list_left">验证码</div>
	            <div class="plat_list_right">
		            <input name="phoneCode" datatype="n" type="text" class="input_2" value="" />
		            <span class="msmCode input_3">获取验证码</span>
		            <span style="display:none;" class="input_4"><font id='outtime'>120</font>秒后可重发</span>
		            <p class="red_text"></p>
	            </div>
	              <div class="clear"></div>
	          </div>
	          <div class="forget_two_text1">如果长时间没有收到验证码，请 <a class='action_hp' href="javascript:;">查看帮助</a></div>
	          <div class="start_goto"><a id="form_submit" href="javascript:;" class="xiayibu_a">下一步</a></div>
	      	</div>
	    </div>
		</form>
	</div>
	
	<div class="footer">
		<div class="footer_center">© Copyright 2011-2016 武汉好哇商业技术有限公司
			鄂ICP备14003221号</div>
	</div>
<div class="yanzheng_tan" style="left:50%;margin-left:-290px; top:50%;margin-top:-134px;display:none;">
	<div class="yanzheng_tan_tit"><span></span>没有收到验证码怎么办？</div>
    <div class="yanzheng_tan_page">
      <p>亲爱的用户，验证码短信正常都会在数秒钟内发送，如果您未收到短信/邮件，请参照如下常见情况进行解决：</p>
      <p>1、由于您的手机设定了某些安全设置，验证码短信可能被拦截进了垃圾箱。请打开垃圾箱查看，并将HOWA智能云平台号码添加为白名单。</p>
      <p>2、由于运营商通道故障造成了短信/邮件发送时间延迟，请耐心稍候片刻或点击重新获取验证码。</p>
      <p>3、关于手机号验证，目前支持移动、联通和电信的所有号码，暂不支持国际及港澳台地区号码。</p>
      <p>如果您尝试了上述方式后均未解决，或存有其他疑问，请通过热线电话027-87050575获取客户协助。</p>
    </div>
</div>
<div class="zhezhao" style="display:none;background-color:#000; width:100%; height:100%; position:fixed; z-index:100; top:0; left:0;filter:alpha(opacity=80);-moz-opacity:0.8;-khtml-opacity: 0.8;opacity: 0.8;"></div>


<script type="text/javascript">
$('.action_hp').click(function(){
	$('.yanzheng_tan,.zhezhao').show();
});
$('.yanzheng_tan_tit span').click(function(){
	$('.yanzheng_tan,.zhezhao').hide();
});
//new PCAS("pca_province,--省--","pca_city,--市--");
$('#go_back_home').click(function() {
	var url = 'http://www.howa.com.cn';
	window.location.href = url;
});
$('#form_submit').click(function() {
	$('form').submit();
});
var s = 120, t;
function times(){
	s--;
	$("#outtime").html(s);
	t = setTimeout('times()', 1000);
	if ( s <= 0 ){
		s = 120;
		clearTimeout(t);

		$('.msmCode').show();
		$('.msmCode').next().hide();

	}
}
//短信验证码
$('.msmCode').click(function(){

	$.post("<?php echo $this->url('phoneCode2') ?>", '',function(json){
		if(json.code == '200'){
			$('.msmCode').hide();
			$('.msmCode').next().show();
			times();
		}else{
			Idialog.tips(json.msg,3);
		}
	},"json");
});
//提交前验证
$('form').Validform({
	tiptype:3,
	ignoreHidden:true,
	ajaxPost:true,
	callback:function(json){
		var next = false;
		$('#Validform_msg').remove();
		if (json.status) {
			alert('连接失败！');
		};
		if(json.code == '200') {
			next = true;
			window.location.href=json.msg;
		}else{
			Idialog.tips(json.msg,3);
			//changeVerify();
		}
		return next;
	}
});

function changeVerify() {
	var timestamp=new Date().getTime();
	var url = "<?php echo $this->url('verify'); ?>";
	url += '&timestamp=' + timestamp;
	$('.login_img').children('img').attr('src', url);
	$('#verifyCode').val('')
}
</script>
</body>
</html>
