<?php
$themePath = $this->basePath('public');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>美业连锁管控平台-忘记密码</title>
<link href="<?php echo $this->basePath('public'); ?>/css/login.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->basePath('public/js/jquery.js'); ?>"></script>
<script src="<?php echo $this->basePath('public'); ?>/js/Idialog.js" type="text/javascript"></script>
<link href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>"></script>
<!--
<script id="adLayer" type="text/javascript" src="<?php echo $this->basePath('public/js/King_Chance_Layer.js');?>" data="<?php echo $themePath;?>"></script>
-->
<style type="text/css">
	.idialog_tips {
		background-color: #fff;
		border: 1px solid #00dddd;
		left: 50%;
		overflow: hidden;
		padding: 20px;
		position: fixed;
		top: 200px;
		z-index: 999;
	}
	#loading {
		position:fixed;
		left:0;
		width:100%;
		height:100%;
		top:0;
		background:rgb(0, 0, 0);
		opacity:0.5;
		filter:alpha(opacity=50);
	}
	#loading div{
		position:absolute;  cursor1:wait;left:50%;top:50%;width:auto;height:16px;padding:13px 22px 28px 30px;background: url(<?php echo $this->basePath('public');?>/images/loading.gif) no-repeat scroll 5px 10px;text-indent: -99999px;color:#000;
	}
</style>
</head>
<body>
	<div class="top">
		<div class="top_center">
			<span
				id="go_back_home" style="float: right; background-color: #fff; border: solid 1px #ddd; display: inline-block; line-height: 25px; height: 25px; padding-left: 15px; padding-right: 15px; color: #666; font-size: 12px; margin-top: 25px; cursor: pointer;">返回首页</span>
			<div class="logo">
				<img src="<?php echo $themePath; ?>/images/howa_logo.png" width="170" height="42" />
			</div>
			<span class="logo_span">忘记密码</span>
		</div>
	</div>
	<div class="forget_page">
		<div class="forget_page_tit forget_buzhou_3">
			<ul>
				<li class="forget_visit">1、确认账号</li>
				<li class="forget_visit">2、安全验证</li>
				<li class="forget_li">3、重置密码</li>
			</ul>
		</div>
		<div class="main">
			<div class="zc_ok_tit" style="padding-bottom:20px;"><span></span>恭喜您重置密码成功！</div>
			<div class="zc_ok_page"> <a href="http://www.howa.com.cn" class="next_button">直接登录</a> </div>
		</div>
	</div>
	
	<div class="footer">
		<div class="footer_center">© Copyright 2011-2016 武汉好哇商业技术有限公司
			鄂ICP备14003221号</div>
	</div>

<script type="text/javascript">
$('#go_back_home').click(function() {
	var url = 'http://www.howa.com.cn';
	window.location.href = url;
});
</script>
</body>
</html>
