<?php
	$themePath = $this->basePath('public');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>meihui连锁管控平台-注册</title>
<link href="<?php echo $this->basePath('public'); ?>/css/login.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->basePath('public/js/jquery.js'); ?>"></script>
<script src="<?php echo $this->basePath('public'); ?>/js/Idialog.js" type="text/javascript"></script>
<link href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>"></script>

<!--
<script id="adLayer" type="text/javascript" src="<?php echo $this->basePath('public/js/King_Chance_Layer.js');?>" data="<?php echo $themePath;?>"></script>
-->
<style type="text/css">
	.idialog_tips {
		background-color: #fff;
		border: 1px solid #00dddd;
		left: 50%;
		overflow: hidden;
		padding: 20px;
		position: fixed;
		top: 200px;
		z-index: 999;
	}
</style>
</head>
<body>

	<div class="top">
		<div class="top_center">
			<span id="go_back_home" style="float: right; background-color: #fff; border: solid 1px #ddd; display: inline-block; line-height: 25px; height: 25px; padding-left: 15px; padding-right: 15px; color: #666; font-size: 12px; margin-top: 25px; cursor: pointer;">返回首页</span>
			<div class="logo">
				<img src="<?php echo $this->basePath('public'); ?>/images/meihui_logo.png" width="170" height="42" />
			</div>
			<span class="logo_span">注册</span>
		</div>
	</div>
	<div class="advertising">
		<div class="advertising_page">
			<a href="###"><img src="<?php echo $themePath; ?>/images/top.jpg"></a><br><br>
	    </div>
	</div>
	<div class="page">
		<div class="page_tit buzhou_4">
			<ul>
				<li class="buzhou_visit">1、基本资料</li>
	            <li class="buzhou_visit">2、选择版本</li>
				<li class="buzhou_visit">3、上传营业执照</li>
	            <li class="buzhou_1_li">4、完成</li>
			</ul>
		</div>
		<div class="main">
			<div class="zc_ok_tit"><span></span>恭喜您注册成功！请等待审核</div>
			<div class="zc_ok_page">
			<p>恭喜您申请meihui智能平台成功，我们将在3个工作日内给您回复审核结果！请保持手机畅通！	     </p>
			<p> 如有疑问请拨打客服电话：027-87050575 </p>
			</div>
			<div class="zc_ok_weixin">
			<p><img src="<?php echo $this->url('showqr') ?>" width="159" height="159" /></p><?php //echo $themePath; ?><!-- /images/meihui.jpg -->
			<p>关注meihui公众号，第一时间获取审核结果</p>
			</div>
		</div>
	</div>
	<div class="footer">
		<div class="footer_center">© Copyright 2011-2015 武汉美慧商业技术有限公司
			鄂ICP备14003221号</div>
	</div>
<script type="text/javascript">
	$('#go_back_home').click(function() {
	var url = 'http://www.etwasd.com';
	window.location.href = url;
	});
</script>
</body>
</html>
