
    <!--table_container-->
    <div class="table_container clear">
        <!--table_con-->
        <div class="table_con pos_cz_qr_top_04">

            <!--table_con_son-->
            <div class="table_con_son">
                <!-- <div class="pos_cz_tow_top pos_cz_qr_02">赠送现金</div>-->
                <div class="table_title khgl_com">
                    <!--<div class="khgl_radio_tilte ck_splb_checked"></div>-->
                    <ul>
                        <li>商品分类</li>
                        <li>品牌或系列</li>
                        <li>商品名称</li>
                        <li>商品编码</li>
                        <li>规格</li>
                        <li>单位</li>
                        <li>库存数量</li>
                        <li>额外数量</li>
                    </ul>
                </div>

                <?php if(empty($list)):?>
                    <div class="table_list khgl_com clear">
                        <!--<div class="khgl_radio_list ck_splb_checked"><input type="checkbox" /></div>-->
                        <ul style="text-align: center;">
                            暂无数据！
                        </ul>
                    </div>
                <?php else:?>
                    <?php foreach($list as $item):?>
                        <?php
                            $num = null; $extra_num = null;
                            if(array_key_exists($item['id'],$invo_num)){
                                $num = $invo_num[$item['id']]['num'];
                                $extra_num = $invo_num[$item['id']]['extra_num'];
                            }
                        ?>
                        <div class="table_list khgl_com clear">
                            <!--<div class="khgl_radio_list ck_splb_checked"><input type="checkbox" /></div>-->
                            <ul>
                                <li class="li001"><?php echo $item['fname'];?></li>
                                <li class="li002"><?php echo $item['cname'];?></li>
                                <li class="li003"><?php echo $item['name'];?></li>
                                <li class="li004"><?php echo $item['code'];?></li>
                                <li class="li005"><?php echo $item['specs'];?></li>
                                <li class="li006"><?php echo $item['unit'];?></li>
                                <li class="li007">
                                    <input name="num" value="<?php echo $num;?>" pid="<?php echo $item['id'];?>" type="text" class="pos_cz_tow_two05 pos_gm_th_02" style="width:100px;" />
                                </li>
                                <li class="li008">
                                    <input name="extra_num" value="<?php echo $extra_num;?>" pid="<?php echo $item['id'];?>" type="text" class="pos_cz_tow_two05 pos_gm_th_02" style="width:100px;" />
                                </li>
                            </ul>
                        </div>
                    <?php endforeach;?>
                <?php endif;?>

            </div><!--table_con_son!end-->

        </div><!--table_con!end-->
        <!--分页-->
    <div class="fjgl_th_for clear">
        <a href="javascript:;" class="syy <?php echo $page==1?'syy011':'';?>">上一页</a>
            <?php if(ceil(count($_list)/$per_page)<=5):?>
                <?php for($i=1;$i<=ceil(count($_list)/$per_page);$i++):?>
                    <a href="javascript:" <?php echo $i==$page?'class="fenye"':'class="fen_page"';?>><?php echo $i;?></a>
                <?php endfor;?>
            <?php else:?>
                <?php if($page<=3):?>
                    <?php for($i=1;$i<=5;$i++):?>
                        <a href="javascript:" <?php echo $i==$page?'class="fenye"':'class="fen_page"';?>><?php echo $i;?></a>
                    <?php endfor;?>
                <?php else:?>
                    <a href="javascript:" class="fen_page">1</a>
                    <?php if($page>=5):?>
                        <a href="javascript:">...</a>
                    <?php endif;?>
                    <?php if($page+2<ceil(count($_list)/$per_page)):?>
                        <a href="javascript:" class="fen_page"><?php echo $page-2;?></a>
                        <a href="javascript:" class="fen_page"><?php echo $page-1;?></a>
                        <a href="javascript:" class="fenye"><?php echo $page;?></a>
                        <a href="javascript:" class="fen_page"><?php echo $page+1;?></a>
                        <a href="javascript:" class="fen_page"><?php echo $page+2;?></a>
                    <?php else:?>
                        <?php for($i=ceil(count($_list)/$per_page)-5;$i<ceil(count($_list)/$per_page);$i++):?>
                            <a href="javascript:" <?php echo $i==$page?'class="fenye"':'class="fen_page"';?>><?php echo $i;?></a>
                        <?php endfor;?>
                    <?php endif;?>
                <?php endif;?>
            <?php endif;?>
            <?php if(count($_list)/$per_page>6):?>
                <?php if(ceil(count($_list)/$per_page)>7&&$page+3<ceil(count($_list)/$per_page)):?>
                <a href="javascript:">...</a>
                <?php endif;?>
                <a href="javascript:" <?php echo ceil(count($_list)/$per_page)==$page?'class="fenye"':'class="fen_page"';?>><?php echo ceil(count($_list)/$per_page);?></a>
            <?php endif;?>

        <a href="javascript:;" class="xyy syy <?php echo $page==ceil(count($_list)/$per_page)?'syy011':'';?>">下一页</a>
        <span style=" margin-left:10px;">每页&nbsp;<?php echo $per_page;?>&nbsp;条
            &nbsp;共&nbsp;<?php echo ceil(count($_list)/$per_page);?>&nbsp;页&nbsp;&nbsp;到第</span>
        <input name="to_page" type="text" style=" width:33px; height:18px;" />页
        <a href="javascript:" class="syy012 to_page">GO</a> &nbsp;&nbsp;&nbsp;
        共&nbsp;<?php echo count($_list);?>&nbsp;条
    </div> <!--分页！end-->
    </div>
    
