<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    <title>meihui</title>

    <!-- Set render engine for 360 browser -->
    <meta name="renderer" content="webkit">

    <!-- No Baidu Siteapp-->
    <meta http-equiv="Cache-Control" content="no-siteapp"/>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileColor" content="#0e90d2">

    <link rel="stylesheet" href="<?php echo $this->basePath('public/h5/assets');?>/css/amazeui.min.css">
    <link rel="stylesheet" href="<?php echo $this->basePath('public/h5/assets');?>/css/app.css">
</head>
<body class="has-header">

<header class="am-text-center am-padding-sm fixed-top">
    <div class="am-fl out"><i class="am-icon-angle-left am-icon-sm"></i></div>
    <b>现金流水报表</b>
</header>

<table class="am-table am-margin-top-sm data-table am-text-center">
    <tr>
        <td>客户姓名</td>
        <td>业务类型</td>
        <td>实收现金</td>
    </tr>
    <?php foreach ($list as $v): ?>
        <tr>
            <td><a href=""><?php echo $v['name'] ?></a></td>
            <td><?php echo $v['type'] ?></td>
            <td><?php echo $v['xj'] ?></td>
        </tr>
    <?php endforeach ?>
   
</table>

<script src="<?php echo $this->basePath('public/h5/assets');?>/js/jquery.min.js"></script>
<script src="<?php echo $this->basePath('public/h5/assets');?>/js/amazeui.min.js"></script>
<script src="<?php echo $this->basePath('public/h5/assets');?>/js/my.js"></script>
<script>
$(function(){
  
    $('.out').click(function(){
        history.go(-1);
    });

    
});
</script>
</body>
</html>
