	<div class="content_right_con">
		<div class="content_right_con_top">消息中心</div>
		<div class="page_add">
		<span style="font-size:12px; color:#666; margin-left:15px;">发布日期：<?php echo date("Y-m-d H:i:s",$model->create_time)  ?></span><span style="font-size:12px; color:#666; margin-left:100px;">发布人：<?php echo $model->send_name ?></span>
		</div>
		<div class="xufei_page">
		<div class="plat_xiaoxi_page"><?php echo $model->content ?></div>
		</div>
	</div>