<div class="row">
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 margin-bottom-10">
		<div class="dashboard-stat blue-madison">
			<div class="visual">
				<i class="fa fa-briefcase fa-icon-medium"></i>
			</div>
			<div class="details">
				<div class="number">
					 <?php echo $YDD;?>
				</div>
				<div class="desc">
					 已到店人数
				</div>
			</div>
			<a class="more" href="<?php echo $this->url("rebook/index/index");?>">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
		<div class="dashboard-stat red-intense">
			<div class="visual">
				<i class="fa fa-shopping-cart"></i>
			</div>
			<div class="details">
				<div class="number">
					 <?php echo $DDD;?>
				</div>
				<div class="desc">
					 待到店人数
				</div>
			</div>
			<a class="more" href="<?php echo $this->url("rebook/index/index");?>">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
		<div class="dashboard-stat green-haze">
			<div class="visual">
				<i class="fa fa-group fa-icon-medium"></i>
			</div>
			<div class="details">
				<div class="number">
					 <?php echo $FWZ;?>
				</div>
				<div class="desc">
					 服务中人数
				</div>
			</div>
			<a class="more" href="<?php echo $this->url("rebook/index/index");?>">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
</div>



<div class="row">
	<div class="col-md-12">
        <div class="portlet portlet-table box blue-steel">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-th-large"></i>待处理订单
                </div>
            </div>
            <div class="portlet-body">
	            <table class="table table-bordered table-hover">
					<thead>
						<tr>
							<th>订单号</th>
							<th>客户</th>
							<th>订单类型</th>
							<th>订单内容</th>
							<th>订单状态</th>
							<th>操作</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($list as $row): ?>
							<?php if ($row['ptype']): ?>
								<tr class="table_list">
									<td><?php echo $row['sn'] ?></td>
									<td><span class="khgl_xmpic"><img src="<?php echo $this->basePath("public") ?>/images/kh_06.png" height="24" width="24"></span><span class="khgl_03"><?php echo $row['cu_name'] ?></span></td>
									<td><?php echo \OrderSale::getType($row['type']) ?></td>
									<td><?php echo \OrderSale::getBody($row['id']) ?></td>
									<td>待付款</td>
									<td class="order"><a rel="<?php echo $row['id'] ?>" data-type="<?php echo $row['type'] ?>" href="javascript:;" class="btn default btn-xs green-stripe khca">查看</a></td>
								</tr>
							<?php else: ?>
								<tr class="table_list">
									<td><?php echo $row['sn'] ?></td>
									<td><span class="khgl_xmpic"><img src="<?php echo $this->basePath("public") ?>/images/kh_06.png" height="24" width="24"></span><span class="khgl_03"><?php echo $row['cu_name'] ?></span></td>
									<td>实操</td>
									<td><?php echo \PracticeOrder::getBody($row['id']) ?></td>
									<td>待确认</td>
									<td class="practice"><a rel="<?php echo $row['id'] ?>" href="javascript:;" class="btn default btn-xs green-stripe khca">查看</a></td>
								</tr>
							<?php endif ?>
						<?php endforeach ?>
					
					</tbody>
				</table>
            	
            </div>
        </div>
    </div>
</div>


	


<?php if ($cu_count==0): ?>
	<!-- 没有客户列表 认为是新系统 -->
	<div id="qt_cover">
		<div class="qtcover" style="display:block;"></div>
		<div class="qtcover_02" style=" top:357px; left:606px;">
		    <div class="qtcover_01_top"><p>检测到您是第一次登录系统，请务必建立《期初客户档案》与《商品期初库存》！<span style=" color:#ff0000;">否则系统将无法正常运行</span></p></div>
		    <div class="qtcover_01_two"><a href="javascript:$('#qt_cover').remove();">确 认</a></div>
		</div>
	</div>
<?php endif ?>


<script type="text/javascript">
$(function(){
	$(".order a").click(function(){
		var type=$(this).attr("data-type");
		var id=$(this).attr("rel");
		switch(type){
			case '0':
				//还款
				to_url('<?php echo $this->url("pos/repay/edit") ?>&id='+id);
				break;
			case '1':
				//购买
				to_url('<?php echo $this->url("pos/sale/edit") ?>&id='+id);
				break;
			case '2':
				//充值
				to_url('<?php echo $this->url("pos/recharge/edit") ?>&id='+id);
				break;
			default:
				
		}

	});

	$(".practice a").click(function(){
		var id=$(this).attr("rel");
		to_url('<?php echo $this->url("pos/practice/pay") ?>&id='+id);
	});


});
</script>