
<h3 class="bold font-green-haze">POS开单</h3>
<div class="tiles">

	<div class="pos_gm_bj tile bg-green double ">
		<div class="tile-body">
			<i class="fa fa-shopping-cart"></i>
		</div>
		<div class="tile-object">
			<div class="name">
				 购买项目/产品/卡券
			</div>
		</div>
	</div>
	<div class="tile bg-red-sunglo pos_cz_bj">
		<div class="tile-body">
			<i class="fa fa-credit-card"></i>
		</div>
		<div class="tile-object">
			<div class="name">
				 充值
			</div>
		</div>
	</div>
	<div class="tile bg-yellow-saffron pos_hk_bj">
		<div class="tile-body">
			<i class="fa fa-gbp"></i>
		</div>
		<div class="tile-object">
			<div class="name">
				 还款
			</div>
		</div>
	</div>
	<div class="tile bg-purple-studio pos_sc_bj">
		<div class="tile-body">
			<i class="fa fa-flask"></i>
		</div>
		<div class="tile-object">
			<div class="name">
				 实操单
			</div>
		</div>
	</div>
	<div class="tile bg-blue-hoki pos_dh_bj">
		<div class="tile-body">
			<i class="fa fa-random"></i>
		</div>
		<div class="tile-object">
			<div class="name">
				 兑换
			</div>
		</div>
	</div>
	<div class="tile bg-grey-cascade double pos_tui_bj">
		<div class="tile-body">
			<i class="fa fa-retweet"></i>
		</div>
		<div class="tile-object">
			<div class="name">
				 退款/退卡/退项/退产品
			</div>
		</div>
	</div>
</div>

<div class="space20"></div>
<h3 class="bold font-blue-hoki">客户服务</h3>
	<div class="tiles">

		<div class="tile bg-yellow-saffron pos_jc_bj">
			<div class="tile-body">
				<i class="fa fa-briefcase"></i>
			</div>
			<div class="tile-object">
				<div class="name">
					 寄存领取
				</div>
			</div>
		</div>
		<div class="tile bg-red-sunglo pos_dj_bj">
			<div class="tile-body">
				<i class="fa fa-plane"></i>
			</div>
			<div class="tile-object">
				<div class="name">
					 会员等级升级
				</div>
			</div>
		</div>
		<div class="tile bg-blue-madison pos_rh_bj">
			<div class="tile-body">
				<i class="fa fa-user"></i>
			</div>
			<div class="tile-object">
				<div class="name">
					 客户入会
				</div>
			</div>
		</div>
		<div class="tile bg-green-meadow pos_ly_bj" data-url="<?php $company_info=\Ivy::app()->user->getState('company_info');echo $company_info['has_invo']!='Y'?$this->url('noinvo/recipients/edit'):$this->url('invo/out/edit',array('type'=>2)) ?>">
			<div class="tile-body">
				<i class="fa fa-laptop"></i>
			</div>
			<div class="tile-object">
				<div class="name">
					 新建领用单
				</div>
			</div>
		</div>
	</div>



<!-- 客户选择弹出框 -->
<div id="choose_cu" style="display:none;">
	<div class="form-horizontal">
		<div class="form-group">
			<div class="col-md-12">
				<div class="ch_cu">
					<button type="button" class="btn blue " data="md_search">本门店搜索</button>
					<button type="button" class="btn " data="all_search" >全连锁搜索</button>
				</div>
			</div>
		</div>

		<div class="form-group md_search">
			<label class="col-md-3 control-label">客户姓名：</label>
			<div class="col-md-9">
				<?php echo \Ivy::app()->widget('common/selectCustomer',array('id'=>'md_s')); ?>
			</div>
		</div>
		<div class="form-group all_search none">
			<label class="col-md-3 control-label">客户姓名：</label>
			<div class="col-md-9">
				<?php echo \Ivy::app()->widget('common/selectCustomer',array('id'=>'all_s','param'=>array('dept=all'))); ?>
			</div>
		</div>
	</div>
</div>

<!-- 客户入会选择弹出框 -->
<div id="choose_cu_rh" style="display:none;">

	<div class="form-horizontal">
		<div class="form-group">
			<div class="col-md-12">
				<button type="button" class="btn blue " data="md_search">本门店搜索</button>
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-3 control-label">客户姓名：</label>
			<div class="col-md-9">
				<?php echo \Ivy::app()->widget('common/selectCustomer'); ?>
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-3 control-label">消费类型：</label>
			<div class="col-md-9 radio-list">
				<label class="radio-inline">
				<input type="radio" name="rh_type" id="sale" value="sale" checked> 购买 </label>
				<label class="radio-inline">
				<input type="radio" name="rh_type" id="recharge" value="recharge"> 充值 </label>
			</div>
		</div>
	</div>
</div>

<!-- 客户会员等级升级-->
<div id="choose_cu_dj" style="display:none;">
	<div class="form-horizontal">
		<div class="form-group">
			<div class="col-md-12">
				<button type="button" class="btn blue " data="md_search">本门店搜索</button>
			</div>
		</div>
		<div class="form-group">
			<label class="col-md-3 control-label">客户姓名：</label>
			<div class="col-md-9">
				<?php echo \Ivy::app()->widget('common/selectCustomer'); ?>
			</div>
		</div>

		<div class="form-group">
			<label class="col-md-3 control-label">当前等级：</label>
			<label class="col-md-9 control-label cu_level" style="text-align:left"></label>
		</div>
		
		<div class="form-group">
			<label class="col-md-3 control-label">新等级：</label>
			<div class="col-md-9">
				<select class="level form-control input-small">
				<?php foreach ($mem_list as $value): ?>
					<option value ="<?php echo $value['id'] ?>"><?php echo $value['level_name'] ?></option>
				<?php endforeach ?>
				</select>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
$(function(){
	
	//卡券兑换
	$(".pos_dh_bj").click(function(){
		$(".ch_cu button").eq(1).hide();
		to_order($(this),"<?php echo $this->url('pos/voucher/add');?>");
	});
	//购买流程
	$(".pos_gm_bj").click(function(){
		$(".ch_cu button").eq(1).hide();
		to_order($(this),"<?php echo $this->url('pos/sale/add');?>");
	});
	//充值流程
	$(".pos_cz_bj").click(function(){
		$(".ch_cu button").eq(1).hide();
		to_order($(this),"<?php echo $this->url('pos/recharge/add');?>");
	});
	//还款流程
	$(".pos_hk_bj").click(function(){
		$(".ch_cu button").eq(1).hide();
		to_order($(this),"<?php echo $this->url('pos/repay/add');?>");
	});
	//退款流程
	$(".pos_tui_bj").click(function(){
		$(".ch_cu button").eq(1).hide();
		to_order($(this),"<?php echo $this->url('pos/refund/pro');?>");
	});
    //寄存领取流程
    $(".pos_jc_bj").click(function(){
    	$(".ch_cu button").eq(1).hide();
        to_order($(this),"<?php echo $this->url('pos/receive/add');?>");
    });
    //寄存领取流程
    $(".pos_ly_bj").click(function(){
    	var url = $(this).attr("data-url");
        to_url(url);
    });

    //实操单 开放跨店
    $(".pos_sc_bj").click(function(){
    	$(".ch_cu button").eq(1).show();
        to_order($(this),"<?php echo $this->url('pos/practice/add');?>");
        //客户搜索范围切换
		$(".ch_cu button").off().on("click",function(){
			var id = $(this).attr("data");
			var box = $(this).closest(".form-horizontal");
			box.find(".md_search").hide();
			box.find(".all_search").hide();
			box.find("."+id).show();
			box.find(".ch_cu button").removeClass("on").removeClass("blue");
			$(this).addClass("on").addClass("blue");
		})
    });

	//选择客户后跳转到业务
	function to_order(self,url){
		var d = Idialog({
			width:500,
			title:'客户选择',
			content:$('#choose_cu'),
			cancel:false,
			close:function(e){
				
			},
			ok:function(obj){
				var _self=obj._self;
				if(_self.find(".on").attr("data")=="all_search")
					var id=_self.find("#all_s").val();
				else
					var id=_self.find("#md_s").val();
				if(id)
					window.location.href=url+"&id="+id;
			}
		});
	}

	//入会购买
    $(".pos_rh_bj").click(function(){
    	var self=$(this);
		var d = Idialog({
			top:150,
			width:500,
			title:'客户选择',
			content:$('#choose_cu_rh'),
			cancel:false,
			close:function(e){
			},
			ok:function(obj){
				var _self=obj._self;
				var id=_self.find("#search_cu_id").val();
				var type=_self.find("input[name=rh_type]:checked").val();
				if(id)
					window.location.href="<?php echo $this->url('pos/sale/rh');?>"+"&id="+id+"&type="+type;
			}
		});
    });

    //会员等级升级
    $(".pos_dj_bj").click(function(){
    	var self=$(this);
		var d = Idialog({
			top:150,
			width:500,
			title:'客户选择',
			content:$('#choose_cu_dj'),
			cancel:false,
			close:function(e){
			},
			ok:function(obj){
				var _self=obj._self;
				var id=_self.find("#search_cu_id").val();
				var level=_self.find(".level").val();
				if(id)
					window.location.href="<?php echo $this->url('pos/index/level');?>"+"&id="+id+"&level="+level;
			}
		});
    });

    //当前客户等级
    $(document).on("change", "#search_cu_id",function(){
		var cu_id=$(this).val();
		$.getJSON("<?php echo $this->url('culevel');?>"+"&cu_id="+cu_id, function(json){
			if(json.code==200){
				//转到付款界面
				$(".cu_level").html(json.data.name);
			}else{
				Idialog.tips(json.msg,2);
			}
		});
	});

	$(document).on("click", "input[name=rh_type]",function(){
		$("input[name=rh_type]").removeAttr("checked");
		$(".radio-list span").removeClass('checked')
		$(this).attr("checked","checked");
		$(this).parent().addClass('checked');
	});

});
</script>