<style type="text/css">
.xzzh,.tk{color:#0077ff;cursor: pointer;}
.pos_kj_top_top,.pos_kj_top_two{margin:0;}
.kj_title{margin-top: 15px;margin-bottom: 5px;}
.qk_name{color: #1bab70;cursor:pointer;}
</style>

<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>POS开单><span>退项目/产品/卡券</span>
	</div>
  
	<!--khgl_shouye-->
	<?php echo $cu_info ?>
	<!--khgl_shouye!end-->
<?php if ($capital_list): ?>
	<!--退款-->
	<div class="pos_cz_tow">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>退款</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
				 <!--table_con-->
				 <div class="table_con">
					<!--table_con_son-->
					<div class="table_con_son">
					 <div class="table_title">
						<ul>
						<li>账户类型</li>
						<?php foreach ($capital_list as $value): ?>
							<li><?php echo $value['name'] ?>（元）</li>
						<?php endforeach ?>
						</ul>
					</div>

					<div class="table_list clear">
						<ul>
						<li class="">账户余额（元）</li>
						<?php foreach ($capital_list as $value): ?>
							<li><?php echo $value['balance'] ?></li>
						<?php endforeach ?>
						</ul>
					</div>
					
					<div class="table_list clear">
						<ul>
						<li class="">退款现金（元）</li>
						<?php foreach ($capital_list as $value): ?>
							<li><input data-max-value="<?php echo $value['balance'] ?>" data-id="<?php echo $value['capital_id'] ?>" type="text" class="pos_cz_tow_two05 capital_tk" /></li>
						<?php endforeach ?>
						</ul>
					</div>
					 
				 </div><!--table_con_son!end-->
				 </div><!--table_con!end-->
			 </div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
						<span class="pos_cz_tow_two04 ">退款现金小计:<span class="pos_cz_zh_02 c_tk_min_all">0</span>元</span>
						<!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
						<span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
			</div>
		</div>
	</div><!--退款!end-->
<?php endif ?>

<?php if ($project_list): ?>
	<!--可退项目-->
	<div class="pos_cz_tow box_xm">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>可退项目</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
			<!--table_con-->
			<div class="table_con">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
						<ul>
							<li >关联订单</li>
							<li style="min-width:100px;">项目名称</li>
							<li style="min-width:40px;">来源</li>
							<li style="min-width:50px;">购买次数</li>
							<li style="min-width:50px;">剩余次数</li>
							<li style="min-width:50px;">成交价格（元）</li>
							<li style="min-width:50px;">实收现金（元）</li>
							<li>现金账户抵扣</li>
							<li>赠送账户抵扣</li>
							<li style="min-width:50px;">欠款</li>
							<li>需退次数</li>
							<li>退入账户（元）</li>
						</ul>
					</div>
					<?php foreach ($project_list as $pro):?>
						<?php
							$money_str=\pos\SaleModel::model()->proMoneyStr($pro['detail_id']);
							if($pro['buy_type']==3){
								$sn = \OrderVoucher::model()->findByPk($pro['order_id'])->sn;
							}else{
								$sn = \OrderSaleDetail::getSn($pro['detail_id']);
							}
						?>

						<div data-id="<?php echo $pro['id'] ?>" data-zh="<?php echo $money_str ?>" data-tk="<?php echo $pro['tk_money_str'] ?>" class="table_list clear">
							<ul>
								<li class=""><?php echo $sn; ?></li>
								<li class=""><?php echo $pro['name'] ?></li>
								<li><?php echo  $pro['buy_type']?\OrderSaleDetail::getBuyType($pro['buy_type']):'不明' ?></li>
								<li><?php echo $pro['num'] ?></li>
								<li><?php echo $pro['re_num'] ?></li>
								<li><?php echo $pro['price']*$pro['rebate']/100 ?></li>
								<li><?php echo $pro['buy_type']!=2?$pro['price']*$pro['rebate']/100-$pro['card_cash']-$pro['card_gift']-$pro['arrears']:0 ?></li>
								<li class="xj xzzh"><?php echo $pro['card_cash'] ?></li>
								<li class="zs xzzh"><?php echo $pro['card_gift'] ?></li>
								<li><?php echo $pro['arrears'] ?></li>
								<li class=""><input  data-max-value="<?php echo $pro['re_num'] ?>" data-price="<?php echo $pro['num']?$pro['price']*$pro['rebate']/100/$pro['num']:0 ?>" data-xj="<?php echo $pro['num']?($pro['pay_price']/$pro['num']):0; ?>" data-max-xj="<?php echo $pro['var_price'] ?>"  data-zs="<?php echo $pro['num']?($pro['card_gift'])/$pro['num']:0; ?>" type="text" value="" class="pos_cz_tow_two05"></li>
								<li class="tk">选择账户</li>
							</ul>
						</div>
					<?php endforeach ?>

				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
				<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
				<!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
				<span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
			</div>
		</div>
	</div><!--可退项目!end-->
<?php endif ?>

<?php if ($product_list): ?>
	<!--可退产品-->
	<div class="pos_cz_tow box_cp">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>可退产品</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
			<!--table_con-->
			<div class="table_con">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
						<ul>
							<li >关联订单</li>
							<li style="min-width:100px;">产品名称</li>
							<li style="min-width:40px;">来源</li>
							<li style="min-width:50px;">购买数量</li>
							<li style="min-width:50px;">剩余数量</li>
							<li style="min-width:50px;">成交价格（元）</li>
							<li style="min-width:50px;">实收现金（元）</li>
							<li>现金账户抵扣</li>
							<li>赠送账户抵扣</li>
							<li style="min-width:50px;">欠款</li>
							<li>需退数量</li>
							<li>退入账户（元）</li>
						</ul>
					</div>
					<?php foreach ($product_list as $pro): ?>
						<?php $money_str=\pos\SaleModel::model()->proMoneyStr($pro['detail_id']); ?>

						<div data-id="<?php echo $pro['id'] ?>" data-zh="<?php echo $money_str ?>" data-tk="<?php echo $pro['tk_money_str'] ?>" class="table_list clear">
							<ul>
								<li class=""><?php echo \OrderSaleDetail::getSn($pro['detail_id']) ?></li>
								<li class=""><?php echo $pro['name'] ?></li>
								<li><?php echo  $pro['buy_type']?\OrderSaleDetail::getBuyType($pro['buy_type']):'不明' ?></li>
								<li><?php echo $pro['num'] ?></li>
								<li><?php echo $pro['remain_num'] ?></li>
								<li><?php echo $pro['price']*$pro['rebate']/100 ?></li>
								<li><?php echo $pro['buy_type']!=2?$pro['price']*$pro['rebate']/100-$pro['card_cash']-$pro['card_gift']-$pro['arrears']:0 ?></li>
								<li class="xj xzzh"><?php echo $pro['card_cash'] ?></li>
								<li class="zs xzzh"><?php echo $pro['card_gift'] ?></li>
								<li><?php echo $pro['arrears'] ?></li>
								<li class=""><input  data-max-value="<?php echo $pro['remain_num'] ?>" data-price="<?php echo $pro['num']?$pro['price']*$pro['rebate']/100/$pro['num']:0 ?>"  data-xj="<?php echo $pro['num']?($pro['pay_price']/$pro['num']):0; ?>" data-max-xj="<?php echo $pro['var_price'] ?>" data-zs="<?php echo $pro['num']?($pro['card_gift'])/$pro['num']:0; ?>"  type="text" value="" class="pos_cz_tow_two05"></li>
								<li class="tk">选择账户</li>
							</ul>
						</div>
					<?php endforeach ?>

				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
				<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
				<!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
				<span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
			</div>
		</div>
	</div><!--可退产品!end-->
<?php endif ?>  
  
<?php if ($voucher_list): ?>
	<!--可退卡券-->
	<div class="pos_cz_tow box_kq">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>可退卡券</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
			<!--table_con-->
			<div class="table_con">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
						<ul>
							<li >关联订单</li>
							<li style="min-width:100px;">卡券名称</li>
							<li style="min-width:40px;">来源</li>
							<li style="min-width:50px;">购买次数</li>
							<li style="min-width:50px;">剩余次数</li>
							<li style="min-width:50px;">成交价格（元）</li>
							<li style="min-width:50px;">实收现金（元）</li>
							<li>现金账户抵扣</li>
							<li>赠送账户抵扣</li>
							<li style="min-width:50px;">欠款</li>
							<li>需退次数</li>
							<li>退入账户（元）</li>
						</ul>
					</div>
					<?php foreach ($voucher_list as $pro): ?>
						<?php $money_str=\pos\SaleModel::model()->proMoneyStr($pro['detail_id']); ?>

						<div data-id="<?php echo $pro['id'] ?>" data-zh="<?php echo $money_str ?>" data-tk="<?php echo $pro['tk_money_str'] ?>" class="table_list clear">
							<ul>
								<li class=""><?php echo \OrderSaleDetail::getSn($pro['detail_id']); ?></li>
								<li class="qk_name"><?php echo $pro['name'] ?></li>
								<li><?php echo  $pro['buy_type']?\OrderSaleDetail::getBuyType($pro['buy_type']):'不明' ?></li>
								<li><?php echo $pro['num'] ?></li>
								<li>1</li>
								<li><?php echo $pro['price']*$pro['rebate']/100 ?></li>
								<li><?php echo $pro['buy_type']!=2?$pro['price']*$pro['rebate']/100-$pro['card_cash']-$pro['card_gift']-$pro['arrears']:0 ?></li>
								<li class="xj xzzh"><?php echo $pro['card_cash'] ?></li>
								<li class="zs xzzh"><?php echo $pro['card_gift'] ?></li>
								<li><?php echo $pro['arrears'] ?></li>
								<li class=""><input  <?php echo $pro['arrears']>0?'disabled="disabled"':''?> data-max-value="<?php echo $pro['num'] ?>" data-price="<?php echo $pro['num']?$pro['price']*$pro['rebate']/100/$pro['num']:0 ?>"  data-xj="<?php echo $pro['num']?($pro['pay_price']/$pro['num']):0; ?>" data-max-xj="<?php echo $pro['var_price'] ?>" data-zs="<?php echo $pro['num']?($pro['card_gift'])/$pro['num']:0; ?>"   type="text" value="" class="pos_cz_tow_two05"></li>
								<li class="tk">选择账户</li>
							</ul>
						</div>
					<?php endforeach ?>

				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
				<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
				<!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
				<span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
			</div>
		</div>
	</div><!--可退产品!end-->

	<!--卡券剩余弹出框-->
	<div class="pos_kj_top qk_detail" style="display:none;">
		<div class="pos_kj_top_top">
			<ul>
				<li style="border-bottom:none;">可兑金额：<font class="re_money">0</font></li>
			</ul>
		</div>
	
		<div class="pos_kj_top_two">
			<div class="kj_title">可兑项目：</div>
			<div class="">
				<!--table_container-->  
				<div class="table_container">
					<!--table_con-->
					<div class="table_con">
						<!--table_con_son-->
						<div class="table_con_son re_proj">
							<div class="table_title">
								<ul>
									<li style="min-width:200px">项目名称</li>
									<li style="border-right: medium none;">剩余次数</li>
								</ul>
							</div>

						</div><!--table_con_son!end-->
					</div><!--table_con!end-->
				</div><!--table_containter!end-->
			</div>
		</div>
	
		<div class="pos_kj_top_two">
			<div class="kj_title">可兑产品：</div>
			<div class="">
				<!--table_container-->  
				<div class="table_container">
					<!--table_con-->
					<div class="table_con">
						<!--table_con_son-->
						<div class="table_con_son re_prod">
							<div class="table_title">
								<ul>
									<li style="min-width:200px">产品名称</li>
									<li style="border-right: medium none;">剩余次数</li>
								</ul>
							</div>

						</div><!--table_con_son!end-->
					</div><!--table_con!end-->
				</div><!--table_containter!end-->
			</div>
		</div>
	</div><!--卡券剩余弹出框!end-->

<?php endif ?>	
  

	<!--备注-->
	<div class="pos_cz_tow pos_cz_for_bz">
		<div class="pos_cz_for_bz01">备注</div>
		<div class="pos_cz_for_bz02">
			<div class="pos_cz_for_bz02_son"><textarea class="order_note" rows="4"></textarea></div>
		</div>
	</div><!--备注!end-->
  
	
	<div class="pos_cz_tow pos_cz_zh">
		<a href="javascript:" class="pos_cz_zh_an c_submit">提交订单
		<!-- <img src="<?php echo $this->basePath('public');?>/images/pos_cz_10.png" /> -->
		</a>
	<div class="pos_cz_zh_01">
		<div class="pos_momey">退款现金合计：<span class="pos_cz_zh_02">￥<font class="tk_all">0.00</font></span></div>
	</div>
	</div>
	
</div>
<!--content_right_con!end-->
{__TOKEN__}

<!-- 选择账户分配弹出 -->
<div style="display:none">
	<div class="tjfj_two pos_gm_th zszhdk">

		<!--table_container-->  
		<div style="margin-bottom:0px;" class="table_container">
			<!--table_con-->
			<div style="margin-right:0px;" class="table_con pos_cz_qr_top_04">

				<!--table_con_son-->
				<div class="table_con_son" style="min-width: 564px;">
					<!-- <div class="pos_cz_tow_top pos_cz_qr_02">赠送现金</div>-->
					<div class="table_title">
						<ul>
						<li style="min-width:200px">账户类型</li>
						<li>余额（元）</li>
						<li style="min-width: 80px; border-right: medium none;">退还金额（元）</li>
						</ul>
					</div>

				</div><!--table_con_son!end-->

			</div><!--table_con!end-->
		</div>
		<!--table_containter!end-->
	</div>

</div>
<!-- 选择账户分配弹出 end-->

<script type="text/javascript">
$(function(){

	//卡券剩余显示
	$(".qk_name").click(function(){
		//客户持有的卡券id
		var re_id = $(this).closest('.table_list').attr("data-id");
		var url="<?php echo $this->url('voucherRe') ?>&id="+re_id;	
		$.post(url,function(data){
			if(data.code==200){
				var dd = Idialog({
					top:150,
					width:600,
					title:'卡券剩余',
					content:$('.qk_detail'),
					cancel:false,
					init:function(content){
						var re=data.data;
						content.find(".re_money").html(re.money);
						if(re.xm){
							$.each( re.xm, function(i, pro){
								var s_list ='<div class="table_list clear"><ul>';
									s_list+='<li class="">'+pro.name+'</li>';
									s_list+='<li class="">'+pro.re_num+'</li>';
									s_list+='</ul></div>';
									content.find('.re_proj').append(s_list);
							});
						}
						if(re.cp){
							$.each( re.cp, function(i, pro){
								var s_list ='<div class="table_list clear"><ul>';
									s_list+='<li class="">'+pro.name+'</li>';
									s_list+='<li class="">'+pro.re_num+'</li>';
									s_list+='</ul></div>';
									content.find('.re_prod').append(s_list);
							});
						}
						table_flash(content.find(".table_container"));
					}
				});
			}else{
				Idialog.tips(data.msg,2);
			}
		}, "json");
	});


	//收起效果
	$(".pos_cz_tow_top_r").click(function(){
		var self=$(this);
		self.parent().next().slideToggle("fast",function(){
			if(self.hasClass("pos_cz_tow_top_rcl")){
				self.removeClass("pos_cz_tow_top_rcl");
			}else{
				self.addClass("pos_cz_tow_top_rcl");
			}
		});
	});

	//现金金额组成
	$('.table_container').on('click','.xzzh',function(){
		var table_list = $(this).closest('.table_list');
		var capital_money=table_list.attr("data-zh");
		var capital_list=capital_xj;
		if($(this).hasClass("zs")) capital_list=capital_zs;
		//console.log(capital_xj)
		var d = Idialog({
			top:150,
			width:500,
			title:'金额组成',
			content:$('.zszhdk'),
			cancel:false,
			init:function(content){
				$.each( capital_list, function(i, capital){
					var money = str_money(capital_money,capital.id);
					var s_list ='<div class="table_list clear"><ul>';
						s_list+='<li class="">'+capital.name+'</li>';
						s_list+='<li class="">'+capital.balance+'</li>';
						s_list+='<li class="">'+money+'</li>';
						s_list+='</ul></div>';
						content.find('.table_con_son').append(s_list);
				});
				table_flash(content);
			}
		});
	});
	//退款组成
	$('.table_container').on('click','.tk',function(){
		var table_list = $(this).closest('.table_list');
		var capital_money=table_list.attr("data-tk");
		var capital_list=capital_xj.concat(capital_zs);
		var _this_obj=$(this);
		var _input_obj=_this_obj.prev().find('.pos_cz_tow_two05');
		// if(_input_obj.attr('disabled')=='disabled'){
		// 	Idialog.tips("有欠款,请先还款!",2);
		// 	return false;
		// }
		if (_input_obj.val()=='') {
			Idialog.tips("请先填写需退次数!",2);
			return false;
		}
		if (parseInt(_input_obj.val())<0 || parseInt(_input_obj.val())>parseInt(_input_obj.attr('data-max-value')) ) {
			Idialog.tips("需退次数填写错误!",2);
			return false;
		};
		var data_xj=parseFloat(_input_obj.attr('data-xj'));
		var data_max_xj=parseFloat(_input_obj.attr('data-max-xj'));
		var data_zs=parseFloat(_input_obj.attr('data-zs'));
		var d = Idialog({
			top:150,
			width:500,
			title:'金额组成',
			content:$('.zszhdk'),
			cancel:false,
			init:function(content){
				var first_xj=0;
				var first_zs=0;
				$.each( capital_list, function(i, capital){
					var money = str_money(capital_money,capital.id);
					if(capital_money){
						first_xj=first_zs=1;
					} 
				
					if (money==0 && capital.type==1 && first_xj==0) {
						money=data_xj*parseInt(_input_obj.val());
						if(money>data_max_xj)
						{
							money=data_max_xj;
						}
						first_xj=1;
					};

					if (money==0 && capital.type==2 && first_zs==0) {
						money=data_zs*parseInt(_input_obj.val());
						first_zs=1;
					};
					var s_list ='<div class="table_list clear"><ul>';
						s_list+='<li class="">'+capital.name+'</li>';
						s_list+='<li class="">'+capital.balance+'</li>';
						s_list+='<li class=""><input type="text" data-capital-type="'+capital.type+'" data-capital-id="'+capital.id+'" class="pos_cz_tow_two05 pos_gm_th_02" value="'+money+'"></li>';
						s_list+='</ul></div>';
						content.find('.table_con_son').append(s_list);
				});
				table_flash(content);
			},
			ok:function(obj){
				var content=obj._self;
				//赠送抵扣情况
				var tk_all=0;
				var tk_xj=0;
				var tk_zs=0;
				var tk = content.find("input").map(function(){
					tk_all+=parseFloat($(this).val());
					if($(this).attr('data-capital-type')==1)
					{
						tk_xj+=parseFloat($(this).val());
					}else
					{
						tk_zs+=parseFloat($(this).val());
					}
					return  $(this).attr('data-capital-id')+"|"+$(this).val();
				}).get().join(",");
				max_xj=(data_xj*parseInt(_input_obj.val())>data_max_xj)?data_max_xj:data_xj*parseInt(_input_obj.val());
				if(tk_xj<0 || tk_xj>max_xj)
				{
					Idialog.tips("现金账户退款超限!",2);
					return false;
				}
				if(tk_zs<0 || tk_zs>(data_zs*parseInt(_input_obj.val())))
				{
					Idialog.tips("赠送账户退款超限!",2);
					return false;
				}
				table_list.attr('data-tk',tk);
				table_list.find('.tk').html(tk_all);
				tk_min_all()
			}
		});
	});
	

	//订单直接赠送 退款
	$(".capital_tk").change(function(){
		tk_min_all();
	});

	//数据提交
	$(".c_submit").click(function(){
		var post_data=submit_data();
		if(post_data==false){
			return false;
		}
		$('.c_submit').html("正在提交订单...").addClass("pos_cz_zh_an_hover").removeClass("pos_cz_zh_an");
		var url="<?php echo $this->url('save') ?>";	
		$.post(url, post_data,function(data){
			Idialog.tips(data.msg,2);
			if(data.code==200){
				//转到付款界面
				setTimeout(function(){to_url('<?php echo $this->url("check");?>&id='+data.data)},3000);
			}
		}, "json");
	});


	//获取具体账户金额
	function str_money(money_str,capital_id){
		var res = 0;
		if(money_str){
			var arr=money_str.split(",");
			$.each( arr, function(i, n){
				var c_m=this.split("|");
				if(c_m[0]==capital_id) res = c_m[1];
			});
		}
		return res;
	}

	//退款小合计填充
	function tk_min_all(){
		$(".tk_min_all").each(function(i){
			var tk_min_all=0;
			$(this).closest('.pos_cz_tow').find(".tk").map(function(){
				tk_min_all+= $.isNumeric(parseInt($(this).html()))?parseInt($(this).html()):0;
			});
			$(this).html(tk_min_all);
		});

		$('.c_tk_min_all').html(eval($('.capital_tk').map(function(){
			return $.isNumeric($(this).val())?parseInt($(this).val()):0;
		}).get().join('+')));

		tk_all();
	}
	//总退款合计填充
	function tk_all(){
		var tk_all=0;
		$(".tk_min_all").map(function(){
			tk_all+= $.isNumeric(parseInt($(this).html()))?parseInt($(this).html()):0;
		});
		$(".capital_tk").map(function(){
			tk_all+= $.isNumeric(parseInt($(this).val()))?parseInt($(this).val()):0;
		});
		$(".tk_all").html(tk_all);
	}


	//提交保存数据构造
	function submit_data(){
		var is_not_null=false;//检查订单数据是否为空
		var data={};
		data.__hash__ = $("input[name='__hash__']").val();//表单令牌
		//账户退款
		data.capital=[];
		var is_next=true;
		$(".capital_tk").each(function(i){
			var money = $.isNumeric(parseInt($(this).val()))?parseInt($(this).val()):0;
			var capital_id = $(this).attr("data-id");
			if(money==0)
				return true;
			if (parseFloat($(this).val())<0 || parseFloat($(this).val())>parseFloat($(this).attr('data-max-value')) ) {
				is_next=false;
				Idialog.tips("退款金额填写错误!",2);
				return false;
			};
			is_not_null=true;
			data.capital.push({
				"capital_id":capital_id, 
				"money":money,
			});
		});
		if(is_next==false)
			return false;
		//购买项目、产品、卡券相关
		data.pro=[];
		$('.box_xm,.box_cp,.box_kq').find(".table_list").each(function(i){
			var num = $.isNumeric(parseInt($(this).find("input").val()))?parseInt($(this).find("input").val()):0;
			var money = $.isNumeric(parseInt($(this).find(".tk").html()))?parseInt($(this).find(".tk").html()):0;
			if(num==0)
				return true;
			var pro_type=3;
			if($(this).closest('.box_xm').length>0)
				var pro_type=1;
			if($(this).closest('.box_cp').length>0)
				var pro_type=2;
			is_not_null=true;
			data.pro.push({
				"re_pro_id":$(this).attr("data-id"), //卡内剩余对应的id
				"num":num,
				"money":money,
				"tk_detail":$(this).attr("data-tk"),//退款详细
				"pro_type":pro_type,//商品类型
			});
		});
		if (is_not_null==false) {
			Idialog.tips("订单内容不能为空",2);
			return false;
		};
		data.cu_id=$('.cu_info').attr("data-id");

		data.note=$('.order_note').val();

		return data;
	}

});
</script>