
<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<style type="text/css">
.tk{color:#0077ff;cursor: pointer;}
.qk_name{color: #1bab70;cursor:pointer;}
</style>

<?php 
$xm_arr=$cp_arr=$kq_arr=array();
foreach ($model->pros as $pro) {
	switch ($pro['pro_type']) {
		case '1':
			$xm_arr[]=$pro;
			break;
		case '2':
			$cp_arr[]=$pro;
			break;
		case '3':
			$kq_arr[]=$pro;
			break;
	}
}
?>
<div class="row">
	<div class="print_show col-md-12">
		<div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/退订单-查看
                </div>
                <div class="tools">
	                	<button onclick="history.go(-1)" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>返回</button>
                </div>
            </div>
        </div>
        <div class="row">
			<div class="col-md-6 col-sm-12">
	            <div class="portlet solid green-haze">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>订单概况
	                    </div>
	                    <div class="actions">
		                    <button class="btn red">退款合计 <font class="tk_all">0</font>元</button>
	                    </div>
	                </div>
	                <div class="portlet-body">
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">实操单号：</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->sn ?>
	                        </div>
	                    </div>
	                    <div class="row static-info">
	                        <div class="col-xs-5 name">耗卡时间</div>
	                        <div class="col-xs-7 value text-right">
	                             <?php echo $model->o_s->pay_time?date('Y-m-d H:i:s',$model->o_s->pay_time):'未耗卡';?>
	                        </div>
	                    </div>

	                    <div class="row static-info">
	                        <div class="col-xs-5 name">订单状态：</div>
	                        <div class="col-xs-7 value text-right">
		                        <?php if (!$model): ?>
	                        	<span class="label label-info label-sm">草稿</span>
								<?php else: ?>
	                        	<span class="label label-warning label-sm"><?php echo \OrderRefund::getStatus($model->o_s->status);?></span>
								<?php endif ?>
	                        </div>
	                    </div>

	                    <div class="row static-info">
                            <div class="col-xs-5 name">制单时间：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->o_s->create_time ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">操作人：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->employName ?>
                            </div>
                        </div>


	                </div>
	            </div>
	        </div>

	        <div class="col-md-6 col-sm-12">
	            <div class="portlet solid red-intense">
	                <div class="portlet-body" style="padding-top: 10px;">
	                    <?php echo $cu_info ?>
	                </div>
	            </div>
	        </div>


        </div>


<?php if ($model->capital): ?>
<?php 
$capital=array();
foreach ($model->capital as $value) {
	$capital[$value['capital_id']]=$value['money'];
}
?>
        <div class="row"> 
	        <div class="col-md-12">
		        <div class="portlet box blue-steel">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>账户退款
	                    </div>
	                </div>
	                <div class="portlet-body">
	                	<div class="table-responsive"> 
							<table class="table" >
								
								<tbody>
									<tr class="table_title">
										<td>账户类型</td>
										<?php foreach ($capital_list as $value): ?>
											<td><?php echo $value['name'] ?>（元）</td>
										<?php endforeach ?>
									</tr>

									<tr class="table_list">
										<td class="">账户余额（元）</td>
										<?php foreach ($capital_list as $value): ?>
											<td><?php echo $value['balance'] ?></td>
										<?php endforeach ?>
									</tr>
									
									<tr class="table_list">
										<td class="">退款现金（元）</td>
										<?php foreach ($capital_list as $value): ?>
											<td><input readonly="true" data-id="<?php echo $value['id'] ?>" type="text" value="<?php echo $capital[$value['capital_id']] ?>" class="pos_cz_tow_two05 capital_tk" /></td>
										<?php endforeach ?>
									</tr>
								</tbody>
							</table>
							<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
								<span class="pos_cz_tow_two04 ">退款现金小计:<span class="pos_cz_zh_02 c_tk_min_all">0</span>元</span>
							</div>
						</div>
	                </div>
	            </div>
	        </div>
        </div>
<?php endif ?>
        

<?php if ($xm_arr): ?>
        <div class="row"> 
	        <div class="col-md-12">
		        <div class="portlet box blue-steel">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>退项目
	                    </div>
	                </div>
	                <div class="portlet-body">
	                	<div class="table-responsive"> 
							<table class="table table-bordered table-hover " >
								<thead>
									<tr>
										<th>项目名称</th>
										<th>来源</th>
										<th>购买次数</th>
										<th>剩余次数</th>
										<th>成交价格（元）</th>
										<th>退款次数</th>
										<th>退入账户（元）</th>
									</tr>
								</thead>
								
								<tbody>
								<?php foreach ($xm_arr as $pro): ?>
									<?php $pro_info=\pos\RefundModel::model()->getProInfo($pro['re_pro_id'],$pro['pro_type']); ?>
									<?php //var_dump($pro_info);die; ?>

									<tr data-id="<?php echo $pro_info['id'] ?>" data-tk="<?php echo $pro['money_str'] ?>" class="table_list">
											<td><?php echo $pro_info['name'] ?></td>
											<td><?php echo $pro_info['buy_type']?\OrderSaleDetail::getBuyType($pro_info['buy_type']):'不明' ?></td>
											<td><?php echo $pro_info['gm_num'] ?></td>
											<td><?php echo $pro_info['sy_num'] ?></td>
											<td><?php echo $pro_info['cj_price'] ?></td>
											<td><?php echo $pro['num']?></td>
											<td class="tk"><?php echo $pro['money']?></td>
									</tr>
								<?php endforeach ?>
								</tbody>
							</table>
							<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
								<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
							</div>
						</div>
	                </div>
	            </div>
	        </div>
        </div>
<?php endif ?>

<?php if ($cp_arr): ?> 
        <div class="row"> 
	        <div class="col-md-12">
		        <div class="portlet box blue-steel">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>退产品
	                    </div>
	                </div>
	                <div class="portlet-body">
	                	<div class="table-responsive"> 
							<table class="table table-bordered table-hover " >
								<thead>
									<tr>
										<th>产品名称</th>
										<th>来源</th>
										<th>购买次数</th>
										<th>剩余次数</th>
										<th>成交价格（元）</th>
										<th>退款次数</th>
										<th>退入账户（元）</th>
									</tr>
								</thead>
								
								<tbody>
								<?php foreach ($cp_arr as $pro): ?>
									<?php $pro_info=\pos\RefundModel::model()->getProInfo($pro['re_pro_id'],$pro['pro_type']); ?>

									<tr data-id="<?php echo $pro_info['id'] ?>" data-tk="<?php echo $pro['money_str'] ?>" class="table_list">
											<td><?php echo $pro_info['name'] ?></td>
											<td><?php echo $pro_info['buy_type']?\OrderSaleDetail::getBuyType($pro_info['buy_type']):'不明' ?></td>
											<td><?php echo $pro_info['gm_num'] ?></td>
											<td><?php echo $pro_info['sy_num'] ?></td>
											<td><?php echo $pro_info['cj_price'] ?></td>
											<td><?php echo $pro['num']?></td>
											<td class="tk"><?php echo $pro['money']?></td>
									</tr>
								<?php endforeach ?>
								</tbody>
							</table>
							<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
								<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
							</div>
						</div>
	                </div>
	            </div>
	        </div>
        </div>
<?php endif ?>

<?php if ($kq_arr): ?> 
        <div class="row"> 
	        <div class="col-md-12">
		        <div class="portlet box blue-steel">
	                <div class="portlet-title">
	                    <div class="caption">
	                        <i class="fa fa-cogs"></i>退卡券
	                    </div>
	                </div>
	                <div class="portlet-body">
	                	<div class="table-responsive"> 
							<table class="table table-bordered table-hover " >
								<thead>
									<tr>
										<th>卡券名称</th>
										<th>来源</th>
										<th>购买次数</th>
										<th>剩余次数</th>
										<th>成交价格（元）</th>
										<th>退款次数</th>
										<th>退入账户（元）</th>
									</tr>
								</thead>
								
								<tbody>
								<?php foreach ($kq_arr as $pro): ?>
									<?php $pro_info=\pos\RefundModel::model()->getProInfo($pro['re_pro_id'],$pro['pro_type']); ?>

									<tr data-id="<?php echo $pro_info['id'] ?>" data-tk="<?php echo $pro['money_str'] ?>" class="table_list">
											<td class="qk_name"><?php echo $pro_info['name'] ?></td>
											<td><?php echo $pro_info['buy_type']?\OrderSaleDetail::getBuyType($pro_info['buy_type']):'不明' ?></td>
											<td><?php echo $pro_info['gm_num'] ?></td>
											<td><?php echo $pro_info['sy_num'] ?></td>
											<td><?php echo $pro_info['cj_price'] ?></td>
											<td><?php echo $pro['num']?></td>
											<td class="tk"><?php echo $pro['money']?></td>
									</tr>
								<?php endforeach ?>
								</tbody>
							</table>
							<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
								<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
							</div>
						</div>
	                </div>
	            </div>
	        </div>
        </div>
<?php endif ?>

		<!--备注-->
		<div class="pos_cz_tow pos_cz_for_bz">
			<div class="pos_cz_for_bz01">备注</div>
			<div class="pos_cz_for_bz02">
				<div class="pos_cz_for_bz02_son">
				<?php echo $model?$model->o_s->note:"" ?>
				</div>
			</div>
		</div>
		<!--备注!end-->
    </div>
</div>


<!--卡券剩余弹出框-->
<div class="pos_kj_top qk_detail" style="display:none;">
	<div class="pos_kj_top_top">
		<ul>
			<li style="border-bottom:none;">可兑金额：<font class="re_money">0</font></li>
		</ul>
	</div>

	<div class="pos_kj_top_two">
		<div class="kj_title">可兑项目：</div>
		<div class="">
			<!--table_container-->  
			<div class="table_container">
				<!--table_con-->
				<div class="table_con">
					<!--table_con_son-->
					<div class="table_con_son re_proj">
						<div class="table_title">
							<ul>
								<li style="min-width:200px">项目名称</li>
								<li style="border-right: medium none;">剩余次数</li>
							</ul>
						</div>

					</div><!--table_con_son!end-->
				</div><!--table_con!end-->
			</div><!--table_containter!end-->
		</div>
	</div>

	<div class="pos_kj_top_two">
		<div class="kj_title">可兑产品：</div>
		<div class="">
			<!--table_container-->  
			<div class="table_container">
				<!--table_con-->
				<div class="table_con">
					<!--table_con_son-->
					<div class="table_con_son re_prod">
						<div class="table_title">
							<ul>
								<li style="min-width:200px">产品名称</li>
								<li style="border-right: medium none;">剩余次数</li>
							</ul>
						</div>

					</div><!--table_con_son!end-->
				</div><!--table_con!end-->
			</div><!--table_containter!end-->
		</div>
	</div>
</div><!--卡券剩余弹出框!end-->


<!-- 选择账户分配弹出 -->
<div style="display:none">
	<div class="zszhdk">
		<div class="pos_gm_th_01">购买《肽美白》1疗次，原价：1000 元</div>
		<!--table_container-->  
		<div class="table_container">
			<!--table_con-->
			<div class="table_con pos_cz_qr_top_04">

				<!--table_con_son-->
				<div class="table_con_son" >
					<table class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>账户类型</th>
								<th>余额(元)</th>
								<th>抵扣金额(元)</th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div><!--table_con_son!end-->

			</div><!--table_con!end-->
		</div>
		<!--table_containter!end-->
	</div>
</div>
<!-- 选择账户分配弹出 end-->


<script type="text/javascript">
$(function(){
	//退款小计
	tk_min_all();

	//卡券剩余显示
	$(".qk_name").click(function(){
		//客户持有的卡券id
		var re_id = $(this).closest('.table_list').attr("data-id");
		var url="<?php echo $this->url('voucherRe') ?>&id="+re_id;	
		$.post(url,function(data){
			if(data.code==200){
				var dd = Idialog({
					top:150,
					width:600,
					title:'卡券剩余',
					content:$('.qk_detail'),
					cancel:false,
					init:function(content){
						var re=data.data;
						content.find(".re_money").html(re.money);
						if(re.xm){
							$.each( re.xm, function(i, pro){
								var s_list ='<div class="table_list"><ul>';
									s_list+='<li class="">'+pro.name+'</li>';
									s_list+='<li class="">'+pro.re_num+'</li>';
									s_list+='</ul></div>';
									content.find('.re_proj').append(s_list);
							});
						}
						if(re.cp){
							$.each( re.cp, function(i, pro){
								var s_list ='<div class="table_list"><ul>';
									s_list+='<li class="">'+pro.name+'</li>';
									s_list+='<li class="">'+pro.re_num+'</li>';
									s_list+='</ul></div>';
									content.find('.re_prod').append(s_list);
							});
						}
					}
				});
			}else{
				Idialog.tips(data.msg,2);
			}
		}, "json");
	});



	//退款组成
	$('.table').on('click','.tk',function(){
		var table_list = $(this).closest('.table_list');
		var capital_money=table_list.attr("data-tk");
		var capital_list=capital_xj.concat(capital_zs);
		var d = Idialog({
			top:150,
			width:500,
			title:'金额组成',
			content:$('.zszhdk'),
			cancel:false,
			init:function(content){
				$.each( capital_list, function(i, capital){
					var money = str_money(capital_money,capital.id);
					var s_list ='<tr class="table_list">';
						s_list+='<td>'+capital.name+'</td>';
						s_list+='<td>'+capital.balance+'</td>';
						s_list+='<td>'+money+'</td>';
						s_list+='</tr>';
						content.find('tbody').append(s_list);
				});
			}
		});
	});
	
	//订单直接赠送 退款
	$(".order_tk").change(function(){
		tk_all();
	});




	//获取具体账户金额
	function str_money(money_str,capital_id){
		var res = 0;
		if(money_str){
			var arr=money_str.split(",");
			$.each( arr, function(i, n){
				var c_m=this.split("|");
				if(c_m[0]==capital_id) res = c_m[1];
			});
		}
		return res;
	}

	//退款小合计填充
	function tk_min_all(){
		$(".tk_min_all").each(function(i){
			var tk_min_all=0;
			$(this).closest('.pos_cz_tow').find(".tk").map(function(){
				tk_min_all+= $.isNumeric(parseInt($(this).html()))?parseInt($(this).html()):0;
			});
			$(this).html(tk_min_all);
		});

		$('.c_tk_min_all').html(eval($('.capital_tk').map(function(){
			return $.isNumeric($(this).val())?parseInt($(this).val()):0;
		}).get().join('+')));

		tk_all();
	}
	//总退款合计填充
	function tk_all(){
		var tk_all=0;
		$(".tk_min_all").map(function(){
			tk_all+= $.isNumeric(parseInt($(this).html()))?parseInt($(this).html()):0;
		});
		$(".capital_tk").map(function(){
			tk_all+= $.isNumeric(parseInt($(this).val()))?parseInt($(this).val()):0;
		});
		$(".tk_all").html(tk_all);
	}

});
</script>