<style type="text/css">
.xzzh,.tk{color:#0077ff;cursor: pointer;}
.pos_kj_top_top,.pos_kj_top_two{margin:0;}
.kj_title{margin-top: 15px;margin-bottom: 5px;}
.qk_name{color: #1bab70;cursor:pointer;}
</style>

<?php 
$xm_arr=$cp_arr=$kq_arr=array();
foreach ($model->pros as $pro) {
	switch ($pro['pro_type']) {
		case '1':
			$xm_arr[]=$pro;
			break;
		case '2':
			$cp_arr[]=$pro;
			break;
		case '3':
			$kq_arr[]=$pro;
			break;
	}
}
?>

<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>POS开单><span>退订单</span>
	</div>
  
	<!--khgl_shouye-->
	<?php echo $cu_info ?>
	<!--khgl_shouye!end-->


<?php if ($model->capital): ?>
<?php 
$capital=array();
foreach ($model->capital as $value) {
	$capital[$value['capital_id']]=$value['money'];
}
?>
	<!--退款-->
	<div class="pos_cz_tow">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>退款</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
				 <!--table_con-->
				 <div class="table_con">
					<!--table_con_son-->
					<div class="table_con_son">
					 <div class="table_title">
						<ul>
						<li>账户类型</li>
						<?php foreach ($capital_list as $value): ?>
							<li><?php echo $value['name'] ?>（元）</li>
						<?php endforeach ?>
						</ul>
					</div>

					<div class="table_list">
						<ul>
						<li class="">账户余额（元）</li>
						<?php foreach ($capital_list as $value): ?>
							<li><?php echo $value['balance'] ?></li>
						<?php endforeach ?>
						</ul>
					</div>
					
					<div class="table_list">
						<ul>
						<li class="">退款现金（元）</li>
						<?php foreach ($capital_list as $value): ?>
							<li><input readonly="true" data-id="<?php echo $value['id'] ?>" type="text" value="<?php echo $capital[$value['capital_id']] ?>" class="pos_cz_tow_two05 capital_tk" /></li>
						<?php endforeach ?>
						</ul>
					</div>
					 
				 </div><!--table_con_son!end-->
				 </div><!--table_con!end-->
			 </div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
				<span class="pos_cz_tow_two04 ">退款现金小计:<span class="pos_cz_zh_02 c_tk_min_all">0</span>元</span>
			</div>
		</div>
	</div><!--退款!end-->
<?php endif ?>

<?php if ($xm_arr): ?>
	<!--可退项目-->
	<div class="pos_cz_tow box_xm">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>退项目</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
			<!--table_con-->
			<div class="table_con">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
						<ul>
							<li style="min-width:150px;">项目名称</li>
							<li >来源</li>
							<li >购买次数</li>
							<li >剩余次数</li>
							<li>成交价格（元）</li>
							<li >退款次数</li>
							<li>退入账户（元）</li>
						</ul>
					</div>
					<?php foreach ($xm_arr as $pro): ?>
						<?php $pro_info=\pos\RefundModel::model()->getProInfo($pro['re_pro_id'],$pro['pro_type']); ?>
						<?php //var_dump($pro_info);die; ?>

						<div data-id="<?php echo $pro_info['id'] ?>" data-tk="<?php echo $pro['money_str'] ?>" class="table_list">
							<ul>
								<li class=""><?php echo $pro_info['name'] ?></li>
								<li><?php echo $pro_info['buy_type']?\OrderSaleDetail::getBuyType($pro_info['buy_type']):'不明' ?></li>
								<li><?php echo $pro_info['gm_num'] ?></li>
								<li><?php echo $pro_info['sy_num'] ?></li>
								<li><?php echo $pro_info['cj_price'] ?></li>
								<li><?php echo $pro['num']?></li>
								<li class="tk"><?php echo $pro['money']?></li>
							</ul>
						</div>
					<?php endforeach ?>

				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
						<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
						<!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
						<span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
			</div>
		</div>
	</div><!--可退项目!end-->
<?php endif ?>  
  
<?php if ($cp_arr): ?> 
	<!--可退产品-->
	<div class="pos_cz_tow box_cp">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>可退产品</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;"> 
			<!--table_con-->
			<div class="table_con">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
						<ul>
							<li style="min-width:150px;">项目名称</li>
							<li >来源</li>
							<li >购买次数</li>
							<li >剩余次数</li>
							<li>成交价格（元）</li>
							<li >退款次数</li>
							<li>退入账户（元）</li>
						</ul>
					</div>
					<?php foreach ($cp_arr as $pro): ?>
						<?php $pro_info=\pos\RefundModel::model()->getProInfo($pro['re_pro_id'],$pro['pro_type']); ?>

						<div data-id="<?php echo $pro_info['id'] ?>" data-tk="<?php echo $pro['money_str'] ?>" class="table_list">
							<ul>
								<li class=""><?php echo $pro_info['name'] ?></li>
								<li><?php echo $pro_info['buy_type']?\OrderSaleDetail::getBuyType($pro_info['buy_type']):'不明' ?></li>
								<li><?php echo $pro_info['gm_num'] ?></li>
								<li><?php echo $pro_info['sy_num'] ?></li>
								<li><?php echo $pro_info['cj_price'] ?></li>
								<li><?php echo $pro['num']?></li>
								<li class="tk"><?php echo $pro['money']?></li>
							</ul>
						</div>
					<?php endforeach ?>

				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
				<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
				<!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
				<span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
			</div>
		</div>
	</div><!--可退产品!end-->
<?php endif ?>  
  
<?php if ($kq_arr): ?> 
	<!--可退卡券-->
	<div class="pos_cz_tow box_kq">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>可退卡券</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
			 
			<!--table_con-->
			<div class="table_con">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
						<ul>
							<li style="min-width:150px;">卡券名称</li>
							<li >来源</li>
							<li >购买次数</li>
							<li >剩余次数</li>
							<li>成交价格（元）</li>
							<li >退款次数</li>
							<li>退入账户（元）</li>
						</ul>
					</div>
					<?php foreach ($kq_arr as $pro): ?>
						<?php $pro_info=\pos\RefundModel::model()->getProInfo($pro['re_pro_id'],$pro['pro_type']); ?>

						<div data-id="<?php echo $pro_info['id'] ?>" data-tk="<?php echo $pro['money_str'] ?>" class="table_list">
							<ul>
								<li class="qk_name"><?php echo $pro_info['name'] ?></li>
								<li><?php echo $pro_info['buy_type']?\OrderSaleDetail::getBuyType($pro_info['buy_type']):'不明' ?></li>
								<li><?php echo $pro_info['gm_num'] ?></li>
								<li><?php echo $pro_info['sy_num'] ?></li>
								<li><?php echo $pro_info['cj_price'] ?></li>
								<li><?php echo $pro['num']?></li>
								<li class="tk"><?php echo $pro['money']?></li>
							</ul>
						</div>
					<?php endforeach ?>

				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two pos_cz_qr_top_02">
				<span class="pos_cz_tow_two04 ">退款小计:<span class="pos_cz_zh_02 tk_min_all">0</span>元</span>
				<!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
				<span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
			</div>
		</div>
	</div><!--可退卡券!end-->

	<!--卡券剩余弹出框-->
	<div class="pos_kj_top qk_detail" style="display:none;">
		<div class="pos_kj_top_top">
			<ul>
				<li style="border-bottom:none;">可兑金额：<font class="re_money">0</font></li>
			</ul>
		</div>
	
		<div class="pos_kj_top_two">
			<div class="kj_title">可兑项目：</div>
			<div class="">
				<!--table_container-->  
				<div class="table_container">
					<!--table_con-->
					<div class="table_con">
						<!--table_con_son-->
						<div class="table_con_son re_proj">
							<div class="table_title">
								<ul>
									<li style="min-width:200px">项目名称</li>
									<li style="border-right: medium none;">剩余次数</li>
								</ul>
							</div>

						</div><!--table_con_son!end-->
					</div><!--table_con!end-->
				</div><!--table_containter!end-->
			</div>
		</div>
	
		<div class="pos_kj_top_two">
			<div class="kj_title">可兑产品：</div>
			<div class="">
				<!--table_container-->  
				<div class="table_container">
					<!--table_con-->
					<div class="table_con">
						<!--table_con_son-->
						<div class="table_con_son re_prod">
							<div class="table_title">
								<ul>
									<li style="min-width:200px">产品名称</li>
									<li style="border-right: medium none;">剩余次数</li>
								</ul>
							</div>

						</div><!--table_con_son!end-->
					</div><!--table_con!end-->
				</div><!--table_containter!end-->
			</div>
		</div>
	</div><!--卡券剩余弹出框!end-->


<?php endif ?>

	<!--备注-->
	<div class="pos_cz_tow pos_cz_for_bz">
		<div class="pos_cz_for_bz01">备注</div>
		<div class="pos_cz_for_bz02">
			<div class="pos_cz_for_bz02_son"><?php echo $model->o_s->note ?></div>
		</div>
	</div><!--备注!end-->
  
	
	<div class="pos_cz_tow pos_cz_zh">
		<!-- <a href="javascript:" class="pos_cz_zh_an c_submit"><img src="<?php echo $this->basePath('public');?>/images/pos_cz_10.png" /></a> -->
	<div class="pos_cz_zh_01">
		<div class="pos_momey">退款现金合计：<span class="pos_cz_zh_02">￥<font class="tk_all">0.00</font></span></div>
	</div>
	</div>
	
</div>
<!--content_right_con!end-->
{__TOKEN__}

<!-- 选择账户分配弹出 -->
<div style="display:none">
	<div class="tjfj_two pos_gm_th zszhdk">

		<!--table_container-->  
		<div style="margin-bottom:0px;" class="table_container">
			<!--table_con-->
			<div style="margin-right:0px;" class="table_con pos_cz_qr_top_04">

				<!--table_con_son-->
				<div class="table_con_son" style="min-width: 564px;">
					<!-- <div class="pos_cz_tow_top pos_cz_qr_02">赠送现金</div>-->
					<div class="table_title">
						<ul>
						<li style="min-width:200px">账户类型</li>
						<li>余额（元）</li>
						<li style="min-width: 80px; border-right: medium none;">抵扣金额（元）</li>
						</ul>
					</div>

				</div><!--table_con_son!end-->

			</div><!--table_con!end-->
		</div>
		<!--table_containter!end-->
	</div>

</div>
<!-- 选择账户分配弹出 end-->

<script type="text/javascript">
$(function(){
	//退款小计
	tk_min_all();

	//卡券剩余显示
	$(".qk_name").click(function(){
		//客户持有的卡券id
		var re_id = $(this).closest('.table_list').attr("data-id");
		var url="<?php echo $this->url('voucherRe') ?>&id="+re_id;	
		$.post(url,function(data){
			if(data.code==200){
				var dd = Idialog({
					top:150,
					width:600,
					title:'卡券剩余',
					content:$('.qk_detail'),
					cancel:false,
					init:function(content){
						var re=data.data;
						content.find(".re_money").html(re.money);
						if(re.xm){
							$.each( re.xm, function(i, pro){
								var s_list ='<div class="table_list"><ul>';
									s_list+='<li class="">'+pro.name+'</li>';
									s_list+='<li class="">'+pro.re_num+'</li>';
									s_list+='</ul></div>';
									content.find('.re_proj').append(s_list);
							});
						}
						if(re.cp){
							$.each( re.cp, function(i, pro){
								var s_list ='<div class="table_list"><ul>';
									s_list+='<li class="">'+pro.name+'</li>';
									s_list+='<li class="">'+pro.re_num+'</li>';
									s_list+='</ul></div>';
									content.find('.re_prod').append(s_list);
							});
						}
						table_flash(content.find(".table_container"));
					}
				});
			}else{
				Idialog.tips(data.msg,2);
			}
		}, "json");
	});

	//收起效果
	$(".pos_cz_tow_top_r").click(function(){
		var self=$(this);
		self.parent().next().slideToggle("fast",function(){
			if(self.hasClass("pos_cz_tow_top_rcl")){
				self.removeClass("pos_cz_tow_top_rcl");
			}else{
				self.addClass("pos_cz_tow_top_rcl");
			}
		});
	});

	//退款组成
	$('.table_container').on('click','.tk',function(){
		var table_list = $(this).closest('.table_list');
		var capital_money=table_list.attr("data-tk");
		var capital_list=capital_xj.concat(capital_zs);
		var d = Idialog({
			top:150,
			width:500,
			title:'金额组成',
			content:$('.zszhdk'),
			cancel:false,
			init:function(content){
				$.each( capital_list, function(i, capital){
					var money = str_money(capital_money,capital.id);
					var s_list ='<div class="table_list"><ul>';
						s_list+='<li class="">'+capital.name+'</li>';
						s_list+='<li class="">'+capital.balance+'</li>';
						s_list+='<li>'+money+'</li>';
						s_list+='</ul></div>';
						content.find('.table_con_son').append(s_list);
				});
				table_flash(content);
			}
		});
	});
	
	//订单直接赠送 退款
	$(".order_tk").change(function(){
		tk_all();
	});




	//获取具体账户金额
	function str_money(money_str,capital_id){
		var res = 0;
		if(money_str){
			var arr=money_str.split(",");
			$.each( arr, function(i, n){
				var c_m=this.split("|");
				if(c_m[0]==capital_id) res = c_m[1];
			});
		}
		return res;
	}

	//退款小合计填充
	function tk_min_all(){
		$(".tk_min_all").each(function(i){
			var tk_min_all=0;
			$(this).closest('.pos_cz_tow').find(".tk").map(function(){
				tk_min_all+= $.isNumeric(parseInt($(this).html()))?parseInt($(this).html()):0;
			});
			$(this).html(tk_min_all);
		});

		$('.c_tk_min_all').html(eval($('.capital_tk').map(function(){
			return $.isNumeric($(this).val())?parseInt($(this).val()):0;
		}).get().join('+')));

		tk_all();
	}
	//总退款合计填充
	function tk_all(){
		var tk_all=0;
		$(".tk_min_all").map(function(){
			tk_all+= $.isNumeric(parseInt($(this).html()))?parseInt($(this).html()):0;
		});
		$(".capital_tk").map(function(){
			tk_all+= $.isNumeric(parseInt($(this).val()))?parseInt($(this).val()):0;
		});
		$(".tk_all").html(tk_all);
	}

});
</script>