<div class="add_card" title="编辑会员卡">
	<div class="tjfj_two">
		<form method="post" action="<?php echo $this->url('add') ?>">
			<input type="hidden" name="yd" value="" />
			<div class="list">
				<label>是否正式会员：</label>
                <div style="margin-left: 100px;">
				<?php echo $this->dropDownList('is_member',array('非正式会员','正式会员'),$model->is_member==0?0:1) ?>
                </div>
			</div>
			<div class="list">
				<label>会员卡名称：</label><div style="margin-left: 100px;"><input type="text" placeholder="黃金卡"
					class="gysgl_07 inputxt" name="level_name"
					value="<?php echo $model->level_name; ?>" /></div>
			</div>
			<div class="list">
				<label>会员卡说明：</label>
				<div style="margin-left: 100px;"><textarea rows="3" style="width: 60%;"><?php echo $model->note; ?></textarea></div>
			</div>
			<input name="id" type="hidden" value="<?php echo $model->id ?>" />
		</form>
	</div>
</div>
<script type="text/javascript">
	$('select[name="is_member"] option:first').remove()
</script>