<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/寄存领取
                </div>
                <div class="tools">
                    <button class="btn btn-sm green table-group-action-submit c_submit"><i class="fa fa-check"></i>提交订单</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>订单概况
                        </div>
                        <div class="actions">
                            <?php if (!$model): ?>
                            <button class="btn red">订单新建</button>
                            <?php else: ?>
                            <button class="btn red">订单编辑</button>
                            <?php endif ?>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">领取单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->sn ?>
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-xs-5 name">订单状态：</div>
                            <div class="col-xs-7 value text-right">
                                <?php if (!$model): ?>
                                <span class="label label-info label-sm">草稿</span>
                                <?php else: ?>
                                <span class="label label-warning label-sm"><?php echo \CustomerProdReceive::getStatus($model->status);?></span>
                                <?php endif ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">本次领取数：</div>
                            <div class="col-xs-7 value text-right">
                                <font class="all_num">0</font>
                            </div>
                        </div>


                        
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>



        <!--寄存商品-->
        <div class="pos_cz_tow">
            <div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>寄存商品</div>
            <div class="pos_cz_tow_two">
                <!--table_container-->
                <div class="table_container">
                    <!--table_con-->
                    <div class="table_con table-responsive">
                        <!--table_con_son-->
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>关联订单</th>
                                    <th>商品名称</th>
                                    <th>来源</th>
                                    <th>寄存数量</th>
                                    <th>规格</th>
                                    <th>可领取数量</th>
                                    <th>领取数量</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $pnum=0; foreach($storageProducts as $storageProduct):?>
                                <?php
                                    $order_sale_detail = \OrderSaleDetail::model()->findByPk($storageProduct['detail_id']);
                                    
                                    if(is_null($order_sale_detail)) continue;

                                    if($order_sale_detail['pay_price']>0)
                                        $max_num = floor($order_sale_detail['var_price']*$order_sale_detail['num']/$order_sale_detail['price']*$order_sale_detail['rebate']/100);
                                    else
                                        $max_num = $storageProduct['remain_num'];

                                    if($order_sale_detail->buy_type==3){
                                        $orderVoucher = \OrderVoucher::model()->findByPk($storageProduct['order_id']);
                                        $sn = $orderVoucher->sn;
                                    }else{
                                        $orderSale = \OrderSale::model()->findByPk($storageProduct['order_id']);
                                        $sn = $orderSale->sn;
                                    }
                                ?>


                                <tr class="table_list">
                                    <!--<li class="li001"><input type="checkbox" /></li>-->
                                    <td class="li001"><a href="#"><?php echo $sn;?></a></td>
                                    <td class="li001"><?php $productInfo = \ProductInfo::model()->findByPk($storageProduct['product_id']);echo $productInfo->name?></td>
                                    <td class="li003"><?php echo \OrderSaleDetail::getBuyType($order_sale_detail->buy_type)?></td>
                                    <td class="li002"><?php echo $storageProduct['remain_num'];?></td>
                                    <td class="li003"><?php echo $productInfo->unit?></td>
                                    <td class="li003"><?php echo $max_num?></td>
                                    <td class="li004 lq_num"><input value="<?php echo $detail_nums[$storageProduct['id']]['num'];?>" type="text" class="pos_cz_tow_two05" /></td>
                                    <input type="hidden" name="order_detail_id[]" value="<?php echo $storageProduct['detail_id'];?>">
                                    <input type="hidden" name="storage_detail_id[]" value="<?php echo $storageProduct['id'];?>">
                                    <input type="hidden" name="remain_num[]" value="<?php echo $storageProduct['remain_num'];?>">
                                    <input type="hidden" name="product_id[]" value="<?php echo $storageProduct['product_id'];?>">
                                </tr>
                                <?php $pnum+=$detail_nums[$storageProduct['id']]['num'];?>
                               
                            <?php endforeach;?>
                            </tbody>
                        </table><!--table_con_son!end-->
                    </div><!--table_con!end-->
                </div>
                <!--table_containter!end-->
                <div class="pos_cz_tow_two_two pos_cz_qr_top_02">
                    <span class="pos_cz_tow_two04">领取商品小计：<em><?php echo $pnum;?></em></span>
                </div>
            </div>
        </div><!--寄存商品!end-->

        <!--备注-->
        <div class="pos_cz_for_bz">
            <div class="pos_cz_for_bz01">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son"><textarea rows="4"></textarea></div>
            </div>
        </div><!--备注!end-->

    </div>
</div>


{__TOKEN__}

<script type="text/javascript">
    //table_flash();
    //收起效果
    $(".pos_cz_tow_top_r").click(function(){
        var self=$(this);
        self.parent().next().slideToggle("fast",function(){
            //alert("Animation Done.");
            if(self.hasClass("pos_cz_tow_top_rcl")){
                self.removeClass("pos_cz_tow_top_rcl");
            }else{
                self.addClass("pos_cz_tow_top_rcl");
            }
        });
    });

    $('.pos_cz_tow_two05').keyup(function(){
        var reg = /^\+?[1-9][0-9]*$/;
        var total=0;
        if($(this).val()!=''){
            if(!reg.test($(this).val())){
                Idialog.tips("请输入正整数",2);
                $(this).val('');
            }else{
                if(parseInt($(this).val())>parseInt($(this).parent().prev().text())){
                    Idialog.tips("您输入的领取数量大于可领取数量,有欠款请先还款后领取！",2);
                    $(this).val('');
                }else{
                    $('.pos_cz_tow_two05').each(function(){
                        if($(this).val()!=''){
                            total += parseInt($(this).val());
                        }
                    });
                }
            }
        }
        $('.pos_cz_tow_two04').find('em').text(total);
        $(".all_num").html(total);
    });

    //数据提交
    $(".c_submit").click(function(){
        var post_data = submit_data();
        if(post_data.receive.length<=0){
            Idialog.tips('请先填写领取数量!',2);
            return false;
        }
        <?php if ($model): ?>
            var url="<?php echo $this->url('editSave',array('id'=>$model->id)) ?>";
        <?php else: ?>
            var url="<?php echo $this->url('addSave') ?>";
        <?php endif ?>
        $.post(url, post_data,function(data){
            Idialog.tips(data.msg,2);
            if(data.code==200){
                //转到付款界面
                setTimeout(function(){to_url('<?php echo $this->url("pay");?>&id='+data.data)},1000);
            }
        }, "json");
    });

    function to_url(url){
        window.location.href=url;
    }

    //提交保存数据构造
    function submit_data(){
        var data={};
        data.__hash__ = $("input[name='__hash__']").val();//表单令牌
        data.receive=[];
        $('.lq_num .pos_cz_tow_two05').each(function(i){
            if($(this).val()!=''){
                data.receive.push({
                    "order_detail_id":$(this).parents('tr').find("input[name='order_detail_id[]']").val(),
                    "storage_detail_id":$(this).parents('tr').find("input[name='storage_detail_id[]']").val(),
                    "remain_num":$(this).parents('tr').find("input[name='remain_num[]']").val(),
                    "product_id":$(this).parents('tr').find("input[name='product_id[]']").val(),
                    "num":$(this).val()
                });
            }
        });
        data.cu_id = $('.cu_info').attr("data-id");
        data.remark = $(".pos_cz_for_bz02_son textarea").val();
        //return false; 发生验证错误 返回false
        return data;
    }

</script>


