
<!--content_right_con-->
<div class="content_right_con">
    <div class="content_right_con_top">
        <!--<div class="fjgl_top_r">
          <a href="javascript:" class="khgl_02 fpkhn">分配客户</a><a href="javascript:" class="fjgl_top_r_01">筛选</a><a href="javascript:" class="fjgl_top_r_02 tjfjz">添加客户</a>
        </div>-->
        <div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>POS开单><span>寄存领取</span>
    </div>

    <!--khgl_shouye-->
    <?php echo $cu_info ?>
    <!--khgl_shouye!end-->


    <!--寄存商品-->
    <div class="pos_cz_tow">
        <div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>寄存商品</div>
        <div class="pos_cz_tow_two">
            <!--table_container-->
            <div class="table_container" style="border:none;">
                <!--table_con-->
                <div class="table_con">
                    <!--table_con_son-->
                    <div class="table_con_son">
                        <div class="table_title">
                            <ul>
                                <!--<li><input type="checkbox" /></li>-->
                                <li>关联订单</li>
                                <li>商品名称</li>
                                <li>来源</li>
                                <li>寄存数量</li>
                                <li>规格</li>
                                <li>可领取数量</li>
                                <li>领取数量</li>
                            </ul>
                        </div>
                        <?php $pnum=0; foreach($storageProducts as $storageProduct):?>
                            <?php
                                $order_sale_detail = \OrderSaleDetail::model()->findByPk($storageProduct['detail_id']);
                                
                                if(is_null($order_sale_detail)) continue;

                                if($order_sale_detail['pay_price']>0)
                                    $max_num = floor($order_sale_detail['var_price']*$order_sale_detail['num']/$order_sale_detail['price']*$order_sale_detail['rebate']/100);
                                else
                                    $max_num = $storageProduct['remain_num'];

                                if($order_sale_detail->buy_type==3){
                                    $orderVoucher = \OrderVoucher::model()->findByPk($storageProduct['order_id']);
                                    $sn = $orderVoucher->sn;
                                }else{
                                    $orderSale = \OrderSale::model()->findByPk($storageProduct['order_id']);
                                    $sn = $orderSale->sn;
                                }
                            ?>
                            <div class="table_list">
                                <ul>
                                    <!--<li class="li001"><input type="checkbox" /></li>-->
                                    <li class="li001"><a href="#"><?php echo $sn;?></a></li>
                                    <li class="li001"><?php $productInfo = \ProductInfo::model()->findByPk($storageProduct['product_id']);echo $productInfo->name?></li>
                                    <li class="li003"><?php echo \OrderSaleDetail::getBuyType($order_sale_detail->buy_type)?></li>
                                    <li class="li002"><?php echo $storageProduct['remain_num'];?></li>
                                    <li class="li003"><?php echo $productInfo->unit?></li>
                                    <li class="li003"><?php echo $max_num?></li>
                                    <li class="li004 lq_num"><input value="<?php echo $detail_nums[$storageProduct['id']]['num'];?>" type="text" class="pos_cz_tow_two05" /></li>
                                    <input type="hidden" name="order_detail_id[]" value="<?php echo $storageProduct['detail_id'];?>">
                                    <input type="hidden" name="storage_detail_id[]" value="<?php echo $storageProduct['id'];?>">
                                    <input type="hidden" name="remain_num[]" value="<?php echo $storageProduct['remain_num'];?>">
                                    <input type="hidden" name="product_id[]" value="<?php echo $storageProduct['product_id'];?>">
                                </ul>
                            </div>
                        <?php $pnum+=$detail_nums[$storageProduct['id']]['num'];endforeach;?>

                    </div><!--table_con_son!end-->
                </div><!--table_con!end-->
            </div>
            <!--table_containter!end-->
            <div class="pos_cz_tow_two_two pos_cz_qr_top_02">
                <span class="pos_cz_tow_two04">领取商品小计：<em><?php echo $pnum;?></em></span>
                <!--<span class="pos_gm_01">还款订单<span class="pos_gm_03">2</span>个</span>
                <span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥5000.00</span></span>-->
            </div>
        </div>
    </div><!--寄存商品!end-->

    <!--备注-->
    <div class="pos_cz_for_bz">
        <div class="pos_cz_for_bz01">备注</div>
        <div class="pos_cz_for_bz02">
            <div class="pos_cz_for_bz02_son"><textarea rows="4"></textarea></div>
        </div>
    </div><!--备注!end-->

    <!---->
    <div class="pos_cz_zh">
        <a href="javascript:" class="pos_cz_zh_an">领取</a>
    </div><!--!end-->
</div>
<!--content_right_con!end-->


{__TOKEN__}

<script type="text/javascript">
    //table_flash();
    //收起效果
    $(".pos_cz_tow_top_r").click(function(){
        var self=$(this);
        self.parent().next().slideToggle("fast",function(){
            //alert("Animation Done.");
            if(self.hasClass("pos_cz_tow_top_rcl")){
                self.removeClass("pos_cz_tow_top_rcl");
            }else{
                self.addClass("pos_cz_tow_top_rcl");
            }
        });
    });

    $('.pos_cz_tow_two05').keyup(function(){
        var reg = /^\+?[1-9][0-9]*$/;
        var total=0;
        if($(this).val()!=''){
            if(!reg.test($(this).val())){
                Idialog.tips("请输入正整数",2);
                $(this).val('');
            }else{
                if(parseInt($(this).val())>parseInt($(this).parent().prev().text())){
                    Idialog.tips("您输入的领取数量大于可领取数量,有欠款请先还款后领取！",2);
                    $(this).val('');
                }else{
                    $('.pos_cz_tow_two05').each(function(){
                        if($(this).val()!=''){
                            total += parseInt($(this).val());
                        }
                    });
                }
            }
        }
        $('.pos_cz_tow_two04').find('em').text(total);
    });

    //数据提交
    $(".pos_cz_zh_an").click(function(){
        var post_data = submit_data();
        if(post_data.receive.length<=0){
            Idialog.tips('请先填写领取数量!',2);
            return false;
        }
        <?php if ($model): ?>
            var url="<?php echo $this->url('editSave',array('id'=>$model->id)) ?>";
        <?php else: ?>
            var url="<?php echo $this->url('addSave') ?>";
        <?php endif ?>
        $.post(url, post_data,function(data){
            Idialog.tips(data.msg,2);
            if(data.code==200){
                //转到付款界面
                setTimeout(function(){to_url('<?php echo $this->url("pay");?>&id='+data.data)},1000);
            }
        }, "json");
    });

    function to_url(url){
        window.location.href=url;
    }

    //提交保存数据构造
    function submit_data(){
        var data={};
        data.__hash__ = $("input[name='__hash__']").val();//表单令牌
        data.receive=[];
        $('.lq_num .pos_cz_tow_two05').each(function(i){
            if($(this).val()!=''){
                data.receive.push({
                    "order_detail_id":$(this).parents('ul').find("input[name='order_detail_id[]']").val(),
                    "storage_detail_id":$(this).parents('ul').find("input[name='storage_detail_id[]']").val(),
                    "remain_num":$(this).parents('ul').find("input[name='remain_num[]']").val(),
                    "product_id":$(this).parents('ul').find("input[name='product_id[]']").val(),
                    "num":$(this).val()
                });
            }
        });
        data.cu_id = $('.cu_info').attr("data-id");
        data.remark = $(".pos_cz_for_bz02_son textarea").val();
        //return false; 发生验证错误 返回false
        return data;
    }

</script>


