<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/寄存领取-确认
                </div>
                <div class="tools">
                    <?php if($model->o_s->status==0): ?>
                        <button class="btn btn-sm blue table-group-action-submit c_submit"><i class="fa fa-check"></i>确认领取</button>
                        <button id="cancelOrder" class="btn btn-sm red table-group-action-submit"><i class="fa fa-eraser"></i>废弃订单</button>
                        <button onclick="to_url('<?php echo $this->url('edit',array('id'=>$model->id)) ?>')" class="btn btn-sm green table-group-action-submit"><i class="fa fa-mail-forward "></i>修改订单</button>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>订单概况
                        </div>
                        <div class="actions">
                            <button class="btn red"><?php echo \CustomerProdReceive::getStatus($model->status);?></button>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">领取单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->sn ?>
                            </div>
                        </div>


                        <div class="row static-info">
                            <div class="col-xs-5 name">订单状态：</div>
                            <div class="col-xs-7 value text-right">
                                <span class="label label-warning label-sm"><?php echo $model->re_status==1?'已领取':'未领取'?></span>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">本次领取数：</div>
                            <div class="col-xs-7 value text-right">
                                <font class="all_num">0</font>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>
        <!--订单信息-->
        <div class="pos_cz_tow">
            <div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>订单信息</div>
            <div class="pos_cz_tow_two">
                <!--table_container-->
                <div class="table_container">
                    <!--table_con-->
                    <div class="table_con table-responsive">
                        <!--table_con_son-->
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>商品名称</th>
                                    <th>寄存数量</th>
                                    <th>规格</th>
                                    <th>领取数量</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php $num=0; foreach($details as $detail):?>
                                <tr class="table_list">
                                    <td class="li001"><?php echo $detail['name'];?></td>
                                    <td class="li002"><?php echo $detail['before_num'];?></td>
                                    <td class="li003"><?php echo $detail['unit'];?></td>
                                    <td class="li006"><?php echo $detail['num'];?></td>
                                </tr>
                                <?php $num += $detail['num'];?>
                            <?php endforeach;?>
                            </tbody>
                        </table><!--table_con_son!end-->
                    </div><!--table_con!end-->
                </div>
                <!--table_containter!end-->
                <div class="pos_cz_tow_two_two pos_cz_qr_top_02">
                    <span class="pos_cz_tow_two04">领取商品小计：<em><?php echo $num;?></em></span>
                </div>
            </div>
        </div><!--订单信息!end-->

        <!--备注-->
        <div class="pos_cz_tow pos_cz_for_bz">
            <div class="pos_cz_for_bz01 pos_cz_qr_top_07">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son">
                    <p class="pos_cz_qr_top_06"><?php echo $model->remark ?></p>
                </div>
            </div>
        </div>
        <!--备注!end-->




    </div>
</div>



{__TOKEN__}

<script type="text/javascript">
$(function(){
    $(".all_num").html(<?php echo $num;?>);

})
    //收起效果
    $(".pos_cz_tow_top_r").click(function(){
        var self=$(this);
        self.parent().next().slideToggle("fast",function(){
            //alert("Animation Done.");
            if(self.hasClass("pos_cz_tow_top_rcl")){
                self.removeClass("pos_cz_tow_top_rcl");
            }else{
                self.addClass("pos_cz_tow_top_rcl");
            }
        });
    });


    function to_url(url){
        window.location.href=url;
    }

    //提交保存数据构造
    function submit_data(){
        var data={};
        data.__hash__ = $("input[name='__hash__']").val();//表单令牌
        // 订单id
        data.order_id = '<?php echo $_GET['id']?>';

        //return false; 发生验证错误 返回false
        return data;
    }

    //数据提交
    $(".c_submit").click(function(){
        var post_data = submit_data();
        $.post("<?php echo $this->url('paySave',array('id'=>$model->id)) ?>", post_data,function(data){
            Idialog.tips(data.msg,2);
            if(data.code==200){
                setTimeout(function(){to_url('<?php echo $this->url("index");?>')},2000);
            }
        }, "json");
    });

    $("#cancelOrder").click(function(){
        if(confirm("您确定要废弃此订单吗？")){
            var data={};
            data.__hash__ = $("input[name='__hash__']").val();//表单令牌
            $.post("<?php echo $this->url('cancel',array('id'=>$model->id)) ?>",data,function(data){
                Idialog.tips(data.msg,2);
                if(data.code==200){
                    setTimeout(function(){to_url('<?php echo $this->url("add");?>&id='+$('.cu_info').attr("data-id"))},2000);
                }
            }, "json");
        }
    });

</script>


