<style>
.xz_cu{width: 160px;border:1px solid #dddddd; height: 26px;display: inline-block;}
.xz_cu input{width: 160px; height: 26px;border:none;}
.xz_cu .search_cu_id_list{position: absolute;width: 160px;}
</style>
<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
	仓库管理>入库记录>新建入库
	</div>
	<form action="<?php echo $this->url('addn') ?>" method="post">
	<div class="fjgl_two" >
		<div class="ck_splb_ckjl_01 ck_splb_ckjl_01_l">入库日期：<?php echo date("Y-m-d") ?></div>
		<div class="ck_splb_ckjl_01 ck_splb_ckjl_01_m">部门：<?php echo $dept_name ?></div>
		<div class="ck_splb_ckjl_01 ck_splb_ckjl_01_r">制单人：<?php echo \Ivy::app()->user->netname ?></div>
	</div>
  
	<div class="ck_splb_ckjl_top">
		<div class="ck_splb_ckjl_top_l">入库类型：</div>
		<div class="ck_splb_ckjl_top_r">
			<div class="ck_splb_ckjl_top_r_son">
				<!-- <select type="text" class="ck_splb_ckjl_top_01"></select> -->
				<?php echo $this->dropDownList('type',\invo\In::getType(),$type,array("class"=>'ck_splb_ckjl_top_01')) ?>

				<?php if ($type==4): ?>
					<span class="ck_splb_ckjl_top_02">发出单位：</span>
					<?php $supplier_list= \SupplierInfo::getList();?>
					<?php echo $this->dropDownList('from_id',$supplier_list,'',array("class"=>'ck_splb_ckjl_top_01')) ?>
				<?php else: ?>
					<span class="ck_splb_ckjl_top_02">退货人：</span>
					<div class="xz_cu"><?php echo \Ivy::app()->widget('common/selectCustomer',array('name'=>'from_id')); ?></div>
				<?php endif ?>

			</div>
		</div>
	</div> 
 
 
	<div class="ck_splb_ckjl_top">
             <div class="ck_splb_ckjl_top_l">出库商品：</div>
             <div class="ck_splb_ckjl_top_r">
                 <div class="ck_splb_ckjl_top_r_son">
                     <div class="ck_splb_ckjl_top_03 action_add">选择商品</div>
                     <!--赠送-->
                    <div class="pos_cz_tow" style=" margin-top:0px;">
                        
                        <div class="pos_cz_tow_two">
                            <!--table_container-->  
                            <div class="table_container" style=" border:none">
                               <!--table_con-->
                               <div class="table_con">
                                  <!--table_con_son-->
                                   <div class="table_con_son">
                                     <div class="table_title">
                                       <ul>
                                         <li>商品分类</li>
                                         <li>品牌或系列</li>
                                         <li>商品名称</li>
                                         <li>商品编码</li>
                                         <li>规格</li>
                                         <li>单位</li>
                                         <li>入库数量</li>
                                         <li>操作</li>
          
                                       </ul>
                                    </div>

                                 </div><!--table_con_son!end-->
                               </div><!--table_con!end-->
                             </div>
                            <!--table_containter!end-->
                            <div class="pos_cz_tow_two_two pos_cz_qr_top_02"><span class="spantj action_add">继续添加</span></div>
                        </div>
                    </div><!--赠送!end-->
                 </div>
             </div>
         </div> 
 
 
	<div class="ck_splb_ckjl_top">
		<div class="ck_splb_ckjl_top_l">备注：</div>
		<div class="ck_splb_ckjl_top_r">
			<div class="ck_splb_ckjl_top_r_son">
				<textarea name="note" rows="4" style=" width:98%;"></textarea>
			</div>
		</div>
	</div>
	</form>
 
 
	<div class="ck_splb_ckjl_top">
		<div class="ck_splb_ckjl_top_l"></div>
		<div class="ck_splb_ckjl_top_r">
			<div class="ck_splb_ckjl_top_r_son">
				<a href="javascript:$('form').submit();" class="ck_splb_ckjl_top_04 ck_splb_ckjl_top_05">确认入库</a>
				<a href="javascript:" class="ck_splb_ckjl_top_04">取 消</a>
				<!-- <a href="javascript:" class="ck_splb_ckjl_top_04 none refuse">拒绝入库</a> -->
				<!-- <a href="javascript:" class="ck_splb_ckjl_top_04">暂缓入库</a> -->
			</div>
		</div>
	</div>
</div>
<!--content_right_con!end-->

<div class="none" id="widget_product">
<?php echo \Ivy::app()->widget('common/selectProduct', array('param'=>"rich",'show_del'=>2)); ?>
</div>


<script type="text/javascript">
$(function(){
	$('select[name="type"]').change(function(){
		if($(this).val()<3){
			to_url('<?php echo $this->url("add") ?>&type='+$(this).val());
		}else{
			to_url('<?php echo $this->url("addn") ?>&type='+$(this).val());
		}
	});


    //删除产品
    $(document).on('click', '.c_del', function(event) {
        event.preventDefault();
        /* Act on the event */
        $(this).closest('.table_list').remove();
    });
    //添加产品
    $('.action_add').click(function(event) {
        /* Act on the event */
        var d = Idialog({
            top:150,
            width:800,
            title:'添加产品',
            content:$('#widget_product'),
            cancel:false,
            ok:function(obj){
                var _self=obj._self;
                var has_list = $('.table_list');//已经存在的列
                var pro_k=has_list.length;//当前序号

                var result_list=_self.find('.result_pro li');
                $.each( result_list, function(i, pro){
                    pro=$(pro);
                    var p_name=pro.attr('data-name');
                    var p_id=pro.attr('rel');
                    var p_num=pro.attr('data-num');
                    var p_price=pro.attr('data-price');
                    var p_unit=pro.attr('data-unit');//产品规格
                    var max_num=pro.attr('data-max-num');
                    //如果存在 则略过
                    if(has_list.filter("[data-id='"+p_id+"']").length>0) return ;

                    var str  ='<div class="table_list" data-id="'+p_id+'"><ul>';
                        str +='<li class="li001">'+pro.attr('data-top_name')+'</li>';
                        str +='<li class="li002">'+pro.attr('data-c_name')+'</li>';
                        str +='<li class="li003">'+p_name+'</li>';
                        str +='<li class="li004">'+pro.attr('data-code')+'</li>';
                        str +='<li class="li005">'+pro.attr('data-specs')+'</li>';
                        str +='<li class="li006">'+p_unit+'</li>';
                        str +='<li class="li007"><input type="hidden" name="d_id[]" value="'+p_id+'" ><input type="text" class="pos_cz_tow_two05" value="1"  name="in_num[]" /></li>';
                        str +='<li class="li008"><a href="javascript:" class="delete c_del">删除</a></li>';
                        str +='</ul></div>';
                    
                    $('.table_con_son').append(str);
                    pro_k++;
                });
                
            }
        });
    });

});
</script>