<?php
$top_cate=\ProCate::getProductTopCate();
$child_cate=array();
if(isset($_GET['t_search']['tpc.id']))
    $tmp_cate=\ProCate::model()->findAll('status=1 AND fid='.(int)$_GET['t_search']['tpc.id']);
    $child_cate = $this->optArr($tmp_cate,'id','name');
?>
<div class="row">
    <div class="col-md-12">

        <!-- <div class="note note-danger">
            <p>
                 有 <span style=" color:#ec314b;"><?php echo $membership_off_count; ?></span> 个客户未设定客户等级，将会影响部分统计数据准确性。
            </p>
        </div> -->


    <!--  模版引擎扩展 -->
    <?php echo $this->datagrid(array(
        'id'=>'list',
        'dataProvider'=>$pager,
        'search'=>true,
        'columns'=>array(
            array(
                'header' => '商品分类',
                'name'  => 'tcname',
                'filter'=>array("tpc.id",$top_cate,""),
            ),
            array(
                'header' => '商品系列',
                'name'  => 'cname',
                'filter'=>array("pc.id",$child_cate,""),
            ),
            array(
                'header' => '商品名称',
                'name'  => 'name',
                'filter'=>"pro.name",
            ),
            array(
                'header' => '商品编码',
                'name' => 'code',
                'filter'=>"pro.code",
            ),
            array(
                'header' => '入库日期',
                'name' => 'in_time',
                'value' => '{date("Y-m-d",$data["in_time"])}'
            ),
            array(
                'header' => '入库类型',
                'name' => 'in_type',
                'value' => '{\invo\In::getType($data["in_type"])}'
            ),
            array(
                'header' => '发出单位',
                'name' => 'from_dept',
                'value' => '{\invo\In::getFromDept($data["id"])}'
            ),
            array(
                'header' => '入前结存',
                'name' => 'before_num',
            ),
            array(
                'header' => '入库数量',
                'name' => 'in_num',
            ),
            array(
                'header' => '入后结存',
                'name' => 'after_num',
            ),
            array(
                'header' => '状态',
                'name' => 'in_status',
                'value' => '{\invo\In::getStatus($data["in_status"])}'
            ),
            array(
                'header' => '操作',
                'rel' => 'id',
                'template' => 'view+'
            ),
           
        ),
    ));?>

    <div class="ck_splb_foot none">
        <a href="javascript:" class="ck_splb_foot_01">确认建立商品期初库存（20）</a>注：期初商品确认建立后将不可更改期初库存！确认商品期初库存只可操作一次，请谨慎操作！
    </div>
    </div>
</div>