<style type="text/css">
.xzzh{color:#0077ff;cursor: pointer;}
</style>

<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>新建客户期初
	</div>
	<!-- 上操作按钮  付款后有效-->
	<?php if ($model): ?>
		<div class="jyjl_top jyjl_czda_top">
			<div class="jyjl_czda_top_l">
				<div class="jyjl_czda_top_top">订单提交成功</div>
				<div class="jyjl_czda_top_two">订单编号：<span><?php echo $model->o_s->sn ?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 订单状态：<span class="spanll"><?php echo \OrderSale::getPayStatusForInit($model->o_s->pay_status);?></span></span></div>
			</div> 
			<!-- <div class="jyjl_czda_top_r">
				<?php if ($model->o_s->pay_status): ?>
					<a class="aysh01" href="javascript:">打印订单</a>
				<?php else: ?>
					<a class="aysh01" href="<?php echo $this->url("pay",array('id'=>$model->o_s->id)) ?>">开账</a>
					<a class="aysh01" href="<?php echo $this->url("del",array('id'=>$model->o_s->id)) ?>">废除</a>
				<?php endif ?>
				
			</div> -->
		</div>
	<?php endif; ?>

	<!--khgl_shouye-->
	<?php echo $cu_info ?>
	<!--khgl_shouye!end-->
	<!--账户余额-->
	<div class="pos_cz_tow box_gift_xj">
      	  <div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>账户余额
          </div>
        <div class="pos_cz_tow_two">
              <!--table_container-->  
          <div class="table_container" style="border:none;">
                 
                 <!--table_con-->
                 <div class="table_con">
                    <!--table_con_son-->
                     <div class="table_con_son" style="min-width: 826px;">
                       <div class="table_title">
                         <ul>
                           <?php foreach ($capital_list as $value): ?>
								<li><?php echo $value['name'] ?>（元）</li>
							<?php endforeach ?>	
                         </ul>
                      </div>
                   	<?php 
                   		if($model){
							$gift_capital = \OrderSaleMoney::model()->where(array('order_id'=>$model->o_s->id))->findAll();
							$gift_arr=array();
							foreach ($gift_capital as $g_c) {
								$gift_arr[$g_c['capital_id']]=$g_c['cash'];
							}
						}
                   	?>
    
                     <div class="table_list">
                       <ul>
                          <?php foreach ($capital_list as $key=>$value): ?>
								<li class="li00<?php echo ++$key ?>">
								<input  data-id="<?php echo $value['id'] ?>" type="text" value="<?php echo $gift_arr[$value['id']] ?>" class="pos_cz_tow_two05" />
								</li>
							<?php endforeach ?>	
                       </ul>
                     </div>
                     
                   </div><!--table_con_son!end-->
                 </div><!--table_con!end-->
          </div>
          <!--table_containter!end--></div>
      </div>
      <!--账户余额end-->
	<!--购买项目-->
	<div class="pos_cz_tow box_xm">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>购买的项目</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
			<!--table_con-->
			<div class="table_con" style="border:none; margin-right:0px;">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
					<ul>
						<li style="min-width:250px">项目</li>
						<li>数量（疗次）</li>
						<li>原价（元）</li>
						<li>面折率</li>
						<li>应付金额（元）</li>
						<li>欠款（元）</li>
						<li>实收金额（元）</li>
						<li style="min-width:80px">操作</li>
					</ul>
					</div>
					<?php if ($model): ?>
						<?php foreach ($model->pros as $pro): ?>
							<?php if($pro['pro_type']!=1) continue; ?>
							<?php if($pro['buy_type']!=1) continue; ?>
							<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

							<div data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" class="table_list">
								<ul>
									<li class="li001"><?php echo $info->name ?>（<?php echo $info->num*$info->price ?>元/<?php echo $info->num ?>疗次）</li>
									<li class="li002"><input type="text" value="<?php echo $pro['num'] ?>" class="pos_cz_tow_two05"></li>
									<li class="li003"><?php echo $pro['price'] ?></li>
									<li class="li004"><input type="text" value="<?php echo $pro['rebate'] ?>" class="pos_cz_tow_two05">&nbsp;%</li>
									<li class="li005"><input type="text" value="<?php echo $pro['pay_price'] ?>" class="pos_cz_tow_two05"></li>
									<li class="li006"><input type="text" value="<?php echo $pro['arrears'] ?>" class="pos_cz_tow_two05" style="color:#f00;"></li>
									<li class="li007"><input type="text" value="<?php echo $pro['cash'] ?>" class="pos_cz_tow_two05"></li>
									<li class="li008"><a class="delete c_del" href="javascript:">删除</a></li>
								</ul>
							</div>
						<?php endforeach ?>
					<?php endif ?>	
				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two"><span class="spantj c_add">继续添加</span></div>
			
		</div>
	</div><!--购买项目!end-->

	<!--赠送-->
	<div class="pos_cz_tow box_gift_xm">
		<div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>赠送的项目</div>
		<div class="pos_cz_tow_two">
			<!--table_container-->  
			<div class="table_container" style="border:none;">
			<!--table_con-->
			<div class="table_con" style="border:none; margin-right:0px;">
				<!--table_con_son-->
				<div class="table_con_son">
					<div class="table_title">
					<ul>
						<li style="min-width:250px">项目</li>
						<li>数量（疗次）</li>
						<li style="min-width:80px">操作</li>
					</ul>
					</div>
					<?php if ($model): ?>
						<?php foreach ($model->pros as $pro): ?>
							<?php if($pro['pro_type']!=1) continue; ?>
							<?php if($pro['buy_type']!=2) continue; ?>
							<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

							<div data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" class="table_list">
								<ul>
									<li class="li001"><?php echo $info->name ?>（<?php echo $info->num*$info->price ?>元/<?php echo $info->num ?>疗次）</li>
									<li class="li002"><input type="text" value="<?php echo $pro['num'] ?>" class="pos_cz_tow_two05"></li>
									<li class="li003"><a class="delete c_del" href="javascript:">删除</a></li>
								</ul>
							</div>
						<?php endforeach ?>
					<?php endif ?>	
				</div><!--table_con_son!end-->
			</div><!--table_con!end-->
			</div>
			<!--table_containter!end-->
			<div class="pos_cz_tow_two_two"><span class="spantj c_add">继续添加</span></div>
			
		</div>
	</div>
	
	<!--赠送!end-->

	<!--备注-->
	<div class="pos_cz_tow pos_cz_for_bz">
		<div class="pos_cz_for_bz01">备注</div>
		<div class="pos_cz_for_bz02">
			<div class="pos_cz_for_bz02_son"><textarea class="order_note" rows="4"><?php echo $model?$model->o_s->note:"" ?></textarea></div>
		</div>
	</div><!--备注!end-->

	<!---->
	<div class="pos_cz_tow pos_cz_zh">
		<?php if (!$model): ?>
			<a href="javascript:" class="pos_cz_zh_an c_submit">建立期初</a>
		<?php else: ?>
			<?php if (!$model->o_s->pay_status): ?>
				<a href="javascript:" class="pos_cz_zh_an c_submit">建立期初</a>
			<?php endif ?>
		<?php endif ?>
		
		
		
	</div><!--!end-->
</div>
<!--content_right_con!end-->


{__TOKEN__}

<div class="none" id="widget_project">
<?php echo \Ivy::app()->widget('common/selectProject',"rich"); ?>
</div>

<div class="none" id="widget_gift_project">
<?php echo \Ivy::app()->widget('common/selectProject',"rich"); ?>
</div>

<script type="text/javascript">

$(function(){

	<?php if ($model): ?>
		change_total();
	<?php endif ?>

	//收起效果
	$(".pos_cz_tow_top_r").click(function(){
		var self=$(this);
		self.parent().next().slideToggle("fast",function(){
			//alert("Animation Done.");
			if(self.hasClass("pos_cz_tow_top_rcl")){
				self.removeClass("pos_cz_tow_top_rcl");
			}else{
				self.addClass("pos_cz_tow_top_rcl");
			}
		});
	});

	//项目的添加
	$('.box_xm').on('click','.c_add',function(){
		var self=$(this).closest('.box_xm');//box对象
		var d = Idialog({
			top:150,
			width:800,
			title:'添加项目',
			content:$('#widget_project'),
			cancel:false,
			ok:function(obj){
				var _self=obj._self;
				var has_list = self.find('.table_list');//已经存在的列
				var pro_k=has_list.length;//当前序号

				var result_list=_self.find('.result_pro li');
				$.each( result_list, function(i, pro){
					pro=$(pro);
					var p_name=pro.attr('data-name');
					var p_id=pro.attr('rel');
					var p_num=pro.attr('data-num');
					var p_price=pro.attr('data-price');
					var p_old_price=parseInt(p_num)*parseInt(p_price);
					//如果存在 则略过
					if(has_list.filter("[data-id='"+p_id+"']").length>0) return ;

					var str  ='<div class="table_list" data-id="'+p_id+'" data-dj="'+p_price+'" ><ul>';
						str +='<li class="li001">'+p_name+'（'+p_old_price+'元/'+p_num+'疗次）</li>';
						str +='<li class="li002"><input type="text" class="pos_cz_tow_two05" value="'+p_num+'" /></li>';
						str +='<li class="li003">'+p_old_price+'</li>';
						str +='<li class="li004"><input type="text" class="pos_cz_tow_two05" value="100" />&nbsp;%</li>';
						str +='<li class="li005"><input type="text" value="'+p_old_price+'" class="pos_cz_tow_two05"></li>';
						str +='<li class="li006"><input type="text" class="pos_cz_tow_two05" value="0" style="color:#f00;"/></li>';
						str +='<li class="li007"><input type="text" class="pos_cz_tow_two05" value="'+p_old_price+'" /></li>';
						str +='<li class="li008"><a href="javascript:" class="delete c_del">删除</a></li>';
						str +='</ul></div>';

					self.find('.table_con_son').append(str);
					pro_k++;
				});
				table_flash();
				change_total();
			}
		});
	});
	//项目删除
	$('.box_xm').on('click','.c_del',function(){
		$(this).closest('.table_list').remove();
		change_total();
	});

	//赠送项目的添加
	$('.box_gift_xm').on('click','.c_add',function(){
		var self=$(this).closest('.box_gift_xm');//box对象
		var d = Idialog({
			top:150,
			width:800,
			title:'添加赠送项目',
			content:$('#widget_gift_project'),
			cancel:false,
			ok:function(obj){
				var _self=obj._self;
				var has_list = self.find('.table_list');//已经存在的列
				var pro_k=has_list.length;//当前序号

				var result_list=_self.find('.result_pro li');
				$.each( result_list, function(i, pro){
					pro=$(pro);
					var p_name=pro.attr('data-name');
					var p_id=pro.attr('rel');
					var p_num=pro.attr('data-num');
					var p_price=pro.attr('data-price');
					var p_old_price=parseInt(p_num)*parseInt(p_price);
					//如果存在 则略过
					if(has_list.filter("[data-id='"+p_id+"']").length>0) return ;

					var str  ='<div class="table_list" data-id="'+p_id+'" data-dj="'+p_price+'" ><ul>';
						str +='<li class="li001">'+p_name+'（'+p_old_price+'元/'+p_num+'疗次）</li>';
						str +='<li class="li002"><input type="text" class="pos_cz_tow_two05" value="1" /></li>';
						str +='<li class="li003"><a href="javascript:" class="delete c_del">删除</a></li>';
						str +='</ul></div>';
					
					self.find('.table_con_son .table_title').after(str);
					pro_k++;
				});
				table_flash();
			}
		});
	});
	//赠送项目删除
	$('.box_gift_xm').on('click','.c_del',function(){
		$(this).closest('.table_list').remove();
		change_gift_total();
	});

	//项目、产品、卡券价格联动
	//修改数量
	$('.box_xm').on('change','.li002 input',function(){
		var table_list=$(this).closest('.table_list');
		var yj=table_list.attr('data-dj')*$(this).val();//新原价
		var yfje=yj*table_list.find('.li004 input').val()/100;//新应付金额
		table_list.find('.li003').html(yj);
		table_list.find('.li005 input').val(yfje);
		table_list.find('.li006 input').val(0);
		table_list.find('.li007 input').val(yfje);
		change_total();
	});
	//修改面折率
	$('.box_xm').on('change','.li004 input',function(){
		var table_list=$(this).closest('.table_list');
		var yfje = table_list.find('.li003').html()*$(this).val()/100;//新应付金额
		table_list.find('.li005 input').val(yfje);
		table_list.find('.li006 input').val(0);
		table_list.find('.li007 input').val(yfje);
		change_total();
	});

	//修改应付金额 改变面折率
	$('.box_xm').on('change','.li005 input',function(){
		var table_list=$(this).closest('.table_list');
		var mzl = parseInt($(this).val())/table_list.find('.li003').html()*100   ;//新面折率
		table_list.find('.li004 input').val(mzl);
		table_list.find('.li006 input').val(0);
		table_list.find('.li007 input').val($(this).val());
		change_total();
	});

	//修改欠款
	$('.box_xm').on('change','.li006 input',function(){
		var table_list=$(this).closest('.table_list');
		var yfje = parseInt(table_list.find('.li005 input').val())-parseInt($(this).val());
		table_list.find('.li007 input').val(yfje);
		change_total();
	});

	//修改实收
	$('.box_xm').on('change','.li007 input',function(){
		var table_list=$(this).closest('.table_list');
		var yfje = parseInt($(this).val())-parseInt(table_list.find('.li005 input').val());
		table_list.find('.li006 input').val(yfje);
		change_total();
	});

	//同步修改 box小计
	function change_total(){
		change_all();
	}
	//项目产品卡券价格联动 end
	
	//同步整单数据
	function change_all(){
		body_resize();//左边高度调整
	}

	//数据提交
	$(".c_submit").click(function(){
		var post_data=submit_data();
		if(post_data==false){
			return false;
		}

		$('.c_submit').html("正在提交订单...").addClass("pos_cz_zh_an_hover").removeClass("pos_cz_zh_an");

		<?php if ($model): ?>
		var url="<?php echo $this->url('editSave',array('id'=>$model->o_s->id)) ?>";			
		<?php else: ?>
		var url="<?php echo $this->url('addSave') ?>";	
		<?php endif ?>
		$.post(url, post_data,function(data){
			Idialog.tips(data.msg,2);
			if(data.code==200){
				//转到付款界面
				setTimeout(function(){to_url('<?php echo $this->url("pay");?>&id='+data.data)},3000);
			}
		}, "json");
	});

	function to_url(url){
		window.location.href=url;
	}

	//提交保存数据构造
	function submit_data(){
		var err=false;
		var data={};
		var old_money=pay_price=current_arrears=0;
		data.__hash__ = $("input[name='__hash__']").val();//表单令牌
		var is_not_null=false;//检查订单数据是否为空
		//购买项目、产品、卡券相关
		data.pro=[];
		$('.box_xm').find(".table_list").each(function(i){
			is_not_null=true;
			pro_type=1;
			old_money+=parseInt($(this).find(".li003").html());
			pay_price+=parseInt($(this).find(".li005 input").val());
			current_arrears+=parseInt($(this).find(".li006 input").val());
			data.pro.push({
				"pro_id":$(this).attr("data-id"),
				"num":$(this).find(".li002 input").val(),
				"price":$(this).find(".li003").html(),//原价
				"pay_price":$(this).find(".li005 input").val(),//应付金额
				"rebate":$(this).find(".li004 input").val(),//面折率
				"arrears":$(this).find(".li006 input").val(),//欠款
				"card_cash":$(this).find(".li007 input").val(),//实收金额
				"pro_type":pro_type,//商品类型
			});
		});
		//赠送项目、产品、卡券相关
		data.gift=[];
		$('.box_gift_xm').find(".table_list").each(function(i){
			is_not_null=true;
			pro_type=3;
			if($(this).closest('.box_gift_xm').length>0)
				var pro_type=1;
			if($(this).closest('.box_gift_cp').length>0)
				var pro_type=2;
			data.gift.push({
				"pro_id":$(this).attr("data-id"),
				"num":$(this).find(".li002 input").val(),
				"price":$(this).attr("data-dj")*$(this).find(".li002 input").val(),//原价 = 单价*数量
				"pro_type":pro_type,//商品类型
			});
		});
		//赠送现金
		data.gift_xj=[];
		$('.box_gift_xj').find("input").each(function(i){
			if($(this).val()!=''){
				is_not_null=true;
				data.gift_xj.push({
					"capital_id":$(this).attr("data-id"),
					"cash":$(this).val()
				});
			}
			
		});
		data.is_init=1;

		// //整单信息-原价
		data.price=old_money;
		// //整单信息-应付金额
		data.pay_price=pay_price;
		// //整单信息-折扣
		data.rebate=(pay_price/old_money*100).toFixed(2);
		 //欠款
		data.arrears=data.current_arrears=current_arrears;
		data.cu_id=$('.cu_info').attr("data-id");

		data.note=$('.order_note').val();

		<?php if ($tag&&$tag=='rh'): ?>
			data.rh_id='-1';
		<?php endif ?>

		if(err)
			return false; //发生验证错误 返回false
		return data;
	}


});
</script>