<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jquery.PrintArea.js"></script>

<?php
	if($model){
		$gift_capital = \OrderSaleMoney::model()->where(array('order_id'=>$model->o_s->id))->findAll();
		$gift_arr=array();
		foreach ($gift_capital as $g_c) {
			$gift_arr[$g_c['capital_id']]=$g_c['cash'];
		}
	}
?>
<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/期初订单
                </div>
                <div class="tools">
                        <button onclick="history.go(-1)" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>返回</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>订单概况
                        </div>
                        <div class="actions">
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单编号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn;?>
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-xs-5 name">账户金额：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo array_sum($gift_arr);?> 元
                            </div>
                        </div>


                        <div class="row static-info">
                            <div class="col-xs-5 name">订单状态：</div>
                            <div class="col-xs-7 value text-right">
                            	<span class="label label-warning label-sm">
                                <?php echo \OrderSale::getPayStatusForInit($model->o_s->pay_status);?>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>


        <!--商品信息-->
		<div class="pos_cz_tow">
			<div class="pos_cz_qr_02 ">客户期初信息</div>
			<div class="pos_cz_tow_two pos_cz_qr_top">
				<!--table_container-->
				<div class="table_container">
					<!--table_con-->
                    <div class="table_con table-responsive">
						<!--table_con_son-->
                        <table class="table table-bordered table-hover ">
                        	<thead>
                        	<tr>
								<?php foreach ($capital_list as $value): ?>
									<th class="pos_news_zeng"><?php echo $value['name'] ?>（元）</th>
								<?php endforeach ?>
							</tr>
							</thead>
							<tbody>
							<tr class="table_list">
									<?php foreach ($capital_list as $key=>$value): ?>
										<td class="li00<?php echo ++$key ?>">
											<input readonly="readonly"  data-id="<?php echo $value['id'] ?>" type="text" value="<?php echo $gift_arr[$value['id']] ?>" class="pos_cz_tow_two05" />
										</td>
									<?php endforeach ?>
							</tr>
							</tbody>
						</table>
						<!--table_con_son!end-->
					</div>
					<!--table_con!end-->
				</div>
				<!--table_containter!end-->
				<!--table_container-->
				<div class="table_container">
					<!--table_con-->
                    <div class="table_con table-responsive">
                        <table class="table table-bordered table-hover ">
							<thead class="pos_news_zeng">
								<tr>
									<th>购买项目</th>
									<th>数量（疗次）</th>
									<th>原价（元）</th>
									<th>面折率</th>
									<th>应付金额（元）</th>
									<th>欠款（元）</th>
									<th>实收金额（元）</th>
								</tr>
							</thead> 
							<tbody>
							<?php if ($model): ?>
								<?php foreach ($model->pros as $pro): ?>
									<?php if($pro['pro_type']!=1) continue; ?>
									<?php if($pro['buy_type']!=1) continue; ?>
									<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

									<tr data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" >
										<td><?php echo $info->name ?>（<?php echo $info->num*$info->price ?>元/<?php echo $info->num ?>疗次）</td>
										<td><?php echo $pro['num'] ?></td>
										<td><?php echo $pro['price'] ?></td>
										<td><?php echo $pro['rebate'] ?>%</td>
										<td><?php echo $pro['pay_price'] ?></td>
										<td><?php echo $pro['arrears'] ?></td>
										<td><?php echo $pro['cash'] ?></td>
									</tr>
								<?php endforeach ?>
							<?php endif ?>
							</tbody>
						</table>
						<!--table_con_son!end-->
					</div>
					<!--table_con!end-->
				</div>
				<!--table_container-->
				<div class="table_container">
					<!--table_con-->
                    <div class="table_con table-responsive">
                        <table class="table table-bordered table-hover ">
							<thead class="pos_news_zeng">
								<tr>
									<th>赠送项目</th>
									<th>数量（疗次）</th>
								</tr>
							</thead>
							<tbody>
							<?php if ($model): ?>
								<?php foreach ($model->pros as $pro): ?>
									<?php if($pro['pro_type']!=1) continue; ?>
									<?php if($pro['buy_type']!=2) continue; ?>
									<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>
									<tr data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" >
										<td><?php echo $info->name ?>（<?php echo $info->num*$info->price ?>元/<?php echo $info->num ?>疗次）</td>
										<td><?php echo $pro['num'] ?></td>
									</tr>
								<?php endforeach ?>
							<?php endif ?>
							</tbody>
						</table>
						<!--table_con_son!end-->
					</div>
					<!--table_con!end-->
				</div>
				<!--table_containter!end-->
			</div>
		</div>
		<!--商品信息!end-->

		<!--备注-->
		<div class="pos_cz_tow pos_cz_for_bz">
			<div class="pos_cz_for_bz01">备注</div>
			<div class="pos_cz_for_bz02">
				<div class="pos_cz_for_bz02_son"><?php echo $model?$model->o_s->note:"" ?></div>
			</div>
		</div>
		<!--备注!end-->





    </div>
</div>



<script type="text/javascript">

$(function(){

	$(".to_print").click(function(){
		$(".print_show").printArea();
	});

});
</script>