<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jquery.PrintArea.js"></script>
<style type="text/css">
.zszh,.xjzh{color:#0077ff;cursor: pointer;}
.pos_other{  float: left;font-size: 16px;color: #1eb488; margin-right: -86px;margin-right:30px}
</style>
<?php $hd_list = \SaleNoticeInfo::model()->getListOpt();?>
<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>期初订单>客户期初信息
	</div>
	<div class="print_show">
		<div class="jyjl_top jyjl_czda_top">
			<div class="jyjl_czda_top_l">
				<div class="jyjl_czda_top_top">期初已建立</div>
				<div class="jyjl_czda_top_two">
					订单编号：
					<span><?php echo $model->o_s->sn;?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						订单状态：<span class="spanll"><?php echo \OrderSale::getPayStatusForInit($model->o_s->pay_status);?></span>
					</span>
				</div>
			</div>
			<div class="jyjl_czda_top_r">
				<a href="javascript:" class="aysh02"><?php echo \OrderSale::getPayStatusForInit($model->o_s->pay_status);?></a>
			</div>
		</div>

		<!--khgl_shouye-->
		<?php echo $cu_info ?>
		<!--khgl_shouye!end-->

		<!--商品信息-->
		<div class="pos_cz_tow" style="box-shadow:none">
			<div class="pos_cz_qr_02 ">客户期初信息</div>
			<div class="pos_cz_tow_two pos_cz_qr_top">
				<!--table_container-->
				<div class="table_container" style="border-bottom:none;">
					<!--table_con-->
					<div class="table_con" >
						<!--table_con_son-->
						<div class="table_con_son">
							<div class="pos_sp_title ">账户余额</div>
							<div class="table_title pos_news_zeng">
								<ul>
									<?php foreach ($capital_list as $value): ?>
										<li><?php echo $value['name'] ?>（元）</li>
									<?php endforeach ?>
								</ul>
							</div>
							<?php
								if($model){
									$gift_capital = \OrderSaleMoney::model()->where(array('order_id'=>$model->o_s->id))->findAll();
									$gift_arr=array();
									foreach ($gift_capital as $g_c) {
										$gift_arr[$g_c['capital_id']]=$g_c['cash'];
									}
								}
							?>
							<div class="table_list">
								<ul>
									<?php foreach ($capital_list as $key=>$value): ?>
										<li class="li00<?php echo ++$key ?>">
											<input readonly="readonly"  data-id="<?php echo $value['id'] ?>" type="text" value="<?php echo $gift_arr[$value['id']] ?>" class="pos_cz_tow_two05" />
										</li>
									<?php endforeach ?>
								</ul>
							</div>
						</div>
						<!--table_con_son!end-->
					</div>
					<!--table_con!end-->
				</div>
				<!--table_containter!end-->
				<div style="height:15px; line-height:15px;"></div>
				<!--table_container-->
				<div class="table_container" style="border-bottom:none;">
					<!--table_con-->
					<div class="table_con">
						<!--table_con_son-->
						<div class="table_con_son">
							<div class="pos_sp_title ">购买的项目</div>
							<div class="table_title pos_news_zeng">
								<ul>
									<li style="min-width:250px">项目</li>
									<li>数量（疗次）</li>
									<li>原价（元）</li>
									<li>面折率</li>
									<li>应付金额（元）</li>
									<li>欠款（元）</li>
									<li>实收金额（元）</li>
								</ul>
							</div>
							<?php if ($model): ?>
								<?php foreach ($model->pros as $pro): ?>
									<?php if($pro['pro_type']!=1) continue; ?>
									<?php if($pro['buy_type']!=1) continue; ?>
									<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

									<div data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" class="table_list">
										<ul>
											<li class="li001"><?php echo $info->name ?>（<?php echo $info->num*$info->price ?>元/<?php echo $info->num ?>疗次）</li>
											<li class="li002"><?php echo $pro['num'] ?></li>
											<li class="li003"><?php echo $pro['price'] ?></li>
											<li class="li004"><?php echo $pro['rebate'] ?>%</li>
											<li class="li005"><?php echo $pro['pay_price'] ?></li>
											<li class="li006"><?php echo $pro['arrears'] ?></li>
											<li class="li007"><?php echo $pro['cash'] ?></li>
										</ul>
									</div>
								<?php endforeach ?>
							<?php endif ?>
						</div>
						<!--table_con_son!end-->
					</div>
					<!--table_con!end-->
				</div>
				<div style="height:15px; line-height:15px;"></div>
				<!--table_container-->
				<div class="table_container" style="border-bottom:none;">
					<!--table_con-->
					<div class="table_con">
						<!--table_con_son-->
						<div class="table_con_son">
							<div class="pos_sp_title ">赠送的项目</div>
							<div class="table_title pos_news_zeng">
								<ul>
									<li style="min-width:250px">项目</li>
									<li>数量（疗次）</li>
								</ul>
							</div>
							<?php if ($model): ?>
								<?php foreach ($model->pros as $pro): ?>
									<?php if($pro['pro_type']!=1) continue; ?>
									<?php if($pro['buy_type']!=2) continue; ?>
									<?php $info=\pos\SaleModel::model()->getProInfo($pro['pro_id'],$pro['pro_type']); ?>

									<div data-dj="<?php echo $info->price ?>" data-id="<?php echo $info->id ?>" data-zs="<?php echo $pro['money_str'] ?>" class="table_list">
										<ul>
											<li class="li001"><?php echo $info->name ?>（<?php echo $info->num*$info->price ?>元/<?php echo $info->num ?>疗次）</li>
											<li class="li002"><?php echo $pro['num'] ?></li>
										</ul>
									</div>
								<?php endforeach ?>
							<?php endif ?>
						</div>
						<!--table_con_son!end-->
					</div>
					<!--table_con!end-->
				</div>
				<!--table_containter!end-->
			</div>
		</div>
		<!--商品信息!end-->

		<!--备注-->
		<div class=" pos_cz_for_bz">
			<div class="pos_cz_qr_top_07">备注</div>
			<div class="pos_cz_for_bz02">
				<div class="pos_cz_for_bz02_son">
					<p class="pos_cz_qr_top_06"><?php echo $model?$model->o_s->note:"" ?></p>
				</div>
			</div>
		</div>
		<!--备注!end-->
	</div>
</div>
<!--content_right_con!end-->

<script type="text/javascript">

$(function(){
	//收起效果
	$(".pos_cz_tow_top_r").click(function(){
		var self=$(this);
		self.parent().next().slideToggle("fast",function(){
			if(self.hasClass("pos_cz_tow_top_rcl")){
				self.removeClass("pos_cz_tow_top_rcl");
			}else{
				self.addClass("pos_cz_tow_top_rcl");
			}
		});
	});

	$(".table_title ul li:last-child").css('min-width','110px');

	$(".to_print").click(function(){
		$(".print_show").printArea();
	});


});
</script>