<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>

<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/还款
                </div>
                <div class="tools">
                    <button class="btn btn-sm green table-group-action-submit c_submit"><i class="fa fa-check"></i>提交订单</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-money"></i>应付金额
                        </div>
                        <div class="actions"><button class="btn red">
                        <font class="money_all"><?php echo $model->o_s->pay_price; ?></font> 元</button>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn ?>
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-xs-5 name">订单状态：</div>
                            <div class="col-xs-7 value text-right">
                                <span class="label label-warning label-sm">
                                <?php 
                                    if($model){
                                        echo \OrderSale::getPayStatus($model->o_s->pay_status);
                                    }else{
                                        echo "新建";
                                    }
                                ?>
                                </span>
                            </div>
                        </div>

                    
                  
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单类型：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->orderType ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">还款订单：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo count($arrears_order_detail);?> 个
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-xs-5 name">还款时间：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->o_s->create_time ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">操作人：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->employName ?>
                            </div>
                        </div>

                        
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>

        <!--销售人员及业绩比例-->
        <?php echo $effect ?>
        <!--销售人员及业绩比例!end-->

        <div class="row" style="margin-top:20px;">
            <div class="col-md-12">
                <div class="portlet box blue-steel">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>欠款订单
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>订单成交日期</th>
                                    <th>订单号</th>
                                    <th>欠款商品名称</th>
                                    <th>欠款金额(元)</th>
                                    <th>现金账户卡扣还款(元)</th>
                                    <th>现金还款(元)</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $total=0; foreach($arrears_order_detail as $detail):?>
                                <?php
                                    $order_sale = \OrderSale::model()->findByPk($detail['order_id']);
                                    $cpm = $detail['repay_capitals']['money'];
                                ?>
                                <tr id="order_detail<?php echo $detail['id']?>" class="table_list khgl_com order_detail">
                                        <td><?php echo $detail['create_time'];?></td>
                                        <td><?php echo $order_sale->sn?></td>
                                        <td><?php echo $detail['pro_name'];?></td>
                                        <td class="arrears"><?php echo $detail['arrears']?></td>
                                        <td>
                                            <input type="hidden" name="capitals[]" value="<?php echo $detail['repay_capitals']['capital']?>">
                                            <input type="hidden" name="proInfo[]" value="<?php echo $detail['pro_id'].'|'.$detail['pro_type'].'|'.$detail['id']?>">
                                            <input value="<?php echo !empty($cpm)?$cpm:'点击选择还款账户'?>" class="add_capitals <?php echo !empty($cpm)?'pos_cz_tow_two05':'cpm'?>" datatype="<?php echo $detail['pro_id'].'|'.$detail['pro_type'].'|'.$detail['id']?>" type="text" readonly="readonly" style="cursor: pointer;"/>
                                        </td>
                                        <td><input value="<?php echo empty($detail['repay_cash'])?'':(int)$detail['repay_cash'];?>" name="cash[]" type="text" class="pos_cz_tow_two05" /></td>
                                        <td>
                                            <a class="btn default btn-xs green-stripe khca" href="<?php echo $this->url('/pos/sale/edit',array('id'=>$order_sale->id));?>">
                                                查看
                                            </a>
                                        </td>
                                </tr>
                            <?php $total+=$cpm+$detail['repay_cash'];endforeach;?>
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>  

        <!--备注-->
        <div class="pos_cz_tow pos_cz_for_bz">
            <div class="pos_cz_for_bz01">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son"><textarea rows="4"></textarea></div>
            </div>
        </div><!--备注!end-->


    </div>
</div>



<!--tjfj-->
<div class="tjfj" style="display:none;">

</div>

{__TOKEN__}

<script type="text/javascript">



    $("input[name='cash[]']").blur(function(){
        var reg = /^\+?[1-9][0-9]*$/;
        var total=0;
        if($(this).val()!=''&&!reg.test($(this).val())){
            Idialog.tips("请输入正整数",2);
            $(this).val('');
        }else{
            $("input[name='cash[]']").each(function(){
                if($(this).val()!=''){
                    total += parseInt($(this).val());
                }
            });
            $(".add_capitals").each(function(){
                if($(this).val()!=''&&reg.test($(this).val())){
                    total += parseInt($(this).val());
                }
            });
        }
        $('.money_all').html(total.toFixed(2));
    });

    $(".add_capitals").click(function(){
        var url="<?php echo $this->url('capitals_view',array('id'=>empty($model->o_s->cu_id)?$_GET['id']:$model->o_s->cu_id))?>";
        var _self = $(this);var capitals = _self.parents(".order_detail").find("input[name='capitals[]']").val();
        $.post(url,
            {'param':_self.attr('datatype'),cu_id:'<?php echo empty($model->o_s->cu_id)?$_GET['id']:$model->o_s->cu_id?>',capitals:capitals},
            function(html){
                $('.tjfj').html(html);
                var title = $("#tck_title").val();
                var d = Idialog({
                    top:150,
                    width:550,
                    title:title,
                    content:$('.tjfj'),
                    ok:function(obj){
                        var detail_id = $("#tck").val();
                        $('.tjfj').empty();
                        var data=[],cash= 0,flat=true,msg='';
                        $("input[name='add_capitals[]']").each(function(){
                            var reg = /^\+?[1-9][0-9]*$/;
                            if($(this).val()!=''&&!reg.test($(this).val())){
                                msg = '请输入正整数';
                                $(this).val('');
                                flat = false;
                                $(this).attr('style','width: 80px;border:dashed 1px #ff0000;background-color:#fff1eb;');
                                return false;
                            }else{
                                if(parseFloat($(this).val())>parseFloat($(this).attr('balance'))){
                                    msg = '卡扣金额不能大于账户余额';
                                    flat = false;
                                    $(this).attr('style','width: 80px;border:dashed 1px #ff0000;background-color:#fff1eb;');
                                    return false;
                                }
                                if(parseFloat($(this).val())>parseFloat($(this).attr('arrears'))){
                                    msg = '卡扣金额不能大于欠款金额';
                                    flat = false;
                                    $(this).attr('style','width: 80px;border:dashed 1px #ff0000;background-color:#fff1eb;');
                                    return false;
                                }
                                if($(this).val()!=''){
                                    data.push($(this).attr('capitalid')+'|'+$(this).val());
                                    cash += parseInt($(this).val());
                                }
                                $(this).attr('style','width: 80px;');
                            }
                        });
                        if(flat==false){
                            Idialog.tips(msg,2);
                            return false;
                        }
                        $('#order_detail'+detail_id).find("input[name='capitals[]']").val(data.join(','));
                        var add_capitals = $('#order_detail'+detail_id).find(".add_capitals");
                        if(cash>0){
                            add_capitals.val(cash);
                            add_capitals.attr('style','');
                            if(!add_capitals.hasClass('pos_cz_tow_two05')){
                                add_capitals.addClass('pos_cz_tow_two05').removeClass('cpm');
                            }
                        }else{
                            add_capitals.val('点击选择还款账户');
                            add_capitals.attr('style','border: 1px solid #ccc;border-radius: 2px;height: 24px;text-align: center;color: #999999;font-size: 11px;cursor: pointer;');
                            if(add_capitals.hasClass('pos_cz_tow_two05')){
                                add_capitals.removeClass('pos_cz_tow_two05')
                            }
                        }
                        var total=0;var reg = /^\+?[1-9][0-9]*$/;
                        $("input[name='cash[]']").each(function(){
                            if($(this).val()!=''){
                                total += parseInt($(this).val());
                            }

                        });
                        $(".add_capitals").each(function(){
                            if($(this).val()!=''&&reg.test($(this).val())){
                                total += parseInt($(this).val());
                            }
                        });
                        $('.money_all').html(total.toFixed(2));
                    }
                });

        });

    });

    //数据提交
    $(".c_submit").click(function(){
        var post_data=submit_data();
        if(post_data==false){
            return false;
        }
        $('.c_submit').addClass("disabled");
        <?php if ($model): ?>
            var url="<?php echo $this->url('editSave',array('id'=>$model->o_s->id)) ?>";
        <?php else: ?>
            var url="<?php echo $this->url('addSave') ?>";
        <?php endif ?>
        $.post(url, post_data,function(data){
            Idialog.tips(data.msg,2);
            if(data.code==200){
                //转到付款界面
                setTimeout(function(){to_url('<?php echo $this->url("order");?>&id='+data.data)},1000);
            }
        }, "json");
    });

    function to_url(url){
        window.location.href=url;
    }

    //提交保存数据构造
    function submit_data(){
        var data={};
        data.__hash__ = $("input[name='__hash__']").val();//表单令牌
        //业绩比例相关
        data.effect=[];
        err = false;
        $(".effect_user").each(function(i){
            data.effect.push({"e_id":$(this).val(),"e_rate":$(this).next().val()});
            if($(this).next().val()==0||$(this).next().val()==''){
                Idialog.tips("业绩不能为空",2);
                err = true;
            }
        });
        data.repay=[];
        var total= 0,_total=0;
        var price_check = true;var arrears=0;
        $(".add_capitals").attr('style','');
        $("input[name='cash[]']").attr('style','');
        $('.order_detail').each(function(i){
            arrears = $(this).find(".arrears").text();
            data.repay.push({
                "capitals":$(this).find("input[name='capitals[]']").val(),
                "proInfo":$(this).find("input[name='proInfo[]']").val(),
                "cash":$(this).find("input[name='cash[]']").val(),
                "arrears":arrears
            });
            total=0;
            if($(this).find("input[name='capitals[]']").val()!=''){
                var capitals = $(this).find("input[name='capitals[]']").val().split('|');
                total += parseInt(capitals[1]);
            }
            if($(this).find("input[name='cash[]']").val()!=''){
                total += parseInt($(this).find("input[name='cash[]']").val());
            }

            if($(this).find("input[name='capitals[]']").val()!=''||$(this).find("input[name='cash[]']").val()!=''){
                if(total>parseFloat(arrears)){
                    $(this).find(".add_capitals").attr('style','border:dashed 1px #ff0000;background-color:#fff1eb;');
                    $(this).find("input[name='cash[]']").attr('style','border:dashed 1px #ff0000;background-color:#fff1eb;');
                    price_check = false;
                }
            }
            _total += total;
        });
        if(_total==0){
            Idialog.tips("还款金额不能为空",2);
            err = true;
        }
        //整单信息-原价
        data.price = _total;
        //整单信息-应付金额
        data.pay_price = _total;
        //整单信息-原价
        data.rebate = 100;

        data.type = 0;

        data.cu_id=$('.cu_info').attr("data-id");

        data.note=$('.pos_cz_for_bz02_son textarea').val();
        if(price_check==false){
            Idialog.tips("还款金额不能大于欠款金额！",2);
            return false;
        }
        if(err)
            return false; //发生验证错误 返回false
        return data;
    }

</script>


