<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>

<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/还款确认
                </div>
                <div class="tools">
                    <button class="btn btn-sm green table-group-action-submit now_pay"><i class="fa fa-mail-forward"></i>立即付款</button>
                    <button onclick="to_url('<?php echo $this->url("edit",array('id'=>$model->o_s->id)) ?>')" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>修改</button>
                    <button id="cancelOrder" class="btn btn-sm red table-group-action-submit"><i class="fa fa-eraser"></i>废除</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-money"></i>应付金额
                        </div>
                        <div class="actions"><button class="btn red">
                        <font class="money_all"><?php echo $model->o_s->pay_price; ?></font> 元</button>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn ?>
                            </div>
                        </div>

                    
                  
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单类型：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->orderType ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">还款订单：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo count($order_sale_detail)?> 个
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-xs-5 name">还款时间：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->o_s->create_time ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">操作人：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->employName ?>
                            </div>
                        </div>

                        
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>

        <!--销售人员及业绩比例-->
        <?php echo $effect ?>
        <!--销售人员及业绩比例!end-->

        <div class="row" style="margin-top:20px;">
            <div class="col-md-12">
                <div class="portlet box blue-steel">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>欠款订单
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>订单成交日期</th>
                                    <th>订单号</th>
                                    <th>欠款商品名称</th>
                                    <th>欠款金额(元)</th>
                                    <th>现金账户卡扣还款(元)</th>
                                    <th>现金还款(元)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($order_sale_detail as $detail):?>
                                <tr class="table_list">
                                        <td class="li001"><?php echo $model->o_s->create_time?></td>
                                        <td class="li002"><?php echo $model->o_s->sn?></td>
                                        <td class="li003"><?php echo $detail['pro_name']?></td>
                                        <td class="li004"><?php echo $detail['arrears']?></td>
                                        <td class="li005"><?php echo $detail['repay']['card']?$detail['repay']['card']:0?></td>
                                        <td class="li006"><?php echo $detail['repay']['cash']?$detail['repay']['cash']:0?></td>
                                </tr>
                            <?php endforeach;?>
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>  

        <!--备注-->
        <div class="pos_cz_tow pos_cz_for_bz">
            <div class="pos_cz_for_bz01">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son"><?php echo $model->o_s->note?></div>
            </div>
        </div><!--备注!end-->


    </div>
</div>



{__TOKEN__}

<script type="text/javascript">

    

    function to_url(url){
        window.location.href=url;
    }

    //提交保存数据构造
    function submit_data(){
        var data={};
        data.__hash__ = $("input[name='__hash__']").val();//表单令牌
        // 订单id
        data.order_id = '<?php echo $_GET['id']?>';

        //return false; 发生验证错误 返回false
        return data;
    }

    //数据提交
    $(".now_pay").click(function(){
        var post_data = submit_data();
        $(".now_pay").addClass("disabled");
        setTimeout(function(){to_url('<?php echo $this->url("pay");?>&id=<?php echo $_GET['id']?>')},2000);
    });

    $("#cancelOrder").click(function(){
        if(confirm("您确定要废弃此订单吗？")){
            var data={};
            data.__hash__ = $("input[name='__hash__']").val();//表单令牌
            $.post("<?php echo $this->url('cancel',array('id'=>$model->o_s->id)) ?>",data,function(data){
                Idialog.tips(data.msg,2);
                if(data.code==200){
                    setTimeout(function(){to_url('<?php echo $this->url("index");?>')},2000);
                }
            }, "json");
        }
    });

</script>


