<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<?php 
    //付款配置
    $config=\CompanyInfo::getConfig('payee');
?>

<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>订单还款/付款
                </div>
                <div class="tools">
                        <button onclick="to_url('<?php echo $this->url("edit",array("id"=>$model->o_s->id)) ?>')" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>订单详情</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-money"></i>应付金额
                        </div>
                        <div class="actions"><button class="btn red"><?php echo $model->o_s->pay_price; ?> 元</button></div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn ?>
                            </div>
                        </div>

                        
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单类型：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->orderType ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">还款订单：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo count($order_sale_detail)?> 个
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-xs-5 name">制单时间：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->o_s->create_time ?>
                            </div>
                        </div>
                        <div class="row static-info">
                            <div class="col-xs-5 name">操作人：</div>
                            <div class="col-xs-7 value text-right">
                                <?php echo $model->employName ?>
                            </div>
                        </div>

                        
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-12">
                <div class="portlet box blue-steel">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>商品付款信息
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-responsive">
                        <table class="table table-bordered table-hover" id="pay">
                            <thead>
                                <tr>
                                    <th style="min-width:150px;">付款商品</th>
                                    <th>还款金额(元)</th>
                                    <th class='xjkk_h'>现金账户卡扣还款(元)</th>
                                    <th class='qk_h'>现金还款(元)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($order_sale_detail as $detail):?>
                                    <?php
                                        $pay_price = ($detail['repay']['card']+$detail['repay']['cash'])?$detail['repay']['card']+$detail['repay']['cash']:0;
                                        $cash_total += $detail['repay']['cash'];
                                    ?>
                                    <tr class="table_list">
                                            <td title="<?php echo $detail['pro_name']?>"><?php echo $detail['pro_name']?></td>
                                            <td class="yfje" title="<?php echo $pay_price;?>"><?php echo sprintf("%.2f",$pay_price);?></td>
                                            <td><?php echo $detail['repay']['card']?$detail['repay']['card']:0?></td>
                                            <td pro-type="1" class="qk_b" title=""><?php echo $detail['repay']['cash']?$detail['repay']['cash']:0?></td>
                                    </tr>
                                <?php endforeach;?>
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>  


        <!--pos_cz_fk_th-->
        <div class="pos_cz_fk_th">
            <div class="pos_cz_fk_th_top pos_fk_title">
                <div class="pos_cz_fk_th_01">应付现金:<span class="pos_cz_fk_top_03 all_xj"><?php echo $cash_total?sprintf("%.2f",$cash_total):0?></span>元</div>
                本次应付现金总计为<span class="pos_cz_fk_top_03 all_yf"><?php echo $cash_total?sprintf("%.2f",$cash_total):0?></span>元，请在相应的支付方式中输入金额：
            </div>
            <div class="pos_cz_fk_th_two ">
                <ul style="padding:0px;">
                <?php if ($config['money']['open']=='true'): ?>
                    <li >
                        <span class="pos_cz_fk_th_two_02">现金</span>
                        <input type="text" name="cash" value="0" class="pos_cz_fk_th_two_03 pos_cz_fk_th_two_chan" />
                    </li>
                <?php endif ?>
                <?php if ($config['post']['open']=='true'): ?>
                    <li >
                        <span class="pos_cz_fk_th_two_02">刷卡</span>
                        <input type="text" name="cash_pos" value="0" class="pos_cz_fk_th_two_03" />
                        <?php echo $this->dropDownList('pos_type',$config['post']['has'],'',array('class'=>'pos_cz_fk_th_two_06')) ?>
                    </li>
                <?php endif ?>
                <?php if ($config['bank']['open']=='true'): ?>
                    <li >
                        <span class="pos_cz_fk_th_two_02">转账</span>
                        <input type="text" name="cash_tra" value="0" class="pos_cz_fk_th_two_03" />
                        <?php echo $this->dropDownList('tra_type',$config['bank']['has'],'',array('class'=>'pos_cz_fk_th_two_06')) ?>
                    </li>
                <?php endif ?>
                <?php if ($config['other']['open']=='true'): ?>
                    <li >
                        <span class="pos_cz_fk_th_two_02">其他</span>
                        <input type="text" name="cash_other" value="0" class="pos_cz_fk_th_two_03" />
                        <?php echo $this->dropDownList('other_type',$config['other']['has'],'',array('class'=>'pos_cz_fk_th_two_06')) ?>
                    </li>
                <?php endif ?>
                </ul>
            </div>
            <div class="pos_cz_fk_th_top pos_fk_title">
                <span class="js_all_qk" style="color: red;display: none;">注意：请确保订单商品和折扣正确，各账户抵扣和现金付款信息无误。一旦进行付款，meihui系统将确保您的业绩及时记录到系统中，且无法对订单进行修改哦。</span>
            </div>
            <div class="pos_cz_fk_th_th">
                <a href="###" class="pos_cz_fk_th_th_a_ok c_submit">立即支付</a>
            </div>
        </div>
        <!--pos_cz_fk_th-->    

        <?php foreach($order_sale_detail as $item):?>
            <input type="hidden" name="cz[]" value="<?php echo $item['price'];?>" capitalid="<?php echo $item['pro_id'];?>" detailid="<?php echo $item['id'];?>">
        <?php endforeach;?>
        <input type="hidden" name="cu_id" value="<?php echo $model->o_s->cu_id;?>">            


    </div>
</div>


{__TOKEN__}

<script type="text/javascript">

    function to_url(url){
        window.location.href=url;
    }

    //提交保存数据构造
    function submit_data(){
        var data={};
        data.__hash__ = $("input[name='__hash__']").val();//表单令牌
        data.order_id = '<?php echo $_GET['id']?>';
        //现钞
        data.cash = $.isNumeric( $("input[name='cash']").val() )?parseFloat($("input[name='cash']").val()):0;
        //pos现金
        data.cash_pos = $.isNumeric( $("input[name='cash_pos']").val() )?parseFloat($("input[name='cash_pos']").val()):0;
        data.pos_type = $("select[name=pos_type]").val();
        if(data.cash_pos>0 && data.pos_type==""){
            Idialog.tips("POS类型未选择！",2);
            return false;
        }
        //转账现金
        data.cash_tra = $.isNumeric( $("input[name='cash_tra']").val() )?parseFloat($("input[name='cash_tra']").val()):0;
        data.tra_type = $("select[name=tra_type]").val();
        if(data.cash_tra>0 && data.tra_type==""){
            Idialog.tips("转账类型未选择！",2);
            return false;
        }
        //其他现金
        data.cash_other = $.isNumeric( $("input[name='cash_other']").val() )?parseFloat($("input[name='cash_other']").val()):0;
        data.other_type = $("select[name=other_type]").val();
        if(data.cash_other>0 && data.other_type==""){
            Idialog.tips("其他类型未选择！",2);
            return false;
        }
        //现金合计计算
        if(data.cash+data.cash_pos+data.cash_tra+data.cash_other != parseFloat($(".all_xj").html())){
            Idialog.tips("现金支付错误！",2);
            return false;
        }
        //客户id
        data.cu_id = $("input[name=cu_id]").val();

  

        //return false; 发生验证错误 返回false
        return data;
    }

    //数据提交
    $(".c_submit").click(function(){
        var post_data = submit_data();
        if(post_data==false)
            return;
        $(".c_submit").addClass("disabled");
        $.post("<?php echo $this->url('paySave',array('id'=>$model->o_s->id)) ?>", post_data,function(data){
            Idialog.tips(data.msg,2);
            if(data.code==200){
                //转到付款界面
                setTimeout(function(){to_url('<?php echo $this->url("index");?>')},2000);
            }
        }, "json");
    });

</script>


