
<style>
    .add_capitals.cpm{
        border: 1px solid #ccc;border-radius: 2px;height: 24px;text-align: center;color: #999999;font-size: 11px;cursor: pointer;
    }
    .cash_view,.capital_view,.capitals_view{
        border-radius: 2px;
        color: #1bab70;
        font-size: 14px;
        font-weight: bold;
        height: 24px;
        text-align: center;
        width: 70px;
    }
    .zszh,.xjzh{color:#0077ff;cursor: pointer;}
    .pos_other{  float: left;font-size: 16px;color: #1eb488; margin-right: -86px;margin-right:30px}
</style>
<!--content_right_con-->
<div class="content_right_con">
    <div class="content_right_con_top">
        <!--<div class="fjgl_top_r">
          <a href="javascript:" class="khgl_02 fpkhn">分配客户</a><a href="javascript:" class="fjgl_top_r_01">筛选</a><a href="javascript:" class="fjgl_top_r_02 tjfjz">添加客户</a>
        </div>-->
        <div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>POS开单><span>还款</span>
    </div>

    <!--khgl_shouye-->
    <?php echo $cu_info ?>
    <!--khgl_shouye!end-->
    <!--销售人员及业绩比例-->
    <?php echo $effect ?>
    <!--销售人员及业绩比例!end-->

    <!--欠款订单-->
    <div class="pos_cz_tow">
        <div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>还款订单</div>
        <div class="pos_cz_tow_two">
            <!--table_container-->
            <div class="table_container">
                <!--table_con-->
                <div class="table_con" style="border:none; margin-right:0px;">
                    <!--table_con_son-->
                    <div class="table_con_son">
                        <div class="table_title khgl_com">
                            <ul>
                                <li style="min-width: 150px;">订单成交日期</li>
                                <li>订单号</li>
                                <li>欠款商品名称</li>
                                <li>（还款前）欠款金额(元)</li>
                                <li style="min-width: 120px;">现金账户卡扣还款(元)</li>
                                <li>现金还款(元)</li>
                                <li style="min-width: 200px;">（还款后）欠款金额(元)</li>
                            </ul>
                        </div>
                        <?php $total=0; foreach($arrears_order_detail as $detail):?>
                            <?php
                                $order_sale = \OrderSale::model()->findByPk($detail['order_id']);
                                $cpm = $detail['repay_capitals']['money'];
                            ?>
                            <div id="order_detail<?php echo $detail['id']?>" class="table_list khgl_com order_detail">
                                <ul>
                                    <li class="li001"><?php echo $detail['create_time'];?></li>
                                    <li class="li002"><?php echo $order_sale->sn?></li>
                                    <li class="li003"><?php echo $detail['pro_name'];?></li>
                                    <li class="li004"><?php echo $detail['arrears']?></li>
                                    <li class="li005">
                                        <input type="hidden" name="capitals[]" value="<?php echo $detail['repay_capitals']['capital']?>">
                                        <input type="hidden" name="proInfo[]" value="<?php echo $detail['pro_id'].'|'.$detail['pro_type'].'|'.$detail['id']?>">
                                        <span class="capital_view add_capitals" style="cursor: pointer;" datatype="<?php echo $detail['pro_id'].'|'.$detail['pro_type'].'|'.$detail['id']?>"><?php echo (int)$cpm;?></span>
                                    </li>
                                    <li class="li006 "><span class="cash_view"><?php echo (int)$detail['repay_cash'];?></span></li>
                                    <li class="li004"><?php echo $detail['after_arrears']?></li>
                                </ul>
                            </div>
                        <?php $total+=$cpm+$detail['repay_cash'];endforeach;?>
                    </div><!--table_con_son!end-->
                </div><!--table_con!end-->
            </div>
            <!--table_containter!end-->
            <div class="pos_cz_tow_two_two">
                <span class="pos_cz_tow_two04 pos_gm_02">应付总金额：<em><?php echo sprintf("%.2f",$total);?></em>&nbsp;元</span>
                <span class="pos_gm_01">还款订单<span class="pos_gm_03"><?php echo count($arrears_order_detail);?></span>个</span>
                <span class="pos_gm_01">还款总额：<span class="pos_gm_04">￥<?php echo sprintf("%.2f",$total);?></span></span>
            </div>
        </div>
    </div><!--欠款订单!end-->

    <!--备注-->
    <div class="pos_cz_tow pos_cz_for_bz">
        <div class="pos_cz_for_bz01">备注</div>
        <div class="pos_cz_for_bz02">
            <div class="pos_cz_for_bz02_son"><textarea rows="4" readonly="readonly"><?php echo $model->o_s->note?></textarea></div>
        </div>
    </div><!--备注!end-->

    <div class="pos_cz_tow pos_cz_for_bz">
        <div class="pos_other" >现金支付：￥<?php echo $model->o_s->cash ?></div>
        <div class="pos_other" >现金账户卡扣：￥<?php echo $model->o_s->cash_card ?></div>
        <div class="pos_other" >POS刷卡：￥<?php echo $model->o_s->cash_pos ?></div>
        <div class="pos_other" >银行转账：￥<?php echo $model->o_s->cash_tra ?></div>
        <div class="pos_other" >其他付款：￥<?php echo $model->o_s->cash_other ?></div>
    </div>
</div>
<!--content_right_con!end-->

<!--tjfj-->
<div class="tjfj" style="top:100px; display:none;">
    <div class="tjfj_top">
        <span class="fjgb">x</span>
        <div class="tjfj_ti">赠送账户抵扣</div>
        <input type="hidden" id="tck" value="">
    </div>
    <div class="tjfj_two pos_gm_th">
        <div class="pos_gm_th_01">
            <div class="pos_hk_02">
                欠款：<div class="pos_hk_01">￥1500.00</div>
            </div>
            <div class="tjfj_pna">购买《肽美白》1疗次，原价：1000 元</div>
        </div>
        <!--table_container-->
        <div class="table_container" style="margin-bottom:20px;">
            <!--table_con-->
            <div class="table_con pos_cz_qr_top_04" style="margin-right:0px;">
                <!--table_con_son-->
                <div class="table_con_son">
                    <div class="table_title">
                        <ul>
                            <li>现金账户</li>
                            <li>账户余额（元）</li>
                            <li>还款金额（元）</li>
                        </ul>
                    </div>
                    <?php foreach($cu_capitals as $cu_capital):?>
                        <div class="table_list">
                            <ul>
                                <li class="li001"><?php echo $cu_capital['name'];?></li>
                                <li class="li002"><?php echo $cu_capital['balance'];?></li>
                                <li class="li003">
                                    <span class="capitals_view" id="add_capitals<?php echo $cu_capital['id']?>">0</span>
                                </li>
                            </ul>
                        </div>
                    <?php endforeach;?>
                </div><!--table_con_son!end-->
            </div><!--table_con!end-->
        </div>
        <!--table_containter!end-->
        <div class="tjfj_two_an">
            <a href="javascript:" class="fjgb">取消</a>
        </div>

    </div>

</div>

{__TOKEN__}

<script type="text/javascript">

    //收起效果
    $(".pos_cz_tow_top_r").click(function(){
        var self=$(this);
        self.parent().next().slideToggle("fast",function(){
            //alert("Animation Done.");
            if(self.hasClass("pos_cz_tow_top_rcl")){
                self.removeClass("pos_cz_tow_top_rcl");
            }else{
                self.addClass("pos_cz_tow_top_rcl");
            }
        });
    });

    $(".add_capitals").click(function(){
        var url="<?php echo $this->url('capitals_view',array('id'=>empty($model->o_s->cu_id)?$_GET['id']:$model->o_s->cu_id))?>";
        var _self = $(this);var capitals = _self.parents(".order_detail").find("input[name='capitals[]']").val();
        $.post(url,
            {'param':_self.attr('datatype'),cu_id:'<?php echo empty($model->o_s->cu_id)?$_GET['id']:$model->o_s->cu_id?>',capitals:capitals},
            function(html){
                $('.tjfj').html(html);
                var title = $("#tck_title").val();
                $("input[name='add_capitals[]']").attr('readonly','readonly');
                var arrears = _self.parent().prev().text();
                $(".pro_arrears").text('￥'+arrears);
                var d = Idialog({
                    top:150,
                    width:550,
                    title:title,
                    content:$('.tjfj'),
                    close:function(e){
                        $(".idialog").remove();
                    },
                    cancel:function(e){
                        $(".idialog").remove();
                    },
                    ok:function(e){
                        $(".idialog").remove();
                    }
                });
                table_flash();

            });

    });

</script>


