<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jquery.PrintArea.js"></script>
<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>

<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-pencil"></i>POS开单/还款详情
                </div>
                <div class="tools">
                    <button class="btn btn-sm yellow table-group-action-submit to_print"><i class="fa fa-check"></i>打印订单</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>订单概况
                        </div>
                        <div class="actions">
                            <button class="btn red">交易成功</button> 
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn ?>
                            </div>
                        </div>

                        <div class="scroller" style="height:140px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">
                            <?php if($model->o_s->pay_status==1): ?>

                                <?php foreach ($model->getXJList() as $key => $value): ?>
                                    <?php if($value>0): ?>
                                    <div class="row static-info">
                                        <div class="col-xs-5 name"><?php echo $key ?>卡扣：</div>
                                        <div class="col-xs-7 value text-right">
                                            <?php echo $value ?> 元
                                        </div>
                                    </div>
                                    <?php endif; ?>
                                <?php endforeach ?>

                                <div class="row static-info">
                                    <div class="col-xs-5 name">实收现金：</div>
                                    <div class="col-xs-7 value text-right">
                                        <font color="yellow"><?php echo $model->o_s->cash+$model->o_s->cash_pos+$model->o_s->cash_tra+$model->o_s->cash_other ?></font> 元
                                        
                                    </div>
                                </div>
                                <?php if($model->o_s->cash>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">现金支付：</div>
                                    <div class="col-xs-7 value text-right">
                                        <?php echo $model->o_s->cash ?> 元
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if($model->o_s->cash_pos>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">POS刷卡：</div>
                                    <div class="col-xs-7 value text-right">
                                        <?php echo $model->o_s->cash_pos ?> 元
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if($model->o_s->cash_tra>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">银行转账：</div>
                                    <div class="col-xs-7 value text-right">
                                        <?php echo $model->o_s->cash_tra ?> 元
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if($model->o_s->cash_other>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">其他方式支付：</div>
                                    <div class="col-xs-7 value text-right"><?php echo $model->o_s->cash_other ?> 元</div>
                                </div>
                                <?php endif; ?>
                            <?php endif; ?>

                            <div class="row static-info">
                                <div class="col-xs-5 name">订单类型：</div>
                                <div class="col-xs-7 value text-right">
                                    <?php echo $model->orderType ?>
                                </div>
                            </div>
                            <div class="row static-info">
                                <div class="col-xs-5 name">还款订单：</div>
                                <div class="col-xs-7 value text-right">
                                    <?php echo count($order_sale_detail)?> 个
                                </div>
                            </div>

                            <div class="row static-info">
                                <div class="col-xs-5 name">还款时间：</div>
                                <div class="col-xs-7 value text-right">
                                    <?php echo $model->o_s->create_time ?>
                                </div>
                            </div>
                            <div class="row static-info">
                                <div class="col-xs-5 name">操作人：</div>
                                <div class="col-xs-7 value text-right">
                                    <?php echo $model->employName ?>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>

        <!--销售人员及业绩比例-->
        <?php echo $effect ?>
        <!--销售人员及业绩比例!end-->

        <div class="row" style="margin-top:20px;">
            <div class="col-md-12">
                <div class="portlet box blue-steel">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>欠款订单还款
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                <th>订单成交日期</th>
                                <th>订单号</th>
                                <th>欠款商品名称</th>
                                <th>(还款前)欠款金额(元)</th>
                                <th>现金账户卡扣还款(元)</th>
                                <th>现金还款(元)</th>
                                <th>(还款后)欠款金额(元)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $total=0; foreach($arrears_order_detail as $detail):?>
                                    <?php
                                        $order_sale = \OrderSale::model()->findByPk($detail['order_id']);
                                        $cpm = $detail['repay_capitals']['money'];
                                    ?>
                                    <tr id="order_detail<?php echo $detail['id']?>" class="table_list khgl_com order_detail">
                                       
                                            <td class="li001"><?php echo $detail['create_time'];?></td>
                                            <td class="li002"><?php echo $order_sale->sn?></td>
                                            <td class="li003"><?php echo $detail['pro_name'];?></td>
                                            <td class="li004"><?php echo $detail['arrears']?></td>
                                            <td class="li005">
                                                <input type="hidden" name="capitals[]" value="<?php echo $detail['repay_capitals']['capital']?>">
                                                <input type="hidden" name="proInfo[]" value="<?php echo $detail['pro_id'].'|'.$detail['pro_type'].'|'.$detail['id']?>">
                                                <span class="capital_view add_capitals" style="cursor: pointer;" datatype="<?php echo $detail['pro_id'].'|'.$detail['pro_type'].'|'.$detail['id']?>"><?php echo (int)$cpm;?></span>
                                            </td>
                                            <td class="li006 "><span class="cash_view"><?php echo (int)$detail['repay_cash'];?></span></td>
                                            <td class="li004"><?php echo $detail['after_arrears']?></td>
                                       
                                    </tr>
                                <?php $total+=$cpm+$detail['repay_cash'];endforeach;?>
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>  

        <!--备注-->
        <div class="pos_cz_tow pos_cz_for_bz">
            <div class="pos_cz_for_bz01">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son"><?php echo $model->o_s->note?></div>
            </div>
        </div><!--备注!end-->


    </div>
</div>

<!--tjfj-->
<div class="tjfj" style="top:100px; display:none;">
    

</div>

{__TOKEN__}

<script type="text/javascript">

    $(".to_print").click(function(){
        $(".print_show").printArea();
    });

    $(".add_capitals").click(function(){
        var url="<?php echo $this->url('capitals_view',array('id'=>empty($model->o_s->cu_id)?$_GET['id']:$model->o_s->cu_id))?>";
        var _self = $(this);var capitals = _self.parents(".order_detail").find("input[name='capitals[]']").val();
        $.post(url,
            {'param':_self.attr('datatype'),cu_id:'<?php echo empty($model->o_s->cu_id)?$_GET['id']:$model->o_s->cu_id?>',capitals:capitals},
            function(html){
                $('.tjfj').html(html);
                var title = $("#tck_title").val();
                $("input[name='add_capitals[]']").attr('readonly','readonly');
                var arrears = _self.parent().prev().text();
                $(".pro_arrears").text('￥'+arrears);
                var d = Idialog({
                    top:150,
                    width:550,
                    title:title,
                    content:$('.tjfj'),
                    close:function(e){
                        $(".idialog").remove();
                    },
                    cancel:function(e){
                        $(".idialog").remove();
                    },
                    ok:function(e){
                        $(".idialog").remove();
                    }
                });
                

            });

    });

</script>


