<style>
    .search_cu_id_list{
        /*  position: absolute;*/
        z-index: 9999;
        background: white;
        max-height: 200px;
        background:  #E8E8E8;
        width: 128px;
        min-width: 100px;
        min-height: 0px;
        overflow-y: auto;
        margin-left: 96px;
        margin-top: -15px;
    }
    .search_cu_id_list li{
        padding:0;
        padding-left: 5px;
        min-height: 0px;
        line-height: 20px;
        border-left: 1px solid green;
    }
    .search_cu_id_list_li_hover{
        background-color: #A9E1FC;
        cursor: pointer;
    }
    .gs_c{height: 28px;text-align: left;display: inline-block;font-size: 14px;}
    .gs_c input{width: auto;}
</style>

<div class="tjfj_two pos_gm_th">
    <div class="yyb_top">
        <label class="yylabel">客户归属：</label>
        <div class="gs_c">
            <input type="radio" value="md" checked="checked" name="gs"/>门店 
            <input type="radio" value="all"  name="gs"/>全连锁 
        </div>
        
        <br/>
        <label class="yylabel">实操房间：</label>
        <select name="room_id" class="yyb_top01" style="color: #000;">
            <option value="<?php echo $room['id']?>"><?php echo $room['name']?></option>
        </select>
        <?php $room_status = \ReBook::model()->getStatus();?>
        <select name="room_status" class="yyb_top02">
            <?php foreach($room_status as $key=>$_room_status):?>
                <option <?php echo $key==$status?'selected="selected"':'';?> value="<?php echo $key;?>"><?php echo $_room_status;?></option>
            <?php endforeach;?>
        </select>
    </div>
    <div class="room-bed">
        <?php foreach($beds as $bed):?>
            <?php if(array_key_exists($bed['id'],$rebooks)):?>
                <div class="yyb_two">
                    <div class="yyb_two_posi"><?php echo $bed['name']?></div>
                    <input type="hidden" name="bed_id"  value="<?php echo $bed['id']?>">
                    <input type="hidden" name="rebook_id"  value="<?php echo $rebooks[$bed['id']]['id']?>">
                    <p class="pyyff">
                        <label class="yylabel">客户：</label>
                        <input type="hidden" name="cu_id"  value="<?php echo $rebooks[$bed['id']]['cu_id'];?>">
                        <input style="color: #000000;" type="text" class="yyb_top01 search_cu_input" placeholder="请输入客户姓名" value="<?php echo \CustomerInfo::model()->findByPk($rebooks[$bed['id']]['cu_id'])->name;?>" />
                        <span class="cancel_book">取约</span>
                    </p>
                    <ul class="search_cu_id_list" style="display: none;"></ul>
                    <p class="pyyff">
                        <label class="yylabel">实操时长：</label>
                        <select name="start_time" class="yyb_top03" style="color: #000000;">
                            <?php foreach($times as $key=>$time):?>
                                <?php if($key==$time_id):?>
                                    <option <?php echo date('H:i',$rebooks[$bed['id']]['starttime'])==$time?'selected="selected"':''?> value="<?php echo $key;?>"><?php echo $time;?></option>
                                <?php endif;?>
                            <?php endforeach;?>
                        </select>至
                        <select name="end_time" class="yyb_top03" style="margin-left:5px;color: #000000;">
                            <?php foreach($times as $key=>$time):?>
                                <?php if($key>$time_id):?>
                                    <option <?php echo date('H:i',$rebooks[$bed['id']]['endtime'])==$time?'selected="selected"':''?> value="<?php echo $key;?>"><?php echo $time;?></option>
                                <?php endif;?>
                            <?php endforeach;?>
                        </select>
                        <span class="cancel_book re_times" style="margin-left: 0;"><?php echo count(explode(',',$rebooks[$bed['id']]['times']))/2;?>小时</span>
                    </p>
                    <p class="pyyff" style=" margin-bottom:0px;">
                        <label class="yylabel">实操美容师：</label>
                        <select name="operators" class="yyb_top01" style="color: #000000;">
                            <option value="">--请选择美容师--</option>
                            <?php foreach($mrs as $mrs_id=>$mrs_name):?>
                                <?php if(in_array($mrs_id,$mrs_zy)&&!in_array($mrs_id,explode(',',$rebooks[$bed['id']]['operator_ids']))):?>
                                    <option style="color:red;" value=""><?php echo $mrs_name;?>(占用)</option>
                                <?php elseif(in_array($mrs_id,explode(',',$rebooks[$bed['id']]['operator_ids']))):?>
                                    <option selected="selected" value="<?php echo $mrs_id;?>"><?php echo $mrs_name;?></option>
                                <?php else:?>
                                    <option value="<?php echo $mrs_id;?>"><?php echo $mrs_name;?></option>
                                <?php endif;?>
                            <?php endforeach;?>
                        </select>
                    </p>
                </div>
            <?php else:?>
                <div class="yyb_two">
                    <div class="yyb_two_posi"><?php echo $bed['name']?></div>
                    <input type="hidden" name="bed_id"  value="<?php echo $bed['id']?>">
                    <input type="hidden" name="rebook_id"  value="">
                    <p class="pyyff">
                        <label class="yylabel">客户：</label>
                        <input type="hidden" name="cu_id"  value="">
                        <input style="color: #000000;" type="text" class="yyb_top01 search_cu_input" placeholder="请输入客户姓名" />
<!--                        <span class="cancel_book">取约</span>-->
                    </p>
                    <ul class="search_cu_id_list" style="display: none;"></ul>
                    <p class="pyyff">
                        <label class="yylabel">实操时长：</label>
                        <select name="start_time" class="yyb_top03" style="color: #000000;">
                            <?php foreach($times as $key=>$time):?>
                                <?php if($key==$time_id):?>
                                    <option value="<?php echo $key;?>"><?php echo $time;?></option>
                                <?php endif;?>
                            <?php endforeach;?>
                        </select>至
                        <select name="end_time" class="yyb_top03" style="margin-left:5px;color: #000000;">
                            <?php foreach($times as $key=>$time):?>
                                <?php if($key>$time_id):?>
                                    <option value="<?php echo $key;?>"><?php echo $time;?></option>
                                <?php endif;?>
                            <?php endforeach;?>
                        </select>
                        <span class="cancel_book re_times" style="margin-left: 0;">0.5小时</span>
                    </p>
                    <p class="pyyff" style=" margin-bottom:0px;">
                        <label class="yylabel">实操美容师：</label>
                        <select name="operators" class="yyb_top01" style="color: #000000;">
                            <option value="">--请选择美容师--</option>
                            <?php foreach($mrs as $mrs_id=>$mrs_name):?>
                                <?php if(in_array($mrs_id,$mrs_zy)):?>
                                    <option style="color:red;" value=""><?php echo $mrs_name;?>(占用)</option>
                                <?php else:?>
                                    <option value="<?php echo $mrs_id;?>"><?php echo $mrs_name;?></option>
                                <?php endif;?>

                            <?php endforeach;?>
                        </select>
                    </p>
                </div>
            <?php endif;?>
        <?php endforeach;?>
    </div>
</div>


<script type="text/javascript">
    //客户模糊搜索
    $(function(){
        $(".search_cu_input").keyup(function(event){    //为搜索框加键盘事件监听
            var _input = $(this);
            var dept_id = $("#dept_id").val();
            if($("input[name='gs']:checked").val()=="all")
                dept_id='all';
            var _now_input_val=$.trim(_input.val());//过滤头尾空格
            if(_now_input_val!=''){ //过滤空置 和 重复提交
                if((event.keyCode!=38)&&(event.keyCode!=40)&&(event.keyCode!=13)){    //判断键盘事件，抛弃上下键跟回车键
                    $.ajax({
                        type: "POST",
                        url: "<?php echo $this->url('/customer/index/searchCustomerList');?>",
                        /*data: "name="+_now_input_val+"<?php if(count($param)>0)echo '&',implode('&', $param) ;?>"+"&dept_id="+dept_id,*/
                        data: {name:_now_input_val,dept:dept_id},
                        dataType: "json",
                        success: function(json){
                            _input.parent().next().empty();
                            _input.parent().next().show();
                            if(json.code==200){
                                $.each( json.data, function(i, v){
                                    if(i==0&&_now_input_val==v.name){
                                        _input.prev().val(v.id);
                                    }
                                    _input.parent().next().append("<li rel='"+v.id+"'>"+v.name+"</li>");
                                });
                                _input.parent().next().show();
                                _input.parent().next().find('li').click( function () {
                                    _input.val($(this).html());
                                    _input.prev().val($(this).attr('rel'));
                                    _input.parent().next().empty();
                                    _input.prev().trigger("change");
                                }).mouseover(function(){
                                    $(this).addClass('search_cu_id_list_li_hover');
                                }).mouseout(function(){
                                    $(this).removeClass('search_cu_id_list_li_hover');
                                });
                            }
                        }
                    });
                }
                //下
                if(event.keyCode==40){
                    var c_li = _input.parent().next().find('.search_cu_id_list_li_hover').first();
                    var li_first = _input.parent().next().find('li:first');
                    if(li_first.length==1){
                        if(c_li.length==0){
                            //无选中状态
                            li_first.trigger("mouseover")
                        }else{
                            //有选中状态
                            if(c_li.next().length==1){
                                c_li.trigger("mouseout")
                                c_li.next().trigger("mouseover")
                            }
                            return false;
                        }
                    }
                    return false;
                }
                //上
                if(event.keyCode==38){
                    var c_li = _input.parent().next().find('.search_cu_id_list_li_hover').first();
                    var li_first = _input.parent().next().find('li:first');
                    if(c_li.length==1&&c_li.prev().length==1){
                        c_li.trigger("mouseout")
                        c_li.prev().trigger("mouseover")
                    }
                    return false;
                }
                //回车
                if(event.keyCode==13){
                    var c_li = _input.parent().next().find('.search_cu_id_list_li_hover').first();
                    if(c_li.length==1){
                        c_li.trigger("click")
                    }
                    _input.parent().next().hide();
                    return false;
                }
            }else{
                $(".search_cu_id_list").text('');
            }
        });

        $(".search_cu_id_list").click(function(){
            $(this).hide();
        });

        $("select[name=start_time],select[name=end_time]").change(function(){
            var start_time,end_time;
            if($(this).attr('name')=='start_time'){
                start_time = parseInt($(this).val());
                end_time = parseInt($("select[name=end_time]").val());
            }else{
                start_time = parseInt($("select[name=start_time]").val());
                end_time = parseInt($(this).val());
            }
            if(start_time>=end_time){
                $(this).parent().find("select[name=start_time]").attr('style','color: #000000;border:dashed 1px #ff0000;background-color:#fff1eb;');
                $(this).parent().find("select[name=end_time]").attr('style','color: #000000;border:dashed 1px #ff0000;background-color:#fff1eb;');
                Idialog.tips('结束时间必须大于开始时间！',2);
            }else{
                $(this).parent().find("select[name=start_time]").attr('style','color: #000000;');
                $(this).parent().find("select[name=end_time]").attr('style','color: #000000;');
                var dept_id = $("#dept_id").val();
                $.post('<?php echo $this->url("getOperators")?>',{date:$("#demo").val(),start_time:start_time,dept_id:dept_id}, function(data) {
                    $(this).parent().find("select[name=operators]").html(data);
                });
                $(this).parent().find(".re_times").html((end_time-start_time)*0.5+'小时');
            }
        });

        $(".cancel_book").click(function(){
            var rebook_id = $(this).parent().parent().find("input[name=rebook_id]").val();
            $.post('<?php echo $this->url("cancel")?>',{rebook_id:rebook_id}, function(data) {
                $(".idialog").remove();
                if(data=='true'){
                    Idialog.tips('取消预约成功！',2);
                    setTimeout(function(){location.reload();},1000);
                }else{
                    Idialog.tips('取消预约失败！',2);
                }
            });
        });

    });



</script>
