<div class="portlet portlet-table  ">
<div class="portlet-body">
<div  class="dataTables_wrapper no-footer">
<div class="table-scrollable">
<table class="table table-striped table-bordered ">
<thead>
<tr role="row">
<th >序号</th>
<th >客户</th>
<th >项目</th>
<th >实操美疗师</th>
<th >是否耗卡</th>
<th >到店时间</th>
</tr>
</thead>
<tbody>

<?php if(!empty($list)):?>
    <?php foreach($list as $key=>$_list):?>
        
            <tr>
                <td ><?php echo $key+1;?></td>
                <td ><?php echo $_list['cu_name'];?></td>
                <td class="li001"><?php echo \ReBook::model()->getPraProNames($_list['id']);?></td>
                <td class="li004"><?php echo implode(';',\ReBook::model()->getPraOperName($_list['id']));?></td>
                <td class="li005"><?php echo $_list['status']==1?'耗卡':'未耗卡';?></td>
                <td class="li005"><?php echo $_list['last_time'];?></td>
            </tr>
       
    <?php endforeach;?>
<?php else:?>
        <tr class="odd">
            <td colspan=7 >No data available in table</td>
        </tr>
<?php endif;?>

</tbody>
</table>
</div></div></div></div>
