<div class="portlet portlet-table  ">
<div class="portlet-body">
<div  class="dataTables_wrapper no-footer">
<div class="table-scrollable">
<table class="table table-striped table-bordered ">
<thead>
<tr role="row">
<th >序号</th>
<th >房间</th>
<th >客户</th>
<th >实操时长</th>
<th >预约时间</th>
<th >实操美疗师</th>
<th >取约操作时间</th>
</tr>
</thead>
<tbody>

<?php if(!empty($list)):?>
    <?php foreach($list as $key=>$_list):?>
        
            <tr>
                <td ><?php echo $key+1;?></td>
                <td ><?php echo $_list['room_name'];?></td>
                <td ><?php echo $_list['cu_name'];?></td>
                <?php $rebook_times = explode(',',$_list['times']);$count_times = count($rebook_times);?>
                <td ><?php echo $count_times/2;?>个小时</td>
                <td ><?php echo $times[$rebook_times[0]].'~'.$times[$rebook_times[$count_times-1]+1];?></td>
                <td ><?php echo implode(';',\ReBook::model()->getOperatorNames($_list['operator_ids']));?></td>
                <td ><?php echo $_list['update_time'];?></td>
            </tr>
       
    <?php endforeach;?>
<?php else:?>
        <tr class="odd">
            <td colspan=7 >No data available in table</td>
        </tr>
<?php endif;?>

</tbody>
</table>
</div></div></div></div>
