<?php 
$mes_list = \SmsMessage::getInList();
$mes_not_read = \SmsMessage::getNotNum();
?>
<div class="head">
	<div class="head_left"><img src="<?php echo $this->basePath('public');?>/images/bu_101.png" /></div>
	<?php echo CompanyInfo::getVersion() ?>
	<div class="head_right">
		<ul>
			<li class="head_right_01">
				<div class="head_right_02"><img src="<?php echo $this->basePath('public');?>/images/bu_105.jpg" /></div>
				<div class="head_right_04">
					<?php echo \Ivy::app()->user->netname ?><p style="color:#999;font-size:12px;"><?php echo \Ivy::app()->user->user_name ?></p>
				</div>
				<div class="head_right_03"><img src="<?php echo $this->basePath('public');?>/images/bu_06.jpg" /></div>
				<div class="plat_user_main">
					<div class="plat_user_main_son">
						<div class="plat_user_main_ico"></div>
						<ul>
							<li><a href="#">我的资料</a></li>
							<li class="to_cpassword"><a href="javascript:;">修改密码</a></li>
							<li><a href="<?php echo $this->url('index/logout'); ?>">退出登录</a></li>
							<li class="action_about"><a href="javascript:;">关于平台</a></li>
					 	</ul>
					</div>
				</div>
			</li>
			
			<li style="position:relative;zoom:1;display: none;" class="zwxx">
				<div class="zwxglgtp">50</div>
				<img class="zwxglgtp_t"  src="<?php echo $this->basePath('public');?>/images/bu_103.png" />
			</li>


			<li style=" position:relative; zoom:1;" class="zwxx">
				<div class="zwxglgtp"><?php echo $mes_not_read ?></div>
				<a href="<?php echo $this->url('sms/message/list') ?>"><img src="<?php echo $this->basePath('public');?>/images/bu_104.png" class="zwxglgtp_t" /></a>
				 
				<div class="plat_user_mainxx">
					<div class="plat_user_mainxx_son">
						<div class="plat_user_mainxx_ico"></div>
						<ul>
						<?php if ($mes_not_read>0): ?>
							<li class="diss">你有<?php echo $mes_not_read ?>条信息未查看！请尽快查看</li>
						<?php endif ?>
							
							<?php foreach ($mes_list as $value): ?>
							<li rel="<?php echo $value['id'];?>" class="zwkyhgh plat_sms">
								<div class="left"></div>
								<div class="right"><p><?php echo $value['title'] ?></p><p class="rqp"><?php echo date("Y-m-d H:i",$value['create_time']) ?></p></div>
							</li>
							<?php endforeach; ?>
						</ul>
						<?php if ($mes_not_read>3): ?>
							<div class="more"><a href="<?php echo $this->url('sms/message/list') ?>">查看更多>></a></div>
						<?php endif ?>
					</div>
				</div>
			</li>


			<?php if (\Ivy::app()->user->position_id==1): ?>
			<?php $show_position = \Ivy::app()->user->getState('show_position');?>
				<li rel='<?php echo $show_position ?>' style="position:relative;zoom:1;line-height:60px;color:#DDD;font-size:12px;" class=" change_position">
					<?php if ($show_position==1): ?>
						<div>切换到管理员</div>
					<?php else: ?>
						<div >切换到总经理</div>
					<?php endif ?>
				</li>
			<?php endif; ?>


		</ul>
	</div>
</div>

<div class="change_password none" title="修改密码">
	<div class="tjfj_two">

		<form method="post" action="" class="change_password_form" autocomplete="off">
		<div class="list">
			<label>输入原始密码：</label>
			<div style="margin-left: 100px;">

				<input  datatype="*" tabindex=1 name="opassword" type="text" class="gysgl_07" placeholder="原始密码" value='' autocomplete="off"/>
			</div>
		</div>
		<div class="list">
			<label>输入新密码：</label>
			<div style="margin-left: 100px;">
			<input class="js_none" type='text' display='none' style="width: 0px;position: absolute;top: 9999px;" />
			<!-- 去浏览器自动填充用 -->
				<input datatype="*" name="npassword" tabindex=2 type="password" class="gysgl_07" placeholder="新密码" value='' autocomplete="off"/>
			</div>
		</div>
		<div class="list">
			<label>输入验证码：</label>
			<div style="margin-left: 100px;">
				<div class="login_list">
					<input datatype="*" name="verifyCode" tabindex=3 type="text" class="input_login" placeholder="请输入验证码" style="width:80px; float:left;margin-right:10px;" />
						<span class="login_img">
							<img src="<?php echo $this->url('index/verify'); ?>" width="100" height="30" />
						</span> 
						<span style="font-size: 12px; line-height: 26px;">看不清<a href="javascript:changeVerify();" class="blue">换一张</a></span>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		
		</form>
	</div>
</div>
<div class="about_html none" title="关于平台">
<?php $about=parse_ini_file(__PROTECTED__.DIRECTORY_SEPARATOR.'beauty.ini');?>
	<div class="tjfj_two">
		<div class="list">
			<label>平台名称：</label>
			<label style="width: auto;"><?php echo $about['product_name'];?></label>
		</div>
		<div style="clear:both"></div>
		<div class="list">
			<label>平台版本：</label>
			<label style="width: auto;"><?php echo $about['version_number'];?></label>
		</div>
		<div style="clear:both"></div>
		<div class="list">
			<label>发布日期：</label>
			<label style="width: auto;"><?php echo $about['release_date'];?></label>
		</div>
		<div style="clear:both"></div>
		<div class="list">
			<label>版权所有：</label>
			<label style="width: auto;"><?php echo $about['copyright'];?></label>
		</div>
		<div style="clear:both"></div>
		<div class="list">
			<label>电子邮箱：</label>
			<label style="width: auto;"><?php echo $about['email'];?></label>
		</div>
		<div style="clear:both"></div>
		<div class="list">
			<label>联系电话：</label>
			<label style="width: auto;"><?php echo $about['tel'];?></label>
		</div>
		<div style="clear:both"></div>
	</div>
</div>
<script type="text/javascript">
//刷新验证码
function changeVerify() {
	var timestamp=new Date().getTime();
	var url = "<?php echo $this->url('index/verify'); ?>";
	url += '&timestamp=' + timestamp;
	$('.login_img').children('img').attr('src', url);
}

$(function(){
	$(".to_cpassword").click(function(){
		var d = Idialog({
			top:120,
			width:450,
			title:'修改密码',
			content:$('.change_password'),
			ok:function(obj){
				var err=false;
				//obj._self.find('form').submit();
				var o_pw=obj._self.find("input[name='opassword']").val();
				var n_pw=obj._self.find("input[name='npassword']").val();
				var v_code=obj._self.find("input[name='verifyCode']").val();
				if(o_pw==""){
					Idialog.tips("原始密码不能为空！");
					return false;
				}
				if(n_pw==""){
					Idialog.tips("新密码不能为空！");
					return false;
				}
				if(v_code==""){
					Idialog.tips("验证码不能为空！");
					return false;
				}
				$.ajax({
					type: "POST",
					url: "<?php echo $this->url('index/cpassword');?>",
					data: {old_pw: o_pw, new_pw: n_pw,v_code: v_code},
					async: false,
					dataType: "json",
					success: function(json){
						if(json.code==200){
							Idialog.tips("修改成功！");
						}else{
							Idialog.tips(json.msg);
							err=true;
						}
					}
				});
				return !err;
			},
		});
	});
	$('.action_about').click(function(event) {
		var d = Idialog({
			top:120,
			width:450,
			title:'关于平台',
			content:$('.about_html'),
			cancel:false,
		});
	});
	$('.plat_sms').click(function(event) {
		var id = $(this).attr('rel');
		var url = '<?php echo $this->url('sms/message/view')?>&id='+id;
		to_url(url);
	});

	// 身份切换
	$('.change_position').click(function(){
		to_url('<?php echo $this->url("boss/index/change")?>');
	});
});
</script>

