<link href="<?php echo $this->basePath('public');?>/css/oldAdmin.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_style.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_v5.3.2_min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/PCASClass.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/cropbox-min.js"></script>
<style type="text/css">
.tjfj_two .mdgl_06{padding:0}
</style>
<script src="http://api.map.baidu.com/api?v=1.4"></script>

<div class="row"> 
	<div class="col-md-12">
		<div class="portlet no_mb">
	        <div class="portlet-title">
	            <div class="actions btn-set">
	            	<a href="javascript:;" class="btn default yellow-stripe s_add"><i class="fa fa-plus"></i>新增门店</a>
					<a href="javascript:;" class="btn default blue-stripe stop_store"><i class="fa fa-mail-forward"></i>已停用门店</a>
				</div>
	        </div>
	    </div>
	</div>

    <div class="col-md-12">
        <div class="portlet box blue-steel">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i>门店列表
                </div>
            </div>
            <div class="portlet-body">
	            <div class="table-responsive">
					<table class="table table-bordered table-hover" >
					<thead>
						<tr>
							<th>可用门店名称</th><th>门店地址</th><th>状态</th><th>操作</th>
						</tr>
					</thead>
					<tbody>
					<?php if ($list): ?>
	                    <?php foreach ($list as $store): ?>
	                        <tr class="table_list" rel="<?php echo $store['id'];?>">
	                                <td><?php echo $store['dept_name'] ?></td>
	                                <td><?php echo $store['address'] ?></td>
	                                <td><?php echo $store['status']==1?"启用":"<fone style=\"color:red\">停用</font>" ?></td>
	                                <td class="xmlb_02">
										<a rel="<?php echo $store['id'] ?>" href="javascript:" class="btn default btn-xs red-stripe change" >停用</a>
										<a href="javascript:" class="btn default btn-xs blue-stripe edit">修改</a>
									</td>
	                        </tr>
	                    <?php endforeach ?>
	                <?php endif ?>
						
					</tbody>
					</table>
	            </div><!--table_con!end-->
            </div>

        </div>


	</div>
</div>	                


<?php if(!empty($_GET['yd'])):?>
<div class="zhezhao">
	<div class="zhezhao_center">
		<span>第一步</span>
		<!--<a class="zhezhao_center_back" href="<?php /*echo $this->url('/admin/admin/index');*/?>">返回首页</a>-->
		<a class="zhezhao_center_next" href="<?php echo $this->url('/admin/employ/index',array('yd'=>1));?>">进入下一步</a>
	</div>
</div>
<?php endif;?>

<!--tjfj-->


<div id="stop_list" style="display:none;">
<!--  模版引擎扩展 -->
<?php echo $this->datagrid(array(
	'id'=>'stop-list',
	'dataProvider'=>array('list'=>$stop_list),
	'search'=>$is_store?false:true,
	'columns'=>array(
		array(
			'header' => '门店名称',
			'name' => 'dept_name',
		),
		array(
			'header' => '地址',
			'name' => 'address',
		),
		array(
			'header' => '操作',
			'rel'=>'id',
			'template'=>'<a href="javascript:;" class="btn default btn-xs green-stripe delete">恢复</a>'
		),
	),
));?>
</div>

<script type="text/javascript">
	<?php if(!empty($_GET['yd'])):?>
		$("body").css("padding-bottom","100px");
		$(".content_left").hide();
		$(".content_right_son").css('margin-left','20px');
	<?php endif;?>

	function validate(classname){
		var nf = classname.Validform({
			tiptype:3,
		});

		nf.addRule([
		{
			ele:".new_inputxt:eq(0)",
			datatype:"*",
			nullmsg:"请输入门店名称！"
		},
		{
			ele:".new_inputxt:eq(1)",
			datatype:"*",
			nullmsg:"请输入房间数量！"
		}
		]);
	}

	//已停用门店
	$(document).on('click','.stop_store',function(){
		var d = Idialog({
				top:150,
				width:600,
				title:'列表',
				content:$('#stop_list'),
				init:function(e){
					e.find("table").css('min-width','100%');
				},
				cancel:false
			});
	});


	//添加门店
	$(document).on('click','.s_add',function(){
		var max_store_num = <?php echo $company->max_store_num ?>;
		var store_num = <?php echo count($list) ?>;
		if(store_num<max_store_num){
		}else{
			var d = Idialog({
				top:150,
				width:500,
				title:'警告',
				content:"您最多可创建"+max_store_num+"家门店，超过"+max_store_num+"家门店请向平台管理员申请新增门店。",
				cancel:false
			});
			return;
		}
		var yd = '<?php echo $_GET['yd'];?>';
		var thisobj = $(this);
		$.get("<?php echo $this->url('edit') ?>", { id: 0 },function(html){
			var d = Idialog({
				top:5,
				width:600,
				title:'新建门店',
				content:html,
				ok:function(obj){
					obj._self.find('form').submit();
					return false;
				},
				init:function(self){
					self.find("form").attr("class","newform");
					self.find(".inputxt").attr("class","new_inputxt");

					validate($('.newform'));
				},
			});
			$("input[name=yd]").val(yd);
		});

		
	});
	
	//停用恢复
	$(document).on('click','.delete',function(){
		var id = $(this).parent().attr('rel');

		var max_store_num = <?php echo $company->max_store_num ?>;
		var store_num = <?php echo count($list) ?>;
		if(store_num<max_store_num){
		}else{
			var d = Idialog({
				top:100,
				width:500,
				title:'警告',
				content:"您最多可创建"+max_store_num+"家门店，超过"+max_store_num+"家门店请向平台管理员申请新增门店。",
				cancel:false
			});
			return;
		}

		$.get("<?php echo $this->url('change') ?>", { id: id },function(html){
			location.reload();
		});

		
	});
	
	$(document).on('click','.change',function(){
		var obj = $(this).parent().parent();
		var id = obj.attr('rel');
		var thisobj = $(this);
		$.get("<?php echo $this->url('change') ?>", { id: id },function(html){
			location.reload();
		});
	});
	
	$(document).on('click','.edit',function(){
		var obj = $(this).parent().parent();
		var id = obj.attr('rel'),yd = '<?php echo $_GET['yd'];?>';
		var thisobj = $(this);
		$.get("<?php echo $this->url('edit') ?>", { id: id },function(html){
			var d = Idialog({
				top:5,
				width:600,
				title:'编辑门店',
				content:html,
				ok:function(obj){
					obj._self.find('form').submit();
					return false;
				},
				init:function(self){
					self.find("form").attr("class","newform");
					self.find(".inputxt").attr("class","new_inputxt");

					validate($('.newform'));
				},
			});
			$("input[name=yd]").val(yd);
		});
	});
	

</script>