<?php 
?>
<link href="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_style.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/Validform/Validform_v5.3.2_min.js"></script>
<style type="text/css">
  .action_tab{
    padding: 0 10px;
    margin-top: 10px;
    overflow: hidden;
    min-height: 250px;
  }
</style>
<script type="text/javascript">
$(function(){
	$('.edit_xm').Validform({
		tiptype:3,
		ignoreHidden:true,
		datatype:{
			"phone":function(gets,obj,curform,regxp){
				/*参数gets是获取到的表单元素值，
				  obj为当前表单元素，
				  curform为当前验证的表单，
				  regxp为内置的一些正则表达式的引用。*/

				var reg1=regxp["m"],
					reg2=regxp["*"],
					mobile=$("#phone");
					tel=$("#tel");

				if(reg1.test(mobile.val())){return true;}
				if(reg2.test(tel.val())){return true;}


				return false;
			}
		}
	});

	$("#cardid").blur(function(){
		if($(this).val()!=''){
			checkCardId($(this));
		}
	});

	$(".edit_xm").submit(function(){
		var flat = checkCardId($("#cardid"));
		if(flat==true){
			return true;
		}else{
			return false;
		}

	});

	function checkCardId(_self){
		var card_id = _self.val(),flat=false;
		var cu_id = '<?php echo empty($_GET['id'])?'':$_GET['id'];?>';
		$.ajax({
			url: "<?php echo $this->url("checkCard")?>",
			dataType: "json",
			type: "POST",
			data: {card_id:card_id,cu_id:cu_id},
			async: false,
			success:function(data){
				if(data.type=='false'){
					if(!_self.hasClass('Validform_error')){
						_self.addClass('Validform_error');
					}
					if(!_self.next().next().hasClass('Validform_wrong')){
						_self.next().next().addClass('Validform_wrong');
					}
					_self.next().next().text(data.msg);
					flat = false;
				}else{
					_self.removeClass('Validform_error');
					_self.next().next().removeClass('Validform_wrong').text('');
					flat = true;

				}
			}
		});
		return flat;
	}
})
</script>
<!--content_right_con-->
		<div class="content_right_con">
		  <div class="content_right_con_top">
				<div class="khgl_01"><img src="<?php echo $this->basePath('public') ?>/images/kh_01.png" /></div>客户管理>
				<?php if($model->id):?>
				<span><?php echo $model->name; ?></span>><span class="khgl_da_01">个人档案</span>
				<?php else: ?>
				<span>新建客户</span>
				<?php endif; ?> 
		  </div>
		  
		  <div class="khgl_da_top">
				<ul>
					<li class="khgl_da_03">个人档案</li>
					<!-- <li>身体档案</li> -->
				</ul>
			
		  </div>
		  
		  <!--个人档案-->
		<div class="khgl_da_con khgl_da_con_toggl">
			<div class="fjgl_two">
				<div class="fjgl_two_son" style="color:#666666; background:none; line-height:24px; padding-left:20px;">
					<span class="khgl_da_02">建档日期：<?php $model->create_time=$model->create_time?$model->create_time:date('Y-m-d H:i:s'); echo date('Y-m-d H:i',strtotime($model->create_time));?></span>
					<?php if($model->id):?>
					<span class="khgl_da_02">入会日期：<?php echo date('Y',$model->enrollment_time)>2000?date('Y-m-d H:i',$model->enrollment_time):"";?></span>
					<?php endif; ?>
				</div>
			</div>
			<form class="edit_xm" method="post" action="<?php echo $this->url('edit',array('id'=>$_GET['id'])) ?>">
			<div class="khgl_da_two">
				<div class="action_tab">
					<div class="khgl_da_two_top"><!-- <a href="#">填写更多资料</a> -->基础信息</div>
					<div class="khgl_da_two_two">
							<ul>
								<li>
									<label>姓名</label>
									<div style="margin-left: 100px;">
										<input type="text" name="name" datatype="*" value="<?php echo $model->name; ?>" nullmsg="客户姓名不能为空！"/>
										<span class="khgl_da_two_two_01">必填</span>
										<!-- <div class="khgl_da_two_two_03">客户姓名不能为空</div> -->
									</div>
								</li>
								<li>
									<label>性别</label>
									<div style="margin-left: 100px;">
										<?php  echo $this->checkBox('sex',\CustomerInfo::getSex(),is_string($model->sex)?$model->sex:'男',array('class'=>'input')); ?>
									</div>
								</li>
								<li>
									<label>生日</label>
									<div style="margin-left: 100px;">
										<input type="text"  id="birthday" name="birthday" value="<?php echo $model->birthday?date('Y-m-d',$model->birthday):'' ?>" />
										<div class="khgl_da_two_two_02">阴历生日：<span id="span_zh_birthday"></span>
											<input name="zh_birthday" id="zh_birthday" type="hidden" value="<?php echo $model->zh_birthday?date('Y-m-d',$model->zh_birthday):'' ?>" />
										</div>
									</div>
								</li>
								<li>
								<label>属相</label>
								<div style="margin-left: 100px;"><?php echo $this->dropDownList('zh_zodiac',\CustomerInfo::getZhZodiac(),$model->zh_zodiac); ?></div>
								</li>
								<li><label>星座</label><div style="margin-left: 100px;"><?php echo $this->dropDownList('zodiak',\CustomerInfo::getZodiak(),$model->zodiak); ?></div></li>
								<li><label>身份证号</label><div style="margin-left: 100px;"><input type="text" name="idcard" value="<?php echo $model->idcard; ?>" /></div></li>
								<li><label>职业类型</label><div style="margin-left: 100px;"><?php echo $this->dropDownList('profession_type',\CustomerInfo::getProfessionType(),$model->profession_type); ?></div></li>
								<li><label>婚姻状况</label><div style="margin-left: 100px;"><?php echo $this->dropDownList('marriage',\CustomerInfo::getMarriage(),$model->marriage); ?></div></li>
							</ul>
					</div>
				</div>
				<div class="action_tab">
					<div class="khgl_da_two_top">联系方式</div>
					<div class="khgl_da_two_two">
							<ul>
								<li><label>手机号码</label>
								<div style="margin-left: 100px;">
								<input name="phone" id="phone" value="<?php echo $model->phone; ?>" type="text" nullmsg="手机固话必填一个" datatype="phone"/>
								<span class="khgl_da_two_two_01">手机固话必填一个</span>
									<!-- <div class="khgl_da_two_two_03"><a href="javascript:">继续添加</a><div>请填写正确的手机号码</div></div> -->
								</div>
								</li>
								<li><label>固话号码</label>
								<div style="margin-left: 100px;">
								<input name="tel" id="tel" value="<?php echo $model->tel; ?>" type="text" nullmsg="手机固话必填一个"  datatype="phone"/>
								<span class="khgl_da_two_two_01">手机固话必填一个</span>
									<!-- <div class="khgl_da_two_two_03"><a href="javascript:">继续添加</a><div>请填写正确的手机号码</div></div> -->
								</div>
								</li>
								<li><label>备用联系号码</label>
								<div style="margin-left: 100px;">
								<input name="back_phone" id="back_phone" value="<?php echo $model->back_phone; ?>" type="text"/>
								
									<!-- <div class="khgl_da_two_two_03"><a href="javascript:">继续添加</a><div>请填写正确的手机号码</div></div> -->
								</div>
								</li>
								<li><label>微信号</label><div style="margin-left: 100px;"><input name="weixin" id="weixin" value="<?php echo $model->weixin; ?>" type="text" /></div></li>
								<li><label>家庭住址</label><div style="margin-left: 100px;"><textarea name="address" id="address"  rows="3" style=" width:200px;"><?php echo $model->address; ?></textarea></div></li>
								<li><label>QQ</label><div style="margin-left: 100px;"><input name="qq" id="qq" value="<?php echo $model->qq; ?>" type="text" /></div></li>
							</ul>
					</div>
				</div>
				<div class="action_tab">
					<div class="khgl_da_two_top">会所相关</div>
					<div class="khgl_da_two_two">
						<ul>
							<li><label>档案归属</label><div style="margin-left: 100px;">
							<?php echo $this->dropDownList('store_id',\EmployDept::getList(),$model->store_id?$model->store_id:\Ivy::app()->user->dept_id,array('datatype'=>'*',)); ?>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                           <li><label>客户来源</label><div style="margin-left: 100px;">
							<?php echo $this->dropDownList('come_type',\CustomerInfo::getComeType(),$model->come_type?$model->come_type:1,array('datatype'=>'*',)); ?>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                           <li><label>专属顾问</label><div style="margin-left: 100px;">
									
							<?php echo $this->dropDownList('counselor_id',\EmployUser::getList(" AND position_id=6 "),$model->counselor_id,array('datatype'=>'*',)); ?>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                           <li><label>专属美疗师</label><div style="margin-left: 100px;">
							<?php echo $this->dropDownList('operator_id',\EmployUser::getList(" AND position_id=7 "),$model->operator_id,array('datatype'=>'*',)); ?>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                           <li><label>客户卡级</label><div style="margin-left: 100px;">
							<?php echo $this->dropDownList('membership_id',\ConfigMembership::getList(),$model->membership_id,array('datatype'=>'*',)); ?>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                           <li><label>客户类型</label><div style="margin-left: 100px;">
							<?php echo $this->dropDownList('cu_type',\CustomerInfo::getCuType(),$model->cu_type,array('datatype'=>'*',)); ?>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                           <li><label>会员卡号</label><div style="margin-left: 100px;">
                           	<input type="text" name="cardid" id="cardid" value="<?php echo $model->cardid; ?>" datatype="*"/>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                           <li><label>会员状态</label><div style="margin-left: 100px;">
                           	<?php echo $this->dropDownList('status',\CustomerInfo::getStatus(),is_array($model->status)?1:$model->status,array('datatype'=>'*',)); ?>
                           	<span class="khgl_da_two_two_01">必填</span></div></li>
                        </ul>
                    
                    </div>
                </div>
                <div class="khgl_da_two_th_01"> <input name="tj" title="提交保存" type="image" src="<?php echo $this->basePath('public') ?>/images/kh_an_010.png" /></div>
             </div>
             </form>
          </div><!--个人档案-->
          
         

          
        </div>
        <!--content_right_con!end-->
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/laydate/laydate.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath("public"); ?>/js/calendar.js"></script>

<script>
//取生肖, 参数必须是四位的年
function getshengxiao(yyyy){ 
	var arr=['猴','鸡','狗','猪','鼠','牛','虎','兔','龙','蛇','马','羊']; 
	return /^\d{4}$/.test(yyyy)?arr[yyyy%12]:null 
} 
 
// 根据生日的月份和日期，计算星座。 
function getAstro(month,day){ 
	var s="摩羯水瓶双鱼牡羊金牛双子巨蟹狮子处女天秤天蝎射手摩羯"; 
	var arr=[20,19,21,21,21,22,23,23,23,23,22,22]; 
	return s.substr(month*2-(day<arr[month-1]?2:0),2); 
}
;!function(){
laydate({
	elem: '#birthday',
	choose: function(dates){ //选择好日期的回调
			dates=dates.split('-')
		 	var lunar = calendar.solar2lunar(dates[0],dates[1],dates[2]);
		 	if (lunar.lMonth<10) {lunar.lMonth='0'+lunar.lMonth};
		 	if (lunar.lDay<10) {lunar.lDay='0'+lunar.lDay};
			$('select[name="zh_zodiac"]').val(getshengxiao(lunar.lYear));
			$('select[name="zodiak"]').val(getAstro(dates[1],dates[2])+'座');
			var zh_birthday=lunar.lYear+'-'+lunar.lMonth+'-'+lunar.lDay;
			$('#span_zh_birthday').html(zh_birthday);
			$('#zh_birthday').val(zh_birthday);
	}
})
}();

$('.action_tab').mouseout(function(event) {
	$('.khgl_da_two_th').removeClass('khgl_da_two_th');
}).mouseover(function(event) {
	$('.khgl_da_two_th').removeClass('khgl_da_two_th');
	$(this).addClass('khgl_da_two_th');
});;
</script>