<?php $cu_avatar=$model->getAvatar($model->id);?>
<link href="<?php echo $this->basePath('public/M');?>/admin/pages/css/profile.css" rel="stylesheet" type="text/css"/>

<div class="modal fade" id="edit-avatar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title">编辑头像</h4>
    </div>
    <div class="modal-body">
        <!-- 头像裁剪 -->
        <div class="avatar_box" style="display:block;">
        <div class="imageBox" style="height:300px;width:300px;">
        <div class="thumbBox"></div>
        <div class="spinner" style="display: none">Loading...</div>
        </div>
        <div class="cropped"></div>
        <div class="action">
        <input type="file" id="file" style="float:left; width: 150px">
        <!--<input type="button" id="btnSave" value="保持" style="float: right">-->
        <input type="button" id="btnCrop" value="裁剪 " style="float: right; height:20px; line-height:20px; margin-left:5px; text-align:center;">
        <input type="button" id="btnZoomIn" value="+  " style="float: right; height:20px; line-height:20px; margin-left:5px; text-align:center;">
        <input type="button" id="btnZoomOut" value="-  " style="float: right; height:20px; line-height:20px; margin-left:5px; text-align:center;">
        </div>
        </div>
        <!-- 头像裁剪end -->
    </div>
    <div class="modal-footer">
        <button type="button" class="btn blue" id="btnSave">确定</button>
        <button type="button" class="btn default" data-dismiss="modal">取消</button>
    </div>
</div>


<div class="row profile">
    <div class="col-md-12">
        <?php if($model->cart_init==0):?>
            <div class="note note-danger">
            <span>新用户需要建立期初数据</span>
            <a href="<?php echo $this->url('pos/init/add',array('id'=>$model->id));?>" class=" tooltips btn-fit-height btn yellow">新建期初</a>
            </div>
        <?php endif;?>
        

        <div class="row">
            <div class="col-md-3">
                <ul class="list-unstyled profile-nav ">
                    <li>
                        <img src="<?php echo $cu_avatar;?>" class="img-responsive img-avatar" alt=""/>
                        <a  class="profile-edit avatar" data-toggle="modal" href="#edit-avatar">修改</a>
                    </li>
                    <li>   
                        <a href="javascript:;">
                            <?php echo $model->name; ?>
                            <span class="label label-danger"><?php echo mb_substr($model->cu_type,0,1,'utf-8');?></span>
                            <span class="label label-success"><?php echo $model->getSmallStatus($model->status); ?></span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                            卡号：<?php echo $model->cardid;?>
                            <span class="profile-tip bg-red"><?php echo $model->lname; ?></span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                        会员来源<span class="profile-tip"><?php echo $model->getComeType($model->come_type); ?></span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                        档案归属<span class="profile-tip"><?php echo $model->dept_name; ?></span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                        最近到店<span class="profile-tip"><?php echo $model->last_time?date('Y-m-d H:i',$model->last_time):""; ?></span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;">
                        <span class="label label-info">顾</span><?php echo $model->cnetname ?>
                        &nbsp;&nbsp;&nbsp;
                        <span class="label label-danger">美</span><?php echo $model->onetname ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('edit',array('id'=>$id)) ?>">个人档案
                        <span class="label label-info profile-tip">GO</span>
                        </a>
                    </li>
                    <li>
                        <a class="action_qr" target="qr" href="<?php echo $this->url('qr',array('id'=>$model->id))?>">二维码
                        <span class="label label-info profile-tip">GO</span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <div class="portlet solid red-sunglo">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cogs"></i>储值账户
                                    </div>
                                    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
                                    <div class="actions">
                                        <a href="<?php echo $this->url('zhdt',array('id'=>$model->id)) ?>" class="btn purple btn-sm">更多</a>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="row static-info">
                                        <div class="col-xs-5 name">欠款：</div>
                                        <div class="col-xs-7 value text-right">
                                             <?php echo $model->arrears; ?><span class="label label-info label-sm"></span> 元
                                        </div>
                                    </div>

                                    <div class="scroller" style="height:130px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">
                                        <?php $CustomerCapital=\CustomerCapital::model()->getListByUser($model->id);
                                        foreach ((array)$CustomerCapital as $key => $value): ?>
                                        <div class="row static-info">
                                            <div class="col-xs-5 name"><?php echo $value['name'] ?><div class="help" explain="<?php echo $value['note']?$value['note']:'无'; ?>"></div></div>
                                            <div class="col-xs-7 value text-right"><?php echo $value['balance']?$value['balance']:'0.00' ?>元</div>
                                        </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-12">
                            <div class="portlet yellow-crusta solid">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cogs"></i>积分账户
                                    </div>
                                    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
                                    <div class="actions">
                                        <a href="<?php echo $this->url('score',array('id'=>$id)) ?>" class="btn yellow btn-sm">更多</a>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="row static-info">
                                        <div class="col-xs-5 name">可用积分：</div>
                                        <div class="col-xs-7 value text-right"><?php echo $model->score; ?></div>
                                    </div>
                                    <div class="row static-info">
                                        <div class="col-xs-5 name">已使用积分：</div>
                                        <div class="col-xs-7 value text-right"><?php echo (int)\CustomerScoreLog::getSumByUser($model->id)->sum_score; ?></div>
                                    </div>
                                    <div class="scroller" style="height:100px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">

                                        <?php $CustomerScoreLog=\CustomerScoreLog::getListByUser($model->id);
                                        foreach ((array)$CustomerScoreLog as $key => $value):?>
                                        <div class="row static-info">
                                            <div class="col-xs-5 name">
                                                <?php echo date('m/d',strtotime($value['create_time'])),$value['pos_dir']=='in'?'赠送积分':'使用积分' ?>
                                            </div>
                                            <div class="col-xs-7 value text-right">
                                            <?php echo $value['pos_dir']=='in'?'+':'-',$value['score']; ?>
                                            </div>
                                        </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                        <?php $count=(int)\CustomerReProject::model()->getSumByUser($model->id)->sum_re_num;?>
                            <div class="portlet blue-hoki solid">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cogs"></i>疗程账户
                                    </div>
                                    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
                                    <div class="actions">
                                        <a href="<?php echo $this->url('sysclc',array('id'=>$model->id)) ?>" class="btn blue btn-sm">更多</a>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="row static-info">
                                        <div class="col-xs-5 name">
                                             剩余实操疗次：
                                        </div>
                                        <div class="col-xs-7 value text-right">
                                             <?php echo $count; ?> 疗次 <a href="<?php echo $this->url('sysclc',array('id'=>$model->id)) ?>" class="label label-info label-sm">详情</a>
                                        </div>
                                    </div>
                                    <div class="scroller" style="height:130px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">
                                    <?php $CustomerReProject=\CustomerReProject::model()->getListByUser($model->id);
                                    foreach ((array)$CustomerReProject as $key => $value):?>
                                    <div class="row static-info">
                                        <div class="col-xs-5 name"><?php echo $value['name'] ;?></div>
                                        <div class="col-xs-7 value text-right"><?php echo (int)$value['sum_re_num'] ?> 疗次</div>
                                    </div>
                                    <?php endforeach; ?>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                        <?php $CustomerVoucher=\CustomerVoucher::getNum($model->id); ?>
                            <div class="portlet solid green-haze">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cogs"></i>卡券账户
                                    </div>
                                    <div class="tools"><a href="javascript:;" class="collapse"></a></div>
                                    <div class="actions">
                                        <a href="<?php echo $this->url('kjgl',array('id'=>$model->id)) ?>" class="btn green btn-sm">更多</a>
                                    </div>
                                </div>
                                <div class="portlet-body">

                                    <div class="scroller" style="height:160px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">
                                    <div class="row static-info">
                                        <div class="col-xs-5 name">可用卡券：</div>
                                        <div class="col-xs-7 value text-right"><?php echo $CustomerVoucher->kykj; ?></div>
                                    </div>
                                    <div class="row static-info">
                                        <div class="col-xs-5 name">已用卡券：</div>
                                        <div class="col-xs-7 value text-right"><?php echo $CustomerVoucher->yykj; ?></div>
                                    </div>
                                    <div class="row static-info">
                                        <div class="col-xs-5 name">失效卡券：</div>
                                        <div class="col-xs-7 value text-right text-right"><?php echo $CustomerVoucher->sxkj ?></div>
                                    </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                        

                    </div>
            </div>
        </div>
    </div>
   
</div>

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN TAB PORTLET-->
        <div class="portlet purple box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>最近20条实操记录
                </div>
                <div class="tools"><a href="javascript:;" class="collapse"></a></div>
            </div>
            <div class="portlet-body">
                <?php
                //实耗记录
                $data=\PracticeOrderDetail::model()
                ->field(array("t.id,t.por_id","left(t.last_time,16) ttime","po.sn","pi.name piname","crp.re_num","t.before_num","t.use_num",
                    "t.after_num","t.operators","osd.buy_type as buy_type"))
                ->join('practice_order po on t.por_id=po.id')
                ->join('project_info pi on t.project_id=pi.id')
                ->join('order_sale_detail osd on t.detail_id=osd.id')
                ->join('customer_re_project crp  on t.detail_id=crp.detail_id AND po.cu_id=crp.cu_id AND t.project_id=crp.project_id')
                ->order('t.last_time DESC')
                ->limit('0,20')
                ->findAll("po.cu_id={$model->id}");
                echo $this->datagrid(array(
                    'dataProvider'=>array('list'=>$data),
                    'columns'=>array(
                        array(
                            'header' => '单据编号',
                            'name'  => 'sn',
                        ),
                        array(
                            'header' => '日期',
                            'name'   => 'ttime',
                        ),
                        array(
                            'header' => '实操项目',
                            'name'   => 'piname',
                            'value'   => '{$data["piname"]}{$data["buy_type"]==1?"（买）":""}{$data["buy_type"]==2?"（赠）":""}{$data["buy_type"]==3?"（兑）":""}',
                        ),
                        array(
                            'header' => '疗程总次数',
                            'name'   => 're_num',
                        ),
                        array(
                            'header' => '实操前剩余',
                            'name'   => 'before_num',
                        ),
                        array(
                            'header' => '本次实操次数',
                            'name'   => 'use_num',
                        ),
                        array(
                            'header' => '实操后剩余',
                            'name' =>  'after_num',
                        ),
                        array(
                            'header' => '美容师',
                            'value'   => '{\EmployUser::getUserNames($data["operators"])}',
                        ),  
                        array(
                            'header' => '操作',
                            'headerCss'=>'width:80px',
                            'rel'=>'id',
                            'value'=> '<a href="{$this->url("pos/practice/view",array("id"=>$data["por_id"]))}" target="new" class="btn default btn-xs green-stripe view">查看</a>',
                        ),
                    ),
                ));?>
            </div>
        </div>
        <!-- END TAB PORTLET-->
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN TAB PORTLET-->
        <div class="portlet box blue tabbable">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>最近20条记录
                </div>
            </div>
            <div class="portlet-body">
                <div class=" portlet-tabs">
                    <ul class="nav nav-tabs">
                        <li>
                            <a href="#portlet_tab3" data-toggle="tab">剩余疗次</a>
                        </li>
                        <li>
                            <a href="#portlet_tab2" data-toggle="tab">账户动态</a>
                        </li>
                        <li class="active">
                            <a href="#portlet_tab1" data-toggle="tab">消费记录</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="portlet_tab1">
                            <?php
                            //消费记录
                            $data=\OrderSale::model()->order('`pay_time` DESC')->limit('0,20')->findAll("cu_id={$model->id} and status>0 and pay_status=1");
                            echo $this->datagrid(array(
                                'dataProvider'=>array('list'=>$data),
                                'columns'=>array(
                                    array(
                                        'header' => '订单类型',
                                        'value' => '{\OrderSale::getType($data["type"])}',
                                    ),
                                    array(
                                        'header' => '项目/产品',
                                        'value' => '{\OrderSale::getProNames($data["id"])}',
                                    ),
                                    array(
                                        'header' => '应付金额',
                                        'name' => 'pay_price',
                                    ),
                                    array(
                                        'header' => '实收现金',
                                        'name' => 'cash',
                                        'value'=>'{$data["cash"]+$data["cash_pos"]+$data["cash_tra"]+$data["cash_other"]}',
                                    ),
                                    array(
                                        'header' => '卡扣金额',
                                        'name' => 'cash_card',
                                    ),
                                    array(
                                        'header' => '订单欠款',
                                        'name'=>'current_arrears',
                                    ),
                                    array(
                                        'header' => '订单状态',
                                        'value' => '{\OrderSale::getStatus($data["status"])}',
                                    ),
                                    array(
                                        'header' => '操作',
                                        'headerCss'=>'width:80px',
                                        'rel'=>'id',
                                        'value'=> '<a href="{\OrderSale::model()->getOrderUrl($data["type"],$data["id"]);}" target="new" class="btn default btn-xs green-stripe view">查看</a>',
                                    ),
                                    
                                ),
                            ));?>
                        </div>
                        <div class="tab-pane" id="portlet_tab2">
                            <?php
                            //账户动态
                            $data=\CustomerCapitalLog::model()->getCapitalLog($model->id);
                            echo $this->datagrid(array(
                                'title'=>"账户动态",
                                'dataProvider'=>array('list'=>$data),
                                'columns'=>array(
                                    array(
                                        'header' => '单据号',
                                        'name' => 'sn',
                                    ),
                                    array(
                                        'header' => '日期',
                                        'name' => 'ctime',
                                    ),
                                    array(
                                        'header' => '账户名称',
                                        'name' => 'cvname',
                                    ),
                                    array(
                                        'header' => '业务类型',
                                        'value'=>'{$data["pos_dir"]=="in"?"存入":"取出"}',
                                    ),
                                    array(
                                        'header' => '变更前',
                                        'name'=>'before_money',
                                    ),
                                    array(
                                        'header' => '存入（充值）',
                                        'value' => '{$data["pos_dir"]=="in"?$data["money"]:""}',
                                    ),
                                    array(
                                        'header' => '取出（卡扣）',
                                        'value'=>'{$data["pos_dir"]=="in"?"":$data["money"]}',
                                    ),
                                    array(
                                        'header' => '变更后',
                                        'name'=>'after_money',
                                    ),
                                    array(
                                        'header' => '操作',
                                        'headerCss'=>'width:80px',
                                        'rel'=>'id',
                                        'value'=> '<a href="{\OrderSale::model()->getOrderUrl($data["type"],$data["id"]);}" target="new" class="btn default btn-xs green-stripe view">查看</a>',
                                    )
                                    
                                ),
                            ));?>
                         
                        </div>
                        <div class="tab-pane" id="portlet_tab3">
                            <?php
                            //剩余实操疗次
                            $data=\CustomerReProject::model()
                            ->field(array("t.id","pi.name piname","IFNULL(os.pay_time,ov.pay_time) pay_time","IFNULL(os.sn,ov.sn) sn","osd.num osd_num","(osd.cash+osd.card_cash) gmje","t.user_num","(t.re_num) sy_num","t.detail_id"))
                            ->join('project_info pi on t.project_id=pi.id')
                            ->join('order_sale_detail osd on t.detail_id=osd.id')
                            ->join('order_sale os on osd.order_id=os.id and osd.buy_type in (1,2)')
                            ->join('order_voucher ov on osd.order_id=ov.id and osd.buy_type=3')
                            ->order('sy_num DESC')
                            ->limit('0,20')
                            ->findAll("t.cu_id={$model->id}");
                            echo $this->datagrid(array(
                                'dataProvider'=>array('list'=>$data),
                                'lastFloat'=>false,
                                'columns'=>array(
                                    array(
                                        'header' => '项目名称',
                                        'name'   => 'piname',
                                    ),
                                    array(
                                        'header' => '购买日期',
                                        'value'  => '{date("Y-m-d H:i",$data["pay_time"])}',
                                    ),
                                    array(
                                        'header' => '购买订单号',
                                        'name'   => 'sn',
                                    ),
                                    array(
                                        'header' => '购买总次数',
                                        'name'   => 'osd_num',
                                    ),
                                    array(
                                        'header' => '购买金额',
                                        'name'   => 'gmje',
                                    ),
                                    array(
                                        'header' => '已实操次数',
                                        'name'   => 'user_num',
                                    ),
                                    array(
                                        'header' => '已消耗金额',
                                        'value' =>  '{$data["osd_num"]?sprintf("%.2f",$data["gmje"]/$data["osd_num"]*$data["user_num"]):""}',
                                    ),
                                    array(
                                        'header' => '剩余次数',
                                        'name'   => 'sy_num',
                                    ),  
                                    array(
                                        'header' => '剩余金额',
                                        'value' => '{$data["osd_num"]?sprintf("%.2f",$data["gmje"]/$data["osd_num"]*$data["sy_num"]):""}',
                                    ),  
                                    array(
                                        'header' => '最近实操时间',
                                        'value'   => '{\PracticeOrderDetail::getLastTime($data["detail_id"])}',
                                    )   
                                ),
                            ));?>  
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END TAB PORTLET-->
    </div>
    </div>

    <div class="row">
    <div class="col-md-12">
    <!-- BEGIN TAB PORTLET-->
    <div class="portlet box yellow tabbable">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-gift"></i>最近20条记录
            </div>
        </div>
        <div class="portlet-body">
            <div class=" portlet-tabs">
                <ul class="nav nav-tabs">
                    <li>
                        <a href="#portlet_tab7" data-toggle="tab">退款记录</a>
                    </li>
                    <li>
                        <a href="#portlet_tab6" data-toggle="tab">领取记录</a>
                    </li>
                    <li class="active">
                        <a href="#portlet_tab5" data-toggle="tab">寄存记录</a>
                    </li>
                </ul>
                <div class="tab-content">
                    
                    <div class="tab-pane active" id="portlet_tab5">
                        <?php
                        //寄存记录
                        $data=\CustomerProdStorageDetail::model()
                        ->field(array("t.id","left(cos.create_time,16) ttime","cos.sn","pi.name piname","t.total_num","t.remain_num","eu.netname"))
                        ->join('customer_prod_storage cos on t.storage_id=cos.id')
                        ->join('product_info pi on t.product_id=pi.id')
                        ->join('employ_user eu on cos.create_user=eu.id')
                        ->order('cos.create_time DESC')
                        ->limit('0,20')
                        ->findAll("cos.cu_id={$model->id}");
                        echo $this->datagrid(array(
                            'dataProvider'=>array('list'=>$data),
                            'columns'=>array(
                                array(
                                    'header' => '单据号',
                                    'name'  => 'sn',
                                ),
                                array(
                                    'header' => '日期',
                                    'name'   => 'ttime',
                                ),
                                array(
                                    'header' => '产品名称',
                                    'name'   => 'piname',
                                ),
                                array(
                                    'header' => '本次存入',
                                    'name'   => 'total_num',
                                ),
                                array(
                                    'header' => '剩余数量',
                                    'name'   => 'remain_num',
                                ),
                                array(
                                    'header' => '经手人',
                                    'name'   => 'netname',
                                )
                            ),
                        ));?>   
                     
                    </div>
                    <div class="tab-pane" id="portlet_tab6">
                        <?php
                        //领取记录
                        $data=\CustomerProdReceiveDetail::model()
                        ->field(array("cpr.id","left(cpr.create_time,16) ttime","cpr.sn","pi.name piname","t.before_num","t.num","t.after_num","eu.netname"))
                        ->join('customer_prod_receive cpr on t.order_id=cpr.id')
                        ->join('product_info pi on t.product_id=pi.id')
                        ->join('employ_user eu on cpr.create_user=eu.id')
                        ->order('cpr.create_time DESC')
                        ->limit('0,20')
                        ->findAll("cpr.cu_id={$model->id}");
                        echo $this->datagrid(array(
                            'dataProvider'=>array('list'=>$data),
                            'columns'=>array(
                                array(
                                    'header' => '单据号',
                                    'name'  => 'sn',
                                ),
                                array(
                                    'header' => '日期',
                                    'name'   => 'ttime',
                                ),
                                array(
                                    'header' => '产品名称',
                                    'name'   => 'piname',
                                ),
                                array(
                                    'header' => '业务前',
                                    'name'   => 'before_num',
                                ),
                                array(
                                    'header' => '本次领取',
                                    'name'   => 'num',
                                ),
                                array(
                                    'header' => '业务后',
                                    'name'   => 'after_num',
                                ),
                                array(
                                    'header' => '经手人',
                                    'name'   => 'netname',
                                ),
                                array(
                                    'header' => '操作',
                                    'headerCss'=>'width:80px',
                                    'rel'=>'id',
                                    'value'=> '<a href="{$this->url("/pos/receive/edit",array("id"=>$data["id"]))}" target="new" class="btn default btn-xs green-stripe view">查看</a>',
                                ),
                            ),
                        ));?>
                    </div>
                    <div class="tab-pane" id="portlet_tab7">
                        <?php
                        //退款记录
                        $data=\OrderRefund::model()
                        ->field(array("t.id","t.pay_time","t.sn","eu.netname"))
                        ->join('employ_user eu on t.made_id=eu.id')
                        ->order('t.create_time DESC')
                        ->limit('0,20')
                        ->findAll("t.cu_id={$model->id} and t.status=1");
                        echo $this->datagrid(array(
                            'dataProvider'=>array('list'=>$data),
                            'columns'=>array(
                                array(
                                    'header' => '单号',
                                    'name'   => 'sn',
                                ),
                                array(
                                    'header' => '日期',
                                    'value'   => '{date("Y-m-d H:i",$data["pay_time"])}',
                                ),
                                array(
                                    'header' => '退掉金额',
                                    'value'   => '{\OrderRefund::getAllMoney($data["id"])}',
                                ),
                                
                                array(
                                    'header' => '经手人',
                                    'name'   => 'netname',
                                ),
                                array(
                                    'header' => '操作',
                                    'headerCss'=>'width:80px',
                                    'rel'=>'id',
                                    'value'=> '<a href="{$this->url("/pos/refund/view",array("id"=>$data["id"]))}" target="new" class="btn default btn-xs green-stripe view">查看</a>',
                                ),
                            ),
                        ));?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END TAB PORTLET-->
    </div>
</div>




<!--content_right_con!end-->
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/cropbox-min.js"></script>
<script type="text/javascript">
    window.onload = function() {
        var options =
        {
            imageBox: '.imageBox',
            thumbBox: '.thumbBox',
            spinner: '.spinner',
            imgSrc: '<?php echo $cu_avatar;?>'
        }
        var cropper = new cropbox(options);
        document.querySelector('#file').addEventListener('change', function(){
            var reader = new FileReader();
            reader.onload = function(e) {
                options.imgSrc = e.target.result;
                cropper = new cropbox(options);
            }
            reader.readAsDataURL(this.files[0]);
            this.files = [];
        })
        document.querySelector('#btnCrop').addEventListener('click', function(){
            var img = cropper.getDataURL();
            document.querySelector('.cropped').innerHTML = '<img src="'+img+'">';
        })
        document.querySelector('#btnZoomIn').addEventListener('click', function(){
            cropper.zoomIn();
        })
        document.querySelector('#btnZoomOut').addEventListener('click', function(){
            cropper.zoomOut();
        })

        document.querySelector('#btnSave').addEventListener('click', function(){
        	var b64=$('.cropped img').attr('src');
        	if(b64==undefined){
        		alert("未裁减");
        	}else{
        		//保存
        		var url="<?php echo $this->url('avatar') ?>";
				$.post(url, { id: <?php echo $model->id; ?>, avatar: b64 },function(data){
					Idialog.tips(data.msg);
					if(data.code=200){
						$('.img-avatar').attr("src",b64);
                        $("#edit-avatar").modal("hide");
					}
				},'json');
					
        	}
        })
        var check_position = function(){
        	var obj = $('.imageBox').css('background-size').split(' ');
        	var w =  parseInt(obj[0]);
        	var h =  parseInt(obj[1]);
        	var pw = (300 - w) / 2;
        	var ph = (300 - h) / 2;
        	$('.imageBox').css('background-position',pw+"px"+" "+ph+"px");
        };
        $('.avatar').click(function(){
        	check_position();
        })
    };


	$('.action_qr').click(function(event) {
		/* Act on the event */
		var url=$(this).attr('href');
		var d = Idialog({
				top:150,
				width:468,
				title:'二维码',
				content:'<img src="'+url+'">',
				cancel:false,
				init:function()
					{
						$(".idialog_title").unbind("mousedown")
					}
				});
		
		return false;
	});
</script>