<!--content_right_con-->
<div class="row">
    <div class="col-md-12 ">

    <!--  模版引擎扩展 -->
    <?php  echo $this->datagrid(array(
        'id'=>'list',
        'dataProvider'=>$pager,
        'search'=>true,
        'columns'=>array(
            array(
                'header' => '采购时间',
                'name'  => 'date',
            ),
            array(
                'header' => '供应商',
                'name'  => 'supp_name',
            ),
            array(
                'header' => '采购商品',
                'name'  => 'product_info',
                'class' => 'li004'
            ),
            array(
                'header' => '备注',
                'name'  => 'note',
            ),
            array(
                'header' => '操作人',
                'name'  => 'user_name',
            ),
            array(
                'header' => '操作',
                "rel"=>"id",
                'template'  => 'view+',
            ),
           
        ),
    ));?>
</div>
</div>
