<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-eye-slash"></i>充值/订单确认
                </div>
                <div class="tools">
                    <button onclick="to_url('<?php echo $this->url("edit");?>&id=<?php echo $_GET['id']?>')" class="btn btn-sm green table-group-action-submit"><i class="fa fa-mail-forward"></i>更新订单</button>
                    <button onclick="to_url('<?php echo $this->url("pay",array('id'=>$model->o_s->id)) ?>')" class="btn btn-sm blue table-group-action-submit"><i class="fa fa-mail-forward "></i>付款</button>
                    <button id="cancelOrder" class="btn btn-sm red table-group-action-submit"><i class="fa fa-eraser"></i>废除</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>订单概况
                        </div>
                        <div class="actions"><button class="btn red"><font class="price_all"><?php echo empty($model)?0:$model->o_s->pay_price?></font>￥</button></div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn ?>
                            </div>
                        </div>

                        <div class="scroller" style="height:140px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">
                            

                           

                            <div class="row static-info">
                                <div class="col-xs-5 name">订单状态：</div>
                                <div class="col-xs-7 value text-right">
                                    <span class="label label-warning label-sm">
                                    <?php 
                                        if($model){
                                            echo \OrderSale::getPayStatus($model->o_s->pay_status);
                                        }else{
                                            echo "新建";
                                        }
                                    ?>
                                    </span>
                                    <?php if($model->o_s->rh_id):?>
                                    <span class="label label-success label-sm">新客入会</span>
                                    <?php endif;?>
                                </div>
                            </div>

                        </div>

                        
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>



        <!--销售人员及业绩比例-->
        <?php echo $effect ?>
        <!--销售人员及业绩比例!end-->


        <div class="pos_cz_tow ">
            <div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>充值账户</div>
            <div class="pos_cz_tow_two">
                <!--table_container-->
                <div class="table_container">
                <!--table_con-->
                <div class="table_con" >
                    <!--table_con_son-->
                    <div class="table_con_son table-responsive">
                        <table class="table table-bordered table-hover pos_table">
                            <thead>
                                <tr>
                                    <?php foreach($cu_capitals as $cu_capital):?>
                                    <th><?php echo $cu_capital['name'];?></th>
                                    <?php endforeach;?>
                                </tr>
                            </thead>
                            <tbody>
                                <tr id="cz_money">
                                <?php $i=1;foreach($cu_capitals as $cu_capital):?>
                                    <td class="li00<?php echo $i;?>"><?php echo $cu_capital['price'];?></td>
                                <?php $i++;endforeach;?>
                                </tr>
                            </tbody>
                        </table>


                        
                    </div><!--table_con_son!end-->
                </div><!--table_con!end-->
                </div>
                <!--table_containter!end-->
                <div class="pos_cz_tow_two_two pos_gm_02_border_top"><span class="pos_cz_tow_two04">应付金额：<em class="price_all"><?php echo empty($model)?0:$model->o_s->pay_price?></em>&nbsp;元</span></div>
            </div>
        </div><!--购买项目!end-->

        <!--赠送-->
        <?php echo $gift_view;?>
        <!--赠送!end-->

        <!--备注-->
        <div class="pos_cz_tow pos_cz_for_bz">
            <div class="pos_cz_for_bz01">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son"><?php echo empty($model)?'':$model->o_s->note?></div>
            </div>
        </div><!--备注!end-->



    </div>
</div>


{__TOKEN__}

<script type="text/javascript">

    function to_url(url){
        window.location.href=url;
    }

    $("#cancelOrder").click(function(){
        if(confirm("您确定要废弃此订单吗？")){
            var data={};
            data.__hash__ = $("input[name='__hash__']").val();//表单令牌
            $.post("<?php echo $this->url('cancel',array('id'=>$model->o_s->id)) ?>",data,function(data){
                Idialog.tips(data.msg,2);
                if(data.code==200){
                    setTimeout(function(){to_url('<?php echo $this->url("index");?>')},2000);
                }
            }, "json");
        }
    });

</script>


