<?php
//付款配置
$config=\CompanyInfo::getConfig('payee');
?>
<style type="text/css">
.rh_gm{height: 40px;line-height: 40px;font-size: 16px;}
</style>
<!--content_right_con-->
<div class="content_right_con">
    <div class="content_right_con_top">
        <!--<div class="fjgl_top_r">
          <a href="javascript:" class="khgl_02 fpkhn">分配客户</a><a href="javascript:" class="fjgl_top_r_01">筛选</a><a href="javascript:" class="fjgl_top_r_02 tjfjz">添加客户</a>
        </div>-->
        <div class="khgl_01"><img src="<?php echo $this->basePath('public');?>/images/kh_01.png" /></div>POS开单><span>充值</span>>付款
    </div>

    <!--pos_cz_fk_top-->
    <div class="pos_cz_fk_top">
        <div class="pos_cz_fk_top_02">
            应付金额：<span class="pos_cz_fk_top_03"><?php echo $model->o_s->pay_price;?></span>元
            <a href="javascript:" class="pos_cz_fk_top_04">订单详情</a>
        </div>请客户及时付款，以便订单尽快处理！
        <span class="pos_cz_fk_top_01"> 订单号：<?php echo $model->o_s->sn;?></span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="spanll"><?php echo $model->o_s->rh_id==0?'':'新客入会订单';?></span>
    </div><!--pos_cz_fk_top!end-->

    <!--pos_cz_fk_two-->
    <div class="pos_cz_fk_two">
        <div class="pos_cz_fk_two_ico">&nbsp;</div>
        <ul>
            <li>客户姓名：<?php echo $model->getCuName(); ?></li>
            <li>订单类型：充值</li>
            <li>商品名称：无</li>
            <li>交易金额：<?php echo $model->o_s->pay_price;?>元</li>
            <li>购买时间：<?php echo date('Y年m月d日 H:i:s',strtotime($model->o_s->create_time)) ?></li>
            <li>操作人：<?php echo $model->employName ?></li>
        </ul>

    </div><!--pos_cz_fk_two!end-->

    <!--khgl_shouye-->
    <?php echo $cu_info ?>
    <!--khgl_shouye!end-->

    <!--入会购买-->
    <?php if ($model->o_s->rh_id=='-1'): 

        $info = \CustomerInfo::model()
        ->field('t.*,m.level_name as membership_name')
        ->join("config_membership as m on m.id=t.membership_id")
        ->findByPk($model->o_s->cu_id);
        $mem_list = \ConfigMembership::model()->findAll("status=1 AND comp_id=".$info->company_id);
    ?>
        
        <div class="pos_cz_for_bz rh_gm">
            当前客户等级：<span class="khgl_shouye_r_top_07"><?php echo $info->membership_name ?></span>
            <span style="margin-left:40px;">入会后等级：</span><select class="pos_cz_fk_th_two_06 rh" style="margin-left:0px;font-size:14px;width:150px;">
                <?php foreach ($mem_list as $value): ?>
                    <option value ="<?php echo $value['id'] ?>"><?php echo $value['level_name'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    <?php endif ?><!--入会购买!end-->

    <!--pos_cz_fk_th-->
    <div class="pos_cz_fk_th">
        <div class="pos_cz_fk_th_top">
            <div class="pos_cz_fk_th_01">应付现金:<span class="pos_cz_fk_top_03 all_xj"><?php echo $model->o_s->pay_price;?></span>元</div>支付方式
        </div>
        <div class="pos_cz_fk_th_two pos_cz_fk_th_two_chan">
            <ul>
                <?php if ($config['money']['open']=='true'): ?>
                    <li  >  <!-- class="pos_cz_fk_th_two_chan" -->
                        <!-- <span class="pos_cz_fk_th_two_04">支付:<span class="pos_cz_fk_th_two_05">0.00</span>元</span>
                        <span class="pos_cz_fk_th_two_01 pos_cz_fk_th_two_0101"></span> -->
                        <span class="pos_cz_fk_th_two_02">现金</span>
                        <input type="text" name="cash" value="0" class="pos_cz_fk_th_two_03 pos_cz_fk_th_two_chan" />
                    </li>
                <?php endif ?>
                <?php if ($config['post']['open']=='true'): ?>
                    <li >
                        <!-- <span class="pos_cz_fk_th_two_04">支付:<span class="pos_cz_fk_th_two_05">0.00</span>元</span>
                        <span class="pos_cz_fk_th_two_01"></span> -->
                        <span class="pos_cz_fk_th_two_02">刷卡</span>
                        <input type="text" name="cash_pos" value="0" class="pos_cz_fk_th_two_03" />
                        <?php echo $this->dropDownList('pos_type',$config['post']['has'],'',array('class'=>'pos_cz_fk_th_two_06')) ?>
                    </li>
                <?php endif ?>
                <?php if ($config['bank']['open']=='true'): ?>
                    <li >
                        <!-- <span class="pos_cz_fk_th_two_04">支付:<span class="pos_cz_fk_th_two_05">0.00</span>元</span>
                        <span class="pos_cz_fk_th_two_01"></span> -->
                        <span class="pos_cz_fk_th_two_02">转账</span>
                        <input type="text" name="cash_tra" value="0" class="pos_cz_fk_th_two_03" />
                        <?php echo $this->dropDownList('tra_type',$config['bank']['has'],'',array('class'=>'pos_cz_fk_th_two_06')) ?>
                    </li>
                <?php endif ?>
                <?php if ($config['other']['open']=='true'): ?>
                    <li >
                        <!-- <span class="pos_cz_fk_th_two_04">支付:<span class="pos_cz_fk_th_two_05">0.00</span>元</span>
                        <span class="pos_cz_fk_th_two_01"></span> -->
                        <span class="pos_cz_fk_th_two_02">其他</span>
                        <input type="text" name="cash_other" value="0" class="pos_cz_fk_th_two_03" />
                        <?php echo $this->dropDownList('other_type',$config['other']['has'],'',array('class'=>'pos_cz_fk_th_two_06')) ?>
                    </li>
                <?php endif ?>
            </ul>

        </div>

        <div class="pos_cz_fk_th_th">
            <a href="javascript:" class="pos_cz_zh_an before">
                付款
            </a>
        </div>
        <div class="pos_cz_fk_th_th" style="display: none;">
            <a href="javascript:" class="pos_cz_zh_an after">
                正在付款，请稍后...
            </a>
        </div>
    </div>
    <!--pos_cz_fk_th-->

    <?php foreach($order_sale_detail as $item):?>
        <input type="hidden" name="cz[]" value="<?php echo $item['price'];?>" capitalid="<?php echo $item['pro_id'];?>" detailid="<?php echo $item['id'];?>">
    <?php endforeach;?>
    <input type="hidden" name="cu_id" value="<?php echo $model->o_s->cu_id;?>">

</div>
<!--content_right_con!end-->

{__TOKEN__}

<script type="text/javascript">

    $(function(){
        $(".pos_cz_fk_top_04").click(function(){
            $(".pos_cz_fk_two").slideToggle();
        });
    });

    function to_url(url){
        window.location.href=url;
    }

    //提交保存数据构造
    function submit_data(){
        var err=false;
        //非法输入检测 负数检测
        $(".content_right_con input").each(function(i){
            var v = $(this).val();
            if($.isNumeric(v) && v<0){
                err=true;
            }
        });
        if(err){
            Idialog.tips("不可输入负值",2);
            return false; //直接返回
        }
        
        var data={};
        data.__hash__ = $("input[name='__hash__']").val();//表单令牌
        //购买项目、产品、卡券相关
        data.cz=[];
        $("input[name='cz[]']").each(function(i){
            var detail_id = $(this).attr("detailid");
            var capital_id = $(this).attr("capitalid");
            var price = $(this).val();
            data.cz.push({
                "detail_id":detail_id,
                "capital_id":capital_id,
                "price":price

            });
        });
        //现钞
        data.cash = $.isNumeric( $("input[name='cash']").val() )?parseFloat($("input[name='cash']").val()):0;
        //pos现金
        data.cash_pos = $.isNumeric( $("input[name='cash_pos']").val() )?parseFloat($("input[name='cash_pos']").val()):0;
        data.pos_type = $("select[name=pos_type]").val();
        if(data.cash_pos>0 && data.pos_type==""){
            Idialog.tips("POS类型未选择！",2);
            return false;
        }
        //转账现金
        data.cash_tra = $.isNumeric( $("input[name='cash_tra']").val() )?parseFloat($("input[name='cash_tra']").val()):0;
        data.tra_type = $("select[name=tra_type]").val();
        if(data.cash_tra>0 && data.tra_type==""){
            Idialog.tips("转账类型未选择！",2);
            return false;
        }
        //其他现金
        data.cash_other = $.isNumeric( $("input[name='cash_other']").val() )?parseFloat($("input[name='cash_other']").val()):0;
        data.other_type = $("select[name=other_type]").val();
        if(data.cash_other>0 && data.other_type==""){
            Idialog.tips("其他类型未选择！",2);
            return false;
        }
        //现金合计计算
        if(data.cash+data.cash_pos+data.cash_tra+data.cash_other != parseFloat($(".all_xj").html())){
            Idialog.tips("现金支付错误！",2);
            return false;
        }
        //客户id
        data.cu_id = $("input[name=cu_id]").val();

        <?php if ($model->o_s->rh_id=='-1'): ?>
            data.rh_id=$(".rh").val();
        <?php endif ?>

        //return false; 发生验证错误 返回false
        return data;
    }

    //数据提交
    $(".pos_cz_fk_th_th .before").click(function(){
        var post_data = submit_data();
        if(post_data==false)
            return;
        $('.pos_cz_fk_th_th .before').parent().hide();
        $('.pos_cz_fk_th_th .after').parent().show();
        $.post("<?php echo $this->url('paySave',array('id'=>$model->o_s->id)) ?>", post_data,function(data){
            //$('.c_submit img').attr("src","<?php echo $this->basePath('public');?>/images/pos_cz_10.png");
            Idialog.tips(data.msg,2);
            if(data.code==200){
                //转到付款界面
                setTimeout(function(){to_url('<?php echo $this->url("index");?>')},2000);
            }
        }, "json");
    });

</script>


