<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/jquery.PrintArea.js"></script>
<link href="<?php echo $this->basePath('public');?>/css/pos.css" rel="stylesheet" type="text/css"/>
<div class="row">
    <div class="print_show col-md-12">
        <div class="portlet">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-eye-slash"></i>充值/订单详情
                </div>
                <div class="tools">
                    <button class="btn btn-sm yellow table-group-action-submit to_print"><i class="fa fa-check"></i>打印订单</button>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="portlet solid green-haze">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i>订单概况
                        </div>
                        <div class="actions"><button class="btn red">交易成功</button> </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-xs-5 name">订单号：</div>
                            <div class="col-xs-7 value text-right">
                                 <?php echo $model->o_s->sn ?>
                            </div>
                        </div>

                        <div class="scroller" style="height:140px" data-rail-visible="1" data-rail-color="blue" data-handle-color="red">
                            <?php if($model->o_s->pay_status==1): ?>

                                <?php foreach ($model->getXJList() as $key => $value): ?>
                                    <?php if($value>0): ?>
                                    <div class="row static-info">
                                        <div class="col-xs-5 name"><?php echo $key ?>卡扣：</div>
                                        <div class="col-xs-7 value text-right">
                                            <?php echo $value ?> 元
                                        </div>
                                    </div>
                                    <?php endif; ?>
                                <?php endforeach ?>

                                <div class="row static-info">
                                    <div class="col-xs-5 name">欠款：</div>
                                    <div class="col-xs-7 value text-right red">
                                        <font color="red"><?php echo $model->o_s->current_arrears ?></font>  元
                                    </div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">实收现金：</div>
                                    <div class="col-xs-7 value text-right">
                                        <font color="yellow"><?php echo $model->o_s->cash+$model->o_s->cash_pos+$model->o_s->cash_tra+$model->o_s->cash_other ?></font> 元
                                        
                                    </div>
                                </div>
                                <?php if($model->o_s->cash>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">现金支付：</div>
                                    <div class="col-xs-7 value text-right">
                                        <?php echo $model->o_s->cash ?> 元
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if($model->o_s->cash_pos>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">POS刷卡：</div>
                                    <div class="col-xs-7 value text-right">
                                        <?php echo $model->o_s->cash_pos ?> 元
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if($model->o_s->cash_tra>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">银行转账：</div>
                                    <div class="col-xs-7 value text-right">
                                        <?php echo $model->o_s->cash_tra ?> 元
                                    </div>
                                </div>
                                <?php endif; ?>
                                <?php if($model->o_s->cash_other>0): ?>
                                <div class="row static-info">
                                    <div class="col-xs-5 name">其他方式支付：</div>
                                    <div class="col-xs-7 value text-right"><?php echo $model->o_s->cash_other ?> 元</div>
                                </div>
                                <?php endif; ?>
                            <?php endif; ?>

                           

                            <div class="row static-info">
                                <div class="col-xs-5 name">订单状态：</div>
                                <div class="col-xs-7 value text-right">
                                    <span class="label label-warning label-sm"><?php echo \OrderSale::getPayStatus($model->o_s->pay_status);?></span>
                                    <?php if($model->o_s->rh_id):?>
                                    <span class="label label-success label-sm">新客入会</span>
                                    <?php endif;?>
                                </div>
                            </div>

                        </div>

                        
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="portlet solid red-intense">
                    <div class="portlet-body" style="padding-top: 10px;">
                        <?php echo $cu_info ?>
                    </div>
                </div>
            </div>
        </div>



        <!--销售人员及业绩比例-->
        <?php echo $effect ?>
        <!--销售人员及业绩比例!end-->


        <div class="pos_cz_tow box_xm">
            <div class="pos_cz_tow_top"><span class="pos_cz_tow_top_r">收起</span>充值账户</div>
            <div class="pos_cz_tow_two">
                <!--table_container-->
                <div class="table_container">
                <!--table_con-->
                <div class="table_con" >
                    <!--table_con_son-->
                    <div class="table_con_son table-responsive">
                        <table class="table table-bordered table-hover pos_table">
                            <thead>
                                <tr>
                                    <?php foreach($cu_capitals as $cu_capital):?>
                                    <th><?php echo $cu_capital['name'];?></th>
                                    <?php endforeach;?>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <?php $i=1;foreach($cu_capitals as $cu_capital):?>
                                        <td class="li00<?php echo $i;?>"><?php echo $cu_capital['price'];?></td>
                                    <?php $i++;endforeach;?>
                                </tr>
                            </tbody>
                        </table>


                        
                    </div><!--table_con_son!end-->
                </div><!--table_con!end-->
                </div>
                <!--table_containter!end-->
                <div class="pos_cz_tow_two_two pos_gm_02_border_top"><span class="pos_cz_tow_two04">应付金额：<em><?php echo $model->o_s->price;?></em>&nbsp;元</span></div>
            </div>
        </div><!--购买项目!end-->

        <!--赠送-->
        <?php echo $gift ?>
        <!--赠送!end-->

        <!--备注-->
        <div class="pos_cz_tow pos_cz_for_bz">
            <div class="pos_cz_for_bz01">备注</div>
            <div class="pos_cz_for_bz02">
                <div class="pos_cz_for_bz02_son"><?php echo empty($model)?'':$model->o_s->note?></div>
            </div>
        </div><!--备注!end-->



    </div>
</div>

<script type="text/javascript">
    $(".to_print").click(function(){
        $(".print_show").printArea();
    });
</script>

