<!--content_right_con-->
<div class="content_right_con">
	<div class="content_right_con_top">
		<div class="fjgl_top_r">
			<a class="fjgl_top_r_02 tjfjz add_top" href="javascript:">新增一级类别</a>
		</div>
		商品管理&gt;商品分类
	</div>


	<?php foreach ($topCate as $key => $value): ?>
	<!--fjgl_th-->
	<div class="fjgl_th sp_fenlei_top">
		<span class="span"><a href="javascript:" class="tjfjz01" rel="<?php echo $key ?>">添加二级类别</a></span>
		<a href="javascript:" class="spfl_0121"><?php echo $value ?><span>（包含二级类别 <?php echo count($childCate[$key]) ?> 个；点击展开）</span></a>

		<div class="fjgl_th spfl0100">
			<div class="fjgl_th_top">
				<ul>
					<li class="sp_fenlei_01">二级类别名称</li>
					<li class="sp_fenlei_02">操作</li>
				</ul>
			</div>
			<?php if ($childCate[$key]): ?>
			<?php foreach ($childCate[$key] as $child): ?>
			<div class="fjgl_th_th clear">
				<ul>
					<li class="sp_fenlei_011" rel="<?php echo $child['id'] ?>"><?php echo $child['name'] ?></li>
					<li class="sp_fenlei_021"><a href="javascript:" rel="<?php echo $child['id'] ?>" class="flxg_01">修改</a><a class="del_cate" rel="<?php echo $child['id'] ?>" href="javascript:">删除</a></li>
				</ul>
			</div>
			<?php endforeach ?>
			<?php endif ?>
		</div>
		

	</div><!--fjgl_th!end-->
	<?php endforeach ?>

</div>
<!--content_right_con!end-->


<!--tjfj01-->
<div class="tjfj_01 dialog">
	<div class="tjfj_top"><span class="fjgb010" style=" color:#FFF;font-size:18px;">x</span>修改类别名称</div>
	<div class="tjfj_two">
		<form method="post" action="#">
			<p><label>商品类型：</label><input  type="text" class="gysgl_07" placeholder="减肥系列1" /></p>
		</form>
		<div class="tjfj_two_an"><a href="javascript:" class="fjgb010">取消</a><a class="edit_sub" href="javascript:">确定</a></div>
	</div>
</div><!--tjfj01!end-->
<!--tjfj-->
<div class="tjfj_02 dialog">
	<div class="tjfj_top"><span class="fjgb010"  style=" color:#FFF;font-size:18px;">x</span>添加二级类别</div>
	<div class="tjfj_two">
		<form method="post" action="#">
			<p><label>商品类型：</label><select class="gysgl_07">
				<?php foreach ($topCate as $key => $value): ?>
					<option value="<?php echo $key ?>"><?php echo $value ?></option>
				<?php endforeach ?>
			</select></p>
			<p><span class="gysgl_08">必填</span><label>二级类别：</label><input type="text" class="gysgl_07" placeholder="分类名" /></p>
		</form>
		<div class="tjfj_two_an"><a href="javascript:" class="fjgb010">取消</a><a class="add_sub" href="javascript:">确定</a></div>
	</div>
</div><!--tjfj!end-->

<!--tjfj-->
<div class="tjfj_03 dialog">
	<div class="tjfj_top"><span class="fjgb010"  style=" color:#FFF;font-size:18px;">x</span>添加一级类别</div>
	<div class="tjfj_two">
		<form method="post" action="#">
			<p style="display:none"><label>商品类型：</label><select class="gysgl_07">
					<option selected="selected" value="0">顶级分类</option>
			</select></p>
			<p><span class="gysgl_08">必填</span><label>一级类别：</label><input type="text" class="gysgl_07" placeholder="分类名" /></p>
		</form>
		<div class="tjfj_two_an"><a href="javascript:" class="fjgb010">取消</a><a class="add_top_sub" href="javascript:">确定</a></div>
	</div>
</div><!--tjfj!end-->

<script type="text/javascript">
$(function(){
	/*商品分-展开*/
	$(".spfl_0121").click(function(){
		$(".spfl_0121").parent().children(".fjgl_th").hide();
		$(this).parent().children(".fjgl_th").toggle();
	});
	// 修改二级分类
	$(".content_right_con").on('click','.flxg_01',function(){
		$(".tjfj_01").show();
		var name = $(this).parent().prev().html();
		$(".tjfj_01").find('input').val(name);
		$(".tjfj_01").find('input').attr('rel',$(this).attr('rel'));

	});


	/*添加二级类*/
	$(".tjfjz01").click(function(){
		$(".tjfj_02").show().find(":input").val('');
		$(".tjfj_02").find("select").val($(this).attr('rel'));
		$(this).parent().next().trigger('click');
	});

	/*添加一级类*/
	$(".add_top").click(function(){
		$(".tjfj_03").show().find(":input").val('');
	});

	/*关闭1*/
	$(".fjgb010").click(function(){
		$(this).parents(".dialog").hide();
	});

	// 添加二级提交
	$(".add_sub").click(function(){
		var _self=$(this);
		var fid=$(".tjfj_02").find("select").val();
		var name=$(".tjfj_02").find("input").val();
		if(''==name){
			alert('不能为空');
			return ;
		}
		$.post('<?php echo $this->url("addCate") ?>', { "fid": fid,"name": name },function(data){
			if(data.code==200){
				var str	='<div class="fjgl_th_th clear"><ul>';
					str+='<li class="sp_fenlei_011" rel="'+data.data.id+'">'+data.data.name+'</li>';
					str+='<li class="sp_fenlei_021"><a class="flxg_01" rel="'+data.data.id+'" href="javascript:">修改</a><a class="del_cate" rel="'+data.data.id+'" href="javascript:">删除</a></li>';
					str+='</ul></div>';
				$(".spfl0100:visible").append(str);
				$(".fjgb010").trigger('click');
				
			}else{
				alert(data.msg);
			}
		}, "json");

	});
	// 添加一级提交
	$(".add_top_sub").click(function(){
		var _self=$(this);
		var fid=$(".tjfj_03").find("select").val();
		var name=$(".tjfj_03").find("input").val();
		if(''==name){
			alert('不能为空');
			return ;
		}
		$.post('<?php echo $this->url("addCate") ?>', { "fid": fid,"name": name },function(data){
			if(data.code==200){
				history.go(0);
			}else{
				alert(data.msg);
			}
		}, "json");

	});
	// 修改提交
	$(".edit_sub").click(function(){
		var self=$(this);
		var id=$(this).parent().parent().find('.gysgl_07').attr('rel');
		var name=$(this).parent().parent().find('.gysgl_07').val();
		$.post('<?php echo $this->url("addCate") ?>', { "id": id ,"name":name},function(data){
			if(data.code==200){
				self.parent().parent().parent().hide();
				$(".spfl0100:visible").find('.sp_fenlei_011[rel="'+id+'"]').html(name);

			}else{
				alert(data.msg);
			}
		}, "json");

	});
	// 删除提交
	$(".content_right_con").on('click','.del_cate',function(){
		var id=$(this).attr('rel');
		var self=$(this);
		$.post('<?php echo $this->url("delCate") ?>', { "id": id },function(data){
			if(data.code==200){
				self.parent().parent().parent().remove();
			}else{
				alert(data.msg);
			}
		}, "json");

	});


})

</script>
