<?php 
$top_cate=\ProCate::getProjectTopCate();
$child_cate=array();
if(isset($_GET['t_search']['c_t.id']))
	$child_cate=\ProCate::model()->findAll('fid='.(int)$_GET['t_search']['c_t.id']);
?>
<link href="<?php echo $this->basePath('public');?>/css/oldAdmin.css" rel="stylesheet" type="text/css"/>

<div class="row">
	<div class="col-md-12">
		<div class="portlet no_mb">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-users"></i>卡券管理
				</div>
				<div class="actions btn-set">
					<a href="<?php echo $this->url('edit') ?>" class="btn default yellow-stripe tjfjz"><i class="fa fa-plus"></i>新增卡券</a>
				</div>
			</div>
		</div>



	<!--  模版引擎扩展 -->
<?php echo $this->datagrid(array(
	'id'=>'list',
	'dataProvider'=>$pager,
	'search'=>false,
	'columns'=>array(
		array(
			'header' => '卡券名称',
			'name'  => 'name',
			'filter'=> "t.name",
		),
		array(
			'header' => '有效期',
			'name'  => 'time',
			'value'=>'{date("Y-m-d",$data["stime"])."至".date("Y-m-d",$data["etime"])}'
		),
		array(
			'header' => '使用范围',
			'name'  => 'scope',
			'value'=>'{$data["scope"]==0?"不限":($data["scope"]==1?"正式会员":"非正式会议")}',
		),
		array(
			'header' => '数量',
			'name'  => 'num',
			'value'=>'{$data["num"]==-1?"不限":$data["num"]}',
		),
		array(
			'header' => '单价',
			'name'  => 'price',
		),
		array(
			'header' => '已发售数量',
			'name'  => 'num',
			'value'=>'{\ConfigVoucher::getVoucherNum($data["id"],"1,2")}'
		),
		array(
			'header' => '售卡累计业绩',
			'name'  => 'price',
			'value'=>'{\ConfigVoucher::getVoucherTotal($data["id"])}'
		),
		array(
			'header' => '已用完数量',
			'name'  => 'num',
			'value'=>'{\ConfigVoucher::getVoucherNum($data["id"],2)}'
		),
		array(
			'header' => '状态',
			'name' => 'status',
			'value'=>'{$data["status"]==1?"启用":"<fone style=\"color:red\">停用</font>"}'
		),
		array(
			'header' => '操作',
			'rel'=>'id',
			'template'=>'<a rel="{$data[id]}" href="javascript:" class="btn default btn-xs red-stripe change" >{$data["status"]==0?"启用":"停用"}</a>
				<a class="btn default btn-xs green-stripe edit" href="'.$this->url('view').'&id={$data["id"]}">查看</a>'
		)
	),
));?>

	

	</div>
</div>


<!--tjfj-->

<div class="add_prod none" title="新增项目">
	<div class="tjfj_two" action="#">
	<form method="post" action="<?php echo $this->url('add') ?>">
		<p><span class="gysgl_08">必填</span><label>项目分类：</label><select class="top_cate">
			<option value="">--请选择--</option>
		<?php foreach ($top_cate as $key => $value): ?>
			<option value="<?php echo $key ?>"><?php echo $value ?></option>
		<?php endforeach ?>
		</select></p>
		<p><span class="gysgl_08">必填</span><label>品牌系列：</label><select name="cate"></select></p>
		<p><span class="gysgl_08">必填</span><label>项目名称：</label><input type="text" name="name" /></p>
		<p><span class="gysgl_08">必填</span><label>项目编码：</label><input type="text" name="code" /></p>
		<p><label>项目疗次：</label><input type="text" placeholder="" name="num" /></p>
		<p><span class="gysgl_08">必填</span><label>单价：</label><input type="text" placeholder="" name="price" /></p>
	</form>
	</div>
</div>








<script type="text/javascript">

$(function(){
	$(document).on('click','.change',function(){
		var obj = $(this).parent().parent();
		var id = $(this).attr('rel');
		var thisobj = $(this);
		$.get("<?php echo $this->url('change') ?>", { id: id },function(html){
			var jobj = $.parseJSON(html);
			var dataobj = jobj['data'];
			var status = dataobj['status'];
			//thisobj.html(status==1?"启用":"<fone style='color:red'>停用</font>");
			thisobj.html(status==0?"启用":"停用");
			thisobj.attr('style',status==0?'':'background-color: #ddd;color: #666;');
			thisobj.parent().prev().attr('title',status==1?"启用":"停用").html(status==1?"启用":'<fone style="color:red">停用</fone>');
		});
	});




});
</script>